### ISSUE TITLE
jdk_net tests fails intermittently with hotspot jdk8 on macosx|linux

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#1259]
Test category: openjdk
Testsuite name: jdk_net
Test name(s): 

- java/net/InetAddress/CheckJNI.java

- java/net/Socket/LinkLocal.java

- java/net/ipv6tests/B6521014.java

- java/net/ipv6tests/TcpTest.java

- java/rmi/transport/dgcDeadLock/DGCDeadLock.java

- java/util/concurrent/locks/Lock/TimedAcquireLeak.java

Product(s) tested: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-201907290328-b10)
OS/architecture: macosx
Platform specific: yes

Reproducibility: intermittent

Exception/Error from Log:

```
06:11:18  JavaTest Message: Test threw exception: java.net.ConnectException: Operation timed out (Connection timed out)
06:11:18  JavaTest Message: shutting down test
06:11:18  
06:11:18  STATUS:Failed.`main' threw exception: java.net.ConnectException: Operation timed out (Connection timed out)
```
JBS: 

- https://bugs.openjdk.java.net/browse/JDK-8178789

- https://bugs.openjdk.java.net/browse/JDK-6459313

- https://bugs.openjdk.java.net/browse/JDK-8006560

- https://bugs.openjdk.java.net/browse/JDK-8151260

- https://bugs.openjdk.java.net/browse/JDK-8029360

- https://bugs.openjdk.java.net/browse/JDK-8155727

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_x86-64_mac/13/

**Comment by sophia-guo** [comment]
java/util/logging/TestLoggerWeakRefLeak.java

JBS: https://bugs.openjdk.java.net/browse/JDK-8199767

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_x86-64_mac/13/testReport/junit/java_util_logging_TestLoggerWeakRefLeak/java/TestLoggerWeakRefLeak/

```
Stacktrace

Execution failed: `main' threw exception: java.io.IOException: well-known file /var/folders/h1/b_v48zpd1zd54jblxnx58p3r0000gr/T/.java_pid34749 is not secure: file's group should be the current group (which is -1) but the group is 0    

Standard Output

Test for WeakReference leak in Logger object
call count = 1000
    

Standard Error

java.io.IOException: well-known file /var/folders/h1/b_v48zpd1zd54jblxnx58p3r0000gr/T/.java_pid34749 is not secure: file's group should be the current group (which is -1) but the group is 0
	at sun.tools.attach.BsdVirtualMachine.checkPermissions(Native Method)
	at sun.tools.attach.BsdVirtualMachine.<init>(BsdVirtualMachine.java:101)
	at sun.tools.attach.BsdAttachProvider.attachVirtualMachine(BsdAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	at TestLoggerWeakRefLeak.getInstanceCountFromHeapHisto(TestLoggerWeakRefLeak.java:130)
	at TestLoggerWeakRefLeak.testIfLeaking(TestLoggerWeakRefLeak.java:80)
	at TestLoggerWeakRefLeak.main(TestLoggerWeakRefLeak.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.io.IOException: well-known file /var/folders/h1/b_v48zpd1zd54jblxnx58p3r0000gr/T/.java_pid34749 is not secure: file's group should be the current group (which is -1) but the group is 0
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.io.IOException: well-known file /var/folders/h1/b_v48zpd1zd54jblxnx58p3r0000gr/T/.java_pid34749 is not secure: file's group should be the current group (which is -1) but the group is 0
    
```

**Comment by sophia-guo** [comment]
Same issue with java/net/ipv6tests/B6521014.java on linux
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/30/testReport/junit/java_net_ipv6tests_B6521014/java/B6521014/

**Comment by sophia-guo** [comment]
rerun x86-64_mac https://ci.adoptium.net/view/Test_grinder/job/Grinder/11397/
java/rmi/transport/dgcDeadLock/DGCDeadLock.java
java/util/concurrent/locks/Lock/TimedAcquireLeak.java
java/util/logging/TestLoggerWeakRefLeak.java
