### ISSUE TITLE
openjdk test failures with jdk 11 hotspot on Macos 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#1267]
Test category: openjdk
Test name(s):

    java/lang/System/LoggerFinder/modules/JDKLoggerForImageTest.java
    java/lang/System/LoggerFinder/modules/LoggerInImageTest.java
    java/lang/System/LoggerFinder/modules/NamedLoggerForImageTest.java
    java/lang/System/LoggerFinder/modules/UnnamedLoggerForImageTest.java
    jdk/modules/etc/DefaultModules.java
    jdk/modules/incubator/ImageModules.java
    java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java
    java/lang/Class/GetPackageBootLoaderChildLayer.java
    java/nio/file/Files/CopyAndMove.java
    java/util/concurrent/locks/Lock/TimedAcquireLeak.java
    java/util/logging/TestLoggerWeakRefLeak.java

Product(s) tested: 
JDK11:
 openjdk version "11.0.5" 2019-10-15
20:42:00  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10-201908081809)
20:42:00  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10-201908081809, mixed mode)OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-201907290328-b10)
JDK13:
06:20:05  openjdk version "13" 2019-09-17
06:20:05  OpenJDK Runtime Environment AdoptOpenJDK (build 13+32-201908100404)
06:20:05  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+32-201908100404, mixed mode, sharing)

OS/architecture: macosx
Platform specific: yes

Reproducibility: yes

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_mac/26/consoleFull
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk13_hs_sanity.openjdk_x86-64_mac/18/consoleFull

**Comment by sophia-guo** [comment]
Related JBS:

java/lang/System/LoggerFinder/modules/JDKLoggerForImageTest.java
java/lang/System/LoggerFinder/modules/LoggerInImageTest.java
java/lang/System/LoggerFinder/modules/NamedLoggerForImageTest.java
java/lang/System/LoggerFinder/modules/UnnamedLoggerForImageTest.java
jdk/modules/etc/DefaultModules.java
jdk/modules/incubator/ImageModules.java

JBS: https://bugs.openjdk.java.net/browse/JDK-8226773
which seems reported for different issue but affected failure cases listed are exactly same. Maybe same issue, if not need to create a new JBS for those failures.

java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java

```
Stacktrace

Execution failed: `main' threw exception: java.net.SocketException: Cannot allocate memory    

Standard Output

Test DatagramChannel to INET socket
join 225.4.5.6 @ en0
Send message from 46.20.235.28 -> group 225.4.5.6 (id=0xf97953e2)
Waiting to receive message
Received message from /46.20.235.28 (id=0xf97953e2)
Message expected
block 46.20.235.28
Exclude-mode filtering not supported!
join 225.4.5.6 @ en0 only-source 1.2.3.4
Send message from 46.20.235.28 -> group 225.4.5.6 (id=0xec1aa785)
Waiting to receive message
No message received (correct)
join 225.4.5.6 @ en0 only-source 46.20.235.28
    

Standard Error

java.net.SocketException: Cannot allocate memory
	at java.base/sun.nio.ch.Net.joinOrDrop4(Native Method)
	at java.base/sun.nio.ch.Net.join4(Net.java:536)
	at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:999)
	at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1027)
	at MulticastSendReceiveTests.test(MulticastSendReceiveTests.java:227)
	at MulticastSendReceiveTests.main(MulticastSendReceiveTests.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
No JBS reports.

java/lang/Class/GetPackageBootLoaderChildLayer.java

```
Stacktrace

Execution failed: `main' threw exception: java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid53097 is not secure: file's group should be the current group (which is -1) but the group is 0    

Standard Output

    

Standard Error

java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid53097 is not secure: file's group should be the current group (which is -1) but the group is 0
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at GetPackageBootLoaderChildLayer.main(GetPackageBootLoaderChildLayer.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:830)

JavaTest Message: Test threw exception: java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid53097 is not secure: file's group should be the current group (which is -1) but the group is 0
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid53097 is not secure: file's group should be the current group (which is -1) but the group is 0
```

No related JBS 

java/nio/file/Files/CopyAndMove.java
https://bugs.openjdk.java.net/browse/JDK-8006645

java/util/concurrent/locks/Lock/TimedAcquireLeak.java
https://bugs.openjdk.java.net/browse/JDK-8155727

java/util/logging/TestLoggerWeakRefLeak.java
https://bugs.openjdk.java.net/browse/JDK-8199767

**Comment by SehrishHussain** [comment]
Another test fail for openjdk18 on aix-ppc64:
**java/lang/System/FileEncodingTest** 
Jenkins URL: https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.openjdk_ppc64_aix/16/testReport/junit/java_lang_ProcessBuilder_Basic/java_id0/Basic_id0/
TRSS Link: https://trss.adoptium.net/allTestsInfo?buildId=616d7be7c6182d02177fff67&limit=5&hasChildren=false

**Comment by llxia** [comment]
FileEncodingTest is reenabled. The test has been fixed in OpenJDK head and for OpenJ9 jdk18. https://github.com/adoptium/aqa-tests/pull/3367

**Comment by sophia-guo** [comment]
The fix for FileEncodingTest has not been backport to jdk18.  https://bugs.openjdk.java.net/browse/JDK-8282042. It will be reenabled for jdk18 once backport is done.

**Comment by sophia-guo** [comment]
java/lang/System/FileEncoding is only excluded in jdk18. Ignore.

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9379/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9379/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9379/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9379/

**Comment by sophia-guo** [comment]
All other tests will be enabled except java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java, which consistently has same error as before 

```
Standard Error

java.net.SocketException: Cannot allocate memory
	at java.base/sun.nio.ch.Net.joinOrDrop4(Native Method)
	at java.base/sun.nio.ch.Net.join4(Net.java:536)
	at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:999)
	at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1027)
	at MulticastSendReceiveTests.test(MulticastSendReceiveTests.java:227)
	at MulticastSendReceiveTests.main(MulticastSendReceiveTests.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Need more investigation or help to open the issue in JBS.

**Comment by smlambert** [comment]
> Need more investigation or help to open the issue in JBS.

May be related to how the Orka Mac nodes are configured, see 4 other multicast related test case failures which still need an issue opened for them, see first item in the list here: https://github.com/adoptium/aqa-tests/issues/5156#issuecomment-2025508317
