### ISSUE TITLE
Intermittent Failures List

### ISSUE THREAD

**Issue by adam-thorpe** [adoptium/aqa-tests#1596]
```
sun/nio/cs/FindDecoderBugs.java
sun/nio/cs/SurrogateGB18030Test.java
sun/nio/cs/Test4206507.java
sun/nio/cs/TestConverterDroppedCharacters.java
sun/nio/cs/TestCp834_SBCS.java
sun/nio/cs/TestEBCDICLineFeed.java
sun/nio/cs/TestGB18030.java
sun/nio/cs/TestHKSCS.java
sun/nio/cs/TestIBMBugs.java
sun/nio/cs/TestISO2022CNDecoder.java
sun/nio/cs/TestISO2022JP.java
sun/nio/cs/TestISO2022JPEncoder.java
sun/nio/cs/TestISO2022JPSubBytes.java
sun/nio/cs/TestIllegalISO2022Esc.java
sun/nio/cs/TestIllegalSJIS.java
sun/nio/cs/TestJIS0208Decoder.java
sun/nio/cs/TestJIS0212Decoder.java
sun/nio/cs/TestMS5022X.java
sun/nio/cs/TestMiscEUC_JP.java
sun/nio/cs/TestSJIS0213.java
sun/nio/cs/TestSJIS0213_SM.java
```
Test_openjdk11_j9_sanity.openjdk_s390x_linux 02-Feb-2020
Test_openjdk11_j9_sanity.openjdk_s390x_linux_xl 10-Feb-2020
```
Various NullPointerException eg.

java.lang.NullPointerException
	at java.base/sun.reflect.misc.ReflectUtil.isAncestor(ReflectUtil.java:178)
	at java.base/sun.reflect.misc.ReflectUtil.needsPackageAccessCheck(ReflectUtil.java:204)
	at java.base/java.lang.Class.checkNonSunProxyMemberAccess(Class.java:279)
	at java.base/java.lang.Class.newInstance(Class.java:2081)
	at java.base/sun.nio.cs.StandardCharsets.lookup(StandardCharsets.java:1322)
	at java.base/sun.nio.cs.StandardCharsets.charsetForName(StandardCharsets.java:1338)
	at java.base/java.nio.charset.Charset.lookup2(Charset.java:473)
	at java.base/java.nio.charset.Charset.lookup(Charset.java:462)
	at java.base/java.nio.charset.Charset.isSupported(Charset.java:503)
	at java.base/java.lang.StringCoding.lookupCharset(StringCoding.java:101)
	at java.base/java.lang.StringCoding.encode(StringCoding.java:412)
	at java.base/java.lang.String.getBytes(String.java:1805)
	at TestHKSCS.main(TestHKSCS.java:44)
```
-> Seems to only occur on `test-marist-ubuntu1604-s390x-4`

**Comment by M-Davies** [comment]
java/util/TimeZone/TimeZoneTest.java Test_openjdk8_hs_sanity.openjdk_x86-64_linux 4-2-2020
Looks like a jenkins issue, test passes locally #1356 
```
TimeZoneTest {
  TestShortZoneIDs {
    Fail: Expected Zone["BET", GMT-3:00, Standard]; got Zone["BET", GMT-3:00, Daylight]
    Uncaught exception thrown in test method TestShortZoneIDs

java.lang.RuntimeException: Uncaught exception thrown in test method TestShortZoneIDs
	at IntlTest.errImpl(IntlTest.java:190)
	at IntlTest.errln(IntlTest.java:177)
	at IntlTest.run(IntlTest.java:123)
	at TimeZoneTest.main(TimeZoneTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by M-Davies** [comment]
java/util/Objects/CheckIndex.java Test_openjdk8_hs_sanity.openjdk_x86-64_linux 4-2-2020
Looks like a jenkins issue, ran on `test-scaleway-ubuntu1604-x64-1`, test passes locally
```
error: cannot find symbol
09:19:58  import com.sun.crypto.provider.Preconditions;
```

**Comment by M-Davies** [comment]
java/util/Locale/Bug8040211.java Test_openjdk8_hs_sanity.openjdk_x86-64_linux 3-2-2020
Looks like a jenkins issue, ran on test-scaleway-ubuntu1604-x64-1, test passes locally
```
   language parse() test failed.
  test_parse() failed.
java.lang.RuntimeException: Failed.
	at Bug8040211.main(Bug8040211.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by M-Davies** [comment]
sun/misc/URLClassPath/JarClassPathFileEntry.java Test_openjdk8_hs_sanity.openjdk_x86-64_linux 3-2-2020
Looks like a jenkins issue, ran on `test-scaleway-ubuntu1604-x64-1`, test passes locally
```
08:22:25  STDOUT:
08:22:25  Creating Context.jar with Class-Path: file:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1580716287318/jdk_lang_0/work/classes/sun/misc/URLClassPath/OTHER/Other.jar
08:22:25  STDERR:
08:22:25  java.lang.ClassNotFoundException: Other
08:22:25  	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
08:22:25  	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
08:22:25  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
08:22:25  	at java.lang.Class.forName0(Native Method)
08:22:25  	at java.lang.Class.forName(Class.java:348)
08:22:25  	at JarClassPathFileEntry.main(JarClassPathFileEntry.java:89)
08:22:25  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:22:25  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:22:25  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:22:25  	at java.lang.reflect.Method.invoke(Method.java:498)
08:22:25  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
08:22:25  	at java.lang.Thread.run(Thread.java:748)
```

**Comment by M-Davies** [comment]
sun/misc/IOUtils/ReadAllBytes.java.ReadAllBytes & sun/misc/IOUtils/ReadNBytes.java.ReadNBytes
Test_openjdk8_hs_sanity.openjdk_x86-64_linux 
3-2-2020
```
08:22:16  /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc/IOUtils/ReadNBytes.java:70: error: method readNBytes in class IOUtils cannot be applied to given types;
08:22:16          int nread = IOUtils.readNBytes(in, readBytes, 0, readBytes.length);
08:22:16                             ^
08:22:16    required: InputStream,int
08:22:16    found: WrapperInputStream,byte[],int,int
08:22:16    reason: actual and formal argument lists differ in length
08:22:16  /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc/IOUtils/ReadNBytes.java:81: error: method readNBytes in class IOUtils cannot be applied to given types;
08:22:16          nread = IOUtils.readNBytes(in, readBytes, 0, readBytes.length);
08:22:16                         ^
08:22:16    required: InputStream,int
08:22:16    found: WrapperInputStream,byte[],int,int
08:22:16    reason: actual and formal argument lists differ in length
08:22:16  /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc/IOUtils/ReadNBytes.java:95: error: method readNBytes in class IOUtils cannot be applied to given types;
08:22:16          check((x = IOUtils.readNBytes(in, tmp, 0, tmp.length)) == 0,
```
Both tests failed in this way

**Comment by adam-thorpe** [comment]
**java/lang/ProcessBuilder/Basic.java#id0** openjdk11_hs_sanity.openjdk_s390x_linux 05-Feb-2020
```
This appears to be a Unix system.
Testing ASCII environment values
Testing Latin1 environment values
Testing Unicode environment values
Testing directory .
Testing directory ..
Testing directory /
Testing directory /bin
cmdp
cmdp 0: /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_s390x_linux/openjdkbinary/j2sdk-image/bin/java
cmdp 1: -XX:+DisplayVMOutputToStderr
cmdp 2: -classpath
cmdp 3: /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_s390x_linux/openjdk-tests/TKG/test_output_15809311881598/jdk_lang_0/work/classes/0/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_s390x_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_s390x_linux/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_s390x_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar
cmdp 4: Basic$JavaChild
cmdp 5: System.getenv()
envp
envp 0: LC_ALL=C\u0000\u0000
envp 1: FO\u0000=B\u0000R
 waitFor process: delta: 29982

Passed = 8984, failed = 1

    
Standard Error
java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:275)
	at Basic$12.run(Basic.java:2110)
java.lang.AssertionError: Some tests failed
	at Basic.main(Basic.java:2742)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by M-Davies** [comment]
**java/net/Inet6Address/B6206527.java** & **java/net/ipv6tests/B6521014.java**
openjdk11_hs/j9_sanity.openjdk_x64_linux

B6206527.java
```
java.net.BindException: Cannot assign requested address (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
	at B6206527.main(B6206527.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

B6521014.java
```
java.net.ConnectException: Network is unreachable (connect failed)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at B6521014.test1(B6521014.java:78)
	at B6521014.main(B6521014.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by adam-thorpe** [comment]
**java/nio/channels/AsynchronousSocketChannel/StressLoopback.java**
Test_openjdk8_j9_sanity.openjdk_ppc64_aix 11-Feb-2020
```
6080004378 -> 6080004378 (PASS)
5719879350 -> 5719879350 (PASS)
4186481217 -> 4186481217 (PASS)
2727255960 -> 2727255960 (PASS)
6688600020 -> 6688600020 (PASS)
4665405175 -> 4665405175 (PASS)
4457082418 -> 4457082418 (PASS)
Total sent 32925 MB

[Timeout]
```

**Comment by adam-thorpe** [comment]
**java/util/zip/ZipFile/TestCleaner.java**
Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl 10-Feb-2020
```
[Timeout]
```

**Comment by M-Davies** [comment]
@adam-thorpe https://github.com/AdoptOpenJDK/openjdk-tests/issues/1596#issuecomment-584552270 has been raised https://github.com/AdoptOpenJDK/openjdk-tests/issues/1612

**Comment by adam-thorpe** [comment]
**java/net/httpclient/websocket/MessageQueueDriver.java**
Test_openjdk11_j9_sanity.openjdk_ppc64_aix 17-Feb-2020
```
Timeout
```

**Comment by adam-thorpe** [comment]
**java/math/BigInteger/largeMemory/SymmetricRangeTests.java**
Test_openjdk14_j9_sanity.openjdk_x86-64_windows_xl 18-Feb-2020
```
Testing overflow in BigInteger.makePositive
Testing Bug 8021204

java.lang.OutOfMemoryError
	at java.base/java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:269)
	at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:261)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:228)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:808)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:240)
	at SymmetricRangeTests.testBug8021204(SymmetricRangeTests.java:103)
	at SymmetricRangeTests.main(SymmetricRangeTests.java:625)
```

**Comment by M-Davies** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1596#issuecomment-583331517

> **java/net/Inet6Address/B6206527.java** & **java/net/ipv6tests/B6521014.java**
> openjdk11_hs/j9_sanity.openjdk_x64_linux 03-02-2020
> 
> B6206527.java
> 
> ```
> java.net.BindException: Cannot assign requested address (Bind failed)
> 	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
> 	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
> 	at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
> 	at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
> 	at B6206527.main(B6206527.java:58)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```
> 
> B6521014.java
> 
> ```
> java.net.ConnectException: Network is unreachable (connect failed)
> 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
> 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
> 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
> 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
> 	at java.base/java.net.Socket.connect(Socket.java:609)
> 	at B6521014.test1(B6521014.java:78)
> 	at B6521014.main(B6521014.java:107)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```

Occurred again on [test-packet-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1) on job [jdk8/linux_x64/J9](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux) 20/02/2020

Count = 2

**Comment by M-Davies** [comment]
**java/nio/channels/SocketChannel/CloseDuringConnect.java**
Test_openjdk/job/Test_openjdk14_j9_sanity.openjdk_x86-64_mac_xl 21-02-2020

Fails roughly 1/4 times on `test-macincloud-macos1013-x64-1` and `test-macincloud-macos1013-x64-2` at least
```
11:16:59  [2020-02-21 11:16:57,471] Agent[0]: stderr: Assertion failed at /Users/jenkins/workspace/build-scripts/jobs/jdk14/jdk14-mac-x64-openj9-macosXL/workspace/build/src/build/macosx-x86_64-server-release/vm/compiler/../omr/compiler/il/OMRBlock.cpp:1041: storeRegNodeInfoEntry != storeNodeInfo->end()
11:16:59  [2020-02-21 11:16:57,471] Agent[0]: stderr: VMState: 0x000561ff
11:16:59  [2020-02-21 11:16:57,471] Agent[0]: stderr: 	We should have a regStore pre split point that can be used to allocate register for replacement node
11:16:59  [2020-02-21 11:16:57,471] Agent[0]: stderr: compiling java/util/concurrent/locks/AbstractQueuedSynchronizer$ConditionObject.awaitNanos(J)J at level: very-hot (profiling)
11:16:59  [2020-02-21 11:16:57,471] Agent[0]: stderr: 
11:16:59  [2020-02-21 11:16:57,472] Agent[0]: stderr: JVMDUMP039I Processing dump event "abort", detail "" at 2020/02/21 11:16:57 - please wait.
11:16:59  [2020-02-21 11:16:57,474] Agent[0]: stderr: JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15822837806546/jdk_custom_0/work/scratch/0/core.20200221.111657.72286.0001.dmp' in response to an event
11:17:03  [2020-02-21 11:17:03,075] Agent[0]: stderr: JVMDUMP012E Error in System dump: The core file created by child process with pid = 72300 was not found. Expected to find core file with name "/cores/core.72300"
11:17:03  [2020-02-21 11:17:03,075] Agent[0]: stderr: JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15822837806546/jdk_custom_0/work/scratch/0/javacore.20200221.111657.72286.0002.txt' in response to an event
11:17:03  [2020-02-21 11:17:03,247] Agent[0]: stderr: JVMDUMP010I Java dump written to /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15822837806546/jdk_custom_0/work/scratch/0/javacore.20200221.111657.72286.0002.txt
11:17:03  [2020-02-21 11:17:03,247] Agent[0]: stderr: JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15822837806546/jdk_custom_0/work/scratch/0/Snap.20200221.111657.72286.0003.trc' in response to an event
11:17:03  [2020-02-21 11:17:03,349] Agent[0]: stderr: JVMDUMP010I Snap dump written to /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15822837806546/jdk_custom_0/work/scratch/0/Snap.20200221.111657.72286.0003.trc
11:17:03  [2020-02-21 11:17:03,350] Agent[0]: stderr: JVMDUMP007I JVM Requesting JIT dump using '/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15822837806546/jdk_custom_0/work/scratch/0/jitdump.20200221.111657.72286.0004.dmp'
11:17:03  [2020-02-21 11:17:03,636] Agent[0]: stderr: JVMDUMP010I JIT dump written to /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15822837806546/jdk_custom_0/work/scratch/0/jitdump.20200221.111657.72286.0004.dmp
11:17:03  [2020-02-21 11:17:03,636] Agent[0]: stderr: JVMDUMP013I Processed dump event "abort", detail "".

TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details
```

**Comment by M-Davies** [comment]
**java/net/InetAddress/CheckJNI.java**
- `Test_openjdk8_j9_sanity.openjdk_x86-64_mac` on `test-macincloud-macos1014-x64-2` 24-02-2020
- Spotted before https://github.com/AdoptOpenJDK/openjdk-tests/issues/1259#issue-478665073
- Open JBS Entry https://bugs.openjdk.java.net/browse/JDK-8178789
```
Standard Output
Testing IPv4 Socket/ServerSocket
Testing IPv4 DatagramSocket
Testing IPv6 Socket
    
Standard Error
JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:262)
	at CheckJNI.main(CheckJNI.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:821)
```

**Comment by smlambert** [comment]
Clearing a milestone off of this issue as its 'on-going'

**Comment by M-Davies** [comment]
**java/util/stream/test/org/openjdk/tests/java/util/stream/TabulatorsTest.java**
- Usually fails 1/10 times on `JDK8/HS/s390x_linux`
```
Program `/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960416ms). 
```

**java/util/stream/test/org/openjdk/tests/java/util/stream/FlatMapOpTest.java**
- Usually fails 5/10 times on `JDK8/HS/s390x_linux`
```
Program `/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960416ms). 
```

**java/util/stream/test/org/openjdk/tests/java/util/stream/StreamBuilderTest.java**
- Usually fails 3/10 times on `JDK8/HS/s390x_linux`
```
Program `/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960416ms). 
```

**Comment by M-Davies** [comment]
**java/util/concurrent/FutureTask/ExplicitSet.java**
**java/util/concurrent/Semaphore/RacingReleases.java**
Intermittent timeouts on JDK8/HS/windows&windows_XL (likely due to https://bugs.openjdk.java.net/browse/JDK-8047181)
