### ISSUE TITLE
thorntail-mp-tck external test fails due to SocketException: Protocol family unavailable

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#1855]
**Describe the bug**
SocketException: Protocol family unavailable

```
[2020-06-15T20:08:06.339Z] [0m[31m2020-06-15 20:08:06,057 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service org.wildfly.undertow.listener.default: org.jboss.msc.service.StartException in service org.wildfly.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
[2020-06-15T20:08:06.339Z] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:211)
[2020-06-15T20:08:06.339Z] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
[2020-06-15T20:08:06.339Z] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
[2020-06-15T20:08:06.339Z] 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
[2020-06-15T20:08:06.339Z] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[2020-06-15T20:08:06.339Z] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
[2020-06-15T20:08:06.339Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
[2020-06-15T20:08:06.339Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
[2020-06-15T20:08:06.339Z] 	at java.lang.Thread.run(Thread.java:823)
[2020-06-15T20:08:06.339Z] Caused by: java.net.SocketException: Protocol family unavailable
[2020-06-15T20:08:06.339Z] 	at sun.nio.ch.Net.bind0(Native Method)
[2020-06-15T20:08:06.339Z] 	at sun.nio.ch.Net.bind(Net.java:433)
[2020-06-15T20:08:06.339Z] 	at sun.nio.ch.Net.bind(Net.java:425)
[2020-06-15T20:08:06.339Z] 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
[2020-06-15T20:08:06.340Z] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
[2020-06-15T20:08:06.340Z] 	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:178)
[2020-06-15T20:08:06.340Z] 	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:310)
[2020-06-15T20:08:06.340Z] 	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:106)
[2020-06-15T20:08:06.340Z] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:199)
[2020-06-15T20:08:06.340Z] 	... 8 more
```

**To Reproduce**
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_thorntail-mp-tck/323/

Note: This job has been failing with this issue for months, so if that specific job has expired, just look at the latest run.

**Expected behavior**
I expect the test to pass.

**Comment by adamfarley** [comment]
According to [this](https://stackoverflow.com/questions/49323827/wildfly-swarm-on-docker-in-macos), [this](https://developer.jboss.org/thread/241488), and [this](https://github.com/elastic/elasticsearch/issues/15143), the problem is that we need to set a property, and we're not doing it.

[Here's](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_thorntail-mp-tck/334/console) a trial run with a custom thorntail where the property is set in the only pom.xml file that 
a) has the string "127.0.0"
and
b) does not have the recommended property set (java.net.preferIPv4Stack)

**Comment by adamfarley** [comment]
Didn't work. Setting aside to focus on other issues.

**Comment by smlambert** [comment]
Since this was found to be failing and not disabled, I will disable it.  Given that Thorntail has [announced their "end of life"](https://thorntail.io/posts/the-end-of-an-era/) I will also plan to remove the target completely in an upcoming PR.

**Comment by smlambert** [comment]
auto exclude test thorntail_microprofile_tck

**Comment by jnjerin** [comment]
Since removal of this test from external tests, can we close this issue as well? @smlambert @sophia-guo @llxia

**Comment by smlambert** [comment]
yes, thanks @jnjerin !
