### ISSUE TITLE
extended.openjdk failure: javax/imageio/AppletResourceTest.java : FontConfiguration NPE

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#2357]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/25/console
Fails both Hotspot and OpenJ9:
```
12:30:22  openjdk version "1.8.0_292"
12:30:22  OpenJDK Runtime Environment (build 1.8.0_292-202103091156-b05)
12:30:22  Eclipse OpenJ9 VM (build openj9-0.26.0-m1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210309_972 (JIT enabled, AOT enabled)
12:30:22  OpenJ9   - b227feba2
12:30:22  OMR      - 4665e2f72
12:30:22  JCL      - 1780cbc92b based on jdk8u292-b05)
```
```
13:29:39  java.lang.NullPointerException
13:29:39  	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
13:29:39  	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
13:29:39  	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
13:29:39  	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
13:29:39  	at sun.font.SunFontManager$2.run(SunFontManager.java:441)
13:29:39  	at java.security.AccessController.doPrivileged(AccessController.java:682)
13:29:39  	at sun.font.SunFontManager.<init>(SunFontManager.java:386)
13:29:39  	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
13:29:39  	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
13:29:39  	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
13:29:39  	at java.lang.Class.newInstance(Class.java:2038)
13:29:39  	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
13:29:39  	at java.security.AccessController.doPrivileged(AccessController.java:682)
13:29:39  	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
13:29:39  	at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
13:29:39  	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
13:29:39  	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:250)
13:29:39  	at sun.awt.X11.XComponentPeer.getFontMetrics(XComponentPeer.java:683)
13:29:39  	at sun.awt.X11.XLabelPeer.getFontMetrics(XLabelPeer.java:48)
13:29:39  	at sun.awt.X11.XLabelPeer.getMinimumSize(XLabelPeer.java:70)
13:29:39  	at sun.awt.X11.XComponentPeer.getPreferredSize(XComponentPeer.java:606)
13:29:39  	at java.awt.Component.preferredSize(Component.java:2643)
13:29:39  	at java.awt.Component.getPreferredSize(Component.java:2626)
13:29:39  	at java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1115)
13:29:39  	at java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:916)
13:29:39  	at java.awt.GridBagLayout.preferredLayoutSize(GridBagLayout.java:736)
13:29:39  	at java.awt.Container.preferredSize(Container.java:1799)
13:29:39  	at java.awt.Container.getPreferredSize(Container.java:1783)
13:29:39  	at java.awt.Window.pack(Window.java:809)
13:29:39  	at com.sun.javatest.regtest.agent.AppletWrapper$AppletRunnable.run(AppletWrapper.java:142)
13:29:39  	at java.lang.Thread.run(Thread.java:823)
13:29:39  STATUS:Failed.Applet thread threw exception: java.lang.NullPointerException
```
Possibly a fontconfig setup issue? or an upstream problem?

**Comment by aahlenst** [comment]
@andrew-m-leonard I suspect a machine issue. [See the list of libraries that need to be present](https://blog.adoptopenjdk.net/2021/01/prerequisites-for-font-support-in-adoptopenjdk/).

**Comment by lumpfish** [comment]
I think this affects a few tests and is being seen when tests are running on docker images:
Failing test run:https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_x86-64_linux/16/consoleFull
To rerun:  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=openjdk&PLATFORM=x86-64_linux_mixed&TARGET=jdk_imageio_0
Machine: test-docker-fedora33-x64-1
Failing tests:
```
javax/imageio/plugins/shared/ImageWriterCompressionTest.java
javax/imageio/AppletResourceTest.java
```

**Comment by sxa** [comment]
Thanks - attaching to https://github.com/AdoptOpenJDK/openjdk-tests/issues/2138

**Comment by sxa** [comment]
Haven't managed to properly look at this today other than trying l grinders on a real and dockerised Ubuntu of the same level. Will aim to continue tomorrow

**Comment by sxa** [comment]
It's not specific to any particular docker image - seen on Ubuntu and Fedora ones

**Comment by sxa** [comment]
As Andreas suggested, adding `fontconfig` has allowed it to pass on [Fedora](https://ci.adoptopenjdk.net/job/Grinder/75/) and [Ubuntu](https://ci.adoptopenjdk.net/job/Grinder/76/). I'll get that deployed to all the docker systems and added into the playbooks.

**Comment by lumpfish** [comment]
I've seen another occurrence on machine `test-docker-fedora33-x64-1` (https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux_testList_1/2/console)

**Comment by sxa** [comment]
Hmmm `fontconfig` is installed on there so I'm not sure what's going on with that system ([replicated on grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/789/console)) - I'll try on the other 2 Fedora33 machines - [790](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/790/console) [791](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/791/console)

**Comment by sxa** [comment]
Hmmm the last two are failing but with a different error
```
11:28:13  STDOUT:
11:28:13  STDERR:
11:28:13  java.lang.RuntimeException: Test failed. Did not get expected IIOException
11:28:13  	at MaxLengthKeywordReadTest.main(MaxLengthKeywordReadTest.java:63)
11:28:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:28:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:28:13  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:28:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:28:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:28:13  	at java.base/java.lang.Thread.run(Thread.java:836)
11:28:13  
11:28:13  JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed. Did not get expected IIOException
11:28:13  JavaTest Message: shutting down test
11:28:13  
11:28:13  STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Test failed. Did not get expected IIOException
11:28:13  rerun:
11:28:13  cd /home/jenkins/workspace/Grinder/openjdk-tests/TKG/output_16233198211531/jdk_imageio_0/work/javax/imageio/plugins/png/MaxLengthKeywordReadTest && \
```
