### ISSUE TITLE
openjdk tests fail on jdk17 with jtreg exception java.lang.IllegalArgumentException: 6+1

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-tests#2652]
openjdk tests are failing on jdk17 with this jtreg exception:
```
10:33:45  Error: Unexpected exception occurred! java.lang.IllegalArgumentException: 6+1
10:33:45  java.lang.IllegalArgumentException: 6+1
10:33:45  	at com.sun.javatest.regtest.tool.Version.<init>(Version.java:80)
10:33:45  	at com.sun.javatest.regtest.config.TestProperties$Cache$Entry.initAllowSmartActionArgs(TestProperties.java:452)
10:33:45  	at com.sun.javatest.regtest.config.TestProperties$Cache$Entry.<init>(TestProperties.java:262)
10:33:45  	at com.sun.javatest.regtest.config.TestProperties$Cache.getEntryInternal(TestProperties.java:509)
10:33:45  	at com.sun.javatest.regtest.config.TestProperties$Cache.getEntry(TestProperties.java:500)
10:33:45  	at com.sun.javatest.regtest.config.TestProperties.<init>(TestProperties.java:57)
10:33:45  	at com.sun.javatest.regtest.config.RegressionTestSuite.<init>(RegressionTestSuite.java:80)
10:33:45  	at com.sun.javatest.regtest.config.RegressionTestSuite.open(RegressionTestSuite.java:65)
10:33:45  	at com.sun.javatest.regtest.config.TestManager.getTestSuites(TestManager.java:165)
10:33:45  	at com.sun.javatest.regtest.tool.Tool.run(Tool.java:1124)
10:33:45  	at com.sun.javatest.regtest.tool.Tool.run(Tool.java:1075)
10:33:45  	at com.sun.javatest.regtest.tool.Tool.main(Tool.java:147)
10:33:45  	at com.sun.javatest.regtest.Main.main(Main.java:58)
```
Example failing jobs: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_linux/

**Comment by sophia-guo** [comment]
Due to https://github.com/adoptium/ci-jenkins-pipelines/issues/165 we are not build jtreg5 or jtreg6 correctly.

**Comment by sophia-guo** [comment]
Fixed. Close it.
