### ISSUE TITLE
extended.openjdk jdk_tools demo/jvmti tests fail because native libs cannot be found

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-tests#2655]
Some demo/jvmti tests fail with message similar to:
```
Could not find agent library /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so in absolute path, with error: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so: cannot open shared object file: No such file or directory
```
The tests only exist in jdk8.  All platforms are affected.

These are failing tests and the their associated missing native library:
```
TEST: demo/jvmti/gctest/Gctest.java
j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so
TEST: demo/jvmti/heapTracker/HeapTrackerTest.java
j2sdk-image/jre/../demo/jvmti/heapTracker/lib/libheapTracker.so
TEST: demo/jvmti/heapViewer/HeapViewerTest.java
j2sdk-image/jre/../demo/jvmti/heapViewer/lib/libheapViewer.so
TEST: demo/jvmti/minst/MinstTest.java
j2sdk-image/jre/../demo/jvmti/minst/lib/libminst.so
TEST: demo/jvmti/mtrace/TraceJFrame.java
j2sdk-image/jre/../demo/jvmti/mtrace/lib/libmtrace.so
TEST: demo/jvmti/versionCheck/FailsWhenJvmtiVersionDiffers.java
j2sdk-image/jre/../demo/jvmti/versionCheck/lib/libversionCheck.so
TEST: demo/jvmti/waiters/WaitersTest.java
j2sdk-image/jre/../demo/jvmti/waiters/lib/libwaiters.so
```
Full output of a failing test:
```
19:12:32  TEST: demo/jvmti/gctest/Gctest.java
19:12:32  TEST JDK: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image
19:12:32  
19:12:32  ACTION: compile -- Passed. Compilation successful
19:12:32  REASON: User specified action: run compile ../DemoRun.java 
19:12:32  TIME:   0.091 seconds
19:12:32  messages:
19:12:32  command: compile /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/../DemoRun.java
19:12:32  reason: User specified action: run compile ../DemoRun.java 
19:12:32  Mode: agentvm
19:12:32  Agent id: 1
19:12:32  elapsed time (seconds): 0.091
19:12:32  configuration:
19:12:32  Boot Layer (javac runtime environment)
19:12:32    class path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar
19:12:32  
19:12:32  javac compilation environment
19:12:32    source path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest
19:12:32    class path:  /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest
19:12:32                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest
19:12:32                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
19:12:32  
19:12:32  rerun:
19:12:32  cd /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/scratch/3 && \
19:12:32  DISPLAY=:0 \
19:12:32  HOME=/home/jenkins \
19:12:32  PATH=/bin:/usr/bin:/usr/sbin \
19:12:32      /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/javac \
19:12:32          -J-ea \
19:12:32          -J-esa \
19:12:32          -J-Xmx512m \
19:12:32          -J-XX:-UseCompressedOops \
19:12:32          -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
19:12:32          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
19:12:32          -J-Dtest.compiler.opts= \
19:12:32          -J-Dtest.java.opts= \
19:12:32          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
19:12:32          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
19:12:32          -J-Dtest.timeout.factor=8.0 \
19:12:32          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test \
19:12:32          -J-Dtest.name=demo/jvmti/gctest/Gctest.java \
19:12:32          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/Gctest.java \
19:12:32          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -d /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -sourcepath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -classpath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/../DemoRun.java
19:12:32  
19:12:32  ACTION: build -- Passed. Build successful
19:12:32  REASON: User specified action: run build BigHello Gctest 
19:12:32  TIME:   0.049 seconds
19:12:32  messages:
19:12:32  command: build BigHello Gctest
19:12:32  reason: User specified action: run build BigHello Gctest 
19:12:32  Test directory:
19:12:32    compile: BigHello, Gctest
19:12:32  elapsed time (seconds): 0.049
19:12:32  
19:12:32  ACTION: compile -- Passed. Compilation successful
19:12:32  REASON: .class file out of date or does not exist
19:12:32  TIME:   0.049 seconds
19:12:32  messages:
19:12:32  command: compile -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/BigHello.java /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/Gctest.java
19:12:32  reason: .class file out of date or does not exist
19:12:32  Mode: agentvm
19:12:32  Agent id: 1
19:12:32  elapsed time (seconds): 0.049
19:12:32  configuration:
19:12:32  Boot Layer (javac runtime environment)
19:12:32    class path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar
19:12:32  
19:12:32  javac compilation environment
19:12:32    source path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest
19:12:32    class path:  /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest
19:12:32                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest
19:12:32                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
19:12:32  
19:12:32  rerun:
19:12:32  cd /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/scratch/3 && \
19:12:32  DISPLAY=:0 \
19:12:32  HOME=/home/jenkins \
19:12:32  PATH=/bin:/usr/bin:/usr/sbin \
19:12:32      /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/javac \
19:12:32          -J-ea \
19:12:32          -J-esa \
19:12:32          -J-Xmx512m \
19:12:32          -J-XX:-UseCompressedOops \
19:12:32          -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
19:12:32          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
19:12:32          -J-Dtest.compiler.opts= \
19:12:32          -J-Dtest.java.opts= \
19:12:32          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
19:12:32          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
19:12:32          -J-Dtest.timeout.factor=8.0 \
19:12:32          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test \
19:12:32          -J-Dtest.name=demo/jvmti/gctest/Gctest.java \
19:12:32          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/Gctest.java \
19:12:32          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -d /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -sourcepath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -classpath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar \
19:12:32          -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/BigHello.java /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/Gctest.java
19:12:32  
19:12:32  ACTION: build -- Passed. All files up to date
19:12:32  REASON: Named class compiled on demand
19:12:32  TIME:   0.0 seconds
19:12:32  messages:
19:12:32  command: build Gctest
19:12:32  reason: Named class compiled on demand
19:12:32  elapsed time (seconds): 0.0
19:12:32  
19:12:32  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Test failed - exit return code non-zero (exitStatus==1)
19:12:32  REASON: User specified action: run main Gctest BigHello 
19:12:32  TIME:   0.023 seconds
19:12:32  messages:
19:12:32  command: main Gctest BigHello
19:12:32  reason: User specified action: run main Gctest BigHello 
19:12:32  Mode: agentvm
19:12:32  Agent id: 5
19:12:32  elapsed time (seconds): 0.023
19:12:32  configuration:
19:12:32  Boot Layer
19:12:32    class path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/junit.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/testng.jar
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/jcommander.jar
19:12:32  
19:12:32  Test Layer
19:12:32    class path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest
19:12:32                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest
19:12:32  
19:12:32  rerun:
19:12:32  cd /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/scratch/3 && \
19:12:32  DISPLAY=:0 \
19:12:32  HOME=/home/jenkins \
19:12:32  PATH=/bin:/usr/bin:/usr/sbin \
19:12:32      /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java \
19:12:32          -Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
19:12:32          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
19:12:32          -Dtest.compiler.opts= \
19:12:32          -Dtest.java.opts= \
19:12:32          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
19:12:32          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
19:12:32          -Dtest.timeout.factor=8.0 \
19:12:32          -Dtest.root=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test \
19:12:32          -Dtest.name=demo/jvmti/gctest/Gctest.java \
19:12:32          -Dtest.file=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest/Gctest.java \
19:12:32          -Dtest.src=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest \
19:12:32          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest \
19:12:32          -classpath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/demo/jvmti/gctest:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar \
19:12:32          Gctest BigHello
19:12:32  STDOUT:
19:12:32  Starting: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/bin/java -cp /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16236919171990/jdk_tools_1/work/classes/1/demo/jvmti/gctest -Xcheck:jni -Xverify:all -agentpath:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so BigHello
19:12:32  Error occurred during initialization of VM
19:12:32  Could not find agent library /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so in absolute path, with error: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so: cannot open shared object file: No such file or directory
19:12:32  Exit code is 1
19:12:32  <beginning of Error Stream buffer>
19:12:32  
19:12:32  <end of buffer>
19:12:32  <beginning of Input Stream buffer>
19:12:32  Error occurred during initialization of VM
19:12:32  Could not find agent library /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so in absolute path, with error: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/jre/../demo/jvmti/gctest/lib/libgctest.so: cannot open shared object file: No such file or directory
19:12:32  
19:12:32  <end of buffer>
19:12:32  STDERR:
19:12:32  java.lang.RuntimeException: Test failed - exit return code non-zero (exitStatus==1)
19:12:32  	at DemoRun.runit(DemoRun.java:207)
19:12:32  	at DemoRun.runit(DemoRun.java:109)
19:12:32  	at Gctest.main(Gctest.java:41)
19:12:32  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:12:32  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:12:32  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:12:32  	at java.lang.reflect.Method.invoke(Method.java:498)
19:12:32  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
19:12:32  	at java.lang.Thread.run(Thread.java:748)
19:12:32  
19:12:32  JavaTest Message: Test threw exception: java.lang.RuntimeException
19:12:32  JavaTest Message: shutting down test
19:12:32  
19:12:32  
19:12:32  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Test failed - exit return code non-zero (exitStatus==1)
```

**Comment by lumpfish** [comment]
Created PR https://github.com/adoptium/aqa-tests/pull/2707 to exclude the tests pending further investigation.
