### ISSUE TITLE
extended.openjdk hotspot_jre jdk8 runtime/SharedArchiveFile tests fail with Error: Unimplemented()

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-tests#2659]
Test suite: extended.openjdk
Test target: hotspot_jre
Release(s): jdk8
Platform(s): ppc_aix, ppcle64_linux

The following tests fail on jdk8 ppc_aix and ppcle64_linux platforms with an "Unimplemented" error.
```
runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java
runtime/SharedArchiveFile/CdsSameObjectAlignment.java
runtime/SharedArchiveFile/LimitSharedSizes.java
runtime/SharedArchiveFile/PrintSharedArchiveAndExit.java
runtime/SharedArchiveFile/SharedArchiveFile.java
runtime/SharedArchiveFile/SpaceUtilizationCheck.java
```
Example failing test output:
```
13:58:05  TEST: runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java
13:58:05  TEST JDK: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image
13:58:05  
13:58:05  ACTION: build -- Passed. Build successful
13:58:05  REASON: Named class compiled on demand
13:58:05  TIME:   0.061 seconds
13:58:05  messages:
13:58:05  command: build CdsDifferentObjectAlignment
13:58:05  reason: Named class compiled on demand
13:58:05  Test directory:
13:58:05    compile: CdsDifferentObjectAlignment
13:58:05  elapsed time (seconds): 0.061
13:58:05  
13:58:05  ACTION: compile -- Passed. Compilation successful
13:58:05  REASON: .class file out of date or does not exist
13:58:05  TIME:   0.061 seconds
13:58:05  messages:
13:58:05  command: compile -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java
13:58:05  reason: .class file out of date or does not exist
13:58:05  Mode: agentvm
13:58:05  Agent id: 1
13:58:05  elapsed time (seconds): 0.061
13:58:05  configuration:
13:58:05  Boot Layer (javac runtime environment)
13:58:05    class path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/lib/tools.jar
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/javatest.jar
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/jtreg.jar
13:58:05  
13:58:05  javac compilation environment
13:58:05    source path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile
13:58:05                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary
13:58:05    class path:  /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile
13:58:05                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile
13:58:05                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary
13:58:05                 /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/lib/tools.jar
13:58:05  
13:58:05  rerun:
13:58:05  cd /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/scratch/1 && \
13:58:05  DISPLAY=:0 \
13:58:05  HOME=/home/jenkins \
13:58:05  LANG=en_US.UTF-8 \
13:58:05  PATH=/bin:/usr/bin:/usr/sbin \
13:58:05      /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/bin/javac \
13:58:05          -J-ea \
13:58:05          -J-esa \
13:58:05          -J-Xmx512m \
13:58:05          -J-XX:-UseCompressedOops \
13:58:05          -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
13:58:05          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
13:58:05          -J-Dtest.compiler.opts= \
13:58:05          -J-Dtest.java.opts= \
13:58:05          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image \
13:58:05          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image \
13:58:05          -J-Dtest.timeout.factor=8.0 \
13:58:05          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test \
13:58:05          -J-Dtest.name=runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java \
13:58:05          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java \
13:58:05          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile \
13:58:05          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary \
13:58:05          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile \
13:58:05          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary \
13:58:05          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary \
13:58:05          -d /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile \
13:58:05          -sourcepath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary \
13:58:05          -classpath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/lib/tools.jar \
13:58:05          -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java
13:58:05  
13:58:05  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
13:58:05  REASON: Assumed action based on file name: run main CdsDifferentObjectAlignment 
13:58:05  TIME:   0.318 seconds
13:58:05  messages:
13:58:05  command: main CdsDifferentObjectAlignment
13:58:05  reason: Assumed action based on file name: run main CdsDifferentObjectAlignment 
13:58:05  Mode: agentvm
13:58:05  Agent id: 5
13:58:05  elapsed time (seconds): 0.318
13:58:05  configuration:
13:58:05  Boot Layer
13:58:05    class path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/javatest.jar
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/jtreg.jar
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/lib/tools.jar
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/junit.jar
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/testng.jar
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/jcommander.jar
13:58:05  
13:58:05  Test Layer
13:58:05    class path: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary
13:58:05                /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary
13:58:05  
13:58:05  rerun:
13:58:05  cd /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/scratch/1 && \
13:58:05  DISPLAY=:0 \
13:58:05  HOME=/home/jenkins \
13:58:05  LANG=en_US.UTF-8 \
13:58:05  PATH=/bin:/usr/bin:/usr/sbin \
13:58:05      /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/bin/java \
13:58:05          -Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
13:58:05          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
13:58:05          -Dtest.compiler.opts= \
13:58:05          -Dtest.java.opts= \
13:58:05          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image \
13:58:05          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image \
13:58:05          -Dtest.timeout.factor=8.0 \
13:58:05          -Dtest.root=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test \
13:58:05          -Dtest.name=runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java \
13:58:05          -Dtest.file=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile/CdsDifferentObjectAlignment.java \
13:58:05          -Dtest.src=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile \
13:58:05          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary \
13:58:05          -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile \
13:58:05          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary \
13:58:05          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary \
13:58:05          -classpath /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/jtreg.jar \
13:58:05          CdsDifferentObjectAlignment
13:58:05  STDERR:
13:58:05   stdout: [Allocated shared space: 37879808 bytes at 0x0000000800000000
13:58:05  Loading classes to share ...
13:58:05  Preload Warning: Cannot find sun/misc/PostVMInitHook
13:58:05  Preload Warning: Cannot find sun/usagetracker/UsageTrackerClient
13:58:05  Preload Warning: Cannot find sun/usagetracker/UsageTrackerClient$1
13:58:05  Preload Warning: Cannot find sun/usagetracker/UsageTrackerClient$4
13:58:05  Preload Warning: Cannot find sun/usagetracker/UsageTrackerClient$3
13:58:05  Preload Warning: Cannot find sun/dc/DuctusRenderingEngine
13:58:05  Preload Warning: Cannot find sun/font/T2KFontScaler
13:58:05  Preload Warning: Cannot find sun/font/T2KFontScaler$1
13:58:05  Preload Warning: Cannot find sun/security/provider/DSA$LegacyDSA
13:58:05  Loading classes to share: done.
13:58:05  Rewriting and linking classes ...
13:58:05  Rewriting and linking classes: done
13:58:05  Number of classes 2565
13:58:05      instance classes   =  2551
13:58:05      obj array classes  =     6
13:58:05      type array classes =     8
13:58:05  Calculating fingerprints ... done. 
13:58:05  Removing unshareable information ... done. 
13:58:05  #
13:58:05  # A fatal error has been detected by the Java Runtime Environment:
13:58:05  #
13:58:05  #  Internal Error (metaspaceShared_ppc.cpp:59), pid=3614, tid=0x00003fff846ff1b0
13:58:05  #  Error: Unimplemented()
13:58:05  #
13:58:05  # JRE version:  (8.0_302-b05) (build )
13:58:05  # Java VM: OpenJDK 64-Bit Server VM (25.302-b05 interpreted mode linux-ppc64le compressed oops)
13:58:05  # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
13:58:05  #
13:58:05  # An error report file with more information is saved as:
13:58:05  # /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/scratch/1/hs_err_pid3614.log
13:58:05  #
13:58:05  # If you would like to submit a bug report, please visit:
13:58:05  #   https://github.com/adoptium/adoptium-support/issues
13:58:05  #
13:58:05  ];
13:58:05   stderr: []
13:58:05   exitValue = 134
13:58:05  
13:58:05  java.lang.RuntimeException: Expected to get exit value of [0]
13:58:05  
13:58:05  	at com.oracle.java.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:362)
13:58:05  	at CdsDifferentObjectAlignment.createAndLoadSharedArchive(CdsDifferentObjectAlignment.java:69)
13:58:05  	at CdsDifferentObjectAlignment.main(CdsDifferentObjectAlignment.java:46)
13:58:05  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:58:05  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:58:05  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:58:05  	at java.lang.reflect.Method.invoke(Method.java:498)
13:58:05  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
13:58:05  	at java.lang.Thread.run(Thread.java:748)
13:58:05  
13:58:05  JavaTest Message: Test threw exception: java.lang.RuntimeException
13:58:05  JavaTest Message: shutting down test
13:58:05  
13:58:05  STDOUT:
13:58:05  Command line: [/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/bin/java -cp /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/SharedArchiveFile:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_1623502564202/hotspot_jre_1/work/classes/1/testlibrary:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/jtreg.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/junit.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/jtreg/lib/jcommander.jar -XX:+UnlockDiagnosticVMOptions -XX:SharedArchiveFile=./sample.jsa -Xshare:dump -XX:ObjectAlignmentInBytes=16 ]
13:58:05  
13:58:05  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
```

**Comment by lumpfish** [comment]
I'll create a PR to exclude the tests from ppc_aix and ppcle64_linux.

**Comment by lumpfish** [comment]
Two additional tests fail in the same way:
```
TEST: runtime/CDSCompressedKPtrs/CDSCompressedKPtrs.java
TEST: runtime/CDSCompressedKPtrs/CDSCompressedKPtrsError.java
```
Adding those to https://github.com/adoptium/aqa-tests/pull/2661

**Comment by smlambert** [comment]
I see another test that has this same Unimplemented error, runtime/CompressedOops/CompressedClassPointers.java on ppc64le during release testing at https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_0/11/testReport/runtime_CompressedOops_CompressedClassPointers/java/CompressedClassPointers/

**Comment by sophia-guo** [comment]
> https://github.com/adoptium/aqa-tests/issues/2659#issuecomment-894657700

This did happen to hotspot_jre_1

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_2/11/#showFailuresLink

**Comment by smlambert** [comment]
Also includes runtime/NMT/NMTWithCDS.java (see https://github.com/adoptium/aqa-tests/issues/4518#issuecomment-1516311121).
