### ISSUE TITLE
sanity.openjdk pLinux: SimulResumerTest: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#2696]
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_ppc64le_linux/530/consoleFull

```
20:27:54  bkpts = 19477, iters = 160
20:27:54  kind = ownedMonitors()
20:27:54  kind = ownedMonitorsAndFrames()
20:27:54  kind = currentContendedMonitor()
20:27:54  kind = frames()
20:27:54  kind = frames(0, size - 1)
20:27:54  kind = frameCount()
20:27:54  kind = name()
20:27:54  kind = status()
20:27:54  kind = ownedMonitors()
20:27:54  bkpts = 19676, iters = 161
20:27:54  kind = ownedMonitors()
20:27:54  kind = ownedMonitorsAndFrames()
20:27:54  kind = currentContendedMonitor()
20:27:54  kind = frames()
20:27:54  kind = frames(0, size - 1)
20:27:54  kind = ownedMonitors()
20:27:54  bkpts = 19866, iters = 162
20:27:54  kind = ownedMonitors()
20:27:54  STDERR:
20:27:54  run args: [SimulResumerTarg]
20:27:54  failure: Got exception from frames(0, size - 1): java.lang.IndexOutOfBoundsException
20:27:54  VMDisconnectedException
20:27:54  java.lang.Exception: SimulResumerTest: failed; bkpts = 20000, iters = 162
20:27:54  	at SimulResumerTest.runTests(SimulResumerTest.java:275)
20:27:54  	at TestScaffold.startTests(TestScaffold.java:429)
20:27:54  	at SimulResumerTest.main(SimulResumerTest.java:120)
20:27:54  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:27:54  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:27:54  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:27:54  	at java.lang.reflect.Method.invoke(Method.java:498)
20:27:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
20:27:54  	at java.lang.Thread.run(Thread.java:748)
```

**Comment by andrew-m-leonard** [comment]
maybe a connection glitch:
```
20:27:54  VMDisconnectedException
```

**Comment by sendaoYan** [comment]
I also catch this intermittent failure on linux aarch64:

```
run args: [SimulResumerTarg]
failure: Got exception from frames(0, size - 1): java.lang.IndexOutOfBoundsException
VMDisconnectedException
java.lang.Exception: SimulResumerTest: failed; bkpts = 20000, iters = 33
        at SimulResumerTest.runTests(SimulResumerTest.java:275)
        at TestScaffold.startTests(TestScaffold.java:429)
        at SimulResumerTest.main(SimulResumerTest.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:855)
```

![image](https://user-images.githubusercontent.com/24123821/172585434-ea95ea12-383d-48bc-a3e2-b7a0b3432ce9.png)
