### ISSUE TITLE
extended.openjdk hotspot_jre jdk8 gc/metaspace/TestMetaspaceMemoryPool.java fails java.lang.RuntimeException: Expected to find a memory pool with name Compressed Class Space

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-tests#2708]
extended.openjdk hotspot_jre jdk8 gc/metaspace/TestMetaspaceMemoryPool.java fails on 64 bit platforms with
```
java.lang.RuntimeException: Expected to find a memory pool with name Compressed Class Space
```

The test case only executes the check which gives rise to the exception on 64 bit platforms (so the test "passes" on 32 bit).

Example failing job: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_aarch64_linux/28/consoleFull

To rerun: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=hotspot&JDK_VENDOR=Temurin&BUILD_LIST=openjdk&PLATFORM=aarch64_linux&TARGET=hotspot_jre_0

Full output of the failing test:
```
[2021-07-03T13:28:38.261Z] TEST: gc/metaspace/TestMetaspaceMemoryPool.java
[2021-07-03T13:28:38.261Z] TEST JDK: C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image
[2021-07-03T13:28:38.261Z] 
[2021-07-03T13:28:38.261Z] ACTION: build -- Passed. Build successful
[2021-07-03T13:28:38.261Z] REASON: Named class compiled on demand
[2021-07-03T13:28:38.261Z] TIME:   0.24 seconds
[2021-07-03T13:28:38.261Z] messages:
[2021-07-03T13:28:38.261Z] command: build TestMetaspaceMemoryPool
[2021-07-03T13:28:38.261Z] reason: Named class compiled on demand
[2021-07-03T13:28:38.261Z] Test directory:
[2021-07-03T13:28:38.261Z]   compile: TestMetaspaceMemoryPool
[2021-07-03T13:28:38.261Z] elapsed time (seconds): 0.24
[2021-07-03T13:28:38.261Z] 
[2021-07-03T13:28:38.261Z] ACTION: compile -- Passed. Compilation successful
[2021-07-03T13:28:38.261Z] REASON: .class file out of date or does not exist
[2021-07-03T13:28:38.261Z] TIME:   0.24 seconds
[2021-07-03T13:28:38.261Z] messages:
[2021-07-03T13:28:38.261Z] command: compile -XDignore.symbol.file=true C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace\TestMetaspaceMemoryPool.java
[2021-07-03T13:28:38.261Z] reason: .class file out of date or does not exist
[2021-07-03T13:28:38.261Z] Mode: agentvm
[2021-07-03T13:28:38.261Z] Agent id: 8
[2021-07-03T13:28:38.261Z] elapsed time (seconds): 0.24
[2021-07-03T13:28:38.261Z] configuration:
[2021-07-03T13:28:38.261Z] Boot Layer (javac runtime environment)
[2021-07-03T13:28:38.261Z]   class path: C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image\lib\tools.jar
[2021-07-03T13:28:38.261Z]               C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\jvmtest\openjdk\jtreg\lib\javatest.jar
[2021-07-03T13:28:38.261Z]               C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\jvmtest\openjdk\jtreg\lib\jtreg.jar
[2021-07-03T13:28:38.261Z] 
[2021-07-03T13:28:38.261Z] javac compilation environment
[2021-07-03T13:28:38.261Z]   source path: C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace
[2021-07-03T13:28:38.261Z]                C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\testlibrary
[2021-07-03T13:28:38.261Z]   class path:  C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace
[2021-07-03T13:28:38.261Z]                C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace
[2021-07-03T13:28:38.261Z]                C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\testlibrary
[2021-07-03T13:28:38.261Z]                C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image\lib\tools.jar
[2021-07-03T13:28:38.261Z] 
[2021-07-03T13:28:38.261Z] rerun:
[2021-07-03T13:28:38.261Z] cd 'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\scratch' && \
[2021-07-03T13:28:38.261Z] PATH='C:\Program Files\AdoptOpenJDK\jdk-8.0.272.10-hotspot\bin;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\DTS\Binn;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\apache-ant\apache-ant-1.10.5\bin;C:\openjdk\jdk-8\bin;C:\rust\bin;C:\Program Files\IcedTeaWeb\WebStart\bin' \
[2021-07-03T13:28:38.261Z] SystemDrive=C: \
[2021-07-03T13:28:38.261Z] SystemRoot='C:\Windows' \
[2021-07-03T13:28:38.261Z] TEMP='C:\Users\jenkins\AppData\Local\Temp' \
[2021-07-03T13:28:38.261Z] TMP='C:\Users\jenkins\AppData\Local\Temp' \
[2021-07-03T13:28:38.261Z] windir='C:\Windows' \
[2021-07-03T13:28:38.261Z]     'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image\bin\javac' \
[2021-07-03T13:28:38.261Z]         -J-ea \
[2021-07-03T13:28:38.261Z]         -J-esa \
[2021-07-03T13:28:38.261Z]         -J-Xmx512m \
[2021-07-03T13:28:38.261Z]         -J-XX:+UseCompressedOops \
[2021-07-03T13:28:38.261Z]         -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops' \
[2021-07-03T13:28:38.261Z]         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops' \
[2021-07-03T13:28:38.261Z]         -J-Dtest.compiler.opts= \
[2021-07-03T13:28:38.261Z]         -J-Dtest.java.opts= \
[2021-07-03T13:28:38.261Z]         -J-Dtest.jdk='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image' \
[2021-07-03T13:28:38.261Z]         -J-Dcompile.jdk='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image' \
[2021-07-03T13:28:38.261Z]         -J-Dtest.timeout.factor=8.0 \
[2021-07-03T13:28:38.261Z]         -J-Dtest.root='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test' \
[2021-07-03T13:28:38.262Z]         -J-Dtest.name=gc/metaspace/TestMetaspaceMemoryPool.java \
[2021-07-03T13:28:38.262Z]         -J-Dtest.file='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace\TestMetaspaceMemoryPool.java' \
[2021-07-03T13:28:38.262Z]         -J-Dtest.src='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace' \
[2021-07-03T13:28:38.262Z]         -J-Dtest.src.path='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\testlibrary' \
[2021-07-03T13:28:38.262Z]         -J-Dtest.classes='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace' \
[2021-07-03T13:28:38.262Z]         -J-Dtest.class.path='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\testlibrary' \
[2021-07-03T13:28:38.262Z]         -J-Dtest.class.path.prefix='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\testlibrary' \
[2021-07-03T13:28:38.262Z]         -d 'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace' \
[2021-07-03T13:28:38.262Z]         -sourcepath 'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\testlibrary' \
[2021-07-03T13:28:38.262Z]         -classpath 'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\testlibrary;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image\lib\tools.jar' \
[2021-07-03T13:28:38.262Z]         -XDignore.symbol.file=true 'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace\TestMetaspaceMemoryPool.java'
[2021-07-03T13:28:38.262Z] 
[2021-07-03T13:28:38.262Z] ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to find a memory pool with name Compressed Class Space
[2021-07-03T13:28:38.262Z] REASON: User specified action: run main/othervm -XX:+IgnoreUnrecognizedVMOptions -XX:-UseCompressedOops TestMetaspaceMemoryPool 
[2021-07-03T13:28:38.262Z] TIME:   0.137 seconds
[2021-07-03T13:28:38.262Z] messages:
[2021-07-03T13:28:38.262Z] command: main -XX:+IgnoreUnrecognizedVMOptions -XX:-UseCompressedOops TestMetaspaceMemoryPool
[2021-07-03T13:28:38.262Z] reason: User specified action: run main/othervm -XX:+IgnoreUnrecognizedVMOptions -XX:-UseCompressedOops TestMetaspaceMemoryPool 
[2021-07-03T13:28:38.262Z] Mode: othervm [/othervm specified]
[2021-07-03T13:28:38.262Z] elapsed time (seconds): 0.137
[2021-07-03T13:28:38.262Z] configuration:
[2021-07-03T13:28:38.262Z] STDOUT:
[2021-07-03T13:28:38.262Z] STDERR:
[2021-07-03T13:28:38.263Z] java.lang.RuntimeException: Expected to find a memory pool with name Compressed Class Space
[2021-07-03T13:28:38.263Z] 	at TestMetaspaceMemoryPool.getMemoryPool(TestMetaspaceMemoryPool.java:73)
[2021-07-03T13:28:38.263Z] 	at TestMetaspaceMemoryPool.main(TestMetaspaceMemoryPool.java:48)
[2021-07-03T13:28:38.263Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-03T13:28:38.263Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-07-03T13:28:38.263Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-03T13:28:38.263Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-07-03T13:28:38.263Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-07-03T13:28:38.263Z] 	at java.lang.Thread.run(Thread.java:748)
[2021-07-03T13:28:38.263Z] 
[2021-07-03T13:28:38.263Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to find a memory pool with name Compressed Class Space
[2021-07-03T13:28:38.263Z] JavaTest Message: shutting down test
[2021-07-03T13:28:38.263Z] 
[2021-07-03T13:28:38.263Z] STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected to find a memory pool with name Compressed Class Space
[2021-07-03T13:28:38.263Z] rerun:
[2021-07-03T13:28:38.263Z] cd 'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\scratch' && \
[2021-07-03T13:28:38.263Z] PATH='C:\Program Files\AdoptOpenJDK\jdk-8.0.272.10-hotspot\bin;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\DTS\Binn;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\apache-ant\apache-ant-1.10.5\bin;C:\openjdk\jdk-8\bin;C:\rust\bin;C:\Program Files\IcedTeaWeb\WebStart\bin' \
[2021-07-03T13:28:38.263Z] SystemDrive=C: \
[2021-07-03T13:28:38.263Z] SystemRoot='C:\Windows' \
[2021-07-03T13:28:38.263Z] TEMP='C:\Users\jenkins\AppData\Local\Temp' \
[2021-07-03T13:28:38.263Z] TMP='C:\Users\jenkins\AppData\Local\Temp' \
[2021-07-03T13:28:38.263Z] windir='C:\Windows' \
[2021-07-03T13:28:38.263Z] CLASSPATH='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\testlibrary;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\testlibrary;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image\lib\tools.jar;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\jvmtest\openjdk\jtreg\lib\javatest.jar;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\jvmtest\openjdk\jtreg\lib\jtreg.jar' \
[2021-07-03T13:28:38.263Z]     'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image\bin\java' \
[2021-07-03T13:28:38.263Z]         -Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops' \
[2021-07-03T13:28:38.263Z]         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops' \
[2021-07-03T13:28:38.263Z]         -Dtest.compiler.opts= \
[2021-07-03T13:28:38.263Z]         -Dtest.java.opts= \
[2021-07-03T13:28:38.263Z]         -Dtest.jdk='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image' \
[2021-07-03T13:28:38.263Z]         -Dcompile.jdk='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\openjdkbinary\j2sdk-image' \
[2021-07-03T13:28:38.263Z]         -Dtest.timeout.factor=8.0 \
[2021-07-03T13:28:38.263Z]         -Dtest.root='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test' \
[2021-07-03T13:28:38.263Z]         -Dtest.name=gc/metaspace/TestMetaspaceMemoryPool.java \
[2021-07-03T13:28:38.263Z]         -Dtest.file='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace\TestMetaspaceMemoryPool.java' \
[2021-07-03T13:28:38.263Z]         -Dtest.src='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace' \
[2021-07-03T13:28:38.263Z]         -Dtest.src.path='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\testlibrary' \
[2021-07-03T13:28:38.263Z]         -Dtest.classes='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace' \
[2021-07-03T13:28:38.263Z]         -Dtest.class.path='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\testlibrary' \
[2021-07-03T13:28:38.263Z]         -Dtest.class.path.prefix='C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\openjdk\openjdk-jdk\hotspot\test\gc\metaspace;C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\classes\testlibrary' \
[2021-07-03T13:28:38.263Z]         -ea \
[2021-07-03T13:28:38.263Z]         -esa \
[2021-07-03T13:28:38.263Z]         -Xmx512m \
[2021-07-03T13:28:38.263Z]         -XX:+UseCompressedOops \
[2021-07-03T13:28:38.263Z]         -XX:+IgnoreUnrecognizedVMOptions \
[2021-07-03T13:28:38.263Z]         -XX:-UseCompressedOops \
[2021-07-03T13:28:38.263Z]         com.sun.javatest.regtest.agent.MainWrapper 'C:\Users\jenkins\workspace\Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16253185581448\hotspot_jre_0\work\gc\metaspace\TestMetaspaceMemoryPool.d\main.0.jta'
[2021-07-03T13:28:38.263Z] 
[2021-07-03T13:28:38.263Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to find a memory pool with name Compressed Class Space
```

**Comment by sophia-guo** [comment]
@lumpfish confirmed that the test was excluded by problem list in upstream openjdk repo. That is it should also be excluded by default in aqa-tests, though it isn't. The reason is hotspot_jre testcase is using the same TEST_RESROOT as jdk, which should be updated to a specific test resource root directory for  jre.

**Comment by sophia-guo** [comment]
Similar to a few other test targets for hotspot components. Will update that.

**Comment by lumpfish** [comment]
I cannot see this test excluded in the default Problemlist.txt: https://github.com/adoptium/jdk8u/blob/master/hotspot/test/ProblemList.txt.  There are tests which are in the default exclude list which are not being excluded, but this test is not one of them.
Is there another exclude list I have missed?

**Comment by sophia-guo** [comment]
No, I'm actually talking about the `compiler/rtm/locking/TestRTMAbortRatio.java`. Didn't look at it carefully.

**Comment by zzambers** [comment]
I have tried to unexclude `gc/metaspace/TestMetaspaceMemoryPool.java` as I do not see this failing in GitHub CI of jdk8u-dev. It failed in some configurations (hotspot_custom_0), but passed in others (hotspot_custom_1). See: 
https://ci.adoptium.net/view/Test_grinder/job/Grinder/6775/tapResults/

Seems like testing is done with both -XX:{+,-}UseCompressedOops. I think these custom vm options interfere with vm options specified by test, which itself tries to perform testing with various combinations of these (causing failures), see:
https://github.com/openjdk/jdk8u-dev/blob/b51619d24e0643aa0afdba87ac20b371dbb594e8/hotspot/test/gc/metaspace/TestMetaspaceMemoryPool.java#L34

Not sure anything can be done about this...

**Comment by sophia-guo** [comment]
> Seems like testing is done with both -XX:{+,-}UseCompressedOops. I think these custom vm options interfere with vm options specified by test, which itself tries to perform testing with various combinations of these (causing failures), see:
https://github.com/openjdk/jdk8u-dev/blob/b51619d24e0643aa0afdba87ac20b371dbb594e8/hotspot/test/gc/metaspace/TestMetaspaceMemoryPool.java#L34

Good catch. Agreed that those tests shouldn't run with both -XX:{+,-}UseCompressedOops.  But curious why it doesn't fail with -XX:-UseCompressedOops as there are tests specific require [-XX:+UseCompressedOops](https://github.com/openjdk/jdk8u-dev/blob/b51619d24e0643aa0afdba87ac20b371dbb594e8/hotspot/test/gc/metaspace/TestMetaspaceMemoryPool.java#L36-L37). 

The difference between testcase_0 and testcase_1 is `-XX:{+,-}UseCompressedOops`, which is added as part of `-vmoption:`. vm options specified by tests cases itself will be appended to all other options. Question is if same option is specified more than once wouldn't the latter one win? For this specific test case I feels like **[this check](https://github.com/openjdk/jdk8u-dev/blob/b51619d24e0643aa0afdba87ac20b371dbb594e8/hotspot/test/gc/metaspace/TestMetaspaceMemoryPool.java#L47-L49)**   can be enhanced to check the last UseCompressedOops options. But may not be necessary to just work with this case.
