### ISSUE TITLE
Move jenkinsfile.run_parallel_tests() in try block

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2730]
[jenkinsfile.run_parallel_tests()
](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests#L345) needs to be moved in try block. Otherwise, the error is misleading.

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1066/console

```
ERROR: Cannot delete workspace :Remote call on test-aws-rhel8-x64-1 failed
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: hudson.AbortException: Cannot delete workspace: Remote call on test-aws-rhel8-x64-1 failed
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: jenkinsfile for class: WorkflowScript
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:355)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:354)
```

The real error is `Cannot delete workspace :Remote call on test-aws-rhel8-x64-1 failed`, not the `MissingPropertyException`.

**Comment by llxia** [comment]
This issue is fixed.
