### ISSUE TITLE
Four tests under sun/management/jdp/ get the error message `Caused by: java.lang.IllegalArgumentException: IPv6 socket cannot join IPv4 multicast group` on AIX with jdk16

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2809]
sun/management/jdp/JdpDefaultsTest.java.JdpDefaultsTest
sun/management/jdp/JdpJmxRemoteDynamicPortTest.java
sun/management/jdp/JdpOffTest.java.JdpOffTest
sun/management/jdp/JdpSpecificAddressTest.java.JdpSpecificAddressTest

```
Exception in thread "main" java.net.SocketException: joinGroup failed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:482)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:329)
	at ClientConnection.connectWithTimeout(ClientConnection.java:58)
	at JdpTestCase.run(JdpTestCase.java:67)
	at JdpJmxRemoteDynamicPortTestCase.main(JdpJmxRemoteDynamicPortTestCase.java:103)
Caused by: java.lang.IllegalArgumentException: IPv6 socket cannot join IPv4 multicast group
	at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:1466)
	at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1551)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:532)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:479)
	... 4 more
]
 exitValue = 1
```

Related https://github.com/adoptium/adoptium/issues/63

**Comment by smlambert** [comment]
What happens when you add -Djava.net.preferIPv4Stack=true as an option?  (Are the tests smart enough to skip portions specific to the Multicast config on the machine?  I have not looked at the test code, there are a different set of multicast tests that benefit from using this option on AIX).

**Comment by sophia-guo** [comment]
Yes, with change the test itself https://github.com/adoptium/jdk16u/compare/master...sophia-guo:ipv6?expand=1, test passed.

https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/265/

All four tests similar. Need to update test itself, which means we need someone to create the issue in JBS and update it if we'd like them to run on AIX.

**Comment by sophia-guo** [comment]
The following tests have same failures
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/#showFailuresLink

[java/net/MulticastSocket/JoinLeave.java.JoinLeave](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/testReport/junit/java_net_MulticastSocket_JoinLeave/java/JoinLeave/)
[java/net/MulticastSocket/MulticastAddresses.java.MulticastAddresses](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/testReport/junit/java_net_MulticastSocket_MulticastAddresses/java/MulticastAddresses/)
[java/net/MulticastSocket/SetOutgoingIf.java.SetOutgoingIf](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/testReport/junit/java_net_MulticastSocket_SetOutgoingIf/java/SetOutgoingIf/)
[java/net/MulticastSocket/B6427403.java.B6427403](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/testReport/junit/java_net_MulticastSocket_B6427403/java/B6427403/)
[java/net/MulticastSocket/NoLoopbackPackets.java.NoLoopbackPackets](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/testReport/junit/java_net_MulticastSocket_NoLoopbackPackets/java/NoLoopbackPackets/)
[java/net/MulticastSocket/Promiscuous.java.Promiscuous](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/testReport/junit/java_net_MulticastSocket_Promiscuous/java/Promiscuous/)
[java/net/MulticastSocket/Test.java.Test](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/36/testReport/junit/java_net_MulticastSocket_Test/java/Test/)
