### ISSUE TITLE
jdk16: java/nio/channels/DatagramChannel/SendReceiveMaxSize.java failed on AIX

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2816]
jdk16: [java/nio/channels/DatagramChannel/SendReceiveMaxSize.java failed on AIX ](https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_ppc64_aix_testList_2/9/console)with message:

```
01:48:35  test SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize$$Lambda$49/0x00000000801036b8@639579dc, 65507, /129.33.196.210): success
01:48:35  test SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize$$Lambda$52/0x0000000080103d40@7720c765, 65527, /0:0:0:0:0:0:0:1): failure
01:48:35  java.net.SocketException: A message for a socket data transfer is too long.
01:48:35  	at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
01:48:35  	at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:897)
```

reran got different error: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/247/console

```
16:17:56  config SendReceiveMaxSize.setUp(): success
16:17:56  test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$48/0x00000004001034b0@f4bc9dc, 65507, /140.211.9.99): success
16:17:56  test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$49/0x00000004001036c0@33ca378f, 65507, /140.211.9.99): success
16:17:56  test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$52/0x0000000400103d48@6f373be2, 65527, /0:0:0:0:0:0:0:1): success
16:17:56  test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$53/0x0000000400106000@7f6f51e3, 65527, /0:0:0:0:0:0:0:1): success
16:17:56  Timeout refired 960 times
...
TEST RESULT: Error. Program `/home/jenkins/workspace/grinder_sandbox_new/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960573ms).

```

related https://github.com/adoptium/adoptium/issues/63

**Comment by Haroon-Khel** [comment]
Grinders 3767 - 3774 are rebuilds of this test on all of our aix machines. All of those grinders seem to fail in the same way as @sophia-guo's rerun job, they time out

```
17:30:44  TEST RESULT: Error. Program `/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960495ms).
```

I'll run some tests on one of the machines in an ssh session to see if I can get a better idea of what's going on

**Comment by Haroon-Khel** [comment]
The title of this test, found in a jtreg report, suggests it should only run on MacOS

`title=Check that it is possible to send and receive datagrams of maximum size on macOS.`

**Comment by smlambert** [comment]
Seems like it is also meant to run on other platforms, given code blocks like this: https://github.com/adoptium/jdk16u/blob/7dcedb672b0e134410954e145483fecbbbd3754d/test/jdk/java/nio/channels/DatagramChannel/SendReceiveMaxSize.java#L142

**Comment by jiekang** [comment]
The latest commit message also mentions updating a test for all platforms:
https://github.com/adoptium/jdk16u/commit/a096c0a83f900c05702f94c35adb51746c0683cd
