### ISSUE TITLE
jdk17+ tools/jlink/JLinkTest.java failed on window32

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2857]
jdk17+ tools/jlink/JLinkTest.java failed on window32

```
jlink options: --output E:\workspace\grinder_sandbox_new\aqa-tests\TKG\output_16313003152445\jdk_custom_2\work\scratch\0\images\bug8240349.image --add-modules java.base --module-path E:\workspace\grinder_sandbox_new\openjdkbinary\j2sdk-image\jmods;E:\workspace\grinder_sandbox_new\aqa-tests\TKG\output_16313003152445\jdk_custom_2\work\scratch\0\jmods;E:\workspace\grinder_sandbox_new\aqa-tests\TKG\output_16313003152445\jdk_custom_2\work\scratch\0\jars;E:\workspace\grinder_sandbox_new\aqa-tests\TKG\output_16313003152445\jdk_custom_2\work\scratch\0\explodedmods\classes --vm=client

java.lang.AssertionError: Failure expected: E:\workspace\grinder_sandbox_new\aqa-tests\TKG\output_16313003152445\jdk_custom_2\work\scratch\0\images\bug8240349.image
	at tests.Result.assertFailure(Result.java:58)
	at JLinkTest.main(JLinkTest.java:378)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/lastCompletedBuild/testReport/junit/tools_jlink_JLinkTest/java/JLinkTest/

The failure test was recently committed by https://bugs.openjdk.java.net/browse/JDK-8240349 
 https://github.com/openjdk/jdk17/commit/4d1cf51b1d4a5e812c9f78b0104e40fbc4883a6c#diff-9081f35054af34efdb5ecadf6bf9fb1269c92ec643d94d6fc7ae3af1ffdb47e8, which might not work for windows 32.

**Comment by sophia-guo** [comment]
Same issue on arm-linux
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0/12/testReport/junit/tools_jlink_JLinkTest/java/JLinkTest/
