### ISSUE TITLE
jdk16+ JFR test jdk/jfr/jmx/streaming/TestClose.java got ` java.lang.Exception: Expected repository to be empty ` on win32 and arm-linux

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2865]
jdk16+ JFR test jdk/jfr/jmx/streaming/TestClose.java got ` java.lang.Exception: Expected repository to be empty ` on win32 and arm-linux

https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_1/12/
https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_arm_linux_testList_1/11/testReport/junit/jdk_jfr_jmx_streaming_TestClose/java/TestClose/
https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_x86-32_windows_testList_1/8/testReport/junit/jdk_jfr_jmx_streaming_TestClose/java/TestClose/

```
Stacktrace
Execution failed: `main' threw exception: java.lang.Exception: Expected repository to be empty    
Standard Output
test-close-1631664268807/2021_09_15_00_04_30.jfr
    
Standard Error
java.lang.Exception: Expected repository to be empty
	at jdk.jfr.jmx.streaming.TestClose.main(TestClose.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
https://github.com/adoptium/aqa-tests/issues/2854

**Comment by sophia-guo** [comment]
Not reproducible. Close it.
