### ISSUE TITLE
Java 17 AIX PPC - tools/jlink/JLinkReproducible3Test fails

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#2867]
[2021-09-15T18:17:31.643Z]         JLinkReproducible3Test
[2021-09-15T18:17:31.643Z] stderr:
[2021-09-15T18:17:31.643Z] WARNING: A terminally deprecated method in java.lang.System has been called
[2021-09-15T18:17:31.643Z] WARNING: System::setSecurityManager has been called by com.sun.javatest.regtest.agent.RegressionSecurityManager (file:/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/jvmtest/openjdk/jtreg/lib/jtreg.jar)
[2021-09-15T18:17:31.643Z] WARNING: Please consider reporting this to the maintainers of com.sun.javatest.regtest.agent.RegressionSecurityManager
[2021-09-15T18:17:31.643Z] WARNING: System::setSecurityManager will be removed in a future release
[2021-09-15T18:17:31.643Z] STDOUT:
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:10.958546Z] Gathering output for process 22020210
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:13.231642Z] Waiting for completion for process 22020210
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:13.231827Z] Waiting for completion finished for process 22020210
[2021-09-15T18:17:31.643Z] Output and diagnostic info for process 22020210 was saved into 'pid-22020210-output.log'
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:13.237872Z] Waiting for completion for process 22020210
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:13.238086Z] Waiting for completion finished for process 22020210
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:13.247020Z] Gathering output for process 22020212
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:15.591254Z] Waiting for completion for process 22020212
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:15.591538Z] Waiting for completion finished for process 22020212
[2021-09-15T18:17:31.643Z] Output and diagnostic info for process 22020212 was saved into 'pid-22020212-output.log'
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:15.593109Z] Waiting for completion for process 22020212
[2021-09-15T18:17:31.643Z] [2021-09-15T18:17:15.593198Z] Waiting for completion finished for process 22020212
[2021-09-15T18:17:31.643Z] STDERR:
[2021-09-15T18:17:31.643Z] java.lang.RuntimeException: jlink producing inconsistent result in modules. Mismatch in modules file occurred at byte position 408716
[2021-09-15T18:17:31.643Z] 	at JLinkReproducible3Test.main(JLinkReproducible3Test.java:81)
[2021-09-15T18:17:31.643Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-15T18:17:31.643Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-15T18:17:31.643Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-15T18:17:31.643Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-15T18:17:31.643Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-09-15T18:17:31.643Z] 	at java.base/java.lang.Thread.run(Thread.java:833)
[2021-09-15T18:17:31.643Z] 
[2021-09-15T18:17:31.643Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2021-09-15T18:17:31.643Z] JavaTest Message: shutting down test

**Comment by sophia-guo** [comment]
This is an known issue https://bugs.openjdk.java.net/browse/JDK-8253688. Will exclude it on aix.
