### ISSUE TITLE
Java 17 AIX - java/nio/channels/DatagramChannel/SendReceiveMaxSize.java fails

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#2868]
[2021-09-15T16:52:51.904Z] ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
[2021-09-15T16:52:51.904Z] REASON: User specified action: run testng/othervm SendReceiveMaxSize 
[2021-09-15T16:52:51.904Z] TIME:   0.843 seconds
[2021-09-15T16:52:51.904Z] messages:
[2021-09-15T16:52:51.904Z] command: testng SendReceiveMaxSize
[2021-09-15T16:52:51.904Z] reason: User specified action: run testng/othervm SendReceiveMaxSize 
[2021-09-15T16:52:51.904Z] Mode: othervm [/othervm specified]
[2021-09-15T16:52:51.904Z] elapsed time (seconds): 0.843
[2021-09-15T16:52:51.904Z] configuration:
[2021-09-15T16:52:51.904Z] STDOUT:
[2021-09-15T16:52:51.904Z] Seed from RandomFactory = 5243798083438487616L
[2021-09-15T16:52:51.904Z] config SendReceiveMaxSize.setUp(): success
[2021-09-15T16:52:51.904Z] test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$102/0x000000040011b2f8@13ebea0b, 65507, /129.33.196.210): success
[2021-09-15T16:52:51.904Z] test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$103/0x000000040011b508@4bc0a9b1, 65507, /129.33.196.210): success
[2021-09-15T16:52:51.904Z] test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$106/0x000000040011bb90@58b3e950, 65527, /0:0:0:0:0:0:0:1): success
[2021-09-15T16:52:51.904Z] test SendReceiveMaxSize.testGetOption(SendReceiveMaxSize$$Lambda$107/0x000000040011bda0@1457a216, 65527, /0:0:0:0:0:0:0:1): success
[2021-09-15T16:52:51.904Z] sendBuf:    java.nio.HeapByteBuffer[pos=0 lim=65507 cap=65507]
[2021-09-15T16:52:51.904Z] receiveBuf: java.nio.HeapByteBuffer[pos=0 lim=65507 cap=65507]
[2021-09-15T16:52:51.904Z] sendBuf:    java.nio.HeapByteBuffer[pos=0 lim=65506 cap=65506]
[2021-09-15T16:52:51.904Z] receiveBuf: java.nio.HeapByteBuffer[pos=0 lim=65506 cap=65506]
[2021-09-15T16:52:51.904Z] test SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize$$Lambda$102/0x000000040011b2f8@13ebea0b, 65507, /129.33.196.210): success
[2021-09-15T16:52:51.904Z] sendBuf:    java.nio.HeapByteBuffer[pos=0 lim=65507 cap=65507]
[2021-09-15T16:52:51.904Z] receiveBuf: java.nio.HeapByteBuffer[pos=0 lim=65507 cap=65507]
[2021-09-15T16:52:51.904Z] sendBuf:    java.nio.HeapByteBuffer[pos=0 lim=65506 cap=65506]
[2021-09-15T16:52:51.904Z] receiveBuf: java.nio.HeapByteBuffer[pos=0 lim=65506 cap=65506]
[2021-09-15T16:52:51.904Z] test SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize$$Lambda$103/0x000000040011b508@4bc0a9b1, 65507, /129.33.196.210): success
[2021-09-15T16:52:51.904Z] test SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize$$Lambda$106/0x000000040011bb90@58b3e950, 65527, /0:0:0:0:0:0:0:1): failure
[2021-09-15T16:52:51.904Z] java.net.SocketException: A message for a socket data transfer is too long.
[2021-09-15T16:52:51.904Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[2021-09-15T16:52:51.904Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
[2021-09-15T16:52:51.904Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:878)
[2021-09-15T16:52:51.904Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
[2021-09-15T16:52:51.904Z] 	at SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize.java:150)
[2021-09-15T16:52:51.904Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-15T16:52:51.904Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-15T16:52:51.904Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-15T16:52:51.904Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-09-15T16:52:51.904Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-09-15T16:52:51.904Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-09-15T16:52:51.904Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-09-15T16:52:51.904Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-09-15T16:52:51.904Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-09-15T16:52:51.904Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-09-15T16:52:51.904Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-09-15T16:52:51.904Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-09-15T16:52:51.904Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-09-15T16:52:51.904Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-09-15T16:52:51.904Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-09-15T16:52:51.904Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-09-15T16:52:51.905Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-09-15T16:52:51.905Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-15T16:52:51.905Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-15T16:52:51.905Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-09-15T16:52:51.905Z] 	at java.base/java.lang.Thread.run(Thread.java:833)
[2021-09-15T16:52:51.905Z] test SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize$$Lambda$107/0x000000040011bda0@1457a216, 65527, /0:0:0:0:0:0:0:1): failure
[2021-09-15T16:52:51.905Z] java.net.SocketException: A message for a socket data transfer is too long.
[2021-09-15T16:52:51.905Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[2021-09-15T16:52:51.905Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
[2021-09-15T16:52:51.905Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:878)
[2021-09-15T16:52:51.905Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
[2021-09-15T16:52:51.905Z] 	at SendReceiveMaxSize.testSendReceiveMaxSize(SendReceiveMaxSize.java:150)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-15T16:52:51.905Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-09-15T16:52:51.905Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-09-15T16:52:51.905Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-09-15T16:52:51.905Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-09-15T16:52:51.905Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-09-15T16:52:51.905Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-09-15T16:52:51.905Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-09-15T16:52:51.905Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-09-15T16:52:51.905Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-09-15T16:52:51.905Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-09-15T16:52:51.905Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-09-15T16:52:51.905Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-15T16:52:51.905Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-15T16:52:51.905Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-15T16:52:51.905Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-09-15T16:52:51.905Z] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by BrijeshNekkare** [comment]
With send buffer size set to 65507 observe failure by tracing "send" system call via truss command 
`_esendto(5, 0x0000000114C05D70, 65507, 0, 0x0000000114C03C90, 28, 0x0000000000000000) Err#59 EMSGSIZE
`EMSGSIZE - The message is too large to be sent all at once as the socket requires.

Success case returns number of characters sent, in this case 65487 - courtesy lumpfish test case at issue [2535](https://github.com/adoptium/aqa-tests/issues/2535)
`_esendto(5, 0x0000000114C05E50, 65487, 0, 0x0000000114C03D70, 28, 0x0000000000000000) = 65487`

So its not a JDK bug, yet to find any related system configuration which could help.

**Comment by karianna** [comment]
Duplication of #2535
