### ISSUE TITLE
jdk16+ jdk/jfr/event/allocation/TestObjectAllocationInNewTLABEvent.java got `ava.lang.RuntimeException: Too few tlab objects allocated: expected 50 >= 80` on win32 and arm-linux 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2870]
jdk16+ jdk/jfr/event/allocation/TestObjectAllocationInNewTLABEvent.java got `ava.lang.RuntimeException: Too few tlab objects allocated: expected 50 >= 80` on win32 and arm-linux 

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk16_hs_extended.openjdk_x86-32_windows_testList_1/9/testReport/junit/jdk_jfr_event_allocation_TestObjectAllocationInNewTLABEvent/java/TestObjectAllocationInNewTLABEvent/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk16_hs_extended.openjdk_x86-32_windows_testList_1/9/testReport/junit/jdk_jfr_event_allocation_TestObjectAllocationInNewTLABEvent/java/TestObjectAllocationInNewTLABEvent/

```
java.lang.RuntimeException: Too few tlab objects allocated: expected 50 >= 80
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertGreaterThanOrEqual(Asserts.java:288)
	at jdk.jfr.event.allocation.TestObjectAllocationInNewTLABEvent.main(TestObjectAllocationInNewTLABEvent.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
https://github.com/adoptium/aqa-tests/issues/2854

**Comment by sophia-guo** [comment]
Not reproducible. Close.
