### ISSUE TITLE
JDK16+ some tests under jdk/incubator/vector/ failed on arm

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2874]
jdk/incubator/vector/Byte512VectorLoadStoreTests.java.Byte512VectorLoadStoreTests
jdk/incubator/vector/Byte64VectorTests.java.Byte64VectorTests
jdk/incubator/vector/ByteMaxVectorTests.java.ByteMaxVectorTests
jdk/incubator/vector/Int64VectorTests.java.Int64VectorTests
jdk/incubator/vector/IntMaxVectorTests.java.IntMaxVectorTests
jdk/incubator/vector/Short64VectorTests.java.Short64VectorTests
jdk/incubator/vector/ShortMaxVectorTests.java.ShortMaxVectorTests

Tests failed with similar message:

```
20:21:08  test ByteMaxVectorTests.ASHRByteMaxVectorTestsMasked(byte[-i * 5], byte[cornerCaseValue(i)], mask[true]): failure
20:21:08  java.lang.AssertionError: at index #3, input1 = -15, input2 = 127, mask = true expected [-1] but found [-128]
20:21:08  	at org.testng.Assert.fail(Assert.java:99)
20:21:08  	at org.testng.Assert.failNotEquals(Assert.java:1037
20:21:08  STDERR:
20:21:08  WARNING: Using incubator modules: jdk.incubator.vector
20:21:08  java.lang.Exception: failures: 5
20:21:08  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
20:21:08  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
20:21:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:21:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
20:21:08  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:21:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
20:21:08  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
20:21:08  	at java.base/java.lang.Thread.run(Thread.java:833)
20:21:08  
20:21:08  JavaTest Message: Test threw exception: java.lang.Exception: failures: 5
20:21:08  JavaTest Message: shutting down test
```
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2/12/consoleFull
https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_arm_linux_testList_2/11/consoleFull

Also with crash information:

```
20:20:14  # A fatal error has been detected by the Java Runtime Environment:
20:20:14  #
20:20:14  #  SIGSEGV (0xb) at pc=0xf76da7ac, pid=962363, tid=962379
20:20:14  #
20:20:14  # JRE version: OpenJDK Runtime Environment Temurin-17+35 (17.0+35) (build 17+35)
20:20:14  # Java VM: OpenJDK Server VM Temurin-17+35 (17+35, mixed mode, sharing, g1 gc, linux-arm)
20:20:14  # Problematic frame:
20:20:14  # V  [libjvm.so+0x7597ac]  PhaseIdealLoop::build_loop_late_post_work(Node*, bool)+0xf8
20:20:14  #
20:20:14  # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2/aqa-tests/TKG/output_16316620517389/jdk_vector_2/work/scratch/5/core.962363)
20:20:14  #
20:20:14  [thread 962392 also had an error]
20:20:14  # An error report file with more information is saved as:
20:20:14  # /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2/aqa-tests/TKG/output_16316620517389/jdk_vector_2/work/scratch/5/hs_err_pid962363.log
20:20:14  test Byte512VectorLoadStoreTests.loadStoreByteBuffer(byte[i * 5], HB:RW:NE, BIG_ENDIAN): success
20:20:14  test Byte512VectorLoadStoreTests.loadStoreByteBuffer(byte[i * 5], DB:RW:NE, LITTLE_ENDIAN): success
20:20:14  test Byte512VectorLoadStoreTests.loadStoreByteBuffer(byte[i * 5], DB:RW:NE, BIG_ENDIAN): success
20:20:14  #
20:20:14  # Compiler replay data is saved as:
20:20:14  # /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2/aqa-tests/TKG/output_16316620517389/jdk_vector_2/work/scratch/5/replay_pid962363.log
20:20:14  #
```

**Comment by sophia-guo** [comment]
jdk/incubator/vector/Byte128VectorLoadStoreTests.java same issue in jdk17

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1/22/testReport/
shows 3 more vector test cases that occur on arm_linux for jdk18 run:

jdk/incubator/vector/Byte64VectorLoadStoreTests.java.Byte64VectorLoadStoreTests
jdk/incubator/vector/ByteMaxVectorLoadStoreTests.java.ByteMaxVectorLoadStoreTests 
jdk/incubator/vector/Byte128VectorLoadStoreTests.java.Byte128VectorLoadStoreTests
