### ISSUE TITLE
External openliberty-mp-tck test failed with IllegalArgumentException error

### ISSUE THREAD

**Issue by LongyuZhang** [adoptium/aqa-tests#2902]
Testname: external/openliberty-mp-tck
jdk_impl: openj9
jdk_verison: 11
platform: xlinux
test_link: https://ci.adoptopenjdk.net/job/Grinder_openliberty-mp-tck/2/console
```
21:02:53  error  : Exception: java.lang.IllegalArgumentException: A Jar can only accept a file or directory that exists: /root/.m2/repository/org/apache/commons/commons-lang3/3.8.0/commons-lang3-3.8.0.jar
21:02:53  	at aQute.bnd.osgi.Jar.<init>(Jar.java:130)
21:02:53  	at aQute.bnd.osgi.Jar.<init>(Jar.java:195)
21:02:53  	at aQute.bnd.build.ProjectBuilder.addClasspath(ProjectBuilder.java:133)
21:02:53  	at aQute.bnd.build.ProjectBuilder.init(ProjectBuilder.java:109)
21:02:53  	at aQute.bnd.osgi.Builder.build(Builder.java:92)
21:02:53  	at aQute.bnd.osgi.Builder.builds(Builder.java:1419)
21:02:53  	at aQute.bnd.build.ProjectBuilder.builds(ProjectBuilder.java:642)
21:02:53  	at aQute.bnd.build.Project.buildLocal(Project.java:1873)
21:02:53  	at aQute.bnd.build.Project.build(Project.java:1685)
21:02:53  	at aQute.bnd.build.Project.build(Project.java:2312)
21:02:53  	at aQute.bnd.build.Project$build$16.call(Unknown Source)
21:02:53  	at aQute.bnd.gradle.BndPlugin$_apply_closure1$_closure12$_closure59.doCall(BndPlugin.groovy:286)
21:02:53  	at jdk.internal.reflect.GeneratedMethodAccessor444.invoke(Unknown Source)
21:02:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:02:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
21:02:53  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
21:02:53  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
21:02:53  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
21:02:53  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
21:02:53  	at groovy.lang.Closure.call(Closure.java:405)
21:02:53  	at groovy.lang.Closure.call(Closure.java:421)
21:02:53  	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:664)
21:02:53  	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:637)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:539)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
21:02:53  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:524)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:507)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:258)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:247)
21:02:53  	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
21:02:53  	at org.gradle.internal.execution.steps.ExecuteStep$$Lambda$460/0x0000000089324e30.get(Unknown Source)
21:02:53  	at java.base/java.util.Optional.orElseGet(Optional.java:369)
21:02:53  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
21:02:53  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
21:02:53  	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:63)
21:02:53  	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
21:02:53  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
21:02:53  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
21:02:53  	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
21:02:53  	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
21:02:53  	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
21:02:53  	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
21:02:53  	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
21:02:53  	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
21:02:53  	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
21:02:53  	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
21:02:53  	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
21:02:53  	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
21:02:53  	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
21:02:53  	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
21:02:53  	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
21:02:53  	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
21:02:53  	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
21:02:53  	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
21:02:53  	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
21:02:53  	at org.gradle.internal.execution.steps.SkipUpToDateStep$$Lambda$454/0x000000008a0b7e90.apply(Unknown Source)
21:02:53  	at java.base/java.util.Optional.map(Optional.java:265)
21:02:53  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
21:02:53  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
21:02:53  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
21:02:53  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
21:02:53  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
21:02:53  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
21:02:53  	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
21:02:53  	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
21:02:53  	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
21:02:53  	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
21:02:53  	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
21:02:53  	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
21:02:53  	at org.gradle.internal.execution.steps.SkipEmptyWorkStep$$Lambda$444/0x0000000089132ce0.get(Unknown Source)
21:02:53  	at java.base/java.util.Optional.orElseGet(Optional.java:369)
21:02:53  	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
21:02:53  	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
21:02:53  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
21:02:53  	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
21:02:53  	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
21:02:53  	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:174)
21:02:53  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:166)
21:02:53  	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
21:02:53  	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
21:02:53  	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
21:02:53  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
21:02:53  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
21:02:53  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
21:02:53  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
21:02:53  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
21:02:53  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
21:02:53  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
21:02:53  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
21:02:53  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
21:02:53  	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
21:02:53  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:374)
21:02:53  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:361)
21:02:53  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:354)
21:02:53  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:340)
21:02:53  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
21:02:53  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$$Lambda$435/0x0000000088bec380.execute(Unknown Source)
21:02:53  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
21:02:53  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
21:02:53  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
21:02:53  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
21:02:53  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
21:02:53  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:02:53  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:02:53  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
21:02:53  	at java.base/java.lang.Thread.run(Thread.java:861)
21:02:53  
21:02:53  error  : Unexpected ProjectBuilder init,  error A Jar can only accept a file or directory that exists: /root/.m2/repository/org/apache/commons/commons-lang3/3.8.0/commons-lang3-3.8.0.jar
21:02:53  
21:02:53  FAILURE: Build failed with an exception.
21:02:53  
21:02:53  * What went wrong:
21:02:53  Execution failed for task ':com.ibm.ws.org.apache.commons.lang3:jar'.
21:02:53  > com.ibm.ws.org.apache.commons.lang3 has errors, 2 errors were reported
```

**Comment by llxia** [comment]
openliberty_microprofile_tck passed in [hotspot](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4148/console). I would like to check again if we can run this test using openj9

**Comment by llxia** [comment]
@LongyuZhang could you look into this issue? Thanks

**Comment by LongyuZhang** [comment]
Tested enabling openliberty_microprofile_tck on _hyc-jenkins_, most machines passed, but there are still some machines have problem downloading Apache Ant, as mentioned in Issue (https://github.ibm.com/runtimes/infrastructure/issues/6056).
Following are more detailed test results:

Failed machines:
- ub20x64rt1-10 (grinder 22319 & 22331)

Passed machines: 
- ub20x64rt3-2  (grinder 22292) 
- ub20x64rt4-4   (grinder 22293) 
- ub20x64rt4-10  ((grinder 22294)
- ub20x64rt1-3 (grinder 22295)
