### ISSUE TITLE
Sparc solaris on Java 8 runs out of memory for JRE test

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3048]
https://trss.adoptium.net/output/test?id=616ff8d4c6182d02178e151b

[2021-10-20T06:45:52.625Z] rerun:
[2021-10-20T06:45:52.625Z] cd /export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/scratch && \
[2021-10-20T06:45:52.625Z] DISPLAY=:2 \
[2021-10-20T06:45:52.625Z] HOME=/export/home/jenkins/ \
[2021-10-20T06:45:52.625Z] PATH=/bin:/usr/bin:/usr/sbin \
[2021-10-20T06:45:52.625Z] TZ=US/Central \
[2021-10-20T06:45:52.625Z]     /export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/openjdkbinary/j2sdk-image/bin/java \
[2021-10-20T06:45:52.625Z]         -Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops -Djava.awt.headless=true' \
[2021-10-20T06:45:52.625Z]         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops -J-Djava.awt.headless=true' \
[2021-10-20T06:45:52.625Z]         -Dtest.compiler.opts= \
[2021-10-20T06:45:52.625Z]         -Dtest.java.opts= \
[2021-10-20T06:45:52.625Z]         -Dtest.jdk=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/openjdkbinary/j2sdk-image \
[2021-10-20T06:45:52.625Z]         -Dcompile.jdk=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/openjdkbinary/j2sdk-image \
[2021-10-20T06:45:52.625Z]         -Dtest.timeout.factor=8.0 \
[2021-10-20T06:45:52.625Z]         -Dtest.root=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test \
[2021-10-20T06:45:52.625Z]         -Dtest.name=runtime/NMT/HugeArenaTracking.java \
[2021-10-20T06:45:52.625Z]         -Dtest.file=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/NMT/HugeArenaTracking.java \
[2021-10-20T06:45:52.625Z]         -Dtest.src=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/NMT \
[2021-10-20T06:45:52.625Z]         -Dtest.src.path=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/NMT:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary/whitebox \
[2021-10-20T06:45:52.625Z]         -Dtest.classes=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/runtime/NMT \
[2021-10-20T06:45:52.625Z]         -Dtest.class.path=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/runtime/NMT:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/testlibrary:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/testlibrary/whitebox \
[2021-10-20T06:45:52.625Z]         -Dtest.class.path.prefix=/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/runtime/NMT:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/NMT:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/testlibrary:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/testlibrary/whitebox \
[2021-10-20T06:45:52.625Z]         -classpath /export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/runtime/NMT:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/runtime/NMT:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/testlibrary:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/classes/testlibrary/whitebox:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/openjdk/openjdk-jdk/hotspot/test/testlibrary/whitebox:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/openjdkbinary/j2sdk-image/lib/tools.jar:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/jvmtest/openjdk/jtreg/lib/javatest.jar:/export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/jvmtest/openjdk/jtreg/lib/jtreg.jar \
[2021-10-20T06:45:52.625Z]         ClassFileInstaller sun.hotspot.WhiteBox
[2021-10-20T06:45:52.625Z] STDERR:
[2021-10-20T06:45:52.625Z] 
[2021-10-20T06:45:52.625Z] JavaTest Message: Test complete.
[2021-10-20T06:45:52.625Z] 
[2021-10-20T06:45:52.625Z] 
[2021-10-20T06:45:52.625Z] ACTION: build -- Passed. All files up to date
[2021-10-20T06:45:52.625Z] REASON: Named class compiled on demand
[2021-10-20T06:45:52.625Z] TIME:   0.0 seconds
[2021-10-20T06:45:52.625Z] messages:
[2021-10-20T06:45:52.625Z] command: build HugeArenaTracking
[2021-10-20T06:45:52.625Z] reason: Named class compiled on demand
[2021-10-20T06:45:52.625Z] elapsed time (seconds): 0.0
[2021-10-20T06:45:52.625Z] 
[2021-10-20T06:45:52.625Z] ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Test (reserved=2GB, committed=2GB)' missing from stdout/stderr
[2021-10-20T06:45:52.625Z] REASON: User specified action: run main/othervm -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:NativeMemoryTracking=detail HugeArenaTracking 
[2021-10-20T06:45:52.625Z] TIME:   18.75 seconds
[2021-10-20T06:45:52.625Z] messages:
[2021-10-20T06:45:52.625Z] command: main -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:NativeMemoryTracking=detail HugeArenaTracking
[2021-10-20T06:45:52.626Z] reason: User specified action: run main/othervm -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:NativeMemoryTracking=detail HugeArenaTracking 
[2021-10-20T06:45:52.626Z] Mode: othervm [/othervm specified]
[2021-10-20T06:45:52.626Z] elapsed time (seconds): 18.75
[2021-10-20T06:45:52.626Z] configuration:
[2021-10-20T06:45:52.626Z] STDOUT:
[2021-10-20T06:45:52.626Z] STDERR:
[2021-10-20T06:45:52.626Z]  stdout: [#
[2021-10-20T06:45:52.626Z] # There is insufficient memory for the Java Runtime Environment to continue.
[2021-10-20T06:45:52.626Z] # Native memory allocation (mmap) failed to map 4194304 bytes for committing reserved memory.
[2021-10-20T06:45:52.626Z] # An error report file with more information is saved as:
[2021-10-20T06:45:52.626Z] # /export/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/aqa-tests/TKG/output_16347118216003/hotspot_jre_0/work/scratch/hs_err_pid22451.log
[2021-10-20T06:45:52.626Z] ];
[2021-10-20T06:45:52.626Z]  stderr: [OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0xffffffff6b400000, 4194304, 1) failed; error='Resource temporarily unavailable' (errno=11)
[2021-10-20T06:45:52.626Z] ]
[2021-10-20T06:45:52.626Z]  exitValue = 1
[2021-10-20T06:45:52.626Z] 
[2021-10-20T06:45:52.626Z] java.lang.RuntimeException: 'Test (reserved=2GB, committed=2GB)' missing from stdout/stderr 
[2021-10-20T06:45:52.626Z] 
[2021-10-20T06:45:52.626Z] 	at com.oracle.java.testlibrary.OutputAnalyzer.shouldContain(OutputAnalyzer.java:134)
[2021-10-20T06:45:52.626Z] 	at HugeArenaTracking.main(HugeArenaTracking.java:71)
[2021-10-20T06:45:52.626Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-20T06:45:52.626Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-10-20T06:45:52.626Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-20T06:45:52.626Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-10-20T06:45:52.626Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-20T06:45:52.626Z] 	at java.lang.Thread.run(Thread.java:748)
[2021-10-20T06:45:52.626Z] 
[2021-10-20T06:45:52.626Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: 'Test (reserved=2GB, committed=2GB)' missing from stdout/stderr 
[2021-10-20T06:45:52.627Z] 
[2021-10-20T06:45:52.627Z] JavaTest Message: shutting down test

**Comment by sophia-guo** [comment]
No longer ship Solaris, close it.
