### ISSUE TITLE
JDK8 linux x64: compiler/rtm/locking/TestRTMTotalCountIncrRate.java failed with `Total locks should be exactly the same as amount of iterations`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3050]
JDK8 linux x64: compiler/rtm/locking/TestRTMTotalCountIncrRate.java failed with `Total locks should be exactly the same as amount of iterations`

```
18:22:03  CompilerOracle: compileonly TestRTMTotalCountIncrRate$Test.lock
18:22:03  TestRTMTotalCountIncrRate$Test.lock@6
18:22:03  # rtm locks total (estimated): 1
18:22:03  # rtm lock aborts  : 1
18:22:03  # rtm lock aborts 0: 0
18:22:03  # rtm lock aborts 1: 0
18:22:03  # rtm lock aborts 2: 0
18:22:03  # rtm lock aborts 3: 0
18:22:03  # rtm lock aborts 4: 0
18:22:03  # rtm lock aborts 5: 0
18:22:03  
18:22:03  STDERR:
18:22:03  java.lang.RuntimeException: Total locks should be exactly the same as amount of iterations.
18:22:03  	at com.oracle.java.testlibrary.Asserts.error(Asserts.java:450)
18:22:03  	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:377)
18:22:03  	at com.oracle.java.testlibrary.Asserts.assertEquals(Asserts.java:169)
18:22:03  	at com.oracle.java.testlibrary.Asserts.assertEQ(Asserts.java:142)
18:22:03  	at TestRTMTotalCountIncrRate.verifyLocksCount(TestRTMTotalCountIncrRate.java:97)
18:22:03  	at TestRTMTotalCountIncrRate.runTestCases(TestRTMTotalCountIncrRate.java:62)
18:22:03  	at com.oracle.java.testlibrary.cli.CommandLineOptionTest.test(CommandLineOptionTest.java:322)
18:22:03  	at TestRTMTotalCountIncrRate.main(TestRTMTotalCountIncrRate.java:160)
18:22:03  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:22:03  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:22:03  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:22:03  	at java.lang.reflect.Method.invoke(Method.java:498)
18:22:03  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
18:22:03  	at java.lang.Thread.run(Thread.java:748)
18:22:03  
18:22:03  JavaTest Message: Test threw exception: java.lang.RuntimeException: Total locks should be exactly the same as amount of iterations.
18:22:03  JavaTest Message: shutting down test
18:22:03  
```

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_2/17/console

rerun:https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/373/

**Comment by sophia-guo** [comment]
window64 https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_0/45/testReport/junit/compiler_rtm_locking_TestRTMTotalCountIncrRate/java/TestRTMTotalCountIncrRate/
