### ISSUE TITLE
some security tests fail for Java 11 Alpine Linux likely due to connectivity

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3056]
https://trss.adoptium.net/output/test?id=616f8f2ec6182d02178a5ce0

Last part of failure:

[2021-10-20T03:07:31.644Z] All Test Results
[2021-10-20T03:07:31.644Z] ================
[2021-10-20T03:07:31.644Z]         req**  client    service  acceptor   Result
[2021-10-20T03:07:31.644Z] ----  -------  ------  ---------  --------  -------
[2021-10-20T03:07:31.644Z]   0:      0**      c0    s4  (0)        Na   ++     
[2021-10-20T03:07:31.644Z]   1:      1**      c1    s4  (2)        Ja   ++     
[2021-10-20T03:07:31.644Z]   2:      1        c1    s4  (2)        Na   ++  xxx
[2021-10-20T03:07:31.644Z]   3:      0        c0    s4  (4)        Jb   ++  xxx
[2021-10-20T03:07:31.644Z]   4:      0        c0    s4  (4)        Jb   --     
[2021-10-20T03:07:31.644Z]   5:      0        c0    s4  (4)        Jb   --     
[2021-10-20T03:07:31.644Z]   6:      0        c0    s4  (4)        Na   --     
[2021-10-20T03:07:31.645Z]   7:      2**      c2    s1  (2)        Ja   ++     
[2021-10-20T03:07:31.645Z]   8:      1        c1    s4  (4)        Jb   --     
[2021-10-20T03:07:31.645Z]   9:      3**      c3    s3  (2)        Ja   ++     
[2021-10-20T03:07:31.645Z]  10:      2        c2    s1  (2)        Na   ++  xxx
[2021-10-20T03:07:31.645Z]  11:      4**      c4    s4  (6)        Jb   ++     
[2021-10-20T03:07:31.645Z]  12:      2        c2    s1  (2)        Nb   --     
[2021-10-20T03:07:31.645Z]  13:      4        c4    s4  (6)        Ja   --     
[2021-10-20T03:07:31.645Z]  14:      5**      c0    s2  (0)        Nb   ++     
[2021-10-20T03:07:31.645Z]  15:      6**      c3    s0  (2)        Jb   ++     
[2021-10-20T03:07:31.645Z]  16:      7**      c3    s3  (4)        Ja   ++     
[2021-10-20T03:07:31.645Z]  17:      3        c3    s3  (4)        Nb   ++  xxx
[2021-10-20T03:07:31.645Z]  18:      2        c2    s1  (2)        Ja   --     
[2021-10-20T03:07:31.645Z]  19:      7        c3    s3  (4)        Nb   ++  xxx
[2021-10-20T03:07:31.645Z]  20:      8**      c3    s0  (4)        Ja   ++     
[2021-10-20T03:07:31.645Z]  21:      9**      c3    s2  (0)        Nb   ++     
[2021-10-20T03:07:31.645Z]  22:      2        c2    s1  (2)        Jb   --     
[2021-10-20T03:07:31.645Z]  23:     10**      c2    s3  (4)        Nb   ++     
[2021-10-20T03:07:31.645Z]  24:     11**      c2    s2  (2)        Jb   ++     
[2021-10-20T03:07:31.645Z]  25:     12**      c0    s2  (4)        Jb   ++     
[2021-10-20T03:07:31.645Z]  26:     13**      c2    s3  (4)        Nb   ++     
[2021-10-20T03:07:31.645Z]  27:     14**      c0    s2  (6)        Ja   ++     
[2021-10-20T03:07:31.645Z]  28:     12        c0    s2  (6)        Jb   --     
[2021-10-20T03:07:31.645Z]  29:      3        c3    s3  (4)        Ja   --     
[2021-10-20T03:07:31.645Z]  30:      3        c3    s3  (4)        Nb   --     
[2021-10-20T03:07:31.645Z]  31:      9        c3    s2  (6)        Na   --     
[2021-10-20T03:07:31.645Z]  32:      1        c1    s4  (6)        Jb   --     
[2021-10-20T03:07:31.645Z]  33:      8        c3    s0  (4)        Nb   ++  xxx
[2021-10-20T03:07:31.645Z]  34:      0        c0    s4  (6)        Nb   --     
[2021-10-20T03:07:31.645Z]  35:      2        c2    s1  (2)        Jb   --     
[2021-10-20T03:07:31.645Z]  36:     11        c2    s2  (6)        Ja   --     
[2021-10-20T03:07:31.645Z]  37:     15**      c0    s0  (4)        Na   ++     
[2021-10-20T03:07:31.645Z]  38:     16**      c0    s2  (8)        Ja   ++     
[2021-10-20T03:07:31.645Z]  39:      9        c3    s2  (8)        Nb   --     
[2021-10-20T03:07:31.645Z]  40:      5        c0    s2 (10)        Ja   ++  xxx
[2021-10-20T03:07:31.645Z]  41:     17**      c2    s1  (2)        Na   ++     
[2021-10-20T03:07:31.645Z]  42:     18**      c1    s4  (8)        Ja   ++     
[2021-10-20T03:07:31.645Z]  43:      7        c3    s3  (4)        Na   --     
[2021-10-20T03:07:31.645Z]  44:     19**      c0    s3  (6)        Ja   ++     
[2021-10-20T03:07:31.645Z]  45:      0        c0    s4  (8)        Ja   --     
[2021-10-20T03:07:31.645Z]  46:      7        c3    s3  (6)        Ja   --     
[2021-10-20T03:07:31.645Z]  47:     20**      c4    s4 (10)        Jb   ++     
[2021-10-20T03:07:31.645Z]  48:     21**      c4    s3  (6)        Na   ++     
[2021-10-20T03:07:31.645Z]  49:     22**      c0    s3  (8)        Ja   ++     
[2021-10-20T03:07:31.645Z]  50:     23**      c3    s1  (2)        Nb   ++     
[2021-10-20T03:07:31.645Z]  51:     15        c0    s0  (6)        Ja   ++  xxx
[2021-10-20T03:07:31.645Z]  52:     24**      c3    s1  (2)        Na   ++     
[2021-10-20T03:07:31.645Z]  53:      5        c0    s2 (10)        Nb   --     
[2021-10-20T03:07:31.645Z]  54:     25**      c4    s3  (8)        Na   ++     
[2021-10-20T03:07:31.645Z]  55:     26**      c0    s3  (8)        Nb   ++     
[2021-10-20T03:07:31.645Z]  56:      6        c3    s0  (6)        Jb   --     
[2021-10-20T03:07:31.645Z]  57:     27**      c4    s2 (12)        Jb   ++     
[2021-10-20T03:07:31.645Z]  58:     28**      c3    s0  (6)        Na   ++     
[2021-10-20T03:07:31.645Z]  59:     29**      c4    s1  (4)        Jb   ++     
[2021-10-20T03:07:31.645Z]  60:     22        c0    s3  (8)        Na   ++  xxx
[2021-10-20T03:07:31.645Z]  61:     30**      c1    s3  (8)        Na   ++     
[2021-10-20T03:07:31.645Z]  62:     31**      c2    s4 (10)        Nb   ++     
[2021-10-20T03:07:31.645Z]  63:     17        c2    s1  (6)        Jb   ++  xxx
[2021-10-20T03:07:31.645Z]  64:     14        c0    s2 (12)        Nb   ++  xxx
[2021-10-20T03:07:31.645Z]  65:     11        c2    s2 (12)        Na   ++  xxx
[2021-10-20T03:07:31.645Z]  66:     21        c4    s3  (8)        Na   --     
[2021-10-20T03:07:31.645Z]  67:     28        c3    s0  (8)        Ja   ++  xxx
[2021-10-20T03:07:31.645Z]  68:     32**      c1    s2 (12)        Nb   ++     
[2021-10-20T03:07:31.645Z]  69:     33**      c2    s3 (10)        Jb   ++     
[2021-10-20T03:07:31.645Z]  70:     34**      c0    s4 (12)        Ja   ++     
[2021-10-20T03:07:31.645Z]  71:     26        c0    s3 (12)        Ja   ++  xxx
[2021-10-20T03:07:31.645Z]  72:     35**      c3    s2 (14)        Ja   ++     
[2021-10-20T03:07:31.645Z]  73:     31        c2    s4 (14)        Ja   ++  xxx
[2021-10-20T03:07:31.645Z]  74:      8        c3    s0  (8)        Nb   --     
[2021-10-20T03:07:31.645Z]  75:     25        c4    s3 (12)        Na   --     
[2021-10-20T03:07:31.645Z]  76:     21        c4    s3 (12)        Na   --     
[2021-10-20T03:07:31.645Z]  77:     17        c2    s1  (6)        Na   --     
[2021-10-20T03:07:31.645Z]  78:     36**      c0    s4 (16)        Jb   ++     
[2021-10-20T03:07:31.645Z]  79:     24        c3    s1  (6)        Nb   --     
[2021-10-20T03:07:31.645Z]  80:     37**      c1    s2 (14)        Na   ++     
[2021-10-20T03:07:31.645Z]  81:     38**      c4    s1  (6)        Na   ++     
[2021-10-20T03:07:31.645Z]  82:     32        c1    s2 (16)        Ja   ++  xxx
[2021-10-20T03:07:31.645Z]  83:      8        c3    s0  (8)        Jb   --     
[2021-10-20T03:07:31.645Z]  84:     39**      c3    s4 (18)        Jb   ++     
[2021-10-20T03:07:31.645Z]  85:     40**      c1    s3 (12)        Nb   ++     
[2021-10-20T03:07:31.645Z]  86:     29        c4    s1  (6)        Jb   --     
[2021-10-20T03:07:31.645Z]  87:     19        c0    s3 (12)        Jb   --     
[2021-10-20T03:07:31.645Z]  88:     35        c3    s2 (16)        Jb   --     
[2021-10-20T03:07:31.645Z]  89:     41**      c2    s3 (14)        Jb   ++     
[2021-10-20T03:07:31.645Z]  90:      6        c3    s0  (8)        Nb   ++  xxx
[2021-10-20T03:07:31.645Z]  91:      1        c1    s4 (18)        Nb   --     
[2021-10-20T03:07:31.645Z]  92:      6        c3    s0  (8)        Nb   --     
[2021-10-20T03:07:31.645Z]  93:     42**      c3    s3 (14)        Na   ++     
[2021-10-20T03:07:31.645Z]  94:     34        c0    s4 (18)        Nb   ++  xxx
[2021-10-20T03:07:31.645Z]  95:     43**      c0    s2 (16)        Na   ++     
[2021-10-20T03:07:31.645Z]  96:     44**      c1    s2 (18)        Ja   ++     
[2021-10-20T03:07:31.645Z]  97:     45**      c2    s3 (16)        Ja   ++     
[2021-10-20T03:07:31.645Z]  98:     44        c1    s2 (18)        Jb   --     
[2021-10-20T03:07:31.645Z]  99:     32        c1    s2 (18)        Nb   --     
[2021-10-20T03:07:31.645Z] 
[2021-10-20T03:07:31.645Z] Path of Reqs
[2021-10-20T03:07:31.645Z] ============
[2021-10-20T03:07:31.645Z]   0 (c0 -> s4): Na(0) -> Jb(3)xxx -> Jb(4) -> Jb(5) -> Na(6) -> Nb(34) -> Ja(45)
[2021-10-20T03:07:31.645Z]   1 (c1 -> s4): Ja(1) -> Na(2)xxx -> Jb(8) -> Jb(32) -> Nb(91)
[2021-10-20T03:07:31.645Z]   2 (c2 -> s1): Ja(7) -> Na(10)xxx -> Nb(12) -> Ja(18) -> Jb(22) -> Jb(35)
[2021-10-20T03:07:31.645Z]   3 (c3 -> s3): Ja(9) -> Nb(17)xxx -> Ja(29) -> Nb(30)
[2021-10-20T03:07:31.645Z]   4 (c4 -> s4): Jb(11) -> Ja(13)
[2021-10-20T03:07:31.645Z]   5 (c0 -> s2): Nb(14) -> Ja(40)xxx -> Nb(53)
[2021-10-20T03:07:31.645Z]   6 (c3 -> s0): Jb(15) -> Jb(56) -> Nb(90)xxx -> Nb(92)
[2021-10-20T03:07:31.645Z]   7 (c3 -> s3): Ja(16) -> Nb(19)xxx -> Na(43) -> Ja(46)
[2021-10-20T03:07:31.645Z]   8 (c3 -> s0): Ja(20) -> Nb(33)xxx -> Nb(74) -> Jb(83)
[2021-10-20T03:07:31.645Z]   9 (c3 -> s2): Nb(21) -> Na(31) -> Nb(39)
[2021-10-20T03:07:31.645Z]  10 (c2 -> s3): Nb(23)
[2021-10-20T03:07:31.645Z]  11 (c2 -> s2): Jb(24) -> Ja(36) -> Na(65)xxx
[2021-10-20T03:07:31.645Z]  12 (c0 -> s2): Jb(25) -> Jb(28)
[2021-10-20T03:07:31.645Z]  13 (c2 -> s3): Nb(26)
[2021-10-20T03:07:31.645Z]  14 (c0 -> s2): Ja(27) -> Nb(64)xxx
[2021-10-20T03:07:31.645Z]  15 (c0 -> s0): Na(37) -> Ja(51)xxx
[2021-10-20T03:07:31.645Z]  16 (c0 -> s2): Ja(38)
[2021-10-20T03:07:31.645Z]  17 (c2 -> s1): Na(41) -> Jb(63)xxx -> Na(77)
[2021-10-20T03:07:31.645Z]  18 (c1 -> s4): Ja(42)
[2021-10-20T03:07:31.645Z]  19 (c0 -> s3): Ja(44) -> Jb(87)
[2021-10-20T03:07:31.645Z]  20 (c4 -> s4): Jb(47)
[2021-10-20T03:07:31.645Z]  21 (c4 -> s3): Na(48) -> Na(66) -> Na(76)
[2021-10-20T03:07:31.645Z]  22 (c0 -> s3): Ja(49) -> Na(60)xxx
[2021-10-20T03:07:31.645Z]  23 (c3 -> s1): Nb(50)
[2021-10-20T03:07:31.645Z]  24 (c3 -> s1): Na(52) -> Nb(79)
[2021-10-20T03:07:31.645Z]  25 (c4 -> s3): Na(54) -> Na(75)
[2021-10-20T03:07:31.645Z]  26 (c0 -> s3): Nb(55) -> Ja(71)xxx
[2021-10-20T03:07:31.645Z]  27 (c4 -> s2): Jb(57)
[2021-10-20T03:07:31.645Z]  28 (c3 -> s0): Na(58) -> Ja(67)xxx
[2021-10-20T03:07:31.645Z]  29 (c4 -> s1): Jb(59) -> Jb(86)
[2021-10-20T03:07:31.645Z]  30 (c1 -> s3): Na(61)
[2021-10-20T03:07:31.645Z]  31 (c2 -> s4): Nb(62) -> Ja(73)xxx
[2021-10-20T03:07:31.645Z]  32 (c1 -> s2): Nb(68) -> Ja(82)xxx -> Nb(99)
[2021-10-20T03:07:31.645Z]  33 (c2 -> s3): Jb(69)
[2021-10-20T03:07:31.645Z]  34 (c0 -> s4): Ja(70) -> Nb(94)xxx
[2021-10-20T03:07:31.645Z]  35 (c3 -> s2): Ja(72) -> Jb(88)
[2021-10-20T03:07:31.645Z]  36 (c0 -> s4): Jb(78)
[2021-10-20T03:07:31.645Z]  37 (c1 -> s2): Na(80)
[2021-10-20T03:07:31.645Z]  38 (c4 -> s1): Na(81)
[2021-10-20T03:07:31.645Z]  39 (c3 -> s4): Jb(84)
[2021-10-20T03:07:31.645Z]  40 (c1 -> s3): Nb(85)
[2021-10-20T03:07:31.645Z]  41 (c2 -> s3): Jb(89)
[2021-10-20T03:07:31.645Z]  42 (c3 -> s3): Na(93)
[2021-10-20T03:07:31.645Z]  43 (c0 -> s2): Na(95)
[2021-10-20T03:07:31.645Z]  44 (c1 -> s2): Ja(96) -> Jb(98)
[2021-10-20T03:07:31.645Z]  45 (c2 -> s3): Ja(97)
[2021-10-20T03:07:31.645Z] 
[2021-10-20T03:07:31.645Z] STDERR:
[2021-10-20T03:07:31.645Z] java.net.SocketTimeoutException: Accept timed out
[2021-10-20T03:07:31.645Z] 	at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
[2021-10-20T03:07:31.645Z] 	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
[2021-10-20T03:07:31.645Z] 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
[2021-10-20T03:07:31.645Z] 	at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
[2021-10-20T03:07:31.645Z] 	at KDC$2.run(KDC.java:1540)
[2021-10-20T03:07:31.645Z] Nsanity started
[2021-10-20T03:07:31.645Z] Ja started
[2021-10-20T03:07:31.645Z] Jb started
[2021-10-20T03:07:31.645Z] Na started
[2021-10-20T03:07:31.645Z] Nb started
[2021-10-20T03:07:31.645Z] java.lang.Exception
[2021-10-20T03:07:31.645Z] 	at ReplayCacheTestProc.main0(ReplayCacheTestProc.java:286)
[2021-10-20T03:07:31.645Z] 	at ReplayCacheTestProc.main(ReplayCacheTestProc.java:333)
[2021-10-20T03:07:31.645Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-20T03:07:31.645Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-10-20T03:07:31.645Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-20T03:07:31.645Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-10-20T03:07:31.645Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-20T03:07:31.645Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-10-20T03:07:31.645Z] java.lang.Exception
[2021-10-20T03:07:31.645Z] 	at ReplayCacheTestProc.main0(ReplayCacheTestProc.java:286)
[2021-10-20T03:07:31.645Z] 	at ReplayCacheTestProc.main(ReplayCacheTestProc.java:333)
[2021-10-20T03:07:31.645Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-20T03:07:31.645Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-10-20T03:07:31.645Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-20T03:07:31.645Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-10-20T03:07:31.645Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-20T03:07:31.645Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-10-20T03:07:31.645Z] 
[2021-10-20T03:07:31.645Z] JavaTest Message: Test threw exception: java.lang.Exception
[2021-10-20T03:07:31.645Z] JavaTest Message: shutting down test
[2021-10-20T03:07:31.645Z]

**Comment by sophia-guo** [comment]
Upstream issue https://bugs.openjdk.java.net/browse/JDK-8258855, close this one

**Comment by smlambert** [comment]
Are these tests excluded under that defect now?  https://bugs.openjdk.java.net/browse/JDK-8258855 - I do not see it mentioned in the ProblemList_openjdk11.txt file.
