### ISSUE TITLE
Java 11 - Alpine Linux fails AWT test (this likely makes sense as we're building headless)

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3057]
https://trss.adoptium.net/output/test?id=616f8d8bc6182d02178a4cb4

tests/TKG/../TKG/output_16346861212239/cmdLineTester_libpathTestRtfChild_0"; else echo ""; echo "cmdLineTester_libpathTestRtfChild_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/aqa-tests/TKG/../TKG/output_16346861212239/TestTargetResult";
[2021-10-19T23:28:42.775Z] Parsing exclude list...
[2021-10-19T23:28:42.775Z]   add excludes for [all]
[2021-10-19T23:28:42.775Z]   add excludes for [linux_x86-64]
[2021-10-19T23:28:42.775Z] DONE in 0 ms.
[2021-10-19T23:28:42.776Z] *** Starting test suite: LIBPATH RtfChild test intended for PMR56610 (CMVC 201272) ***
[2021-10-19T23:28:42.776Z] Testing: RtfChild testcase
[2021-10-19T23:28:42.776Z] Test start time: 2021/10/19 23:28:42 Greenwich Mean Time
[2021-10-19T23:28:42.776Z] Running command: /home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/bin/java   -Dcom.sun.management.jmxremote -cp /home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/libpathTest/libpathTest.jar org.openj9.test.libpath.RtfChild
[2021-10-19T23:28:44.021Z] Time spent starting: 21 milliseconds
[2021-10-19T23:28:44.021Z] 	Match (success): I am the child
[2021-10-19T23:28:44.021Z] 	Match (required): com.ibm.oti.vm.bootstrap.library.path=null
[2021-10-19T23:28:44.021Z] 	Match (required): sun.boot.library.path=/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib
[2021-10-19T23:28:44.021Z] 	Match (required): java.library.path=/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/../lib:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
[2021-10-19T23:28:44.021Z] Time spent executing: 694 milliseconds
[2021-10-19T23:28:44.021Z] Test result: FAILED
[2021-10-19T23:28:44.021Z] Output from test:
[2021-10-19T23:28:44.021Z]  [OUT] I am the child
[2021-10-19T23:28:44.021Z]  [OUT] com.ibm.oti.vm.bootstrap.library.path=null
[2021-10-19T23:28:44.021Z]  [OUT] sun.boot.library.path=/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib
[2021-10-19T23:28:44.021Z]  [OUT] java.library.path=/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/../lib:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
[2021-10-19T23:28:44.021Z]  [OUT] fontmanger LIB: libfontmanager.so
[2021-10-19T23:28:44.021Z]  [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /home/jenkins/workspace/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib/libawt_xawt.so
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.Runtime.load0(Runtime.java:768)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.System.load(System.java:1837)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:1873)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1395)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1393)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1392)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1425)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/java.awt.EventQueue.isDispatchThread(EventQueue.java:1086)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1493)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.reclaim(StyleContext.java:456)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.addAttribute(StyleContext.java:313)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext$NamedStyle.addAttribute(StyleContext.java:1539)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext$NamedStyle.setName(StyleContext.java:1349)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext$NamedStyle.<init>(StyleContext.java:1296)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.addStyle(StyleContext.java:108)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.<init>(StyleContext.java:88)
[2021-10-19T23:28:44.021Z]  [ERR] 	at java.desktop/javax.swing.text.DefaultStyledDocument.<init>(DefaultStyledDocument.java:108)
[2021-10-19T23:28:44.021Z]  [ERR] 	at org.openj9.test.libpath.RtfChild.convert(RtfChild.java:41)
[2021-10-19T23:28:44.021Z]  [ERR] 	at org.openj9.test.libpath.RtfChild.main(RtfChild.java:60)
[2021-10-19T23:28:44.021Z] >> Success condition was found: [Output match: I am the child]
[2021-10-19T23:28:44.021Z] >> Required condition was found: [Output match: com.ibm.oti.vm.bootstrap.library.path=]
[2021-10-19T23:28:44.021Z] >> Required condition was found: [Output match: sun.boot.library.path=]
[2021-10-19T23:28:44.021Z] >> Required condition was found: [Output match: java.library.path=]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: Could not find or load main class]
[2021-10-19T23:28:44.021Z] >> Failure condition was found: [Output match: java.lang.UnsatisfiedLinkError]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: Not found in com.ibm.oti.vm.bootstrap.library.path]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: at Rtf.main]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: at RtfChild.main]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: Unhandled Exception]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: Exception:]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: corrupt]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: Processing dump event]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: JVM requested Java dump]
[2021-10-19T23:28:44.021Z] >> Failure condition was not found: [Output match: JVM requested Snap dump]
[2021-10-19T23:28:44.021Z] 
[2021-10-19T23:28:44.021Z] 
[2021-10-19T23:28:44.021Z] ---TEST RESULTS---
[2021-10-19T23:28:44.021Z] Number of PASSED tests: 0 out of 1
[2021-10-19T23:28:44.021Z] Number of FAILED tests: 1 out of 1
[2021-10-19T23:28:44.021Z] 
[2021-10-19T23:28:44.021Z] ---SUMMARY OF FAILED TESTS---
[2021-10-19T23:28:44.021Z] RtfChild testcase
[2021-10-19T23:28:44.021Z] -----------------------------

**Comment by sxa** [comment]
Noting that I've hit this during the Ubuntu 24.04/riscv64/sanity.functional suite too, although it didn't fail on Fedora37 ...
