### ISSUE TITLE
Java 11 Alpine Linux test failures due to ./prog not being able to be run

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3058]
https://trss.adoptium.net/output/test?id=616f8db7c6182d02178a4e73

2021-10-19T23:55:41.968Z] ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
[2021-10-19T23:55:41.968Z] REASON: User specified action: run main/othervm/timeout=300 -Djdk.lang.Process.launchMechanism=posix_spawn Basic 
[2021-10-19T23:55:41.968Z] TIME:   12.175 seconds
[2021-10-19T23:55:41.968Z] messages:
[2021-10-19T23:55:41.968Z] command: main -Djdk.lang.Process.launchMechanism=posix_spawn Basic
[2021-10-19T23:55:41.968Z] reason: User specified action: run main/othervm/timeout=300 -Djdk.lang.Process.launchMechanism=posix_spawn Basic 
[2021-10-19T23:55:41.968Z] Mode: othervm [/othervm specified]
[2021-10-19T23:55:41.968Z] Additional options from @modules: --add-modules java.base --add-opens java.base/java.lang=ALL-UNNAMED
[2021-10-19T23:55:41.968Z] elapsed time (seconds): 12.175
[2021-10-19T23:55:41.968Z] configuration:
[2021-10-19T23:55:41.968Z] Boot Layer
[2021-10-19T23:55:41.968Z]   add modules: java.base           
[2021-10-19T23:55:41.968Z]   add opens:   java.base/java.lang ALL-UNNAMED
[2021-10-19T23:55:41.968Z] 
[2021-10-19T23:55:41.968Z] STDOUT:
[2021-10-19T23:55:41.968Z] This appears to be a Unix system.
[2021-10-19T23:55:41.968Z] Testing ASCII environment values
[2021-10-19T23:55:41.968Z] Testing Latin1 environment values
[2021-10-19T23:55:41.968Z] Testing Unicode environment values
[2021-10-19T23:55:41.968Z] Testing directory .
[2021-10-19T23:55:41.968Z] Testing directory ..
[2021-10-19T23:55:41.968Z] Testing directory /
[2021-10-19T23:55:41.968Z] Testing directory /bin
[2021-10-19T23:55:41.968Z] cmdp
[2021-10-19T23:55:41.968Z] cmdp 0: /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/openjdkbinary/j2sdk-image/bin/java
[2021-10-19T23:55:41.968Z] cmdp 1: -XX:+DisplayVMOutputToStderr
[2021-10-19T23:55:41.968Z] cmdp 2: -classpath
[2021-10-19T23:55:41.968Z] cmdp 3: /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/aqa-tests/TKG/output_16346876608868/jdk_lang_0/work/classes/11/java/lang/ProcessBuilder/Basic_id1.d:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/aqa-tests/TKG/output_16346876608868/jdk_lang_0/work/classes/11/test/lib:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/aqa-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/jvmtest/openjdk/jtreg/lib/jtreg.jar
[2021-10-19T23:55:41.968Z] cmdp 4: Basic$JavaChild
[2021-10-19T23:55:41.968Z] cmdp 5: System.getenv()
[2021-10-19T23:55:41.968Z] envp
[2021-10-19T23:55:41.968Z] envp 0: LC_ALL=C
[2021-10-19T23:55:41.968Z] envp 1: FO=BR
[2021-10-19T23:55:41.968Z]  waitFor process: delta: 68080
[2021-10-19T23:55:41.968Z] 
[2021-10-19T23:55:41.968Z] Passed = 9021, failed = 2
[2021-10-19T23:55:41.968Z] 
[2021-10-19T23:55:41.968Z] STDERR:
[2021-10-19T23:55:41.968Z] >'java.io.IOException: Cannot run program "./prog": error=8, Exec format error
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[2021-10-19T23:55:41.968Z] 	at Basic.run(Basic.java:2728)
[2021-10-19T23:55:41.968Z] 	at Basic$JavaChild.main(Basic.java:491)
[2021-10-19T23:55:41.968Z] Caused by: java.io.IOException: error=8, Exec format error
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[2021-10-19T23:55:41.968Z] 	... 3 more
[2021-10-19T23:55:41.968Z] Exception in thread "main" java.lang.NullPointerException
[2021-10-19T23:55:41.968Z] 	at Basic$JavaChild.main(Basic.java:491)
[2021-10-19T23:55:41.968Z] '< not equal to ''
[2021-10-19T23:55:41.968Z] java.lang.Exception: Stack trace
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.Thread.dumpStack(Thread.java:1383)
[2021-10-19T23:55:41.968Z] 	at Basic.fail(Basic.java:2799)
[2021-10-19T23:55:41.968Z] 	at Basic.fail(Basic.java:2800)
[2021-10-19T23:55:41.968Z] 	at Basic.equal(Basic.java:2806)
[2021-10-19T23:55:41.968Z] 	at Basic.realMain(Basic.java:2000)
[2021-10-19T23:55:41.968Z] 	at Basic.main(Basic.java:2809)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-10-19T23:55:41.968Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-10-19T23:55:41.968Z] >'1'< not equal to '0'
[2021-10-19T23:55:41.968Z] java.lang.Exception: Stack trace
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.Thread.dumpStack(Thread.java:1383)
[2021-10-19T23:55:41.968Z] 	at Basic.fail(Basic.java:2799)
[2021-10-19T23:55:41.968Z] 	at Basic.fail(Basic.java:2800)
[2021-10-19T23:55:41.968Z] 	at Basic.equal(Basic.java:2806)
[2021-10-19T23:55:41.968Z] 	at Basic.realMain(Basic.java:2001)
[2021-10-19T23:55:41.968Z] 	at Basic.main(Basic.java:2809)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-10-19T23:55:41.968Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-10-19T23:55:41.968Z] java.lang.AssertionError: Some tests failed
[2021-10-19T23:55:41.968Z] 	at Basic.main(Basic.java:2811)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-10-19T23:55:41.968Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-10-19T23:55:41.968Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-19T23:55:41.968Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-10-19T23:55:41.968Z] 
[2021-10-19T23:55:41.968Z] JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
[2021-10-19T23:55:41.968Z] JavaTest Message: shutting down test

**Comment by smlambert** [comment]
This should likely transfer to infrastructure repo, if prog is not available in the alpine-linux docker images.

**Comment by karianna** [comment]
> This should likely transfer to infrastructure repo, if prog is not available in the alpine-linux docker images.

Yeah I think there are a few classes of 'Set this special thing up for Alpine' that I'll ask George and Stephanie to look at.  Overall pretty impressed with Alpine's stability on hotspot and class lib tests

**Comment by calderast** [comment]
We've seen this at msft for java/lang/ProcessBuilder/Basic.java#id0 and java/lang/ProcessBuilder/Basic.java#id1 on both jdk11 and jdk17, also on JBS: https://bugs.openjdk.java.net/browse/JDK-8245748

**Comment by sophia-guo** [comment]
Close this in favour of https://bugs.openjdk.java.net/browse/JDK-8245748
