### ISSUE TITLE
JDK8 arm32 TestJlmRemote test failures

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3117]
The following tests from the sanity system suite are failing on jdk 8 arm 32 

```
TestJlmRemoteClassNoAuth_2
TestJlmRemoteMemoryAuth_2
TestJlmRemoteMemoryNoAuth_2
TestJlmRemoteThreadNoAuth_2
```
Latest failure
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_arm_linux/79/tapResults/

TestJlmRemoteClassNoAuth_2

```
STF 21:05:37.433 - Running command: /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/openjdkbinary/j2sdk-image/bin/java -Xmx256m -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/jvmtest/system/aqa-systemtest/openjdk.test.jlm/bin:/home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/jvmtest/system/systemtest_prereqs/junit/junit.jar net.adoptopenjdk.test.jlm.remote.ClassProfiler server /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/output_1635799406766/TestJlmRemoteClassNoAuth_2/20211101-210007-TestJlmRemoteClassNoAuth/results/cls_proxy.log /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/output_1635799406766/TestJlmRemoteClassNoAuth_2/20211101-210007-TestJlmRemoteClassNoAuth/results/cls_proxy.csv anon localhost 1234
STF 21:05:37.433 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/output_1635799406766/TestJlmRemoteClassNoAuth_2/20211101-210007-TestJlmRemoteClassNoAuth/results/6.CL2.stderr
STF 21:05:37.433 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/output_1635799406766/TestJlmRemoteClassNoAuth_2/20211101-210007-TestJlmRemoteClassNoAuth/results/6.CL2.stdout
STF 21:05:37.435 - 
STF 21:05:37.435 - +------ Step 7 - Wait for processes to complete
STF 21:05:37.435 - | Wait for processes to meet expectations
STF 21:05:37.435 - |   Processes: [LT2, CL2]
STF 21:05:37.435 - |
STF 21:05:37.436 - Monitoring processes: CL2 LT2
CL2 j> 2021/11/01 21:05:37.510 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
CL2 j> 2021/11/01 21:05:37.532 Attempting to connect
CL2 j> 2021/11/01 21:05:37.683 Monitored VM not ready at Nov 1, 2021 9:05:37 PM (attempt 1, elapsed 137ms).
CL2 j> 2021/11/01 21:05:37.683 Waiting 5 secs and trying again...
STF 21:05:38.869 - **FAILED** Process LT2 has ended unexpectedly
STF 21:05:38.870 - Monitoring Report Summary:
STF 21:05:38.870 -   o Process CL2 is still running
STF 21:05:38.870 -   o Process LT2 has ended unexpectedly
STF 21:05:38.870 - Killing processes: CL2 LT2
STF 21:05:38.871 -   o Process CL2 pid 2637889 stop()
STF 21:05:48.873 -   o Process CL2 pid 2637889 terminate()
STF 21:05:49.874 -   o Process CL2 pid 2637889 killed
CL2 j> 2021/11/01 21:05:42.684 Attempting to connect
CL2 j> 2021/11/01 21:05:42.686 Monitored VM not ready at Nov 1, 2021 9:05:42 PM (attempt 2, elapsed 5154ms).
CL2 j> 2021/11/01 21:05:42.686 Waiting 5 secs and trying again...
CL2 j> 2021/11/01 21:05:47.687 Attempting to connect
CL2 j> 2021/11/01 21:05:47.689 Monitored VM not ready at Nov 1, 2021 9:05:47 PM (attempt 3, elapsed 10156ms).
CL2 j> 2021/11/01 21:05:47.689 Waiting 5 secs and trying again...
STF 21:05:49.874 -   o Process LT2 pid 2637887 is not running
**FAILED** at step 7 (Wait for processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/../TKG/output_1635799406766/TestJlmRemoteClassNoAuth_2/20211101-210007-TestJlmRemoteClassNoAuth/execute.pl line 292.
STF 21:05:50.123 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 21:05:50.123 - 
STF 21:05:50.124 - ====================   T E A R D O W N   ====================
STF 21:05:50.124 - Running teardown: perl /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/../TKG/output_1635799406766/TestJlmRemoteClassNoAuth_2/20211101-210007-TestJlmRemoteClassNoAuth/tearDown.pl
STF 21:05:50.182 - TEARDOWN stage completed
STF 21:05:50.185 - 
STF 21:05:50.185 - =====================   R E S U L T S   =====================
STF 21:05:50.185 - Stage results:
STF 21:05:50.185 -   setUp:     pass
STF 21:05:50.185 -   execute:  *fail*
STF 21:05:50.185 -   teardown:  pass
STF 21:05:50.185 - 
STF 21:05:50.185 - Overall result: **FAILED**
```

These two tests have a similar error log:
TestJlmRemoteMemoryAuth_2
TestJlmRemoteMemoryNoAuth_2

```
STF 21:05:51.754 - Monitoring processes: CL1 LT1
CL1 j> 2021/11/01 21:05:51.827 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
CL1 j> 2021/11/01 21:05:51.842 Attempting to connect
CL1 j> 2021/11/01 21:05:51.928 Monitored VM not ready at Nov 1, 2021 9:05:51 PM (attempt 1, elapsed 78ms).
CL1 j> 2021/11/01 21:05:51.928 Waiting 5 secs and trying again...
CL1 j> 2021/11/01 21:05:56.929 Attempting to connect
CL1 j> 2021/11/01 21:05:59.720 Connection established!
CL1 j> 2021/11/01 21:06:00.268 Starting to write data
STF 21:07:49.010 - **FAILED** Process LT1 has ended unexpectedly
STF 21:07:49.011 - Monitoring Report Summary:
STF 21:07:49.011 -   o Process CL1 is still running
STF 21:07:49.011 -   o Process LT1 has ended unexpectedly
STF 21:07:49.011 - Killing processes: CL1 LT1
STF 21:07:49.011 -   o Process LT1 pid 2638056 is not running
STF 21:07:49.011 -   o Process CL1 pid 2638057 stop()
STF 21:07:50.012 -   o Process CL1 pid 2638057 killed
CL1 .........j> 2021/11/01 21:07:49.319 Exiting as ConnectException thrown receiving data from the connected JVM.  This may mean the JVM we are connected to has finished. null
CL1 stderr java.lang.reflect.UndeclaredThrowableException
CL1 stderr 	at com.sun.proxy.$Proxy1.getUptime(Unknown Source)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.recordMemoryStats(MemoryProfiler.java:303)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.getStatsViaProxy(MemoryProfiler.java:187)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:110)
CL1 stderr Caused by: java.rmi.ConnectException: Connection refused to host: 172.17.0.10; nested exception is: 
CL1 stderr 	java.net.ConnectException: Connection refused (Connection refused)
CL1 stderr 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
CL1 stderr 	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
CL1 stderr 	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
CL1 stderr 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
CL1 stderr 	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
CL1 stderr 	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
CL1 stderr 	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
CL1 stderr 	at com.sun.jmx.mbeanserver.MXBeanProxy$GetHandler.invoke(MXBeanProxy.java:122)
CL1 stderr 	at com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
CL1 stderr 	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
CL1 stderr 	... 4 more
CL1 stderr Caused by: java.net.ConnectException: Connection refused (Connection refused)
CL1 stderr 	at java.net.PlainSocketImpl.socketConnect(Native Method)
CL1 stderr 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
CL1 stderr 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
CL1 stderr 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
CL1 stderr 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
CL1 stderr 	at java.net.Socket.connect(Socket.java:607)
CL1 stderr 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:288)
CL1 stderr 	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:147)
CL1 stderr 	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
CL1 stderr 	at javax.rmi.ssl.SslRMIClientSocketFactory.createSocket(SslRMIClientSocketFactory.java:121)
CL1 stderr 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
CL1 stderr 	... 13 more
CL1 stderr Exception in thread "main" java.lang.AssertionError: Exiting as ConnectException thrown receiving data from the connected JVM.  This may mean the JVM we are connected to has finished. null
CL1 stderr 	at org.junit.Assert.fail(Assert.java:88)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.getStatsViaProxy(MemoryProfiler.java:211)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:110)
**FAILED** at step 5 (Wait for the processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/../TKG/output_1635799406766/TestJlmRemoteMemoryAuth_2/20211101-210550-TestJlmRemoteMemoryAuth/execute.pl line 173.
STF 21:07:50.358 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 21:07:50.358 - 
STF 21:07:50.358 - ====================   T E A R D O W N   ====================
STF 21:07:50.358 - Running teardown: perl /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/../TKG/output_1635799406766/TestJlmRemoteMemoryAuth_2/20211101-210550-TestJlmRemoteMemoryAuth/tearDown.pl
STF 21:07:50.410 - TEARDOWN stage completed
STF 21:07:50.414 - 
STF 21:07:50.414 - =====================   R E S U L T S   =====================
STF 21:07:50.415 - Stage results:
STF 21:07:50.415 -   setUp:     pass
STF 21:07:50.415 -   execute:  *fail*
STF 21:07:50.415 -   teardown:  pass
STF 21:07:50.415 - 
STF 21:07:50.415 - Overall result: **FAILED**

TestJlmRemoteMemoryAuth_2_FAILED
```

TestJlmRemoteThreadNoAuth_2

```
CL2 j> 2021/11/01 21:36:51.277  done.
STF 21:36:53.460 - **FAILED** Process LT2 has ended unexpectedly
CL2 j> 2021/11/01 21:36:53.341 Connection refused to host: 172.17.0.10; nested exception is: 
CL2 	java.net.ConnectException: Connection refused (Connection refused)
CL2 stderr java.rmi.ConnectException: Connection refused to host: 172.17.0.10; nested exception is: 
CL2 stderr 	java.net.ConnectException: Connection refused (Connection refused)
CL2 stderr 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
CL2 stderr 	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
CL2 stderr 	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
CL2 stderr 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
CL2 stderr 	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
CL2 stderr 	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
CL2 stderr 	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.recordThreadStats(ThreadProfiler.java:255)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:204)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
CL2 stderr Caused by: java.net.ConnectException: Connection refused (Connection refused)
CL2 stderr 	at java.net.PlainSocketImpl.socketConnect(Native Method)
CL2 stderr 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
CL2 stderr 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
CL2 stderr 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
CL2 stderr 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
CL2 stderr 	at java.net.Socket.connect(Socket.java:607)
CL2 stderr 	at java.net.Socket.connect(Socket.java:556)
CL2 stderr 	at java.net.Socket.<init>(Socket.java:452)
CL2 stderr 	at java.net.Socket.<init>(Socket.java:229)
CL2 stderr 	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
CL2 stderr 	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
CL2 stderr 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
CL2 stderr 	... 9 more
CL2 stderr Exception in thread "main" java.lang.AssertionError: Connection refused to host: 172.17.0.10; nested exception is: 
CL2 stderr 	java.net.ConnectException: Connection refused (Connection refused)
CL2 stderr 	at org.junit.Assert.fail(Assert.java:88)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.recordThreadStats(ThreadProfiler.java:263)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:204)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
STF 21:36:53.461 - Monitoring Report Summary:
STF 21:36:53.461 -   o Process CL2 ended with exit code (1) and not the expected exit code/s (0)
STF 21:36:53.461 -   o Process LT2 has ended unexpectedly
STF 21:36:53.462 - Killing processes: CL2 LT2
STF 21:36:53.462 -   o Process CL2 pid 2639949 is not running
STF 21:36:53.462 -   o Process LT2 pid 2639948 is not running
**FAILED** at step 7 (Wait for processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/../TKG/output_1635799406766/TestJlmRemoteThreadNoAuth_2/20211101-212550-TestJlmRemoteThreadNoAuth/execute.pl line 292.
STF 21:36:53.743 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 21:36:53.743 - 
STF 21:36:53.743 - ====================   T E A R D O W N   ====================
STF 21:36:53.743 - Running teardown: perl /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_arm_linux/aqa-tests/TKG/../TKG/output_1635799406766/TestJlmRemoteThreadNoAuth_2/20211101-212550-TestJlmRemoteThreadNoAuth/tearDown.pl
STF 21:36:53.795 - TEARDOWN stage completed
STF 21:36:53.801 - 
STF 21:36:53.802 - =====================   R E S U L T S   =====================
STF 21:36:53.802 - Stage results:
STF 21:36:53.802 -   setUp:     pass
STF 21:36:53.802 -   execute:  *fail*
STF 21:36:53.803 -   teardown:  pass
STF 21:36:53.803 - 
STF 21:36:53.803 - Overall result: **FAILED**

TestJlmRemoteThreadNoAuth_2_FAILED

```

**Comment by Haroon-Khel** [comment]
These tests passed on build-equinix-ubuntu1604-armv7l-1 https://ci.adoptopenjdk.net/job/Grinder/2434/console

**Comment by Haroon-Khel** [comment]
Moved over to infra repo https://github.com/adoptium/infrastructure/issues/2376
