### ISSUE TITLE
jdk_util_2 test failures on JDK8 arm32 

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3118]
Many tests from jdk_util_2 in the hs sanity openjdk test suite fail on arm32

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/280/testReport/

Null pointers errors
java/util/concurrent/BlockingQueue/MultipleProducersSingleConsumerLoops.java.MultipleProducersSingleConsumerLoops
java/util/concurrent/ExecutorCompletionService/ExecutorCompletionServiceLoops.java.ExecutorCompletionServiceLoops
java/util/logging/TestLogConfigurationDeadLock.java.TestLogConfigurationDeadLock
java/util/logging/TestLogConfigurationDeadLockWithConf.java.TestLogConfigurationDeadLockWithConf
java/util/concurrent/BlockingQueue/CancelledProducerConsumerLoops.java.CancelledProducerConsumerLoops

Many of the error logs of the above test failures have the following format

```
[2021-11-01T20:54:47.311Z] STDERR:
[2021-11-01T20:54:47.311Z] java.util.concurrent.ExecutionException: java.lang.NullPointerException
[2021-11-01T20:54:47.311Z] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[2021-11-01T20:54:47.311Z] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[2021-11-01T20:54:47.311Z] 	at CancelledProducerConsumerLoops.oneRun(CancelledProducerConsumerLoops.java:101)
[2021-11-01T20:54:47.311Z] 	at CancelledProducerConsumerLoops.oneTest(CancelledProducerConsumerLoops.java:125)
[2021-11-01T20:54:47.311Z] 	at CancelledProducerConsumerLoops.main(CancelledProducerConsumerLoops.java:65)
[2021-11-01T20:54:47.311Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-01T20:54:47.311Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-01T20:54:47.311Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-01T20:54:47.311Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
```

Assert failure
java/util/stream/boottest/java/util/stream/DoubleNodeTest.java.DoubleNodeTest
java/util/stream/boottest/java/util/stream/IntNodeTest.java.IntNodeTest
java/util/stream/test/org/openjdk/tests/java/util/stream/RangeTest.java.RangeTest
java/util/stream/boottest/java/util/stream/LongNodeTest.java.LongNodeTest
java/util/stream/boottest/java/util/stream/NodeTest.java.NodeTest
java/util/stream/boottest/java/util/stream/FlagOpTest.java.FlagOpTest
java/util/stream/test/org/openjdk/tests/java/util/stream/FilterOpTest.java.FilterOpTest
java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest.java.InfiniteStreamWithLimitOpTest
java/util/stream/test/org/openjdk/tests/java/util/stream/IntSliceOpTest.java.IntSliceOpTest
java/util/stream/test/org/openjdk/tests/java/util/stream/IntUniqOpTest.java.IntUniqOpTest
java/util/stream/test/org/openjdk/tests/java/util/stream/SequentialOpTest.java.SequentialOpTest
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamBuilderTest.java.StreamBuilderTest

Many of these error logs are of the following format

```
[2021-11-01T20:59:11.062Z] PAR_STREAM_FOR_EACH: [actual size=1023] != [expected size=1024]
[2021-11-01T20:59:11.062Z] java.lang.AssertionError: Maps do not have the same size:1023 != 1024
```

Many of the existing openjdk bug issues involving these tests concern compilation and dump issues, but not null pointer

**Comment by Haroon-Khel** [comment]
These tests passed on build-equinix-ubuntu1604-armv7l-1. It seems its an infrastructure issue https://ci.adoptopenjdk.net/job/Grinder/2429/console

**Comment by Haroon-Khel** [comment]
Moved over to infra repo https://github.com/adoptium/infrastructure/issues/2376
