### ISSUE TITLE
Linux x86-64 jdk_build_1 failed AbsPathsInImage with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3234]
[2022-01-19T03:29:17.587Z] Running test jdk_build_1 ...
[2022-01-19T03:29:17.587Z] ===============================================
[2022-01-19T03:29:17.587Z] jdk_build_1 Start Time: Wed Jan 19 02:47:56 2022 Epoch Time (ms): 1642560476172
[2022-01-19T03:29:17.587Z] Nothing to be done for setup.
[2022-01-19T03:29:17.587Z] variation: Mode650
[2022-01-19T03:29:17.587Z] JVM_OPTIONS:  -XX:-UseCompressedOops 
[2022-01-19T03:29:17.587Z] { itercnt=1; \
[2022-01-19T03:29:17.587Z] mkdir -p "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../TKG/output_16425427777025/jdk_build_1"; \
[2022-01-19T03:29:17.587Z] cd "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../TKG/output_16425427777025/jdk_build_1"; \
[2022-01-19T03:29:17.587Z] "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xmx512m -jar "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
[2022-01-19T03:29:17.587Z] -agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:3  -nativepath:"/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/openjdk-test-image/jdk/jtreg/native" -vmoptions:"-Xmx512m  -XX:-UseCompressedOops  " \
[2022-01-19T03:29:17.588Z] -w ""/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../TKG/output_16425427777025/jdk_build_1"/work" \
[2022-01-19T03:29:17.588Z] -r "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../../jvmtest/openjdk/report" \
[2022-01-19T03:29:17.588Z] -jdk:"/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image" \
[2022-01-19T03:29:17.588Z] -exclude:"/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../openjdk/openjdk-jdk/test/jdk/ProblemList.txt" \
[2022-01-19T03:29:17.588Z] -exclude:"/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../../jvmtest/openjdk/excludes/ProblemList_openjdk11.txt" \
[2022-01-19T03:29:17.588Z] "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../openjdk/openjdk-jdk/test/jdk:build"; \
[2022-01-19T03:29:17.588Z] if [ $? -eq 0 ] ; then echo ""; echo "jdk_build_1""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/..;  else echo ""; echo "jdk_build_1""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../TKG/output_16425427777025/TestTargetResult";
[2022-01-19T03:29:18.203Z] Directory "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/../TKG/output_16425427777025/jdk_build_1/work" not found: creating
[2022-01-19T03:29:25.313Z] XML output with verification to /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work
[2022-01-19T03:30:41.009Z] --------------------------------------------------
[2022-01-19T03:30:41.009Z] TEST: build/AbsPathsInImage.java
[2022-01-19T03:30:41.009Z] TEST JDK: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image
[2022-01-19T03:30:41.009Z] 
[2022-01-19T03:30:41.009Z] ACTION: build -- Passed. Build successful
[2022-01-19T03:30:41.009Z] REASON: Named class compiled on demand
[2022-01-19T03:30:41.009Z] TIME:   5.105 seconds
[2022-01-19T03:30:41.009Z] messages:
[2022-01-19T03:30:41.009Z] command: build AbsPathsInImage
[2022-01-19T03:30:41.009Z] reason: Named class compiled on demand
[2022-01-19T03:30:41.009Z] Test directory:
[2022-01-19T03:30:41.009Z]   compile: AbsPathsInImage
[2022-01-19T03:30:41.009Z] elapsed time (seconds): 5.105
[2022-01-19T03:30:41.009Z] 
[2022-01-19T03:30:41.009Z] ACTION: compile -- Passed. Compilation successful
[2022-01-19T03:30:41.009Z] REASON: .class file out of date or does not exist
[2022-01-19T03:30:41.009Z] TIME:   5.099 seconds
[2022-01-19T03:30:41.009Z] messages:
[2022-01-19T03:30:41.009Z] command: compile /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build/AbsPathsInImage.java
[2022-01-19T03:30:41.009Z] reason: .class file out of date or does not exist
[2022-01-19T03:30:41.009Z] Mode: agentvm
[2022-01-19T03:30:41.009Z] Agent id: 2
[2022-01-19T03:30:41.009Z] elapsed time (seconds): 5.099
[2022-01-19T03:30:41.009Z] configuration:
[2022-01-19T03:30:41.009Z] Boot Layer (javac runtime environment)
[2022-01-19T03:30:41.009Z]   class path: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/javatest.jar 
[2022-01-19T03:30:41.009Z]               /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/jtreg.jar 
[2022-01-19T03:30:41.009Z]   patch:      java.base /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/patches/java.base
[2022-01-19T03:30:41.009Z] 
[2022-01-19T03:30:41.009Z] javac compilation environment
[2022-01-19T03:30:41.009Z]   source path: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build
[2022-01-19T03:30:41.009Z]   class path:  /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build
[2022-01-19T03:30:41.009Z]                /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d
[2022-01-19T03:30:41.009Z] 
[2022-01-19T03:30:41.009Z] rerun:
[2022-01-19T03:30:41.009Z] cd /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/scratch/0 && \
[2022-01-19T03:30:41.009Z] DISPLAY=:1 \
[2022-01-19T03:30:41.009Z] HOME=/home/jenkins \
[2022-01-19T03:30:41.009Z] LANG=C.UTF-8 \
[2022-01-19T03:30:41.009Z] PATH=/bin:/usr/bin:/usr/sbin \
[2022-01-19T03:30:41.009Z]     /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image/bin/javac \
[2022-01-19T03:30:41.009Z]         -J-ea \
[2022-01-19T03:30:41.009Z]         -J-esa \
[2022-01-19T03:30:41.009Z]         -J-Xmx512m \
[2022-01-19T03:30:41.009Z]         -J-XX:-UseCompressedOops \
[2022-01-19T03:30:41.009Z]         -J-Djava.library.path=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
[2022-01-19T03:30:41.009Z]         -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
[2022-01-19T03:30:41.009Z]         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
[2022-01-19T03:30:41.009Z]         -J-Dtest.compiler.opts= \
[2022-01-19T03:30:41.009Z]         -J-Dtest.java.opts= \
[2022-01-19T03:30:41.009Z]         -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image \
[2022-01-19T03:30:41.009Z]         -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image \
[2022-01-19T03:30:41.009Z]         -J-Dtest.timeout.factor=8.0 \
[2022-01-19T03:30:41.009Z]         -J-Dtest.nativepath=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
[2022-01-19T03:30:41.009Z]         -J-Dtest.root=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk \
[2022-01-19T03:30:41.009Z]         -J-Dtest.name=build/AbsPathsInImage.java \
[2022-01-19T03:30:41.009Z]         -J-Dtest.file=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build/AbsPathsInImage.java \
[2022-01-19T03:30:41.010Z]         -J-Dtest.src=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build \
[2022-01-19T03:30:41.010Z]         -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build \
[2022-01-19T03:30:41.010Z]         -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d \
[2022-01-19T03:30:41.010Z]         -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d \
[2022-01-19T03:30:41.010Z]         -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build \
[2022-01-19T03:30:41.010Z]         -d /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d \
[2022-01-19T03:30:41.010Z]         -sourcepath /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build \
[2022-01-19T03:30:41.010Z]         -classpath /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build/AbsPathsInImage.java
[2022-01-19T03:30:41.010Z] 
[2022-01-19T03:30:41.010Z] ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.ArrayIndexOutOfBoundsException: Index 498 out of bounds for length 498
[2022-01-19T03:30:41.010Z] REASON: User specified action: run main AbsPathsInImage 
[2022-01-19T03:30:41.010Z] TIME:   68.711 seconds
[2022-01-19T03:30:41.010Z] messages:
[2022-01-19T03:30:41.010Z] command: main AbsPathsInImage
[2022-01-19T03:30:41.010Z] reason: User specified action: run main AbsPathsInImage 
[2022-01-19T03:30:41.010Z] Mode: agentvm
[2022-01-19T03:30:41.010Z] Agent id: 4
[2022-01-19T03:30:41.010Z] elapsed time (seconds): 68.711
[2022-01-19T03:30:41.010Z] configuration:
[2022-01-19T03:30:41.010Z] Boot Layer
[2022-01-19T03:30:41.010Z]   class path: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/javatest.jar 
[2022-01-19T03:30:41.010Z]               /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/jtreg.jar 
[2022-01-19T03:30:41.010Z]               /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/junit.jar 
[2022-01-19T03:30:41.010Z]               /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/testng.jar 
[2022-01-19T03:30:41.010Z]               /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/jcommander.jar 
[2022-01-19T03:30:41.010Z]   patch:      java.base /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/patches/java.base
[2022-01-19T03:30:41.010Z] 
[2022-01-19T03:30:41.010Z] Test Layer
[2022-01-19T03:30:41.010Z]   class path: /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d
[2022-01-19T03:30:41.010Z]               /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build
[2022-01-19T03:30:41.010Z] 
[2022-01-19T03:30:41.010Z] rerun:
[2022-01-19T03:30:41.010Z] cd /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/scratch/0 && \
[2022-01-19T03:30:41.010Z] DISPLAY=:1 \
[2022-01-19T03:30:41.010Z] HOME=/home/jenkins \
[2022-01-19T03:30:41.010Z] LANG=C.UTF-8 \
[2022-01-19T03:30:41.010Z] PATH=/bin:/usr/bin:/usr/sbin \
[2022-01-19T03:30:41.010Z]     /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image/bin/java \
[2022-01-19T03:30:41.010Z]         -Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
[2022-01-19T03:30:41.010Z]         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
[2022-01-19T03:30:41.010Z]         -Dtest.compiler.opts= \
[2022-01-19T03:30:41.010Z]         -Dtest.java.opts= \
[2022-01-19T03:30:41.010Z]         -Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image \
[2022-01-19T03:30:41.010Z]         -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image \
[2022-01-19T03:30:41.010Z]         -Dtest.timeout.factor=8.0 \
[2022-01-19T03:30:41.010Z]         -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
[2022-01-19T03:30:41.010Z]         -Dtest.root=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk \
[2022-01-19T03:30:41.010Z]         -Dtest.name=build/AbsPathsInImage.java \
[2022-01-19T03:30:41.010Z]         -Dtest.file=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build/AbsPathsInImage.java \
[2022-01-19T03:30:41.010Z]         -Dtest.src=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build \
[2022-01-19T03:30:41.010Z]         -Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build \
[2022-01-19T03:30:41.010Z]         -Dtest.classes=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d \
[2022-01-19T03:30:41.010Z]         -Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d \
[2022-01-19T03:30:41.010Z]         -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build \
[2022-01-19T03:30:41.010Z]         -classpath /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work/classes/1/build/AbsPathsInImage.d:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/build:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/jtreg/lib/jtreg.jar \
[2022-01-19T03:30:41.010Z]         AbsPathsInImage
[2022-01-19T03:30:41.010Z] STDERR:
[2022-01-19T03:30:41.010Z] java.lang.ArrayIndexOutOfBoundsException: Index 498 out of bounds for length 498
[2022-01-19T03:30:41.010Z] 	at AbsPathsInImage.scanBytes(AbsPathsInImage.java:200)
[2022-01-19T03:30:41.010Z] 	at AbsPathsInImage.scanFile(AbsPathsInImage.java:168)
[2022-01-19T03:30:41.010Z] 	at AbsPathsInImage$1.visitFile(AbsPathsInImage.java:160)
[2022-01-19T03:30:41.010Z] 	at AbsPathsInImage$1.visitFile(AbsPathsInImage.java:144)
[2022-01-19T03:30:41.010Z] 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2725)
[2022-01-19T03:30:41.010Z] 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
[2022-01-19T03:30:41.010Z] 	at AbsPathsInImage.scanFiles(AbsPathsInImage.java:144)
[2022-01-19T03:30:41.010Z] 	at AbsPathsInImage.main(AbsPathsInImage.java:110)
[2022-01-19T03:30:41.010Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-19T03:30:41.010Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-01-19T03:30:41.010Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-19T03:30:41.010Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-01-19T03:30:41.010Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-01-19T03:30:41.010Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-01-19T03:30:41.010Z] 
[2022-01-19T03:30:41.010Z] JavaTest Message: Test threw exception: java.lang.ArrayIndexOutOfBoundsException
[2022-01-19T03:30:41.010Z] JavaTest Message: shutting down test
[2022-01-19T03:30:41.010Z] 
[2022-01-19T03:30:41.010Z] STDOUT:
[2022-01-19T03:30:41.010Z] Getting patterns from local environment
[2022-01-19T03:30:41.010Z] Looking for:
[2022-01-19T03:30:41.010Z] /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk
[2022-01-19T03:30:41.010Z] /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/openjdkbinary
[2022-01-19T03:30:41.011Z] 
[2022-01-19T03:30:41.011Z] 
[2022-01-19T03:30:41.011Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.ArrayIndexOutOfBoundsException: Index 498 out of bounds for length 498
[2022-01-19T03:30:41.011Z] --------------------------------------------------
[2022-01-19T03:30:41.011Z] Test results: passed: 1; failed: 1
[2022-01-19T03:30:57.894Z] Report written to /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/report/html/report.html
[2022-01-19T03:30:57.894Z] Results written to /home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16425427777025/jdk_build_1/work
[2022-01-19T03:30:57.894Z] Error: Some tests failed or other problems occurred.
[2022-01-19T03:30:57.894Z] 
[2022-01-19T03:30:57.894Z] jdk_build_1_FAILED
[2022-01-19T03:30:57.894Z] 
[2022-01-19T03:30:57.894Z] Nothing to be done for teardown.
[2022-01-19T03:30:57.894Z] jdk_build_1 Finish Time: Wed Jan 19 02:49:35 2022 Epoch Time (ms): 1642560575513

**Comment by karianna** [comment]
This failed in the 11.0.13 release but passed after 10 grinders.  Seems Intermittent

**Comment by sophia-guo** [comment]
Looks like it's not intermittent in recent runs.

[Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/35/) ⚠️ UNSTABLE ⚠️

jdk_build_1 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=62573c3172761a4c5c11e705) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62573b2272761a4c5c11e304&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0&testId=62573c3172761a4c5c11e705&testName=jdk_build_1)

[Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2/35/) ⚠️ UNSTABLE ⚠️
jdk_build_0 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=62573c2272761a4c5c11e65b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62573b2272761a4c5c11e300&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2&testId=62573c2272761a4c5c11e65b&testName=jdk_build_0)

**Comment by smlambert** [comment]
Close as dup of https://github.com/adoptium/aqa-tests/issues/3988

**Comment by sophia-guo** [comment]
This is a different error from #3988, which happens only to jdk11 as the commit https://github.com/adoptium/jdk17u/commit/5fff0506f9dca6bcfe91992138ceff32d86370a8 is not backport to jdk11. With the commit https://github.com/sophia-guo/jdk11u/blob/test/test/jdk/build/AbsPathsInImage.java#L211 https://ci.adoptium.net/job/Grinder/11238/console - passed . Will see if we can backport otherwise consider as excluded permanent.
