### ISSUE TITLE
CustomeLauncherTest fails as its unable to find the launcher executable on Alpine Linux 11

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3238]
java.io.IOException: Cannot run program "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux/aqa-tests/TKG/output_16425959244573/jdk_management_0/work/scratch/13/launcher": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at jdk.testlibrary.ProcessTools.startProcess(ProcessTools.java:162)
	at jdk.testlibrary.ProcessTools.startProcess(ProcessTools.java:129)
	at CustomLauncherTest.main(CustomLauncherTest.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 10 more

JavaTest Message: Test threw exception: java.io.IOException: Cannot run program "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux/aqa-tests/TKG/output_16425959244573/jdk_management_0/work/scratch/13/launcher": error=2, No such file or directory
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.io.IOException: Cannot run program "/home/jenkins/workspace/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux/aqa-tests/TKG/output_16425959244573/jdk_management_0/work/scratch/13/launcher": error=2, No such file or directory

**Comment by karianna** [comment]
I'm immediately suspicious about the really long path.

**Comment by smlambert** [comment]
https://bugs.openjdk.java.net/browse/JDK-8240604

For JDK8 and JDK11, this test uses prebuilt executables in test/sun/management/jmxremote/bootstrap/ dir.... in JDK15+ it builds the executable from launcher.c file

We can/should exclude this on 8/11 for alpine-linux.
