### ISSUE TITLE
java/net/Socket/GetLocalAddress.java.GetLocalAddress fails on jdk8 hotspot aix 

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3251]
Latest failure link https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64_aix_testList_1/25/testReport/

The test java/net/Socket/GetLocalAddress.java.GetLocalAddress from jdk_net_1 in the extended openjdk test suite fails on aix for jdk8 hotspot

```
[2022-01-19T14:56:14.750Z] java.net.NoRouteToHostException: Can't assign requested address (Address not available)
[2022-01-19T14:56:14.750Z] 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[2022-01-19T14:56:14.750Z] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[2022-01-19T14:56:14.750Z] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[2022-01-19T14:56:14.750Z] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[2022-01-19T14:56:14.750Z] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
```
Trss link
https://trss.adoptium.net/output/test?id=61e84e1fa7df1a2924029952

**Comment by Haroon-Khel** [comment]
Also fails with this error
```
[2022-01-19T15:44:08.046Z] java.net.NoRouteToHostException: A route to the remote host is not available. (Host unreachable)
[2022-01-19T15:44:08.046Z] 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[2022-01-19T15:44:08.046Z] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[2022-01-19T15:44:08.046Z] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[2022-01-19T15:44:08.046Z] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[2022-01-19T15:44:08.046Z] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
```

**Comment by Haroon-Khel** [comment]
Rerunning on build-1 https://ci.adoptopenjdk.net/job/Grinder/3275/console

**Comment by Haroon-Khel** [comment]
Passes on build-osuosl-1 https://ci.adoptopenjdk.net/job/Grinder/3275/console. Possible infra issue. Rerunning again on test-osuosl-72-1 to confirm https://ci.adoptopenjdk.net/job/Grinder/3278/console

**Comment by Haroon-Khel** [comment]
Transferred over to infrastructure repo https://github.com/adoptium/infrastructure/issues/2456
