### ISSUE TITLE
jdk_jfr_2 fail on jdk8 arm32 linux

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3301]
Initial failure link
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_2/27/testReport/

Trss link
https://trss.adoptium.net/output/test?id=61f04ecaa7df1a292406cf24

Grinder Rerun on test-sxa-armv7l-ubuntu2004-odroid-2
https://ci.adoptopenjdk.net/job/Grinder/3328/testReport/

Though the rerun was aborted, all of the jdk_jfr_2 tests ran.

The following test failures are from the grinder rerun:

**Failures**
jdk/jfr/event/compiler/TestCompilerPhase.java.TestCompilerPhase
jdk/jfr/event/gc/collection/TestGCCauseWithG1ConcurrentMark.java.TestGCCauseWithG1ConcurrentMark
jdk/jfr/event/gc/collection/TestGCCauseWithG1FullCollection.java.TestGCCauseWithG1FullCollection jdk/jfr/event/gc/detailed/TestEvacuationFailedEvent.java.TestEvacuationFailedEvent
jdk/jfr/event/gc/detailed/TestEvacuationInfoEvent.java.TestEvacuationInfoEvent
jdk/jfr/event/gc/detailed/TestG1HeapRegionTypeChangeEvent.java.TestG1HeapRegionTypeChangeEvent
jdk/jfr/event/gc/detailed/TestG1MMUEvent.java.TestG1MMUEvent
jdk/jfr/event/gc/detailed/TestPromotionEventWithG1.java.TestPromotionEventWithG1
jdk/jfr/event/gc/heapsummary/TestHeapSummaryEventG1.java.TestHeapSummaryEventG1
jdk/jfr/event/gc/objectcount/TestObjectCountAfterGCEventWithG1ConcurrentMark.java.TestObjectCountAfterGCEventWithG1ConcurrentMark
jdk/jfr/event/gc/stacktrace/TestG1HumongousAllocationPendingStackTrace.java.TestG1HumongousAllocationPendingStackTrace
jdk/jfr/event/gc/stacktrace/TestG1OldAllocationPendingStackTrace.java.TestG1OldAllocationPendingStackTrace
jdk/jfr/event/gc/stacktrace/TestG1YoungAllocationPendingStackTrace.java.TestG1YoungAllocationPendingStackTrace
jdk/jfr/event/gc/stacktrace/TestMetaspaceG1GCAllocationPendingStackTrace.java.TestMetaspaceG1GCAllocationPendingStackTrace
jdk/jfr/event/oldobject/TestObjectDescription.java.TestObjectDescription
jdk/jfr/event/os/TestCPUInformation.java.TestCPUInformation
jdk/jfr/event/runtime/TestShutdownEvent.java.TestShutdownEvent
jdk/jfr/event/runtime/TestSizeTFlags.java.TestSizeTFlags

**Intermittent**
jdk/jfr/event/gc/stacktrace/TestParallelMarkSweepAllocationPendingStackTrace.java.TestParallelMarkSweepAllocationPendingStackTrace (failed 2/5)
jdk/jfr/jvm/TestLargeJavaEvent512k.java.TestLargeJavaEvent512k (failed 2/5)

**Comment by Haroon-Khel** [comment]
`jdk/jfr/event/compiler/TestCompilerPhase.java.TestCompilerPhase`
`jdk/jfr/event/gc/collection/TestGCCauseWithG1ConcurrentMark.java.TestGCCauseWithG1ConcurrentMark`
`jdk/jfr/event/gc/collection/TestGCCauseWithG1FullCollection.java.TestGCCauseWithG1FullCollection`
Related upstream issue https://bugs.openjdk.java.net/browse/JDK-8230707

`jdk/jfr/event/gc/detailed/TestEvacuationFailedEvent.java.TestEvacuationFailedEvent`
Known upstream issue https://bugs.openjdk.java.net/browse/JDK-8270443


`jdk/jfr/event/gc/detailed/TestEvacuationInfoEvent.java.TestEvacuationInfoEvent`
`jdk/jfr/event/gc/detailed/TestG1HeapRegionTypeChangeEvent.java.TestG1HeapRegionTypeChangeEvent`
`jdk/jfr/event/gc/detailed/TestG1MMUEvent.java.TestG1MMUEvent`
Error log:
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.RuntimeException: No events found: expected false, was true
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
```

`jdk/jfr/event/gc/detailed/TestPromotionEventWithG1.java.TestPromotionEventWithG1`
Error log:
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.RuntimeException: Test failed since the MXBean for the Young Collector could not be found.: expected null to not equal null
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertNotEquals(Asserts.java:394)
```

`jdk/jfr/event/gc/heapsummary/TestHeapSummaryEventG1.java.TestHeapSummaryEventG1`
Error log:
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.RuntimeException: Wrong collector types: got('DefNew','SerialOld'), expected('G1New','G1Old')
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
```

`jdk/jfr/event/gc/objectcount/TestObjectCountAfterGCEventWithG1ConcurrentMark.java.TestObjectCountAfterGCEventWithG1ConcurrentMark`
Error log:
```
Execution failed: `main' threw exception: java.lang.RuntimeException: No event System.gc event of type jdk.GarbageCollection: expected true, was false    
```

`jdk/jfr/event/gc/stacktrace/TestG1HumongousAllocationPendingStackTrace.java.TestG1HumongousAllocationPendingStackTrace`
`jdk/jfr/event/gc/stacktrace/TestG1OldAllocationPendingStackTrace.java.TestG1OldAllocationPendingStackTrace`
`jdk/jfr/event/gc/stacktrace/TestG1YoungAllocationPendingStackTrace.java.TestG1YoungAllocationPendingStackTrace`
`jdk/jfr/event/gc/stacktrace/TestMetaspaceG1GCAllocationPendingStackTrace.java.TestMetaspaceG1GCAllocationPendingStackTrace`
Error log:
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.IllegalArgumentException: javax.management.InstanceNotFoundException: java.lang:type=GarbageCollector,name=G1 Young Generation
	at java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:630)
```

`jdk/jfr/event/oldobject/TestObjectDescription.java.TestObjectDescription`
`jdk/jfr/event/runtime/TestShutdownEvent.java.TestShutdownEvent`
Error log:
```
Program `/ssd/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960718ms).
```

`jdk/jfr/event/os/TestCPUInformation.java.TestCPUInformation`
Error log:
```
java.lang.RuntimeException: Value not in (Intel, AMD, Unknown x86, SPARC, ARM, PPC, PowerPC, AArch64, s390), field='description', value='0x41:0x2:0xc0f:3'
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.jfr.EventField.lambda$containsAny$10(EventField.java:133)
```

jdk/jfr/event/runtime/TestSizeTFlags.java.TestSizeTFlags
Error log:
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.RuntimeException: Flag not found or value error!: expected true, was false
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
```

**Comment by sxa** [comment]
@Haroon-Khel Can you confirm whether these also fail against the last GA release?

**Comment by Haroon-Khel** [comment]
Running https://ci.adoptopenjdk.net/job/Grinder/3371/console

**Comment by sxa** [comment]
@smlambert These seem to be failing in the above re-run too (Still going so not conclusive that it's the same failure) On the basis that it's not a regression I suspect we should not consider this a stop-ship and possibly get the failures investigated post-release the failures later.

**Comment by sxa** [comment]
@smlambert On the basis of your comment in https://github.com/adoptium/aqa-tests/issues/3297#issuecomment-1026048211 would you agree that the same applies here and since it's not a regression we should not block this release?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/3301#issuecomment-1026782500 - agree, non-blocking for the release, but want to have a post-release sweep of these remaining failures to properly raise issues in the repos where the (hopefully soon to be determined) core problem needs to be fixed.

**Comment by Haroon-Khel** [comment]
Rerunning with https://github.com/adoptium/aarch32-jdk8u as the `JDK_REPO` https://ci.adoptopenjdk.net/job/Grinder/3398/console

**Comment by Haroon-Khel** [comment]
The same tests failed. The tests
```
jdk/jfr/event/gc/stacktrace/TestG1HumongousAllocationPendingStackTrace.java.TestG1HumongousAllocationPendingStackTrace
jdk/jfr/event/gc/stacktrace/TestG1OldAllocationPendingStackTrace.java.TestG1OldAllocationPendingStackTrace
jdk/jfr/event/gc/stacktrace/TestG1YoungAllocationPendingStackTrace.java.TestG1YoungAllocationPendingStackTrace
jdk/jfr/event/gc/stacktrace/TestMetaspaceG1GCAllocationPendingStackTrace.java.TestMetaspaceG1GCAllocationPendingStackTrace
```
still failed because they could not find G1GC
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.IllegalArgumentException: javax.management.InstanceNotFoundException: java.lang:type=GarbageCollector,name=G1 Young Generation
	at java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:630)
```
Much like https://github.com/adoptium/aqa-tests/issues/3297#issuecomment-1026962321, I wouldn't expect these tests to hit this error when supplied with https://github.com/adoptium/aarch32-jdk8u as the `JDK_REPO`

**Comment by sophia-guo** [comment]
Some are infra issue https://github.com/adoptium/infrastructure/issues/2684

**Comment by smlambert** [comment]
Still hitting many issues as part of the July 2023 runs (resulting in crashes, see https://github.com/adoptium/aqa-tests/issues/4679#issuecomment-1651848102).  We should do another sweep of excludes and chase this upstream for jfr investigation and fixes if it is not specific to infrastructure limitations.

**Comment by roberttoyonaga** [comment]
Please see my comment here (https://github.com/adoptium/aqa-tests/issues/3115#issuecomment-2256561374) that explains why many of the issues are happening.
