### ISSUE TITLE
java/net/httpclient/SpecialHeadersTest.java failure JDK-11.0.14.1+1 Possible regression

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3329]
The test java/net/httpclient/SpecialHeadersTest.java, from the extended openjdk suite, fails in the JDK-11.0.14.1+1 re spin on MacOS and both x64 and x32 windows

```
[2022-02-08T19:23:04.485Z] --- Starting 
[2022-02-08T19:23:04.485Z] Http2TestContext::handle Http2TestExchangeImpl: Http2TestExchangeImpl@100dac2
[2022-02-08T19:23:04.485Z] Http1UriStringHandler received, uri: https://localhost:60724/https2?name=HOST
[2022-02-08T19:23:04.485Z] Got response: (GET https://localhost:60724/https2?name=HOST) 200
[2022-02-08T19:23:04.485Z] Got body: https://localhost:60724/https2?name=HOST
[2022-02-08T19:23:04.485Z] test SpecialHeadersTest.test("https://localhost:60724/https2", "Host: <DEFAULT>", true): failure
[2022-02-08T19:23:04.485Z] java.util.NoSuchElementException: No value present
[2022-02-08T19:23:04.485Z] 	at java.base/java.util.Optional.get(Optional.java:148)
[2022-02-08T19:23:04.485Z] 	at SpecialHeadersTest.test(SpecialHeadersTest.java:187)
[2022-02-08T19:23:04.485Z] 	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[2022-02-08T19:23:04.485Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-02-08T19:23:04.485Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

MacOS
Failure link https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_0/31/testReport/
TRSS link https://trss.adoptium.net/output/test?id=6203137ba7df1a29241fffe6
Grinder rerun https://ci.adoptopenjdk.net/job/Grinder/3551/console

Windows x64
Failure link https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_windows_testList_1/32/testReport/
TRSS link https://trss.adoptium.net/output/test?id=620309bca7df1a29241fde24
Grinder rerun https://ci.adoptopenjdk.net/job/Grinder/3550/console

Windows x32
Failure link https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-32_windows_testList_1/32/testReport/
TRSS link https://trss.adoptium.net/output/test?id=6202d16ca7df1a29241f9059
Grinder rerun https://ci.adoptopenjdk.net/job/Grinder/3552/console

**Comment by sophia-guo** [comment]
Rerun with aqa-tests master
Macos passed : https://ci.adoptopenjdk.net/job/Grinder/3553/console
Windows64: https://ci.adoptopenjdk.net/job/Grinder/3554/console
Windows32: https://ci.adoptopenjdk.net/job/Grinder/3556/console

**Comment by sophia-guo** [comment]
The failure is for aqa-tests release branch has not updated to cherry pick the patch for release [jdk-11.0.14.1-ga](https://github.com/openjdk/jdk11u/releases/tag/jdk-11.0.14.1-ga), close this.

@ShelleyLambert mentioned we will decide what to cherry pick and update the aqa-tests release branch.

**Comment by sxa** [comment]
Please let's not close issues until we have verified that we have a solution that definitely fixes the problem.
