### ISSUE TITLE
running test build with CLOUD_PROVIDER got `Scripts not permitted to use method jenkins.model.Jenkins getNode java.lang.String. Administrators can decide whether to approve or reject this signature`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3336]
running test build with CLOUD_PROVIDER got `Scripts not permitted to use method jenkins.model.Jenkins getNode java.lang.String. Administrators can decide whether to approve or reject this signature`

```
Found a total of 7 nodes with the 'ci.role.test&&hw.arch.x86&&sw.os.linux' label
Scripts not permitted to use method jenkins.model.Jenkins getNode java.lang.String. Administrators can decide whether to approve or reject this signature.
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method jenkins.model.Jenkins getNode java.lang.String
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectMethod(StaticWhitelist.java:265)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)

```
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/399/console

Suppose need administrator @ShelleyLambert to approve the scripts https://github.com/adoptium/aqa-tests/pull/3304

**Comment by jiekang** [comment]
@smlambert

**Comment by sxa** [comment]
I've approved the use of `getNode` :-) If any more things are holding it up, feel free to open and post in #infrastructure in slack to get our attention on it.
