### ISSUE TITLE
Test jobs got error message `Cannot run program "/Users/jenkins/.../j2sdk-image/Contents/Home/jre/bin/java -version": error=2, No such file or directory`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3359]
All test jobs got following error message. Though it doesn't affect job status.
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_x86-64_mac/593/console
```
13:43:00  java.io.IOException: Cannot run program "/Users/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/jre/bin/java -version": error=2, No such file or directory
13:43:00  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
13:43:00  	at org.openj9.envInfo.CmdExecutor.execute(CmdExecutor.java:40)
13:43:00  	at org.openj9.envInfo.JavaInfo.getJavaVersion(JavaInfo.java:171)
13:43:00  	at org.openj9.envInfo.EnvDetector.getJavaInfo(EnvDetector.java:53)
13:43:00  	at org.openj9.envInfo.EnvDetector.parseArgs(EnvDetector.java:32)
13:43:00  	at org.openj9.envInfo.EnvDetector.main(EnvDetector.java:27)
13:43:00  Caused by: java.io.IOException: error=2, No such file or directory
13:43:00  	at java.lang.UNIXProcess.forkAndExec(Native Method)
13:43:00  	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
13:43:00  	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
13:43:00  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
13:43:00  	... 5 more
13:43:00  Cannot determine System.getProperty('java.version')=Command could not be executed
```

**Comment by llxia** [comment]
dup of https://github.com/adoptium/TKG/issues/277
