### ISSUE TITLE
openliberty_microprofile_tck failed with jdk17

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3381]
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/442/console

openliberty_microprofile_tck_0 failed with jdk17. 

```
20:00:41  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
20:00:57  java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
20:00:57  	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
20:00:57  	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
20:00:57  	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
20:00:57  	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
20:00:57  	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
20:00:57  	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
...
20:00:57  FAILURE: Build failed with an exception.
20:00:57  
20:00:57  * What went wrong:
20:00:57  Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
20:00:57  
20:00:57  * Try:
20:00:57  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
20:00:57  
20:00:57  * Get more help at https://help.gradle.org/
20:00:57  
20:00:57  BUILD FAILED in 14s
20:00:57  
20:00:57  openliberty_microprofile_tck_0_FAILED
```

**Comment by sophia-guo** [comment]
Need to rerun if https://github.com/adoptium/aqa-tests/issues/3380#issuecomment-1063177929 is done.

**Comment by sophia-guo** [comment]
rerun with latest tag:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/560/

**Comment by sophia-guo** [comment]
Latest error:

```
15:18:30  APPLICATION_TAG=gm-22.0.0.2
15:18:30  OS_TAG=ubuntu
15:18:30  Using default openjdk image Java
15:18:30  JAVA_BIN is: /opt/java/openjdk/bin
15:18:30  =JAVA VERSION OUTPUT BEGIN=
15:18:30  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
15:18:30  openjdk version "17.0.3-beta" 2022-04-19
15:18:30  OpenJDK Runtime Environment Temurin-17.0.3+5-202203242328 (build 17.0.3-beta+5-202203242328)
15:18:30  OpenJDK 64-Bit Server VM Temurin-17.0.3+5-202203242328 (build 17.0.3-beta+5-202203242328, mixed mode, sharing)
15:18:30  =JAVA VERSION OUTPUT END=
15:18:30  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
15:18:49  
15:18:49  FAILURE: Build failed with an exception.
15:18:49  
15:18:49  * What went wrong:
15:18:49  Could not open cp_settings generic class cache for settings file '/open-liberty/dev/settings.gradle' (/root/.gradle/caches/6.8.3/scripts/1pr0g9z0vcvm8cbp2kf00lsw0).
15:18:49  > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61
15:18:49  
15:18:49  * Try:
15:18:49  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
15:18:49  
15:18:49  * Get more help at https://help.gradle.org/
15:18:49  
15:18:49  BUILD FAILED in 17s
15:18:49  
15:18:49  openliberty_microprofile_tck_0_FAILED
15:
```

**Comment by sophia-guo** [comment]
looks like the [compatibility issue](https://docs.gradle.org/current/userguide/compatibility.html). First gradle version supports jdk17 is 7.3

https://stackoverflow.com/questions/69425829/unsupported-class-file-major-version-61-error

**Comment by sophia-guo** [comment]
auto exclude test openliberty_microprofile_tck ver=17+

**Comment by smlambert** [comment]
auto exclude test openliberty_microprofile_tck ver=17

**Comment by sophia-guo** [comment]
Thanks @ShelleyLambert ! Just to confirm that ver=17+ doesn't work? `auto exclude test openliberty_microprofile_tck ver=17+`

**Comment by sophia-guo** [comment]
Close it.

**Comment by smlambert** [comment]
@sophia-guo - I see your comment at https://github.com/adoptium/aqa-tests/issues/3381#issuecomment-1082050983, perhaps we create an enhancement issue to support it (its not listed as supported in the docs https://github.com/adoptium/aqa-tests/blob/master/doc/userGuide.md#automatically-exclude-a-test-target).

**Comment by sophia-guo** [comment]
Also no error message.:-)

**Comment by smlambert** [comment]
Yep, because if we do close it, it will be a signal to the new Auto-reenable pipeline to reinclude and test it.  If there is a better upstream issue (at the openliberty project that describes this failure, we would use it to exclude the test by, instead of placeholder issues in aqa-tests repo).
