### ISSUE TITLE
external test quarkus_test failed with jdk17 (passed with jdk11)

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3392]
external test quarkus_test failed with jdk17 (passed with jdk11)
jdk11: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/457/
jdk17: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/451/console

```
18:06:45  2022-02-28 23:06:44,238 INFO  [io.quarkus] (main) Quarkus stopped in 0.017s
18:06:45  [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 5.559 s <<< FAILURE! - in io.quarkus.vertx.http.hotreload.HotReloadWithFilterTest
18:06:45  [ERROR] testFilterChange  Time elapsed: 3.545 s  <<< FAILURE!
18:06:45  java.lang.AssertionError: 
18:06:45  1 expectation failed.
18:06:45  Expected status code <200> but was <500>.
18:06:45  
18:06:45  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
18:06:45  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
18:06:45  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
18:06:45  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
18:06:45  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
18:06:45  	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
...
18:07:35  [INFO] Quarkus - Security - Deployment .................... SUCCESS [  8.817 s]
18:07:35  [INFO] Quarkus - Vert.x - HTTP - Deployment ............... FAILURE [01:11 min]
```

**Comment by sophia-guo** [comment]
We currently are not using the latest stable build which appears to be https://github.com/quarkusio/quarkus/releases/tag/2.7.2.Final. We likely should switch to using it by updating tag_version="2.7.2.Final" to the [quarkus/test.properties](https://github.com/adoptium/aqa-tests/blob/master/external/quarkus/test.properties#L5) file.

We may still see the issue being reported, but at least we are pulling a stable build (otherwise we are just pulling from old versions).

**Comment by yinggzz** [comment]
I can take this issue

**Comment by yinggzz** [comment]
external test quarks_test with jdk 17 after updating tag https://ci.adoptopenjdk.net/job/Grinder/3800/

**Comment by sophia-guo** [comment]
With the updated latest release version the new failure is:
https://ci.adoptopenjdk.net/job/Grinder/3800/console
11:55:42  [INFO] Quarkus - OpenTelemetry - Deployment ............... FAILURE [01:00 min]

```
11:55:10  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
11:55:10  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
11:55:10  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
11:55:10  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
11:55:10  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
11:55:10  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
11:55:10  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
11:55:10  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
11:55:10  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
11:55:10  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
...
```

**Comment by sophia-guo** [comment]
Recent run got same failure as #https://github.com/adoptium/aqa-tests/issues/3382, close this one.
