### ISSUE TITLE
external tomcat_test failed with both jdk11 and jdk17

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3398]
external tomcat_test failed with both jdk11 and jdk17 and believe failed with jdk8.
8: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/470/
11: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/459/
17: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/469/

```
01:30:24      [junit] 03-Mar-2022 06:30:24.258 INFO [main] org.apache.catalina.startup.LoggingBaseTest.setUp Starting test case [testOptions[201]]
01:30:24      [junit] 03-Mar-2022 06:30:24.259 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[org.apache.coyote.http11.Http11AprProtocol-auto-202]]
01:30:24      [junit] 	org.apache.catalina.LifecycleException: The configured protocol [org.apache.coyote.http11.Http11AprProtocol] requires the APR/native library which is not available
01:30:24      [junit] 		at org.apache.catalina.connector.Connector.initInternal(Connector.java:1036)
01:30:24      [junit] 		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
0
...
01:30:30      [junit] 03-Mar-2022 06:30:29.759 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Tomcat]
01:30:30      [junit] 03-Mar-2022 06:30:29.759 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.7]
01:30:30      [junit] 03-Mar-2022 06:30:29.764 INFO [main] org.apache.catalina.startup.ContextConfig.getDefaultWebXmlFragment No global web.xml found
Cancelling nested steps due to timeout
09:50:25  Sending interrupt signal to process
09:50:37  Terminated
09:50:37  
09:50:37  tomcat_test_0_FAILED
```

Looks like setting issue.

**Comment by sophia-guo** [comment]
Couple notes:

1. https://github.com/apache/tomcat supports four different version Tomcat 8, 9, 10.0, 10.1
2. Originally tests was added for Tomcat 8 with version 8.5
3. Recently tests changed with tag_version="10.0.7" so it changes to test Tomcat 10.0 instead of 8. ,Latest Tomcat 10.0 version is [10.0.17](https://github.com/apache/tomcat/releases/tag/10.0.17)
4. The failure shows it has the dependency of APR/native. So it might be setting up issue. Looking at [travis setup](https://github.com/apache/tomcat/blob/10.0.17/.travis.yml) there are extra steps need to setup the environment. Or
5. Try to run specific jobs as setting in the [workflow file](https://github.com/apache/tomcat/blob/main/.github/workflows/ci.yml#L45-L50)

**Comment by sophia-guo** [comment]
@yinggzz see if you could help with couple issues mentioned in https://github.com/adoptium/aqa-tests/issues/3398#issuecomment-1058325633

**Comment by smlambert** [comment]
More notes to clarify steps 4 and 5 in https://github.com/adoptium/aqa-tests/issues/3449#issuecomment-1069844385:
4. Comparing https://github.com/apache/tomcat/blob/10.0.17/.travis.yml#L28-L38 with what is installed in the container https://github.com/adoptium/aqa-tests/blob/master/external/tomcat/test.properties#L6 (confirming by looking at the generated Dockerfile that is now attached to the test job).
5. The tomcat project is running https://github.com/apache/tomcat/blob/main/.github/workflows/ci.yml#L47 with ANT_OPTS set as https://github.com/apache/tomcat/blob/main/.github/workflows/ci.yml#L49, where as we are currently running this https://github.com/adoptium/aqa-tests/blob/master/external/tomcat/dockerfile/tomcat-test.sh#L26

**Comment by yinggzz** [comment]
I would like to work on this

**Comment by yinggzz** [comment]
Since original grinder test results expired, rerun to look at the dockerfile generated; 
jkd8: https://ci.adoptopenjdk.net/job/Grinder/3860/  
jkd11: https://ci.adoptopenjdk.net/job/Grinder/3861/

**Comment by yinggzz** [comment]
**step 4:** 
looking at dockerfile in jdk8 tomcat test [link]( https://ci.adoptopenjdk.net/job/Grinder/3880/)
the below are installed: 
```
RUN apt-get update \
	&& apt-get install -y --no-install-recommends git wget tar make gcc linux-libc-dev libc6-dev perl \
	&& rm -rf /var/lib/apt/lists/*
```
compared to travis.yml
<img width="304" alt="packages" src="https://user-images.githubusercontent.com/74112748/159599639-199e9746-6ed9-46cb-8268-9f5fc49bde46.png">

**step 5:** 
tomcat run on jdk11 after adding ant_opts as shown in workflow file: 
https://ci.adoptopenjdk.net/job/Grinder/3881/ 

old failure still persists:
```
20:09:27      [junit] 	org.apache.catalina.LifecycleException: The configured protocol [org.apache.coyote.http11.Http11AprProtocol] requires the APR/native library which is not available
...
20:09:42  FAILED test targets:
20:09:42  	tomcat_test_0
```

**Comment by yinggzz** [comment]
tomcat run on jdk 11 after adding "install" section of [travis setup](https://github.com/apache/tomcat/blob/10.0.17/.travis.yml) in tomcat/test.sh: https://ci.adoptopenjdk.net/job/Grinder/4149/console
same error: 
```
13:25:56      [junit] 28-Mar-2022 17:25:56.325 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[org.apache.coyote.http11.Http11AprProtocol-auto-1]]
13:25:56      [junit] 	org.apache.catalina.LifecycleException: The configured protocol [org.apache.coyote.http11.Http11AprProtocol] requires the APR/native library which is not available
```

**Comment by sophia-guo** [comment]
@yinggzz For step 4 if there are different packages installed for travis job we'd like to install them in our environments. That is installing the packages build-essential, automake, autoconf, libssl-dev, subversion, libtool-bin, which can be done by update the test.properties.

The failure you mentioned in https://github.com/adoptium/aqa-tests/issues/3398#issuecomment-1081070334 shows  `APR/native library which is not available`. That means we need to probably either install or build `APR/native library`, something similar to 

```
git clone -q -b 1.6.x --single-branch https://github.com/apache/apr.git $HOME/tmp/apr
cd $HOME/tmp/apr
./buildconf
./configure --prefix=$HOME/tmp/apr-build
make
make install
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/tmp/apr-build/lib"
```

**Comment by yinggzz** [comment]
> @yinggzz For step 4 if there are different packages installed for travis job we'd like to install them in our environments. That is installing the packages build-essential, automake, autoconf, libssl-dev, subversion, libtool-bin, which can be done by update the test.properties.
> 
> The failure you mentioned in [#3398 (comment)](https://github.com/adoptium/aqa-tests/issues/3398#issuecomment-1081070334) shows `APR/native library which is not available`. That means we need to probably either install or build `APR/native library`, something similar to
> 
> ```
> git clone -q -b 1.6.x --single-branch https://github.com/apache/apr.git $HOME/tmp/apr
> cd $HOME/tmp/apr
> ./buildconf
> ./configure --prefix=$HOME/tmp/apr-build
> make
> make install
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/tmp/apr-build/lib"
> ```

@sophia-guo Thank you for the clarifications, for installing APR/native library, should I add it to test.sh?
