### ISSUE TITLE
external netty_test failed with both jdk11 and jdk17

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3402]
external netty_test failed with both jdk11 and jdk17
11: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/460/
17:

```
00:33:39  [[1;34mINFO[m] Running io.netty.handler.ssl.[1mOpenSslKeyMaterialManagerTest[m
00:33:39  [[1;31mERROR[m] [1;31mTests [0;1mrun: [0;1m1[m, Failures: 0, [1;31mErrors: [0;1;31m1[m, Skipped: 0, Time elapsed: 0.003 s[1;31m <<< FAILURE![m - in io.netty.handler.ssl.[1mOpenSslKeyMaterialManagerTest[m
00:33:39  [[1;31mERROR[m] testChooseClientAliasReturnsNull  Time elapsed: 0.002 s  <<< ERROR!
00:33:39  java.lang.UnsatisfiedLinkError: failed to load the required native library
00:33:39  	at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:596)
00:33:39  	at io.netty.handler.ssl.OpenSslKeyMaterialManagerTest.testChooseClientAliasReturnsNull(OpenSslKeyMaterialManagerTest.java:36)
00:33:39  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:33:39  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:33:39  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:33:39  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:33:39  	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
0
...
00:33:42  [[1;34mINFO[m] Netty/Dev-Tools .................................... [1;32mSUCCESS[m [ 11.545 s]
00:33:42  [[1;34mINFO[m] Netty .............................................. [1;32mSUCCESS[m [ 35.668 s]
00:33:42  [[1;34mINFO[m] Netty/Common ....................................... [1;32mSUCCESS[m [02:34 min]
00:33:42  [[1;34mINFO[m] Netty/Buffer ....................................... [1;32mSUCCESS[m [02:32 min]
00:33:42  [[1;34mINFO[m] Netty/Resolver ..................................... [1;32mSUCCESS[m [ 16.509 s]
00:33:42  [[1;34mINFO[m] Netty/Transport .................................... [1;32mSUCCESS[m [01:33 min]
00:33:42  [[1;34mINFO[m] Netty/Codec ........................................ [1;32mSUCCESS[m [01:17 min]
00:33:42  [[1;34mINFO[m] Netty/Codec/DNS .................................... [1;32mSUCCESS[m [ 20.725 s]
00:33:42  [[1;34mINFO[m] Netty/Codec/HAProxy ................................ [1;32mSUCCESS[m [ 18.864 s]
00:33:42  [[1;34mINFO[m] Netty/Handler ...................................... [1;31mFAILURE[m [26:22 min]
00:33:42  [[1;34mINFO[m] Netty/Codec/HTTP ................................... [1;33mSKIPPED[m
```

Looks like setting issue. `failed to load the required native library`

**Comment by sophia-guo** [comment]
[tag_version="4.1"](https://github.com/adoptium/aqa-tests/blob/master/external/netty/test.properties#L6) .  [There is no tag 4.1](https://github.com/netty/netty/tags), 4.1 is the default branch. `remotes/origin/HEAD -> origin/4.1`. 

Need to update [tag_version="4.1"](https://github.com/adoptium/aqa-tests/blob/master/external/netty/test.properties#L6) to  tag_version="netty-4.1.74.Final" and see the new result.

**Comment by yinggzz** [comment]
I can take this issue 😀

**Comment by sophia-guo** [comment]
https://github.com/adoptium/aqa-tests/pull/3461#issuecomment-1067184309 the issue should be fixed by https://github.com/adoptium/aqa-tests/pull/3479. Need to rerun to update netty_test status.

**Comment by sophia-guo** [comment]
Close this in favour of https://github.com/adoptium/aqa-tests/issues/3565
