### ISSUE TITLE
external jenkins_test failed with both jdk11 and jdk17

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3406]
external jenkins_test failed with both jdk11 and jdk17
jenkins_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/466/

```
02:07:52  [INFO] Running hudson.FilePathTest
02:09:01  [ERROR] Tests run: 16, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 64.813 s <<< FAILURE! - in hudson.FunctionsTest
02:09:01  [ERROR] printThrowable(hudson.FunctionsTest)  Time elapsed: 0.063 s  <<< FAILURE!
02:09:01  org.junit.ComparisonFailure: 
02:09:01  expected:<....method2(C.java:27)
02:09:01  [Caused by: [CIRCULAR REFERENCE: ]p.Exc1]
02:09:01  > but was:<....method2(C.java:27)
02:09:01  [	[CIRCULAR REFERENCE:]p.Exc1]
02:09:01  >
02:09:01  	at org.junit.Assert.assertEquals(Assert.java:117)
02:09:01  	at org.junit.Assert.assertEquals(Assert.java:146)
02:09:01  	at hudson.FunctionsTest.assertPrintThrowable(FunctionsTest.java:531)
02:09:01  	at hudson.FunctionsTest.printThrowable(FunctionsTest.java:516)
02:09:01  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:09:01  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:09:01  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:09:01  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:09:01  	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
02:09:01  	at 
...
...
02:10:07  [INFO] ------------------------------------------------------------------------
02:10:07  [INFO] Reactor Summary for Jenkins main module 2.235:
02:10:07  [INFO] 
02:10:07  [INFO] Jenkins main module ................................ SUCCESS [  0.528 s]
02:10:07  [INFO] Jenkins BOM ........................................ SUCCESS [  0.045 s]
02:10:07  [INFO] Jenkins cli ........................................ SUCCESS [  6.234 s]
02:10:07  [INFO] Jenkins core ....................................... FAILURE [03:45 min]
02:10:07  [INFO] Jenkins war ........................................ SKIPPED
02:10:07  [INFO] Tests for Jenkins core ............................. SKIPPED
02:10:07  [INFO] ------------------------------------------------------------------------
02:10
```

**Comment by sophia-guo** [comment]
Would like to first update jenkins version to jenkins-2.319.3 [tag_version="jenkins-2.235"](https://github.com/adoptium/aqa-tests/blob/master/external/jenkins/test.properties#L5) to see if the failure is same.

**Comment by abhijeetjejurkar** [comment]
Hey,
 can I work on this?
