### ISSUE TITLE
external wildfly failed 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3409]
external wildfly failed 
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/467/console
```
04:06:38  [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.649 s <<< FAILURE! - in org.jboss.as.test.integration.ws.wsse.trust.WSBearerElytronSecurityPropagationTestCase
04:06:38  [ERROR] testBearer(org.jboss.as.test.integration.ws.wsse.trust.WSBearerElytronSecurityPropagationTestCase)  Time elapsed: 0.318 s  <<< ERROR!
04:06:38  javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
04:06:38  	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:162)
04:06:38  	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:128)
04:06:38  	at org.jboss.wsf.stack.cxf.client.ProviderImpl$JBossWSServiceImpl.<init>(ProviderImpl.java:574)
04:06:38  	at org.jboss.wsf.stack.cxf.client.ProviderImpl.createServiceDelegate(ProviderImpl.java:258)
04:06:38  	at javax.xml.ws.Service.<init>(Service.java:82)
04:06:38  	at javax.xml.ws.Service.create(Service.java:735)
...
...
04:07:05  [INFO] WildFly Test Suite: Integration - WS ............... FAILURE [02:49 min]
```

**Comment by sophia-guo** [comment]
Would be helpful to first update to latest version https://github.com/wildfly/wildfly/releases/tag/26.0.1.Final. That is update `tag_version="19.1.0.Final"` to `tag_version="16.0.1.Final"` in https://github.com/adoptium/aqa-tests/blob/master/external/wildfly/test.properties#L5

**Comment by abhijeetjejurkar** [comment]
Hi, I am Abhijeet Jejurkar, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you!
