### ISSUE TITLE
6 renaissance targets FAILED in Test_openjdk18_hs_extended.perf_* most platforms for jdk18

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3469]
renaissance-chi-square_0,renaissance-dec-tree_0,renaissance-gauss-mix_0,renaissance-log-regression_0,renaissance-als_0,renaissance-movie-lens_0 targets fail on ppc64_aix, ppc64le_linux, aarch64_linux, x86-64_windows, x86-64_mac.  Below is information on renaissance-chi-square, but all 6 targets are consistently failing on both ci.role.perf machines with `Caused by: java.lang.StringIndexOutOfBoundsException: Range [0, 3) out of bounds for length 2`.

**Test Info**
Test Name: renaissance-chi-square_0

Test Duration: 8 sec
Machine: test-osuosl-aix72-ppc64-2
TRSS link for the test output: https://trss.adoptium.net/output/test?id=622dc1a957fa857008d28cca

**Build Info**
Build Name: Test_openjdk18_hs_extended.perf_ppc64_aix
Jenkins Build start time: Mar 12 2022, 08:06 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.perf_ppc64_aix/24/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=622dc11757fa857008d28c36

**Java Version**
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment Temurin-18+37 (build 18+37)
OpenJDK 64-Bit Server VM Temurin-18+37 (build 18+37, mixed mode)

**This test has been failed 6 times since Jan 29 2022, 09:28 pm**
**Java Version when the issue first seen**
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment Temurin-18+33 (build 18+33)
OpenJDK 64-Bit Server VM Temurin-18+33 (build 18+33, mixed mode)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.perf_ppc64_aix/19/

The test failed on machine test-osuosl-aix72-ppc64-2 4 times 
The test failed on machine test-osuosl-aix72-ppc64-1 2 times 

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=renaissance-chi-square_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk18&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;DYNAMIC_COMPILE=false&amp;TKG_SHA=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=perf&amp;UPSTREAM_JOB_NUMBER=19&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

```
[2022-03-13T02:39:35.772Z] Exception occurred in org.renaissance.apache.spark.DecTree@382d549a: null
[2022-03-13T02:39:35.772Z] java.lang.ExceptionInInitializerError
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.PartitioningUtils$.<init>(PartitioningUtils.scala:415)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.PartitioningUtils$.<clinit>(PartitioningUtils.scala)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileCatalog.inferPartitioning(PartitioningAwareFileCatalog.scala:126)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.ListingFileCatalog.partitionSpec(ListingFileCatalog.scala:60)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileCatalog.allFiles(PartitioningAwareFileCatalog.scala:74)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:395)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:392)
[2022-03-13T02:39:35.772Z] 	at scala.Option.orElse(Option.scala:289)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:391)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
[2022-03-13T02:39:35.772Z] 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:132)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.apache.spark.DecTree.prepareAndLoadInput(DecTree.scala:84)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.apache.spark.DecTree.setUpBeforeAll(DecTree.scala:116)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
[2022-03-13T02:39:35.773Z] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2022-03-13T02:39:35.773Z] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2022-03-13T02:39:35.773Z] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-03-13T02:39:35.773Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-03-13T02:39:35.773Z] 	at org.renaissance.Launcher.main(Launcher.java:18)
[2022-03-13T02:39:35.773Z] Caused by: java.lang.StringIndexOutOfBoundsException: Range [0, 3) out of bounds for length 2
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
[2022-03-13T02:39:35.773Z] 	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
[2022-03-13T02:39:35.773Z] 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
[2022-03-13T02:39:35.773Z] 	at java.base/java.lang.String.substring(String.java:2703)
[2022-03-13T02:39:35.773Z] 	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:48)
[2022-03-13T02:39:35.773Z] 	... 24 more
[2022-03-13T02:39:35.773Z] The following benchmarks failed: dec-tree
[2022-03-13T02:39:35.773Z] 
[2022-03-13T02:39:35.773Z] renaissance-dec-tree_0_FAILED
```

**Comment by smlambert** [comment]
auto exclude test renaissance-chi-square ver=18 plat=ppc64_aix

**Comment by smlambert** [comment]
Investigate renaissance dependencies, seems something not happy on ppc64/ppc64le machines.

**Comment by llxia** [comment]
Close this issue as JDK18 is out of support. If this happens with a supported JDK, we should open a new issue.

**Comment by llxia** [comment]
@Amrutha-Kanhirathingal please verify if the issue happens with the supported version.

**Comment by Amrutha-Kanhirathingal** [comment]
Hi @llxia ,
Targeted test list job triggered on jdk21 
 jhttps://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49703/console

As a result  in ppc64le_linux https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49705/parameters/
2 tests are executed and passed
```
PASSED test targets:
 renaissance-chi-square_0
renaissance-dec-tree_0
```

**Comment by llxia** [comment]
Please run all tests, not just 2. Your Grinder finished with UNSTABLE. Please take a look. 
In general, if the test passes with the supported JDK version, we can re-enable it. If it is excluded for 18+ due to this issue, please run with JDK21 and at least on both Windows and xlinux platforms.
Please check playlist for details: https://github.com/adoptium/aqa-tests/blob/master/perf/renaissance/playlist.xml

**Comment by Amrutha-Kanhirathingal** [comment]
> Hi [@llxia](https://github.com/llxia) , Targeted test list job triggered on jdk21 https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49703/console


This build includes all disabled test executed in ppc64_aix, ppc64le_linux, aarch64_linux, x86-64_windows, x86-64_mac as per playlist.xml where version is jdk21

below jobs are its child jobs based on platform

https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49704/console:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49705/console :
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49706/console :
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49707/console :
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49708/console : 

where these jobs executed just 2 test cases and result is  passed 
renaissance-chi-square_0
renaissance-dec-tree_0

we have to check why the jobs  did n't executed other targeted tests

**Comment by Amrutha-Kanhirathingal** [comment]
Hi @llxia ,

Issue tested with JDK21 on Windows and xlinux platforms.

|Testname|Platform|JDK|Result|
|---|---|---|---|
|renaissance-chi-square|x86-64_linux : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50468    <br>x86-64_windows :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50469/| jdk21 | Pass|
|renaissance-als|x86-64_linux : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50472  <br>x86-64_windows :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50473| jdk21 | Pass|
|renaissance-dec-tree|x86-64_linux : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50477<br>x86-64_windows :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50475/| jdk21 | Pass|
|renaissance-gauss-mix|x86-64_linux : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50493  <br>x86-64_windows :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50480/| jdk21 | Pass|
|renaissance-log-regression|x86-64_linux : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50482  <br>x86-64_windows :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50483/| jdk21 | Pass|
|renaissance-movie-lens|x86-64_linux : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50496  <br>x86-64_windows :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50495 <br>s390x_linux :https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50503| jdk21 | Pass|

**Comment by llxia** [comment]
Thanks @Amrutha-Kanhirathingal . Please reenable the tests.
