### ISSUE TITLE
jdk18 [x86-32_windows] : test.java.time.format.TestUnicodeExtension.test_withLocale failed on some  locale

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3494]
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_2/27/consoleFull

test.java.time.format.TestUnicodeExtension.test_withLocale failed on some locale with `java.time.format.DateTimeParseException`

```
19:50:44  test test.java.time.format.TestUnicodeExtension.test_withLocale(ja_JP, null, null, null, null, "2017?8?10???? 15?15?00? ??????????"): failure
19:50:44  java.time.format.DateTimeParseException: Text '2017?8?10???? 15?15?00? ??????????' could not be parsed at index 24
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2056)
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
19:50:44  	at test.java.time.format.TestUnicodeExtension.test_withLocale(TestUnicodeExtension.java:862)
...
19:50:44  test test.java.time.format.TestUnicodeExtension.test_withLocale(fa, null, null, null, null, "??????? 10 ??? 2017? ???? 15:15:00 (??? ???????? ??? ??????)"): failure
19:50:44  java.time.format.DateTimeParseException: Text '??????? 10 ??? 2017? ???? 15:15:00 (??? ???????? ??? ??????)' could not be parsed at index 36
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2056)
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
...
19:50:44  test test.java.time.format.TestUnicodeExtension.test_withLocale(dz, null, null, null, null, "??????????, ????????2017 ??????????? ????10 ??????? 3 ?????? 15:00 ?????? ???????????????????????????????????????"): failure
19:50:44  java.time.format.DateTimeParseException: Text '??????????, ????????2017 ??????????? ????10 ??????? 3 ?????? 15:...' could not be parsed at index 74
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2056)
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
...
19:50:44  test test.java.time.format.TestUnicodeExtension.test_withLocale(fa__#u-nu-latn, null, null, null, null, "??????? 10 ??? 2017? ???? 15:15:00 (??? ???????? ??? ??????)"): failure
19:50:44  java.time.format.DateTimeParseException: Text '??????? 10 ??? 2017? ???? 15:15:00 (??? ???????? ??? ??????)' could not be parsed at index 36
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2056)
19:50:44  	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
19:50:44  	at test.java.time.format.TestUnicodeExtension.test_withLocale(TestUnicodeExtension.java:862)

````

**Comment by sophia-guo** [comment]
same exception with different test on Mac https://github.com/adoptium/aqa-tests/issues/3498
