### ISSUE TITLE
jdk_jfr_1 tests are failing on linux s390x jdk18+36 release triage

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3497]
The following two tests are failing on linux s390x for the jdk18+36 release

`jdk/jfr/api/consumer/TestRecordedFullStackTrace.java.TestRecordedFullStackTrace`

```
java.lang.RuntimeException: Wrong stacktrace depth. Expected:64: expected 64 to equal 63
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
```

`jdk/jfr/event/profiling/TestFullStackTrace.java.TestFullStackTrace`

```
java.lang.RuntimeException: Wrong stacktrace depth. Expected:64: expected 64 to equal 63
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
```

Job link https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_0/25/
Trss https://trss.adoptium.net/output/test?id=623b35f672761a4c5cf842de
Grinder rerun failure https://ci.adoptopenjdk.net/job/Grinder/3916/console

These tests are from jdk_jfr_1 from the extended openjdk test suite

**Comment by Haroon-Khel** [comment]
Upstream bug
https://bugs.openjdk.java.net/browse/JDK-8280155

> The following tests have failed on some machines:
> jdk/jfr/api/consumer/TestRecordedFullStackTrace.java
> jdk/jfr/event/profiling/TestFullStackTrace.java
