### ISSUE TITLE
quarkus_quickstarts_test_0 failed on JDK11 s390 

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3518]
The subtest amazon-dynamodb-quickstart of quarkus_quickstarts_test_0 failed on s390. Most subtests in quarkus_quickstarts_test_0 are skipped.

amazon-dynamodb-quickstart failure happened on both openj9 and hotspot JDK11.

hotspot: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/581/
openj9: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/580/

```
00:14:09.526  2022-03-31 14:49:46,886 INFO  [doc.12.17]] (pool-5-thread-1) Container localstack/localstack:0.12.17 is starting: f9436416dcce68c4fc5d1775e72c401fe78cabafcd41ac4c1688bb1fee2a7d16
00:14:09.526  2022-03-31 14:50:47,434 ERROR [doc.12.17]] (pool-5-thread-1) Could not start container: java.lang.IllegalStateException: Container exited with code 1
00:14:09.526  	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
00:14:09.526  	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
00:14:09.526  	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
00:14:09.526  	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
00:14:09.526  	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
00:14:09.526  	at org.acme.dynamodb.DynamodbResource.start(DynamodbResource.java:37)
00:14:09.526  	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:452)
00:14:09.526  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
00:14:09.526  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:14:09.526  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:14:09.526  	at java.base/java.lang.Thread.run(Thread.java:829)
00:14:09.526  
00:14:09.526  2022-03-31 14:50:47,448 ERROR [doc.12.17]] (pool-5-thread-1) Log output from the failed container:
00:14:09.526  standard_init_linux.go:190: exec user process caused "no such file or directory"
00:14:09.526  
00:14:09.526  [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 85.992 s <<< FAILURE! - in org.acme.dynamodb.DynamodbResourcesTest
00:14:09.526  [ERROR] org.acme.dynamodb.DynamodbResourcesTest.testResource(String)[1]  Time elapsed: 0.004 s  <<< ERROR!
00:14:09.526  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
00:14:09.526  Caused by: java.lang.reflect.InvocationTargetException
00:14:09.526  Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.dynamodb.DynamodbResource@c2b7e76
00:14:09.526  Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.dynamodb.DynamodbResource@c2b7e76
00:14:09.526  Caused by: java.lang.RuntimeException: Could not start Dynamodb localstack server
00:14:09.526  Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
00:14:09.526  Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
00:14:09.526  Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
00:14:09.526  Caused by: java.lang.IllegalStateException: Container exited with code 1
00:14:09.526  
00:14:09.526  [INFO] 
00:14:09.526  [INFO] Results:
00:14:09.526  [INFO] 
00:14:09.526  [ERROR] Errors: 
00:14:09.526  [ERROR]   DynamodbResourcesTest.testResource(String)[1] » Runtime java.lang.reflect.Invo...
00:14:09.526  [INFO] 
00:14:09.526  [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1
00:14:09.526  [INFO] 
00:14:09.526  [INFO] ------------------------------------------------------------------------
00:14:09.526  [INFO] Reactor Summary:
00:14:09.526  [INFO] 
00:14:09.526  [INFO] amazon-dynamodb-quickstart 1.0.0-SNAPSHOT .......... FAILURE [01:35 min]
00:14:09.526  [INFO] amazon-kms-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.526  [INFO] amazon-s3-quickstart 1.0.0-SNAPSHOT ................ SKIPPED
00:14:09.526  [INFO] amazon-ses-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.526  [INFO] amazon-sns-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.526  [INFO] amazon-sqs-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.526  [INFO] amazon-ssm-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.526  [INFO] amqp-quickstart-producer 1.0.0-SNAPSHOT ............ SKIPPED
00:14:09.526  [INFO] amqp-quickstart-processor 1.0.0-SNAPSHOT ........... SKIPPED
00:14:09.526  [INFO] amqp-quickstart 1.0.0-SNAPSHOT ..................... SKIPPED
00:14:09.526  [INFO] awt-graphics-rest-quickstart 1.0.0-SNAPSHOT ........ SKIPPED
00:14:09.526  [INFO] cache-quickstart 1.0.0-SNAPSHOT .................... SKIPPED
00:14:09.526  [INFO] config-quickstart 1.0.0-SNAPSHOT ................... SKIPPED
00:14:09.526  [INFO] context-propagation-quickstart 1.0.0-SNAPSHOT ...... SKIPPED
00:14:09.526  [INFO] funqy-http-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.526  [INFO] funqy-amazon-lambda-quickstart 1.0.0-SNAPSHOT ...... SKIPPED
00:14:09.526  [INFO] funqy-amazon-lambda-http-quickstart 1.0.0-SNAPSHOT . SKIPPED
00:14:09.526  [INFO] funqy-knative-events-quickstart 1.0.0-SNAPSHOT ..... SKIPPED
00:14:09.526  [INFO] funqy-google-cloud-functions-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.526  [INFO] funqy-google-cloud-functions-http-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.527  [INFO] funqy-quickstart-projects 1.0.0-SNAPSHOT ........... SKIPPED
00:14:09.527  [INFO] getting-started 1.0.0-SNAPSHOT ..................... SKIPPED
00:14:09.527  [INFO] getting-started-async 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.527  [INFO] getting-started-reactive 1.0.0-SNAPSHOT ............ SKIPPED
00:14:09.527  [INFO] getting-started-reactive-rest 1.0.0-SNAPSHOT ....... SKIPPED
00:14:09.527  [INFO] getting-started-knative 1.0.0-SNAPSHOT ............. SKIPPED
00:14:09.527  [INFO] getting-started-testing 1.0.0-SNAPSHOT ............. SKIPPED
00:14:09.527  [INFO] getting-started-command-mode 1.0.0-SNAPSHOT ........ SKIPPED
00:14:09.527  [INFO] google-cloud-functions-quickstart 1.0.0-SNAPSHOT ... SKIPPED
00:14:09.527  [INFO] google-cloud-functions-http-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.527  [INFO] hibernate-reactive-quickstart 1.0.0-SNAPSHOT ....... SKIPPED
00:14:09.527  [INFO] hibernate-reactive-routes-quickstart 1.0.0-SNAPSHOT  SKIPPED
00:14:09.527  [INFO] grpc-plain-text-quickstart 1.0.0-SNAPSHOT .......... SKIPPED
00:14:09.527  [INFO] grpc-tls-quickstart 1.0.0-SNAPSHOT ................. SKIPPED
00:14:09.527  [INFO] hibernate-reactive-panache-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.527  [INFO] infinispan-client-quickstart 1.0.0-SNAPSHOT ........ SKIPPED
00:14:09.527  [INFO] jms-quickstart 1.0.0-SNAPSHOT ...................... SKIPPED
00:14:09.527  [INFO] kafka-quickstart-producer 1.0.0-SNAPSHOT ........... SKIPPED
00:14:09.527  [INFO] kafka-quickstart-processor 1.0.0-SNAPSHOT .......... SKIPPED
00:14:09.527  [INFO] kafka-avro-schema-quickstart 1.0.0-SNAPSHOT ........ SKIPPED
00:14:09.527  [INFO] kafka-bare-quickstart 1.0-SNAPSHOT ................. SKIPPED
00:14:09.527  [INFO] kafka-streams-quickstart 1.0.0-SNAPSHOT ............ SKIPPED
00:14:09.527  [INFO] kafka-streams-quickstart-producer 1.0.0-SNAPSHOT ... SKIPPED
00:14:09.527  [INFO] kafka-streams-quickstart-aggregator 1.0.0-SNAPSHOT . SKIPPED
00:14:09.527  [INFO] kogito-quickstart 1.0.0-SNAPSHOT ................... SKIPPED
00:14:09.527  [INFO] kogito-drl-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.527  [INFO] kogito-dmn-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.527  [INFO] kogito-pmml-quickstart 1.0.0-SNAPSHOT .............. SKIPPED
00:14:09.527  [INFO] optaplanner-quickstart 1.0.0-SNAPSHOT .............. SKIPPED
00:14:09.527  [INFO] lifecycle-quickstart 1.0.0-SNAPSHOT ................ SKIPPED
00:14:09.527  [INFO] micrometer-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.527  [INFO] microprofile-fault-tolerance-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.527  [INFO] microprofile-graphql-quickstart 1.0.0-SNAPSHOT ..... SKIPPED
00:14:09.527  [INFO] microprofile-graphql-client-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.527  [INFO] microprofile-health-quickstart 1.0.0-SNAPSHOT ...... SKIPPED
00:14:09.527  [INFO] microprofile-metrics-quickstart 1.0.0-SNAPSHOT ..... SKIPPED
00:14:09.527  [INFO] mongodb-quickstart 1.0.0-SNAPSHOT .................. SKIPPED
00:14:09.527  [INFO] mongodb-panache-quickstart 1.0.0-SNAPSHOT .......... SKIPPED
00:14:09.527  [INFO] openapi-swaggerui-quickstart 1.0.0-SNAPSHOT ........ SKIPPED
00:14:09.527  [INFO] opentracing-quickstart 1.0.0-SNAPSHOT .............. SKIPPED
00:14:09.527  [INFO] opentelemetry-quickstart 1.0.0-SNAPSHOT ............ SKIPPED
00:14:09.527  [INFO] qute-quickstart 1.0.0-SNAPSHOT ..................... SKIPPED
00:14:09.527  [INFO] rabbitmq-quickstart-producer 1.0.0-SNAPSHOT ........ SKIPPED
00:14:09.527  [INFO] rabbitmq-quickstart 1.0.0-SNAPSHOT ................. SKIPPED
00:14:09.527  [INFO] rest-client-reactive-quickstart 1.0.0-SNAPSHOT ..... SKIPPED
00:14:09.527  [INFO] reactive-routes-quickstart 1.0.0-SNAPSHOT .......... SKIPPED
00:14:09.527  [INFO] quickstart-projects 1.0.0-SNAPSHOT ................. SKIPPED
00:14:09.527  [INFO] reactive-messaging-http-quickstart 1.0.0-SNAPSHOT .. SKIPPED
00:14:09.527  [INFO] reactive-messaging-websockets-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.527  [INFO] rest-json-quickstart 1.0.0-SNAPSHOT ................ SKIPPED
00:14:09.527  [INFO] scheduler-quickstart 1.0.0-SNAPSHOT ................ SKIPPED
00:14:09.527  [INFO] security-jpa-quickstart 1.0.0-SNAPSHOT ............. SKIPPED
00:14:09.527  [INFO] security-jwt-quickstart 1.0.0-SNAPSHOT ............. SKIPPED
00:14:09.527  [INFO] security-oauth2-quickstart 1.0.0-SNAPSHOT .......... SKIPPED
00:14:09.527  [INFO] security-openid-connect-quickstart 1.0.0-SNAPSHOT .. SKIPPED
00:14:09.527  [INFO] software-transactional-memory-quickstart 1.0.0-SNAPSHOT SKIPPED
00:14:09.527  [INFO] spring-di-quickstart 1.0.0-SNAPSHOT ................ SKIPPED
00:14:09.527  [INFO] spring-web-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.527  [INFO] spring-security-quickstart 1.0.0-SNAPSHOT .......... SKIPPED
00:14:09.527  [INFO] spring-scheduled-quickstart 1.0.0-SNAPSHOT ......... SKIPPED
00:14:09.527  [INFO] spring-boot-properties-quickstart 1.0.0-SNAPSHOT ... SKIPPED
00:14:09.527  [INFO] spring-data-rest-quickstart 1.0.0-SNAPSHOT ......... SKIPPED
00:14:09.527  [INFO] stork-quickstart 1.0.0-SNAPSHOT .................... SKIPPED
00:14:09.527  [INFO] tests-with-coverage-quickstart 1.0.0-SNAPSHOT ...... SKIPPED
00:14:09.527  [INFO] tika-quickstart 1.0.0-SNAPSHOT ..................... SKIPPED
00:14:09.527  [INFO] validation-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.527  [INFO] websockets-quickstart 1.0.0-SNAPSHOT ............... SKIPPED
00:14:09.527  [INFO] liquibase-quickstart 1.0.0-SNAPSHOT ................ SKIPPED
00:14:09.527  [INFO] liquibase-mongodb-quickstart 1.0.0-SNAPSHOT ........ SKIPPED
00:14:09.527  [INFO] mailer-quickstart 1.0.0-SNAPSHOT ................... SKIPPED
00:14:09.527  [INFO] kafka-panache-quickstart 1.0.0-SNAPSHOT ............ SKIPPED
00:14:09.527  [INFO] kafka-panache-reactive-quickstart 1.0.0-SNAPSHOT ... SKIPPED
00:14:09.527  [INFO] jta-quickstart 1.0-SNAPSHOT ........................ SKIPPED
00:14:09.527  [INFO] ------------------------------------------------------------------------
00:14:09.527  [INFO] BUILD FAILURE
00:14:09.527  [INFO] ------------------------------------------------------------------------
00:14:09.527  [INFO] Total time:  01:41 min
00:14:09.527  [INFO] Finished at: 2022-03-31T14:50:47Z
00:14:09.527  [INFO] ------------------------------------------------------------------------
00:14:09.527  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project amazon-dynamodb-quickstart: There are test failures.
00:14:09.527  [ERROR] 
00:14:09.527  [ERROR] Please refer to /quarkus-quickstarts/amazon-dynamodb-quickstart/target/surefire-reports for the individual test results.
00:14:09.527  [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
00:14:09.527  [ERROR] -> [Help 1]
00:14:09.527  [ERROR] 
00:14:09.527  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
00:14:09.527  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
00:14:09.527  [ERROR] 
00:14:09.527  [ERROR] For more information about the errors and possible solutions, please read the following articles:
00:14:09.527  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
00:14:09.527  Build quarkus_quickstarts completed
```

**Comment by llxia** [comment]
Internal/backlog/issues/776

**Comment by llxia** [comment]
@LongyuZhang could you exclude this test on aarch64_linux and s390_linux? Thanks
