### ISSUE TITLE
[ external - netty ] : status

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3565]
Same failure with 8, 11, 17.
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/685/console

```
11:31:16  15:31:16.265 [main] DEBUG io.netty.handler.ssl.OpenSsl - Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See https://netty.io/wiki/forked-tomcat-native.html for more information.
11:31:16  java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
11:31:16  	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
11:31:16  	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
11:31:16  	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
11:31:16  	at io.netty.handler.ssl.SslProvider.isTlsv13Supported(SslProvider.java:77)
11:31:16  	at io.netty.handler.ssl.SslProvider.isTlsv13Supported(SslProvider.java:64)
11:31:16  	at io.netty.util.internal.NettyBlockHoundIntegrationTest.testTrustManagerVerifyTLSv13OpenSSL(NettyBlockHoundIntegrationTest.java:265)
1
```

**Comment by sophia-guo** [comment]
Same issue as before. More details https://github.com/adoptium/aqa-tests/issues/3402
