### ISSUE TITLE
jdk11 jdk_compile failures on macos12

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3591]
56 compiler/aot/* tests failed on [test-macincloud-macos1201-x64-1](https://ci.adoptopenjdk.net/computer/test-macincloud-macos1201-x64-1)  only  with message:

```
15:02:26  Preparing compiled binary (0 ms)
15:02:26  Creating binary: libHelloWorld.so.o (9 ms)
15:02:26  Creating shared library: libHelloWorld.so (19 ms)
15:02:26  Exception in thread "main" java.lang.InternalError: ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
15:02:26  	at jdk.aot@11.0.15-beta/jdk.tools.jaotc.Linker.link(Linker.java:142)
15:02:26  	at jdk.aot@11.0.15-beta/jdk.tools.jaotc.Main.run(Main.java:262)
15:02:26  	at jdk.aot@11.0.15-beta/jdk.tools.jaotc.Main.run(Main.java:133)
15:02:26  	at jdk.aot@11.0.15-beta/jdk.tools.jaotc.Main.main(Main.java:89)
15:02:26  
15:02:26  Command line: [/Users/jenkins/workspace/grinder_sandbox_new/openjdkbinary/j2sdk-image/Contents/Home/bin/../bin/java -cp /Users/jenkins/workspace/grinder_sandbox_new/aqa-tests/TKG/output_1650394746878/hotspot_custom_1/work/classes/0/compiler/aot/verification/ClassAndLibraryNotMatchTest.d:/Users/jenkins/workspace/grinder_sandbox_new/aqa-tests/openjdk/openjdk-jdk/test/hotspot/jtreg/compiler/aot/verification:/Users/jenkins/workspace/grinder_sandbox_new/aqa-tests/TKG/output_1650394746878/hotspot_custom_1/work/classes/0/test/lib:/Users/jenkins/workspace/grinder_sandbox_new/aqa-tests/TKG/output_1650394746878/hotspot_custom_1/work/classes/0:/Users/jenkins/workspace/grinder_sandbox_new/jvmtest/openjdk/jtreg/lib/javatest.jar:/Users/jenkins/workspace/grinder_sandbox_new/jvmtest/openjdk/jtreg/lib/jtreg.jar:/Users/jenkins/workspace/grinder_sandbox_new/jvmtest/openjdk/jtreg/lib/junit.jar:/Users/jenkins/workspace/grinder_sandbox_new/jvmtest/openjdk/jtreg/lib/testng.jar:/Users/jenkins/workspace/grinder_sandbox_new/jvmtest/openjdk/jtreg/lib/jcommander.jar -ea -esa -Xmx512m -XX:-UseCompressedOops -cp . -XX:+UnlockExperimentalVMOptions -XX:+UseAOT -XX:AOTLibrary=./libHelloWorld.so HelloWorld ]
15:02:26  STDERR:
15:02:26   stdout: [error opening file: dlopen(./libHelloWorld.so, 0x0001): tried: '/Users/jenkins/workspace/grinder_sandbox_new/openjdkbinary/j2sdk-image/Contents/Home/lib/server/././libHelloWorld.so' (no such file), '/Users/jenkins/workspace/grinder_sandbox_new/openjdkbinary/j2sdk-image/Contents/Home/lib/server/.././libHelloWorld.so' (no such file), '/Users/jenkins/workspace/grinder_sandbox_new/openjdkbinary/j2sdk-image/Contents/Home/bin/../lib/jli/./libHelloWorld.so' (no such file), './libHelloWorld.so' (no such file), '/usr/local/lib/libHelloWorld.so' (no such file), '/usr/lib/libHelloWorld.so' (no such file), '/Users/jenkins/workspace/grinder_sandbox_new/aqa-tests/TKG/output_1650394746878/hotspot_custom_1/work/scratch/1/libHelloWorld.so' (no such file), '/usr/local/lib/libHelloWorld.so' (no such file), '/usr/lib/libHelloWorld.so' (no such file)
15:02:26  ];
15:02:26   stderr: []
15:02:26   exitValue = 1
15:02:26  
15:02:26  java.lang.RuntimeException: Expected to get exit value of [0]
```

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_1/41/
https://trss.adoptium.net/deepHistory?testId=625744b172761a4c5c12015c

**Comment by sophia-guo** [comment]
Same on [test-macincloud-macos1201-x64-2](https://ci.adoptopenjdk.net/computer/test-macincloud-macos1201-x64-2)

**Comment by sophia-guo** [comment]
We would like to take those two machines offline before the issues is fixed (either update the test cases or update machine configuration?). Looks like https://ci.adoptopenjdk.net/computer/test-macincloud-macos1201-x64-1/ is offline due to some other updates. 

The interesting thing is both machines are labeled as macos10.10 https://ci.adoptopenjdk.net/label/macos10.10/, which is incorrect. Might be updated from macos10.10 to macos10.12?
