### ISSUE TITLE
jfr/event/io/TestInstrumentation.java run fail on linux-x64 by jdk8

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3605]
**Describe the bug**
jfr/event/io/TestInstrumentation.java run fail on linux-x64 by jdk8

**To Reproduce**
1. build jdk8
```bash
bash configure --prefix=$PWD
make images
make install
```
2.run test
```
rm -rf tmp ; jtreg -v:fail,error -w tmp -nr -jdk:/apsarapangu/disk1/yansendao/openjdk/jdk8u/jvm/openjdk-1.8.0-internal ./openjdk/openjdk-jdk/jdk/test/jdk/jfr/event/io/TestInstrumentation.java
```

**Expected behavior**
´test run pass, or add jfr/event/io/TestInstrumentation.java to Problemlist.txt

**Actualed behavior**
```
TestTransformation: Test failed in phase Retransformed
];
 stderr: [java.lang.RuntimeException: Wrong number of events: expected 4 to equal 7
        at jdk.test.lib.Asserts.fail(Asserts.java:594)
        at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
        at jdk.jfr.event.io.IOHelper.verifyEquals(IOHelper.java:60)
        at jdk.jfr.event.io.TestSocketEvents.test(TestSocketEvents.java:118)
        at jdk.jfr.event.io.TestSocketEvents.main(TestSocketEvents.java:63)
        at jdk.jfr.event.io.TestInstrumentation$TestMain.runAllTests(TestInstrumentation.java:194)
        at jdk.jfr.event.io.TestInstrumentation$TestMain.main(TestInstrumentation.java:179)
Exception in thread "main" java.lang.RuntimeException: Wrong number of events: expected 4 to equal 7
        at jdk.test.lib.Asserts.fail(Asserts.java:594)
        at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
        at jdk.jfr.event.io.IOHelper.verifyEquals(IOHelper.java:60)
        at jdk.jfr.event.io.TestSocketEvents.test(TestSocketEvents.java:118)
        at jdk.jfr.event.io.TestSocketEvents.main(TestSocketEvents.java:63)
        at jdk.jfr.event.io.TestInstrumentation$TestMain.runAllTests(TestInstrumentation.java:194)
        at jdk.jfr.event.io.TestInstrumentation$TestMain.main(TestInstrumentation.java:179)
]
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

        at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
        at jdk.jfr.event.io.TestInstrumentation.launchTest(TestInstrumentation.java:289)
        at jdk.jfr.event.io.TestInstrumentation.main(TestInstrumentation.java:244)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
```

test log from TKG:

[extended.openjdk.log](https://github.com/adoptium/aqa-tests/files/8552888/extended.openjdk.log)

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/24123821/165052027-cc37fd15-b300-4b09-b12e-cee8d48006dc.png)

**Comment by sophia-guo** [comment]
Yes, tests should be excluded. https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_1/37/testReport/jdk_jfr_event_io_TestInstrumentation/java/TestInstrumentation/



https://github.com/adoptium/aqa-tests/issues/2985

https://bugs.openjdk.java.net/browse/JDK-8202142
