### ISSUE TITLE
jdk18 jdk/jfr/jcmd/TestJcmdDump.java.TestJcmdDump failed with `-XX:-UseCompressedOops` on ppc64le

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3617]
jdk18 jdk/jfr/jcmd/TestJcmdDump.java.TestJcmdDump failed with `-XX:-UseCompressedOops` on ppc64le

https://ci.adoptopenjdk.net/job/Grinder/4527

```
 stdout: [20257:
Dumped recording, 300.2 kB written to:
https://ci.adoptopenjdk.net/job/Grinder/4527

/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16509419536481/jdk_jfr_1/work/scratch/1/TestJCMdDump.jfr
];
 stderr: []
 exitValue = 0

java.lang.OutOfMemoryError: Java heap space
	at jdk.jfr.jcmd.TestJcmdDump.jfrDump(TestJcmdDump.java:106)
	at jdk.jfr.jcmd.TestJcmdDump.main(TestJcmdDump.java:87)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000800c02000.invokeStatic(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000800c03400.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)

JavaTest Message: Test threw exception: java.lang.OutOfMemoryError: Java heap space
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.OutOfMemoryError: Java heap space`
```
Running with `-Xss4m` and remove option `-XX:-UseCompressedOops` test passed:
https://ci.adoptopenjdk.net/job/Grinder/4573/console

Need to confirm if the test works well with non-compressed.

**Comment by smlambert** [comment]
https://github.com/adoptium/aqa-tests/issues/3492

**Comment by sophia-guo** [comment]
Dup
