### ISSUE TITLE
jdk_other_2 / LdapPoolTimeoutTest.java FAILED in Test_openjdk17_hs_extended.openjdk_x86-32_windows

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3619]
**Test Info**
Test Name: jdk_other_2
Test Duration: 3 min 31 sec
Machine: test-ibmcloud-win2012r2-x64-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=625f58ca72761a4c5c1408f0

**Build Info**
Build Name: Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2
Jenkins Build start time: Apr 19 2022, 07:07 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2/40/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=625f57cf72761a4c5c14063c

**Java Version**
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, emulated-client, sharing)

**This test has been failed 2 times since Apr 10 2022, 11:05 am**
**Java Version when the issue first seen**
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+5 (build 17.0.3+5)
OpenJDK Server VM Temurin-17.0.3+5 (build 17.0.3+5, mixed mode, emulated-client, sharing)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2/39/

The test failed on machine test-ibmcloud-win2012r2-x64-1 1 times 
The test failed on machine build-alibaba-win2012r2-x64-2 1 times 

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=&amp;TARGET=jdk_other_2&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_hs_extended.openjdk_x86-32_windows&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-32_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x86-32-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-17.0.3%2B7_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=60&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=29&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

---

jdk_other_2 - com/sun/jndi/ldap/LdapPoolTimeoutTest.java fails with
```
19:33:42  STDOUT:
19:33:42  java.lang.AssertionError: expected [true] but found [false]
19:33:42  	at org.testng.Assert.fail(Assert.java:99)
19:33:42  	at org.testng.Assert.failNotEquals(Assert.java:1037)
19:33:42  	at org.testng.Assert.assertTrue(Assert.java:45)
19:33:42  	at org.testng.Assert.assertTrue(Assert.java:55)
19:33:42  	at LdapPoolTimeoutTest.attemptConnect(LdapPoolTimeoutTest.java:124)
19:33:42  	at LdapPoolTimeoutTest.lambda$test$0(LdapPoolTimeoutTest.java:91)
19:33:42  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:33:42  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
19:33:42  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
19:33:42  	at java.base/java.lang.Thread.run(Thread.java:833)
19:33:42  STDERR:
19:33:42  MSG RTE: javax.naming.CommunicationException: example.com:1234 [Root exception is java.net.ConnectException: Connection timed out: no further information]
19:33:42  MSG: Timed out waiting for lock
```

Rerun on RI (Azul) in [Grinder/4584](https://ci.adoptopenjdk.net/job/Grinder/4584), which is failing in the same way...

**Comment by smlambert** [comment]
Also seen in jdk11 win32 (see https://github.com/adoptium/aqa-tests/issues/3596#issuecomment-1105919813)
