### ISSUE TITLE
[arm32 jdk11] java/nio/file/DirectoryStream/SecureDS.java failed

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3635]
[java/nio/file/DirectoryStream/SecureDS.java](https://github.com/openjdk/jdk11u/blob/master/test/jdk/java/nio/file/DirectoryStream/SecureDS.java#L47-L51) failed with error message:

```
java.lang.AssertionError: SecureDirectoryStream not supported.
	at SecureDS.main(SecureDS.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Reported https://github.com/adoptium/aqa-tests/issues/3596#issuecomment-1104643594
Also 
https://github.com/adoptium/infrastructure/issues/2374#issuecomment-980159992

**Comment by smlambert** [comment]
Also fails with "not supported" on aarch64_alpine-linux and x86-64_alpine-linux platforms, with the challenge that there does not seem to be a way to exclude it for just those platforms (differentiated from linux).
