### ISSUE TITLE
[jdk18] compiler/jvmci/jdk.vm.ci.hotspot.test/src/jdk/vm/ci/hotspot/test/TestTranslatedException.java failed on multiple platform

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3658]
[jdk18] compiler/jvmci/jdk.vm.ci.hotspot.test/src/jdk/vm/ci/hotspot/test/TestTranslatedException.java failed on linux-x64 , windows-x64, mac-aarch64, linux-aarch64
https://github.com/adoptium/aqa-tests/issues/3599

Rerun with azul and Oracle RI got the same failure

```
23:12:00  STDOUT:
23:12:00  test jdk.vm.ci.hotspot.test.TestTranslatedException.encodeDecodeTest(): failure
23:12:00  java.lang.NoSuchMethodException: jdk.vm.ci.hotspot.TranslatedException.decodeThrowable(java.lang.String)
23:12:00  	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2707)
23:12:00  	at jdk.vm.ci.hotspot.test.TestTranslatedException.encodeDecodeTest(TestTranslatedException.java:59)
23:12:00  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
23:12:00  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
```

**Comment by sophia-guo** [comment]
Also mac-x64
