### ISSUE TITLE
jdk/com/sun/jdi/JdwpAllowTest.java fail on some linux machine

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3685]
**Describe the bug**
jdk/com/sun/jdi/JdwpAllowTest.java fail on some linux machine

```
Command line: ['/home/yansendao.ysd/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0' '-cp' '/home/yansendao.ysd/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao.ysd/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' 'ba045762-7d0b-432a-9cb1-957bb4c0b4a2.lck']
LingeredApp failed to start: java.io.IOException: App exited unexpectedly with 2
 LingeredApp stdout: [];
 LingeredApp stderr: [ERROR: transport error 202: socket creation failed: Address family not supported by protocol
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
]
 LingeredApp exitValue = 2
STDERR:
localhost address: 127.0.0.1

Starting DefaultTest
java.io.IOException: App exited unexpectedly with 2
        at jdk.test.lib.apps.LingeredApp.waitAppReady(LingeredApp.java:288)
        at jdk.test.lib.apps.LingeredApp.waitAppReady(LingeredApp.java:304)
        at jdk.test.lib.apps.LingeredApp.startAppExactJvmOpts(LingeredApp.java:448)
        at jdk.test.lib.apps.LingeredApp.startApp(LingeredApp.java:465)
        at jdk.test.lib.apps.LingeredApp.startApp(LingeredApp.java:477)
        at JdwpAllowTest.positiveTest(JdwpAllowTest.java:108)
        at JdwpAllowTest.main(JdwpAllowTest.java:221)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
rm -rf tmp ; jtreg -v:fail,error,time,nopass -nr -w tmp aqa-tests/openjdk/openjdk-jdk/test/jdk/com/sun/jdi/JdwpAllowTest.java

**Expected behavior**
test run pass on all platform?

**Screenshots**

![image](https://user-images.githubusercontent.com/24123821/169484786-6a0c0882-48e3-4b47-8b39-6d61517267c1.png)

**Additional context**
I can’t find any usefull meaasge from [TRSS](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_1/38/testReport/com_sun_jdi_JdwpAllowTest/java/) about ths testcase's test result logs.

on my another machine, with the same jdk, this test run pass:

```
STDOUT:
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '550e1a3b-6fe7-49e2-8351-b83c2ae112fa.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 55823
Listening for transport dt_socket at address: 47195
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=*' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' 'dcbda335-8520-41dc-a94a-baa684545c54.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 49261
Listening for transport dt_socket at address: 33691
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=127.0.0.1' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '240c9c64-4584-41df-a66e-5eebcc0237b4.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 36225
Listening for transport dt_socket at address: 47273
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=127.0.0.1+10.0.0.0/8+172.16.0.0/12+192.168.0.0/24' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '12c8d039-1d92-41cc-8ad3-3811fb4ee90f.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 52337
Listening for transport dt_socket at address: 42371
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=0.0.0.0' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '77021f51-34cd-4396-9e56-ba802a953b4b.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 43993
];
 LingeredApp stderr: [Debugger failed to attach: ERROR: Peer not allowed to connect: <bad address>

]
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=127.0.0.1;192.168.0.0/24' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' 'db63ce49-1ca6-4444-8a50-d7537ced716d.lck']
LingeredApp failed to start: java.io.IOException: App exited unexpectedly with 2
 LingeredApp stdout: [];
 LingeredApp stderr: [Error in allow option: '127.0.0.1;192.168.0.0'
ERROR: transport error 103: invalid IP address in allow option
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
]
 LingeredApp exitValue = 2
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' 'acfccdd1-3143-4af6-a041-0524e3840f88.lck']
LingeredApp failed to start: java.io.IOException: App exited unexpectedly with 1
 LingeredApp stdout: [];
 LingeredApp stderr: [ERROR: JDWP option syntax error: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=
]
 LingeredApp exitValue = 1
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=*+127.0.0.1' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '0368a394-baf4-4ade-9000-ab07bb60e7ff.lck']
LingeredApp failed to start: java.io.IOException: App exited unexpectedly with 2
 LingeredApp stdout: [];
 LingeredApp stderr: [Error in allow option: '*+127.0.0.1'
ERROR: transport error 103: allow option '*' cannot be expanded
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
]
 LingeredApp exitValue = 2
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=127.0.0.1+*' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '04add3c5-cce9-432a-9d41-872946f066d9.lck']
LingeredApp failed to start: java.io.IOException: App exited unexpectedly with 2
 LingeredApp stdout: [];
 LingeredApp stderr: [Error in allow option: '*'
ERROR: transport error 103: invalid IP address in allow option
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
]
 LingeredApp exitValue = 2
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=96.0.0.0/2' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '9b87aedb-3feb-4366-a3ea-c09247347958.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 48617
Listening for transport dt_socket at address: 37691
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=96.0.0.0/3' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' 'ba5416f7-b6cb-44bf-97d6-7f048e80b9ca.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 55711
Listening for transport dt_socket at address: 56117
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=0:0:0:0:0:0:0:1000/114' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' 'db5fa65c-498c-4101-918f-a16696f947cf.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 58453
Listening for transport dt_socket at address: 34629
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
Command line: ['/home/yansendao/software/jdk/2022-05/dragonwell-17.0.3.0.3+7-GA/bin/java' '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:0,allow=0:0:0:0:0:0:0:1000/115' '-cp' '/home/yansendao/tmp/classes/com/sun/jdi/JdwpAllowTest.d:/home/yansendao/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '0d2e4390-9c92-4757-84da-a1df7f7d4787.lck']
 LingeredApp stdout: [Listening for transport dt_socket at address: 36159
Listening for transport dt_socket at address: 54645
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
STDERR:
localhost address: 127.0.0.1

Starting DefaultTest
DefaultTest PASSED

Starting ExplicitDefaultTest
ExplicitDefaultTest PASSED

Starting AllowTest
AllowTest PASSED

Starting MultiAllowTest
MultiAllowTest PASSED

Starting DenyTest
DenyTest: returned a negative code as expected: -1
DenyTest PASSED

Starting MultiDenyTest
MultiDenyTest: caught expected IOException
MultiDenyTest PASSED

Starting EmptyAllowOptionTest
EmptyAllowOptionTest: caught expected IOException
EmptyAllowOptionTest PASSED

Starting ExplicitMultiDefault1Test
ExplicitMultiDefault1Test: caught expected IOException
ExplicitMultiDefault1Test PASSED

Starting ExplicitMultiDefault2Test
ExplicitMultiDefault2Test: caught expected IOException
ExplicitMultiDefault2Test PASSED

Starting PositiveMaskTest(127.0.0.1)
PositiveMaskTest(127.0.0.1) PASSED

Starting NegativeMaskTest(127.0.0.1)
NegativeMaskTest(127.0.0.1) PASSED

Starting PositiveMaskTest(0:0:0:0:0:0:0:1)
PositiveMaskTest(0:0:0:0:0:0:0:1) PASSED

Starting NegativeMaskTest(0:0:0:0:0:0:0:1)
NegativeMaskTest(0:0:0:0:0:0:0:1) PASSED

Test PASSED
STATUS:Passed.
```

**Comment by sendaoYan** [comment]
Add jvm [options](https://stackoverflow.com/questions/63955736/enabling-jdwp-on-a-jdk-14-app-results-in-address-family-not-supported-by-protoco)(-Djava.net.preferIPv4Stack=true) can make this test run success:

![image](https://user-images.githubusercontent.com/24123821/169492724-fbe5434f-9a8c-4f46-aa39-21c3d77432ee.png)

**Comment by smlambert** [comment]
Yes, indeed.

```
LingeredApp stderr: [ERROR: transport error 202: socket creation failed: Address family not supported by protocol

ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)

JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
```

I was going to say that the error message seemed to indicate that the machine where this test failed may be trying to use IPv6 localhost [::], and that machine may need to be configured differently, as the alternate approach setting EXTRA_OPTIONS parameter with -Djava.net.preferIPv4Stack=true will mean it shifts to use IPv4 localhost address.

**Comment by sendaoYan** [comment]
> Yes, indeed.
> 
> ```
> LingeredApp stderr: [ERROR: transport error 202: socket creation failed: Address family not supported by protocol
> 
> ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
> 
> JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
> ```
> 
> I was going to say that the error message seemed to indicate that the machine where this test failed may be trying to use IPv6 localhost [::], and that machine may need to be configured differently, as the alternate approach setting EXTRA_OPTIONS parameter with -Djava.net.preferIPv4Stack=true will mean it shifts to use IPv4 localhost address.
> 
> From a machine configuration perspective, the ansible playbooks in the [infrastructure](https://github.com/adoptium/infrastructure) repo are used and there are some [IPv6/tasks](https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/IPv6/tasks) in the set.

If I set EXTRA_OPTIONS="-Djava.net.preferIPv4Stack=true" before start aqa-tests, then same other testcases fail, such as test/jdk/java/net/InetAddress/InternalNameServiceTest.java, it will fail as:

```
STDOUT:
 TEST HOST TO  IP ADDRESS MAPPINGS 
UnknownHostException as expected for host host3.sample-domain
UnknownHostException as expected for host host4.sample-domain
UnknownHostException as expected for host host5.sample-domain
STDERR:
java.net.UnknownHostException: Unable to resolve host host-ipv6.sample-domain in hosts file TestHosts
        at java.base/java.net.InetAddress$HostsFileNameService.lookupAllHostAddr(InetAddress.java:1081)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
        at java.base/java.net.InetAddress.getByName(InetAddress.java:1251)
        at InternalNameServiceTest.testHostToIPAddressMappings(InternalNameServiceTest.java:135)
        at InternalNameServiceTest.main(InternalNameServiceTest.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by smlambert** [comment]
Yes, ultimately the openjdk test suite expects that both IPv6 and IPv4 will be tested (so a machine configured to support it).  In the meantime, we can exclude the single test if your test machines are not configured in the expected way.

**Comment by sendaoYan** [comment]
> Yes, ultimately the openjdk test suite expects that both IPv6 and IPv4 will be tested (so a machine configured to support it). In the meantime, we can exclude the single test if your test machines are not configured in the expected way.

Thanks

**Comment by sendaoYan** [comment]
I modify these two testcase to run pass temporary:

```diff
 git diff
diff --git a/test/jdk/com/sun/jdi/JdwpAllowTest.java b/test/jdk/com/sun/jdi/JdwpAllowTest.java
index 6fa29ba14..6aa125a1c 100644
--- a/test/jdk/com/sun/jdi/JdwpAllowTest.java
+++ b/test/jdk/com/sun/jdi/JdwpAllowTest.java
@@ -215,6 +215,7 @@ public class JdwpAllowTest {
     }
 
     public static void main(String[] args) throws Exception {
+        System.setProperty("test.java.opts", System.getProperty("test.java.opts") + " -Djava.net.preferIPv4Stack=true");
         init();
 
         // No allow option is the same as the allow option ',allow=*' is passed
diff --git a/test/jdk/com/sun/jdi/JdwpListenTest.java b/test/jdk/com/sun/jdi/JdwpListenTest.java
index a55eefb58..7907035e6 100644
--- a/test/jdk/com/sun/jdi/JdwpListenTest.java
+++ b/test/jdk/com/sun/jdi/JdwpListenTest.java
@@ -53,6 +53,7 @@ public class JdwpListenTest {
     private static boolean allowNegativeTesting = false;
 
     public static void main(String[] args) throws Exception {
+        System.setProperty("test.java.opts", System.getProperty("test.java.opts") + " -Djava.net.preferIPv4Stack=true");
         List<InetAddress> addresses = Utils.getAddressesWithSymbolicAndNumericScopes();
 
         boolean ipv4EnclosedTested = false;
```
