### ISSUE TITLE
TestJlmRemoteMemoryNoAuth_0 randomly fail: java.lang.AssertionError: Peak Usage used memory smaller than Current Usage used memory

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3710]
**Describe the bug**
TestJlmRemoteMemoryNoAuth_0 randomly fail. 

**To Reproduce**
```bash
cd aqa-tests
export JDK_VERSION=8
export JAVA_HOME=~/software/jdk/2022-05/jdk8u332-b09
export TEST_JDK_HOME=$JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH
export USE_TESTENV_PROPERTIES=true
export JDK_IMPL=hotspot
export BUILD_LIST=system
./compile.sh
cd TKG
for i in `seq 100` ; do time make _TestJlmRemoteMemoryNoAuth_0 &> test-TestJlmRemoteMemoryNoAuth_0-$i.log ; done
```

**Expected behavior**
run pass everytime.

**fail log**

```
CL1 stderr j> 2022/05/27 21:06:56.512   Peak usage smaller than current usage here:
CL1 stderr j> 2022/05/27 21:06:56.512   Memory Pool:              Code Cache
CL1 stderr j> 2022/05/27 21:06:56.512   Memory Type:              Non-heap memory
CL1 stderr j> 2022/05/27 21:06:56.512   Peak Usage:               init = 2555904(2496K) used = 31874048(31127K) committed = 33357824(32576K) max = 251658240(245760K)
CL1 stderr j> 2022/05/27 21:06:56.512   Current Usage:            init = 2555904(2496K) used = 31887040(31139K) committed = 33357824(32576K) max = 251658240(245760K)
CL1 stderr Exception in thread "main" java.lang.AssertionError: Peak Usage used memory smaller than Current Usage used memory
CL1 stderr      at org.junit.Assert.fail(Assert.java:88)
CL1 stderr      at net.adoptopenjdk.test.jlm.resources.MemoryData.checkPeakAndCurrentMemoryUsage(MemoryData.java:521)
CL1 stderr      at net.adoptopenjdk.test.jlm.resources.MemoryData.writeData(MemoryData.java:182)
CL1 stderr      at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.getStatsViaProxy(MemoryProfiler.java:183)
CL1 stderr      at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:110)
STF 21:06:56.543 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
STF 21:06:56.543 - Monitoring Report Summary:
STF 21:06:56.543 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
STF 21:06:56.543 -   o Process LT1 is still running as expected
STF 21:06:56.543 - Killing processes: CL1 LT1
STF 21:06:56.543 -   o Process LT1 pid 21815 stop()
STF 21:06:57.544 -   o Process LT1 pid 21815 killed
STF 21:06:57.544 -   o Process CL1 pid 21816 is not running
**FAILED** at step 3 (Wait for processes to complete). Expected return value=0 Actual=1 at /mnt_array/yansendao.ysd/aqa-tests-jdk8/TKG/../TKG/output_16536567696807/TestJlmRemoteMemoryNoAuth_0/20220527-210609-TestJlm
RemoteMemoryNoAuth/execute.pl line 160.
STF 21:06:57.599 - **FAILED** execute script failed. Expected return value=0 Actual=1
```
[test-TestJlmRemoteMemoryNoAuth_0-17.log](https://github.com/adoptium/aqa-tests/files/8796327/test-TestJlmRemoteMemoryNoAuth_0-17.log)

**Additional context**

The probability of random failure is about 1 in 100.
![image](https://user-images.githubusercontent.com/24123821/170937327-c783d8a8-d80c-4d7c-a25f-3512a0dd083b.png)

[output_16536567696807.zip](https://github.com/adoptium/aqa-tests/files/8796351/output_16536567696807.zip)

**Comment by smlambert** [comment]
related: https://github.com/adoptium/aqa-systemtest/issues/274

**Comment by sendaoYan** [comment]
> 

@smlambert Thanks. I think we can follow this issue on https://github.com/adoptium/aqa-systemtest/issues/274. So close this issue now.
