### ISSUE TITLE
_OAuthTest_0 intermittent fail on ubuntu20.04

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3717]
**Describe the bug**
_OAuthTest_0 intermittent fail on ubuntu20.04

**To Reproduce**
```bash
export JDK_VERSION=11
export JAVA_HOME=~/software/jdk/2022-05/jdk-11.0.15+10
export TEST_JDK_HOME=$JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH
export USE_TESTENV_PROPERTIES=true
export JDK_IMPL=hotspot
export BUILD_LIST=system
cd aqa-tests
./compile.sh
cd TKG
for i in `seq 10` ; do make _OAuthTest_0 &> test-OAuthTest_0-$i.log ; done
```

**Expected behavior**
run pass everytime.

**Screenshots**
![image](https://user-images.githubusercontent.com/24123821/171409609-04c1a2d1-f316-4f2d-8840-66f00cb2d3ec.png)

**Additional context**
![image](https://user-images.githubusercontent.com/24123821/171410129-532a9866-64ec-4dbc-8436-2577fabc1354.png)

```
STF 17:46:06.528 - Running command: /home/yansendao/software/jdk/2022-05/jdk-11.0.15+10/bin/java -classpath /home/yansendao/jvmtest/system/aqa-systemtest/openjdk.test.security/bin net.adoptopenjdk.test.auth.Client /home/yansendao/jvmtest/system/aqa-systemtest/openjdk.test.security/src/test.security/net/adoptopenjdk/test/auth/testkeys TLSv1.3
STF 17:46:06.528 - Redirecting stderr to /home/yansendao/aqa-tests-jdk11/TKG/output_16540767655362/OAuthTest_0/20220601-174605-OAuthTest/results/3.CLI.stderr
STF 17:46:06.528 - Redirecting stdout to /home/yansendao/aqa-tests-jdk11/TKG/output_16540767655362/OAuthTest_0/20220601-174605-OAuthTest/results/3.CLI.stdout
STF 17:46:06.529 -
STF 17:46:06.529 - +------ Step 4 - Wait for clients to complete
STF 17:46:06.529 - | Wait for processes to meet expectations
STF 17:46:06.529 - |   Processes: [CLI]
STF 17:46:06.529 - |
STF 17:46:06.529 - Monitoring processes: CLI
CLI stderr Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
CLI stderr      at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
CLI stderr      at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
CLI stderr      at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
CLI stderr      at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
CLI stderr      at java.base/java.net.Socket.connect(Socket.java:609)
CLI stderr      at java.base/java.net.Socket.connect(Socket.java:558)
CLI stderr      at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
CLI stderr      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
CLI stderr      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
CLI stderr      at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
CLI stderr      at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
CLI stderr      at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
CLI stderr      at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
CLI stderr      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
CLI stderr      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
CLI stderr      at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
CLI stderr      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
CLI stderr      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
CLI stderr      at net.adoptopenjdk.test.auth.Client.main(Client.java:23)
STF 17:46:06.629 - **FAILED** Process CLI ended with exit code (1) and not the expected exit code/s (0)
STF 17:46:06.629 - Monitoring Report Summary:
STF 17:46:06.630 -   o Process CLI ended with exit code (1) and not the expected exit code/s (0)
```
[test-OAuthTest_0-2.log](https://github.com/adoptium/aqa-tests/files/8814264/test-OAuthTest_0-2.log)
[test-OAuthTest_0-4.log](https://github.com/adoptium/aqa-tests/files/8814265/test-OAuthTest_0-4.log)

**Comment by joeyleeeeeee97** [comment]
@sendaoYan  I will take a look at this failure.

**Comment by sophia-guo** [comment]
Dup of #3237
