### ISSUE TITLE
ComodoCA.java intermittently fail because of internet unstable

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3736]
**Describe the bug**
test/jdk/security/infra/java/security/cert/CertPathValidator/certification/ComodoCA.java intermittently fail because of internet unstable

**To Reproduce**
```bash
cd jdk17u/test/jdk/security/infra/java/security/cert/CertPathValidator/certification
javac -g ComodoCA.java ValidatePathWithParams.java 
java -Dtest.jdk=$JAVA_HOME -Djava.security.debug=certpath ComodoCA CRL
```

or run testcase by jtreg:
```bash
jtreg test/jdk/security/infra/java/security/cert/CertPathValidator/certification/ComodoCA.java
```

**result**

```log
certpath: Trying to fetch CRL from DP http://crl.comodoca.com/COMODORSACertificationAuthority.crl
certpath: CertStore URI:http://crl.comodoca.com/COMODORSACertificationAuthority.crl
certpath: Exception fetching CRL:
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.security.provider.certpath.URICertStore.engineGetCRLs(URICertStore.java:385)
        at java.base/java.security.cert.CertStore.getCRLs(CertStore.java:182)
        at java.base/sun.security.provider.certpath.DistributionPointFetcher.getCRL(DistributionPointFetcher.java:271)
        at java.base/sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:214)
        at java.base/sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:145)
        at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:586)
        at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:471)
        at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:373)
        at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:343)
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
        at ValidatePathWithParams.doCertPathValidate(ValidatePathWithParams.java:288)
        at ValidatePathWithParams.validate(ValidatePathWithParams.java:142)
        at ComodoRSA.runTest(ComodoCA.java:218)
        at ComodoCA.main(ComodoCA.java:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:833)
certpath: X509CertSelector.match(SN: 3e8
  Issuer: CN=Hongkong Post Root CA 1, O=Hongkong Post, C=HK
  Subject: CN=Hongkong Post Root CA 1, O=Hongkong Post, C=HK)
certpath: X509CertSelector.match: subject DNs don't match
java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
        at ValidatePathWithParams.validate(ValidatePathWithParams.java:177)
        at ComodoRSA.runTest(ComodoCA.java:218)
        at ComodoCA.main(ComodoCA.java:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.security.cert.CertPathValidatorException: Unable to determine revocation status due to network error
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
        at ValidatePathWithParams.doCertPathValidate(ValidatePathWithParams.java:288)
        at ValidatePathWithParams.validate(ValidatePathWithParams.java:142)
        ... 8 more
Caused by: sun.security.provider.certpath.PKIX$CertStoreTypeException: java.net.ConnectException: Connection refused
        at java.base/sun.security.provider.certpath.URICertStore.engineGetCRLs(URICertStore.java:419)
        at java.base/java.security.cert.CertStore.getCRLs(CertStore.java:182)
        at java.base/sun.security.provider.certpath.DistributionPointFetcher.getCRL(DistributionPointFetcher.java:271)
        at java.base/sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:214)
        at java.base/sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:145)
        at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:586)
        at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:471)
        at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:373)
        at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:343)
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
        ... 14 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.security.provider.certpath.URICertStore.engineGetCRLs(URICertStore.java:385)
        ... 23 more
```

**Expected behavior**

I write a another demo to show the internet unstable:
SocketTest.java 
```java
import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;

public class SocketTest {

    static Socket socket = null;

    public static void main(String[] args) throws IOException {
        socket = new Socket("crl.comodoca.com", 80);
        InputStream s = socket.getInputStream();
        socket.close();
    }
}
```
[SocketTest.java.txt](https://github.com/adoptium/aqa-tests/files/8852944/SocketTest.java.txt)

![image](https://user-images.githubusercontent.com/24123821/172373728-62a645a6-dc3c-47d7-9166-b58f9149b738.png)

So, shoule we exclude this testcase, when the vendor is alibaba?

**Comment by smlambert** [comment]
Yes, let's exclude the list of tests that are unstable due to network access issues.  You can see that we are adding vendor specific ProblemList for this purpose.  We have not yet added one for Alibaba, but the intention was to do that and then some of the test cases you have recently flagged from the openjdk suite can be excluded.

**Comment by sendaoYan** [comment]
If I bind web address crl.comodoca.com to definite ip address 172.64.155.188, this test run success everytime. 
So, I think we can close this issue now. If this failure recour, we can reopen it.

![image](https://user-images.githubusercontent.com/24123821/173316494-53bc4496-8c26-43a5-8eaf-d8009e657c2d.png)
