### ISSUE TITLE
VersionCheck.java run fail by dragonwell8

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3751]
**Describe the bug**
jdk/test/tools/launcher/VersionCheck.java run fail by dragonwell8

**To Reproduce**
`jtreg jdk/test/tools/launcher/VersionCheck.java`

```log
Internal Strings Test: 0
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/idlj
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/jgroup
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/jhat
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/java
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/javac
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/javah
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/javap
Testing (-version): /home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/jdb
STDERR:
java.lang.AssertionError: Some tests failed
        at VersionCheck.main(VersionCheck.java:227)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:855)
```

**Expected behavior**
The resaon of this testcase run fail, is the command `jgroup -v` return non zero.

![image](https://user-images.githubusercontent.com/24123821/173037524-6ae43478-7ea7-4b89-a96b-bd71d439ac1f.png)

If we make some modify on this case, then this testcas will pass(add jgroup to BLACKLIST_VERSION String array):

![image](https://user-images.githubusercontent.com/24123821/173038308-d3a92c69-415b-44a2-8a75-d8c40af88429.png)

**So, can we add this testcase to alibaba problemlist?**

**Comment by smlambert** [comment]
> So, can we add this testcase to alibaba problemlist?

Yes please do 👍
