### ISSUE TITLE
TestConstructorFinder.java run fail by dragonwell8/dragonwell11

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3752]
**Describe the bug**
jdk/test/java/beans/XMLDecoder/8028054/TestConstructorFinder.java run fail by dragonwell8

**To Reproduce**
`jtreg jdk/test/java/beans/XMLDecoder/8028054/TestConstructorFinder.java`

```
java.lang.UnsatisfiedLinkError: java.dyn.CoroutineSupport.registerNatives()V
        at java.dyn.CoroutineSupport.registerNatives(Native Method)
        at java.dyn.CoroutineSupport.<clinit>(CoroutineSupport.java:60)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at Task.getClasses(Task.java:90)
        at TestConstructorFinder.main(TestConstructorFinder.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:855)
```

**Expected behavior**
The reason of this testcase run fail, is dragonwell can't load native library registerNatives. But only enable Coroutine dragonwell can load registerNatives.

If we modify this case like this:
```diff
diff --git a/jdk/test/java/beans/XMLDecoder/8028054/TestConstructorFinder.java b/jdk/test/java/beans/XMLDecoder/8028054/TestConstructorFinder.java
index 1bce91ec..3adb2e33 100644
--- a/jdk/test/java/beans/XMLDecoder/8028054/TestConstructorFinder.java
+++ b/jdk/test/java/beans/XMLDecoder/8028054/TestConstructorFinder.java
@@ -34,7 +34,7 @@ import java.util.List;
  * @summary Tests that cached constructors have synchronized access
  * @author Sergey Malenkov
  * @compile -XDignore.symbol.file TestConstructorFinder.java
- * @run main TestConstructorFinder
+ * @run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine TestConstructorFinder
  */
```

Then this testcase will run pass:

![image](https://user-images.githubusercontent.com/24123821/173042146-65ebb51c-83a0-47fb-9e3c-d5c0feebad23.png)

**So, can we add this testcase to alibaba problemlist?**

**Comment by smlambert** [comment]
> So, can we add this testcase to alibaba problemlist?

Yes, please do 👍
