### ISSUE TITLE
TestPromotionFailedEventWithParNew.java intermittently fail on linux-arch64 by temurin8

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3770]
**Describe the bug**
jdk/jfr/event/gc/detailed/TestPromotionFailedEventWithParNew.java intermittently fail on linux-arch64 by temurin8

**To Reproduce**
```bash
export JDK_VERSION=8
export JAVA_HOME=~/software/jdk/2022-05/jdk8u332-b09/
export TEST_JDK_HOME=$JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH
export USE_TESTENV_PROPERTIES=true
export JDK_IMPL=hotspot
export BUILD_LIST=openjdk
cd aqa-tests
./compile.sh
cd TKG
time for i in `seq 50000` ; do make _jdk_jfr_1 &> test-jdk_jfr_1-index-$i.log ; done
```

result:
```log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffffa81ca690, pid=3690192, tid=0x0000ffffa74791e0
#
# JRE version: OpenJDK Runtime Environment (8.0_332-b09) (build 1.8.0_332-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.332-b09 mixed mode linux-aarch64 )
# Problematic frame:
# C  [libc.so.6+0x86690]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/yansendao/aqa-tests-temurin8/TKG/output_1655247961990/jdk_jfr_1/work/scratch/26/hs_err_pid3690192.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
];
 stderr: [
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "JFR Periodic Tasks"
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
]
 exitValue = 134

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
	at jdk.jfr.event.gc.detailed.ExecuteOOMApp.execute(ExecuteOOMApp.java:58)
	at jdk.jfr.event.gc.detailed.PromotionFailedEvent.test(PromotionFailedEvent.java:45)
	at jdk.jfr.event.gc.detailed.TestPromotionFailedEventWithParNew.main(TestPromotionFailedEventWithParNew.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
```

[hs_err_pid3690192.log](https://github.com/adoptium/aqa-tests/files/8905262/hs_err_pid3690192.log)
[test-jdk_jfr_1-index-455.log](https://github.com/adoptium/aqa-tests/files/8905263/test-jdk_jfr_1-index-455.log)

**Expected behavior**
run pass everytime.

**Additional context**

![image](https://user-images.githubusercontent.com/24123821/173725550-976d92c6-2128-4742-8944-8f9d1687be78.png)

**Comment by sendaoYan** [comment]
If we can not reproduce the failure, I think we can close this issue now. Thanks
