### ISSUE TITLE
win32: sun/security/ssl/SSLSocketImpl/SSLSocketLeak.java failed with jdk11 and jdk17

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3811]
sun/security/ssl/SSLSocketImpl/SSLSocketLeak.java failed with jdk11 and jdk17

```
13:57:25  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.UnsatisfiedLinkError: 'long jdk.test.lib.util.FileUtils.getWinProcessHandleCount()'
13:57:25  REASON: User specified action: run main/othervm SSLSocketLeak 
13:57:25  TIME:   0.289 seconds
13:57:25  messages:
13:57:25  command: main SSLSocketLeak
13:57:25  reason: User specified action: run main/othervm SSLSocketLeak 
13:57:25  Mode: othervm [/othervm specified]
13:57:25  elapsed time (seconds): 0.289
13:57:25  configuration:
13:57:25  STDOUT:
13:57:25  STDERR:
13:57:25  java.lang.UnsatisfiedLinkError: 'long jdk.test.lib.util.FileUtils.getWinProcessHandleCount()'
13:57:25  	at jdk.test.lib.util.FileUtils.getWinProcessHandleCount(Native Method)
13:57:25  	at jdk.test.lib.util.FileUtils.getProcessHandleCount(FileUtils.java:374)
13:57:25  	at SSLSocketLeak.main(SSLSocketLeak.java:49)
13:57:25  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:57:25  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
13:57:25  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:57:25  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
13:57:25  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:57:25  	at java.base/java.lang.Thread.run(Thread.java:833)

```

Grinder with April release the error is different:

```
16:44:17  java.lang.UnsatisfiedLinkError: no FileUtils in java.library.path: E:\workspace\Grinder\openjdkbinary\j2sdk-image\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\DTS\Binn;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\openjdk\jdk-8\bin;C:\apache-ant\apache-ant-1.10.5\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\IncrediBuild;C:\rust\bin;C:\Program Files\IcedTeaWEB\bin;.
16:44:17  	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
16:44:17  	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
16:44:17  	at java.base/java.lang.System.loadLibrary(System.java:1989)
16:44:17  	at jdk.test.lib.util.FileUtils.getProcessHandleCount(FileUtils.java:371)
16:44:17  	at SSLSocketLeak.main(SSLSocketLeak.java:49)
16:44:17  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:44:17  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:44:17  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:44:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:44:17  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
```

Feels like test issue. jni library FileUtils updated?

**Comment by sophia-guo** [comment]
Windows uses FileUtils library and JNI getWinProcessHandleCount(). Passed on win64 and failed on win32. @jerboaa could you take a look?

**Comment by sophia-guo** [comment]
Could be windows32 compiler issue https://github.com/openjdk/jdk17u/blob/master/test/lib/jdk/test/lib/util/libFileUtils.c#L27-L43 ?

**Comment by karianna** [comment]
Will take a look internally (may be a July PSU target fix for us)

**Comment by smlambert** [comment]
ok, meantime I guess we exclude this testcase on win32
