### ISSUE TITLE
JDK17+: ConcurrentLoadTest_5m and MiniMix_aot_5m failed on aix intermittently with same error message

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3819]
JDK17+: ConcurrentLoadTest_5m failed on random aix machines. The failure is intermittent with high rate.

https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.system_ppc64_aix/154/consoleFull

```
21:25:25  LT  testStarted : testAPI(net.adoptopenjdk.test.concurrent.atomic.AtomicLongArrayTest)
21:25:25  LT  testFailure: testAPI(net.adoptopenjdk.test.concurrent.atomic.AtomicLongArrayTest): 27 : weakCompareAndSet() expected:<true> but was:<false>
21:25:25  LT  junit.framework.AssertionFailedError: 27 : weakCompareAndSet() expected:<true> but was:<false>
21:25:25  LT  	at junit.framework.Assert.fail(Assert.java:57)
21:25:25  LT  	at junit.framework.Assert.failNotEquals(Assert.java:329)
21:25:25  LT  	at junit.framework.Assert.assertEquals(Assert.java:78)
21:25:25  LT  	at junit.framework.Assert.assertEquals(Assert.java:174)
```

**Comment by sendaoYan** [comment]
Does it same to https://github.com/adoptium/aqa-tests/issues/3700

**Comment by sophia-guo** [comment]
The console output looks different.

```
22:16:00  LT  >>> Captured test output >>>
22:16:00  LT  testStarted : testAPI(net.adoptopenjdk.test.concurrent.atomic.AtomicLongArrayTest)
22:16:00  LT  testFailure: testAPI(net.adoptopenjdk.test.concurrent.atomic.AtomicLongArrayTest): 27 : weakCompareAndSet() expected:<true> but was:<false>
22:16:00  LT  junit.framework.AssertionFailedError: 27 : weakCompareAndSet() expected:<true> but was:<false>
22:16:00  LT  	at junit.framework.Assert.fail(Assert.java:57)
22:16:00  LT  	at junit.framework.Assert.failNotEquals(Assert.java:329)
22:16:00  LT  	at junit.framework.Assert.assertEquals(Assert.java:78)
22:16:00  LT  	at junit.framework.Assert.assertEquals(Assert.java:174)
22:16:00  LT  	at junit.framework.TestCase.assertEquals(TestCase.java:333)
22:16:00  LT  	at net.adoptopenjdk.test.concurrent.atomic.AtomicLongArrayTest.testAPI(AtomicLongArrayTest.java:137)
22:16:00  LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:16:00  LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
22:16:00  LT  	at junit.framework.TestCase.runTest(TestCase.java:176)
22:16:00  LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
22:16:00  LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
22:16:00  LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
22:16:00  LT  	at junit.framework.TestResult.run(TestResult.java:125)
22:16:00  LT  	at junit.framework.TestCase.run(TestCase.java:129)
22:16:00  LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
22:16:00  LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
22:16:00  LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
22:16:00  LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
22:16:00  LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
22:16:00  LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
```

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.system_ppc64_aix/105/consoleFull

**Comment by sophia-guo** [comment]
ppc64le https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.system_ppc64le_linux/134/consoleFull
