### ISSUE TITLE
jdk11 arm: jdk/jfr/api/recording/state/TestStateInvalid.java got `[error][jfr] Could not finish chunk`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3836]
jdk11 arm: jdk/jfr/api/recording/state/TestStateInvalid.java got `[error][jfr] Could not finish chunk`

```
18:06:36  STDOUT:
18:06:36  [0.780s][error][jfr] Could not finish chunk. C:\Users\jenkins\AppData\Local\Temp\2022_07_02_22_06_31_1928\2022_07_02_22_06_31.part -> C:\Users\jenkins\AppData\Local\Temp\2022_07_02_22_06_31_1928\2022_07_02_22_06_31.jfr
18:06:36  [0.784s][error][jfr] Could not finish chunk. C:\Users\jenkins\AppData\Local\Temp\2022_07_02_22_06_31_1928\2022_07_02_22_06_31.jfr
18:06:36  STDERR:
18:06:36  java.lang.Error: not finished chunk 2022-07-02T22:06:31.152030400Z
18:06:36  	at jdk.jfr/jdk.jfr.internal.PlatformRecording.appendChunk(PlatformRecording.java:524)
18:06:36  	at jdk.jfr/jdk.jfr.internal.PlatformRecorder.finishChunk(PlatformRecorder.java:395)
18:06:36  	at jdk.jfr/jdk.jfr.internal.PlatformRecorder.stop(PlatformRecorder.java:286)
18:06:36  	at jdk.jfr/jdk.jfr.internal.PlatformRecording.stop(PlatformRecording.java:157)
18:06:36  	at jdk.jfr/jdk.jfr.Recording.stop(Recording.java:210)
18:06:36  	at jdk.jfr.api.recording.state.TestStateInvalid.main(TestStateInvalid.java:54)
18:06:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:06:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:06:36  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:06:36  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:06:36  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)

```

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-32_windows_testList_0/49/consoleFull

**Comment by sophia-guo** [comment]
win32 is not supported any more, close this.

**Comment by smlambert** [comment]
> win32 is not supported any more, close this.

Well 'technically' win32 is no longer built as a Temurin binary.  AQAvit is used by other distributions, not just Temurin.  However, I am fine with closing these open issues.  I just would not say that AQAvit no longer supports win32.
