### ISSUE TITLE
run sanity.jck fail because of java.lang.NumberFormatException: For input string: "8b"

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3861]
**Describe the bug**
run sanity.jck fail because of java.lang.NumberFormatException: For input string: "8b"

```log
mkdir -p "/home/yansendao/aqa-tests-jdk8/TKG/../TKG/output_16578765208911/jck-runtime-api-java_lang-instrument_0"; \
cd "/home/yansendao/aqa-tests-jdk8/TKG/../TKG/output_16578765208911/jck-runtime-api-java_lang-instrument_0"; \
"/home/yansendao/software/jdk/2022-05/dragonwell-8.11.12/bin/java" -Djvm.options=" " -Dother.opts="" -cp /home/yansendao/aqa-tests-jdk8/TKG/../jck/jtrunner/bin JavaTestRunner resultsRoot="/home/yansendao/aqa-tests-jdk8/TKG/../TKG/output_16578765208911/jck-runtime-api-java_lang-instrument_0" testRoot=/home/yansendao/aqa-tests-jdk8/TKG/.. tests=api/java_lang/instrument jckRoot=/home/yansendao/jck/jck8b jckversion=8b testsuite=RUNTIME; \
if [ $? -eq 0 ] ; then echo ""; echo "jck-runtime-api-java_lang-instrument_0""_PASSED"; echo ""; cd /home/yansendao/aqa-tests-jdk8/TKG/..;  else echo ""; echo "jck-runtime-api-java_lang-instrument_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/yansendao/aqa-tests-jdk8/TKG/../TKG/output_16578765208911/TestTargetResult";
jckversion determined to be jck8b
test-args jckversion 8b does not match actual jckversion jck8b. Using actual jckversion jck8b
Using initial excludes list file /home/yansendao/jck/jck8b/JCK-runtime-8b/lib/jck8b.jtx
Unable to find additional excludes list file /home/yansendao/jck/jck8b/excludes/jck8b.jtx
Unable to find known failures list file /home/yansendao/jck/jck8b/excludes/jck8b.kfl
java.lang.NumberFormatException: For input string: "8b"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at JavaTestRunner.getJckVersionInt(JavaTestRunner.java:1324)
	at JavaTestRunner.generateJTB(JavaTestRunner.java:332)
	at JavaTestRunner.main(JavaTestRunner.java:173)
```

**To Reproduce**
```bash
export JAVA_HOME=${HOME}/software/jdk/2022-05/dragonwell-8.11.12
export JDK_VERSION=8
export TEST_JDK_HOME=$JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH
export USE_TESTENV_PROPERTIES=true
export JDK_IMPL=hotspot
export BUILD_LIST=jck
export JCK_VERSION=8b
cd aqa-tests
./compile.sh
cd TKG
time make _sanity.jck
```

**Expected behavior**
The jck test support jck8b and jck8c

**patch**
```diff
git diff jck/
diff --git a/jck/jtrunner/JavaTestRunner.java b/jck/jtrunner/JavaTestRunner.java
index 749750f..01cb0a4 100644
--- a/jck/jtrunner/JavaTestRunner.java
+++ b/jck/jtrunner/JavaTestRunner.java
@@ -1170,7 +1170,7 @@ public class JavaTestRunner {
                        testSpecificJvmOptions += " -Djava.security.properties=" + secPropsFile;
                }
                
-               Matcher matcher = Pattern.compile("jck(\\d+)c?").matcher(jckVersion);
+               Matcher matcher = Pattern.compile("jck(\\d+)[bc]?").matcher(jckVersion);
                if (matcher.matches()) {
                        // first group is going to be 8, 9, 10, 11, etc.
                        int jckVerNum = Integer.parseInt(matcher.group(1));
@@ -1318,7 +1318,7 @@ public class JavaTestRunner {
        }
        
        private static int getJckVersionInt(String version) {
-               if (version.equals("8c")) {
+               if (version.equals("8c") || version.equals("8b")) {
                        return 8; 
                } else {
                        return Integer.parseInt(version); 
```

![image](https://user-images.githubusercontent.com/24123821/179201013-0bfbac46-11f1-4b7e-862b-f4c10d2fb903.png)

**Comment by smlambert** [comment]
hi @sendaoYan - sent a DM to you re: this issue
