### ISSUE TITLE
jdk8 jtreg testcase TestLookForUntestedEvents.java run fail

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3889]
**Describe the bug**
jdk8 jtreg testcase jdk/test/jdk/jfr/event/metadata/TestLookForUntestedEvents.java run fail

**To Reproduce**
1. download jdk8: wget https://corretto.aws/downloads/resources/8.342.07.3/amazon-corretto-8.342.07.3-linux-aarch64.tar.gz
2. tar xf amazon-corretto-8.342.07.3-linux-aarch64.tar.gz
3. git clone jdk8u repo:  git clone --depth 1 --branch jdk8u342-b07 git@github.com:adoptium/jdk8u.git ~/aqa-tests-jdk8/openjdk/openjdk-jdk 
4. run test
jtreg -va -nr -w tmp -jdk:/home/yansendao/software/jdk/2022-07/corretto/amazon-corretto-8.342.07.3-linux-aarch64 jdk/test/jdk/jfr/event/metadata/TestLookForUntestedEvents.java

**Expected behavior**
run pass

**result**
```log
STDOUT:
==========================
Events declared in jdk.test.lib.jfr.EventNames differ from events returned by FlightRecorder.getEventTypes()

Set eventsFromEventNamesClass has more elements than set jfrEventTypes:
OptoArrayObjectAllocation
OptoInstanceObjectAllocation

This could be because:
1) You forgot to write a unit test. Please do so in test/jdk/jdk/jfr/event/
2) You wrote a unit test, but you didn't reference the event in
   test/lib/jdk/test/lib/jfr/EventNames.java. 
3) It is not feasible to test the event, not even a sanity test. 
   Add the event name to test/lib/jdk/test/lib/jfr/EventNames.java 
   and a short comment why it can't be tested
4) The event is experimental. Please add 'experimental="true"' to <Event> 
   element in metadata.xml if it is a native event, or @Experimental if it is a 
   Java event. The event will now not show up in JMC
==========================
STDERR:
java.lang.RuntimeException: Events declared in jdk.test.lib.jfr.EventNames differ from events returned by FlightRecorder.getEventTypes()
        at jdk.jfr.event.metadata.TestLookForUntestedEvents.checkEventNamesClass(TestLookForUntestedEvents.java:177)
        at jdk.jfr.event.metadata.TestLookForUntestedEvents.main(TestLookForUntestedEvents.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:750)
```

**Additional context**

https://github.com/adoptium/aqa-tests/blob/v0.9.3-release/testenv/testenv.properties#L12

The jdk8u repo branch is set to jdk8u342-b07. If the branch set to jdk8u342-ga, this testcase will run pass.

**Comment by sendaoYan** [comment]
> Would shifting to use the v0.9.4-release branch release branch resolve this? https://github.com/adoptium/aqa-tests/blob/v0.9.4-release/testenv/testenv.properties#L12

I can't replay this fail now. I think we should reopen this issue if it occur again.
