### ISSUE TITLE
MissingResourceCauseTestRun.java/HashedPasswordFileTest.java/JImageExtractTest.java run fail by root user

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3901]
**Describe the bug**
java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java run fail by root user

```log
STDOUT:
Command line: [chmod 000 UnreadableRB.properties]
[2022-08-01T03:34:03.190952969Z] Gathering output for process 60223
[2022-08-01T03:34:03.211121049Z] Waiting for completion for process 60223
[2022-08-01T03:34:03.211226766Z] Waiting for completion finished for process 60223
Output and diagnostic info for process 60223 was saved into 'pid-60223-output.log'



[2022-08-01T03:34:03.213681223Z] Waiting for completion for process 60223
[2022-08-01T03:34:03.213758593Z] Waiting for completion finished for process 60223
Command line: [/mnt_array/yansendao.ysd/software/jdk/2022-07/corretto/x64/amazon-corretto-17.0.4.8.1-linux-x64/bin/java -ea -esa -cp /mnt_array/yansendao.ysd/git/dragonwell17/tmp/classes/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.d:/mnt_array/yansendao.ysd/git/dragonwell17/test/jdk/java/util/ResourceBundle/Control:. MissingResourceCauseTest]
[2022-08-01T03:34:03.248908701Z] Gathering output for process 60228
[2022-08-01T03:34:03.344730939Z] Waiting for completion for process 60228
[2022-08-01T03:34:03.344829143Z] Waiting for completion finished for process 60228
Output and diagnostic info for process 60228 was saved into 'pid-60228-output.log'
Exception in thread "main" java.lang.RuntimeException: getBundle("UnreadableRB") doesn't throw class java.io.IOException
        at MissingResourceCauseTest.callGetBundle(MissingResourceCauseTest.java:51)
        at MissingResourceCauseTest.callGetBundle(MissingResourceCauseTest.java:43)
        at MissingResourceCauseTest.main(MissingResourceCauseTest.java:37)

[2022-08-01T03:34:03.345549329Z] Waiting for completion for process 60228
[2022-08-01T03:34:03.345626772Z] Waiting for completion finished for process 60228
Command line: [chmod 666 UnreadableRB.properties]
[2022-08-01T03:34:03.349959898Z] Gathering output for process 60251
[2022-08-01T03:34:03.350531461Z] Waiting for completion for process 60251
[2022-08-01T03:34:03.350650830Z] Waiting for completion finished for process 60251
Output and diagnostic info for process 60251 was saved into 'pid-60251-output.log'



[2022-08-01T03:34:03.351270229Z] Waiting for completion for process 60251
[2022-08-01T03:34:03.351363346Z] Waiting for completion finished for process 60251
STDERR:
java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
        at MissingResourceCauseTestRun.runCmd(MissingResourceCauseTestRun.java:97)
        at MissingResourceCauseTestRun.main(MissingResourceCauseTestRun.java:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:833)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
rerun:
cd /mnt_array/yansendao.ysd/git/dragonwell17/tmp/scratch && \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/mnt_array/yansendao.ysd/git/dragonwell17/tmp/classes/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.d:/mnt_array/yansendao.ysd/git/dragonwell17/test/jdk/java/util/ResourceBundle/Control:/mnt_array/yansendao.ysd/git/dragonwell17/tmp/classes/test/lib:/mnt_array/yansendao.ysd/git/dragonwell17/test/lib:/mnt_array/yansendao.ysd/software/jdk/jtreg/lib/javatest.jar:/mnt_array/yansendao.ysd/software/jdk/jtreg/lib/jtreg.jar \
    /mnt_array/yansendao.ysd/software/jdk/2022-07/corretto/x64/amazon-corretto-17.0.4.8.1-linux-x64/bin/java \
        -Dtest.vm.opts= \
        -Dtest.tool.vm.opts= \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/mnt_array/yansendao.ysd/software/jdk/2022-07/corretto/x64/amazon-corretto-17.0.4.8.1-linux-x64 \
        -Dcompile.jdk=/mnt_array/yansendao.ysd/software/jdk/2022-07/corretto/x64/amazon-corretto-17.0.4.8.1-linux-x64 \
        -Dtest.timeout.factor=1.0 \
        -Dtest.root=/mnt_array/yansendao.ysd/git/dragonwell17/test/jdk \
        -Dtest.name=java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java \
        -Dtest.file=/mnt_array/yansendao.ysd/git/dragonwell17/test/jdk/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java \
        -Dtest.src=/mnt_array/yansendao.ysd/git/dragonwell17/test/jdk/java/util/ResourceBundle/Control \
        -Dtest.src.path=/mnt_array/yansendao.ysd/git/dragonwell17/test/jdk/java/util/ResourceBundle/Control:/mnt_array/yansendao.ysd/git/dragonwell17/test/lib \
        -Dtest.classes=/mnt_array/yansendao.ysd/git/dragonwell17/tmp/classes/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.d \
        -Dtest.class.path=/mnt_array/yansendao.ysd/git/dragonwell17/tmp/classes/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.d:/mnt_array/yansendao.ysd/git/dragonwell17/tmp/classes/test/lib \
        com.sun.javatest.regtest.agent.MainWrapper /mnt_array/yansendao.ysd/git/dragonwell17/tmp/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.d/main.1.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
```

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):

rm -rf tmp ; sudo jtreg -v:fail,error,time,nopass -nr -w tmp -jdk:$HOME/software/jdk/2022-07/corretto/x64/amazon-corretto-17.0.4.8.1-linux-x64 test/jdk/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java

**Expected behavior**
The testcases of dragonwell feature multi-tenant must run by root user, but MissingResourceCauseTestRun.java run fail by root user. So we shoule exclude this testcase by vendor problemlist.

**Comment by sendaoYan** [comment]
test/jdk/javax/management/security/HashedPasswordFileTest.java test/jdk/tools/jimage/JImageExtractTest.java has the same problem.

![image](https://user-images.githubusercontent.com/24123821/182093414-c8594897-46bb-4aa5-908d-48a3b048b538.png)


[sudo.log](https://github.com/adoptium/aqa-tests/files/9231730/sudo.log)
