### ISSUE TITLE
java/util/Properties/StoreReproducibilityTest.java fails IST Date comparison on Java 19

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3979]
Possibly a machine TZ setup problem (machine reported Dublin/Europe TZ) but not sure.  [TRSS Test Output](https://trss.adoptium.net/output/test?id=632b55fe93ac60470bc694d0) and [TRSS Test Output](https://trss.adoptium.net/output/test?id=632b55fe93ac60470bc694d1)

Execution failed: `main' threw exception: java.lang.RuntimeException: Expected date comment Wed Sep 21 15:38:13 IST 2022 to be after Wed Sep 21 15:38:12 IST 2022 but was Wed Sep 21 11:08:13 IST 2022

Could be related to [recent Java 19 patch](https://github.com/adoptium/jdk19/commit/e4d9fc811e0ef0eb9b097e06525a1183445d8d79) in this area

[2022-09-21T14:38:25.133Z]  stdout: [Current default timezone is sun.util.calendar.ZoneInfo[id="Europe/Dublin",offset=0,dstSavings=3600000,useDaylight=true,transitions=227,lastRule=java.util.SimpleTimeZone[id=Europe/Dublin,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
[2022-09-21T14:38:25.133Z] ];
[2022-09-21T14:38:25.133Z]  stderr: []
[2022-09-21T14:38:25.133Z]  exitValue = 0
[2022-09-21T14:38:25.133Z] 
[2022-09-21T14:38:25.133Z] java.lang.RuntimeException: Expected date comment Wed Sep 21 15:38:13 IST 2022 to be after Wed Sep 21 15:38:12 IST 2022 but was Wed Sep 21 11:08:13 IST 2022
[2022-09-21T14:38:25.133Z] 	at StoreReproducibilityTest.assertCurrentDate(StoreReproducibilityTest.java:434)
[2022-09-21T14:38:25.133Z] 	at StoreReproducibilityTest.testEmptySysPropValue(StoreReproducibilityTest.java:256)
[2022-09-21T14:38:25.133Z] 	at StoreReproducibilityTest.main(StoreReproducibilityTest.java:71)
[2022-09-21T14:38:25.133Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-09-21T14:38:25.133Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-09-21T14:38:25.133Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-09-21T14:38:25.133Z] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[2022-09-21T14:38:25.133Z] 
[2022-09-21T14:38:25.133Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-09-21T14:38:25.133Z] JavaTest Message: shutting down test

**Comment by jiekang** [comment]
This has been fixed via:

https://bugs.openjdk.org/browse/JDK-8316540
https://github.com/openjdk/jdk/commit/f7578e8048ee961f22b57ee2b7eed9e9ab783cf5

**Comment by smlambert** [comment]
As per https://github.com/adoptium/aqa-tests/issues/3979#issuecomment-1802113236, closing this one.
