### ISSUE TITLE
jpackage dpkg commands fails in Linux for Java 19 due to missing libs

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3980]
Java 19 [TRSS Test Output(https://trss.adoptium.net/output/test?id=632b5f0493ac60470bc6acad)

e.g. <snippet only>

[2022-09-21T17:12:21.687Z] [17:09:29.266] Command [PID: 1511582]:
[2022-09-21T17:12:21.687Z]     dpkg -S /lib/x86_64-linux-gnu/libXtst.so.6
[2022-09-21T17:12:21.687Z] [17:09:29.266] Output:
[2022-09-21T17:12:21.687Z]     dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libXtst.so.6
[2022-09-21T17:12:21.687Z] [17:09:29.266] Returned: 1
[2022-09-21T17:12:21.687Z] 
[2022-09-21T17:12:21.687Z] [17:09:29.267] java.io.IOException: Command [dpkg, -S, /lib/x86_64-linux-gnu/libXtst.so.6] exited with 1 code
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.Executor.executeExpectSuccess(Executor.java:90)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.LinuxDebBundler.lambda$initLibProvidersLookup$14(LinuxDebBundler.java:250)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.LibProvidersLookup.lambda$execute$1(LibProvidersLookup.java:73)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
[2022-09-21T17:12:21.687Z] 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.LibProvidersLookup.execute(LibProvidersLookup.java:84)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.LinuxPackageBundler.getListOfNeededPackages(LinuxPackageBundler.java:195)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.LinuxPackageBundler.createDefaultReplacementData(LinuxPackageBundler.java:222)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.LinuxPackageBundler.execute(LinuxPackageBundler.java:155)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.Arguments.generateBundle(Arguments.java:700)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.internal.Arguments.processArguments(Arguments.java:565)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.main.Main.execute(Main.java:91)
[2022-09-21T17:12:21.687Z] 	at jdk.jpackage/jdk.jpackage.main.Main.main(Main.java:52)
[2022-09-21T17:12:21.687Z] [17:09:29.268] Running dpkg
[2022-09-21T17:12:21.687Z] [17:09:29.282] Command [PID: 1511588]:
[2022-09-21T17:12:21.687Z]     dpkg -S /lib/x86_64-linux-gnu/libXext.so.6
[2022-09-21T17:12:21.687Z] [17:09:29.282] Output:
[2022-09-21T17:12:21.687Z]     dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libXext.so.6
[2022-09-21T17:12:21.687Z] [17:09:29.282] Returned: 1

**Comment by smlambert** [comment]
[deep history](https://trss.adoptium.net/deepHistory?testId=632b5f0493ac60470bc6acad)
