### ISSUE TITLE
jdk_net_0 BlockingSocketOps times out on ppc64 aix for Java 19

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3981]
[TRSS Test Output](https://trss.adoptium.net/output/test?id=632bf1b993ac60470bc854ff) - contains full thread dump

e.g.,

[2022-09-21T22:27:38.048Z] rerun:
[2022-09-21T22:27:38.048Z] cd /home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/scratch && \
[2022-09-21T22:27:38.048Z] DISPLAY=unix:0 \
[2022-09-21T22:27:38.048Z] HOME=/home/jenkins \
[2022-09-21T22:27:38.048Z] LANG=en_US \
[2022-09-21T22:27:38.048Z] PATH=/bin:/usr/bin:/usr/sbin \
[2022-09-21T22:27:38.048Z] TZ=CUT0 \
[2022-09-21T22:27:38.048Z]     /home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/bin/javac \
[2022-09-21T22:27:38.048Z]         -J-ea \
[2022-09-21T22:27:38.048Z]         -J-esa \
[2022-09-21T22:27:38.048Z]         -J-Xmx512m \
[2022-09-21T22:27:38.048Z]         -J-XX:-UseCompressedOops \
[2022-09-21T22:27:38.048Z]         -J-Djava.library.path=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
[2022-09-21T22:27:38.048Z]         -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
[2022-09-21T22:27:38.048Z]         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
[2022-09-21T22:27:38.048Z]         -J-Dtest.compiler.opts= \
[2022-09-21T22:27:38.048Z]         -J-Dtest.java.opts= \
[2022-09-21T22:27:38.048Z]         -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image \
[2022-09-21T22:27:38.048Z]         -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image \
[2022-09-21T22:27:38.048Z]         -J-Dtest.timeout.factor=8.0 \
[2022-09-21T22:27:38.048Z]         -J-Dtest.nativepath=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
[2022-09-21T22:27:38.048Z]         -J-Dtest.root=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk \
[2022-09-21T22:27:38.048Z]         -J-Dtest.name=java/net/vthread/BlockingSocketOps.java#id0 \
[2022-09-21T22:27:38.048Z]         -J-Dtest.file=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/vthread/BlockingSocketOps.java \
[2022-09-21T22:27:38.048Z]         -J-Dtest.src=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/vthread \
[2022-09-21T22:27:38.048Z]         -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/vthread:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/lib \
[2022-09-21T22:27:38.048Z]         -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/java/net/vthread/BlockingSocketOps_id0.d \
[2022-09-21T22:27:38.048Z]         -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/java/net/vthread/BlockingSocketOps_id0.d:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/test/lib \
[2022-09-21T22:27:38.048Z]         -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/java/net/vthread/BlockingSocketOps_id0.d:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/vthread:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/test/lib \
[2022-09-21T22:27:38.048Z]         -J-Dtest.enable.preview=true \
[2022-09-21T22:27:38.048Z]         -d /home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/java/net/vthread/BlockingSocketOps_id0.d \
[2022-09-21T22:27:38.048Z]         -sourcepath /home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/vthread:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/lib \
[2022-09-21T22:27:38.048Z]         -classpath /home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/vthread:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/java/net/vthread/BlockingSocketOps_id0.d:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1663787279976/jdk_net_1/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/jvmtest/openjdk/jtreg/lib/guice.jar \
[2022-09-21T22:27:38.048Z]         --enable-preview \
[2022-09-21T22:27:38.048Z]         --source=19 /home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/vthread/BlockingSocketOps.java
[2022-09-21T22:27:38.048Z] direct:
[2022-09-21T22:27:38.048Z] Note: /home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/aqa-tests/openjdk/openjdk-jdk/test/lib/jdk/test/lib/thread/VThreadRunner.java uses preview features of Java SE 19.
[2022-09-21T22:27:38.048Z] Note: Recompile with -Xlint:preview for details.
[2022-09-21T22:27:38.048Z] 
[2022-09-21T22:27:38.048Z] ACTION: testng -- Error. Program `/home/jenkins/workspace/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 2400000ms, elapsed time including timeout handling was 2400506ms).
[2022-09-21T22:27:38.048Z] REASON: User specified action: run testng/othervm/timeout=300 BlockingSocketOps 
[2022-09-21T22:27:38.048Z] TIME:   2400.524 seconds
[2022-09-21T22:27:38.048Z] messages:
[2022-09-21T22:27:38.048Z] command: testng BlockingSocketOps
[2022-09-21T22:27:38.048Z] reason: User specified action: run testng/othervm/timeout=300 BlockingSocketOps 
[2022-09-21T22:27:38.048Z] Mode: othervm [/othervm specified]
[2022-09-21T22:27:38.048Z] Timeout information:
[2022-09-21T22:27:38.048Z] Running jstack on process 20906344
[2022-09-21T22:27:38.048Z] 2022-09-21 22:38:41

**Comment by smlambert** [comment]
Looks like its vthread preview feature related 

Also from that jdk_net target see:

https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_0/25/testReport/java_net_vthread_HttpALot/java/HttpALot/

```
java.lang.UnsupportedOperationException: Unimplemented on AIX
	at java.base/sun.nio.ch.PollsetPoller.poll(PollsetPoller.java:60)
	at java.base/sun.nio.ch.Poller.poll(Poller.java:363)
	at java.base/sun.nio.ch.Poller.pollLoop(Poller.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
java.lang.UnsupportedOperationException: Unimplemented on AIX
	at java.base/sun.nio.ch.PollsetPoller.poll(PollsetPoller.java:60)
	at java.base/sun.nio.ch.Poller.poll(Poller.java:363)
	at java.base/sun.nio.ch.Poller.pollLoop(Poller.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
java.lang.UnsupportedOperationException: Unimplemented on AIX
	at java.base/sun.nio.ch.PollsetPoller.implRegister(PollsetPoller.java:48)
	at java.base/sun.nio.ch.Poller.updateLoop(Poller.java:289)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
```
Will presume since they are not implemented these need to be excluded for AIX.

**Comment by smlambert** [comment]
The action to take here is to exclude the java/net/vthread/HttpALot.java test case on AIX (and other platforms where it is not supported.

This can be done by adding a line into the ProblemList file, at the end of the jdk_net section:
https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk19.txt#L206

`java/net/vthread/HttpALot.java https://github.com/adoptium/aqa-tests/issues/4024 aix-all`

**Comment by lumuchris256** [comment]
hi @smlambert  i would want to take on this one

**Comment by smlambert** [comment]
Looking at the live test runs, there are 3 more testcases that should get excluded as part of this issue:
https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_0/25/testReport/

```
java/net/vthread/HttpALot.java https://github.com/adoptium/aqa-tests/issues/4024 aix-all
java/net/vthread/BlockingSocketOps.java https://github.com/adoptium/aqa-tests/issues/4024 aix-all
java/net/vthread/InterruptHttp.java https://github.com/adoptium/aqa-tests/issues/4024 aix-all
jdk/net/ExtendedSocketOption/DontFragmentTest.java.DontFragmentTest https://github.com/adoptium/aqa-tests/issues/4024 aix-all
java/nio/channels/vthread/BlockingChannelOps.java#id0 https://github.com/adoptium/aqa-tests/issues/4024 aix-all
```

**Comment by lumuchris256** [comment]
> Looking at the live test runs, there are 2 more testcases that should get excluded as part of this issue: https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_0/25/testReport/
> 
> ```
> java/net/vthread/HttpALot.java https://github.com/adoptium/aqa-tests/issues/4024 aix-all
> java/net/vthread/BlockingSocketOps.java https://github.com/adoptium/aqa-tests/issues/4024 aix-all
> java/net/vthread/InterruptHttp.java https://github.com/adoptium/aqa-tests/issues/4024 aix-all
> jdk/net/ExtendedSocketOption/DontFragmentTest.java.DontFragmentTest https://github.com/adoptium/aqa-tests/issues/4024 aix-all
> ```

i am going to take on this as well
