### ISSUE TITLE
testClassArrayType fails for Alpine Aarch64 on Java 19

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3984]
[TRSS Test Output](https://trss.adoptium.net/output/test?id=632b9c1693ac60470bc771bb)

Seems to be a recent failure.

[2022-09-21T13:34:09.013Z] FAILED: testClassArrayType
[2022-09-21T13:34:09.014Z] java.lang.UnsupportedOperationException: java.lang.IllegalArgumentException
[2022-09-21T13:34:09.014Z] 	at java.base/java.lang.Class.arrayType(Class.java:4508)
[2022-09-21T13:34:09.014Z] 	at org.openj9.test.java_lang.Test_Class.arrayTypeTestGeneral(Test_Class.java:166)
[2022-09-21T13:34:09.014Z] 	at org.openj9.test.java_lang.Test_Class.testClassArrayType(Test_Class.java:152)
[2022-09-21T13:34:09.014Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-09-21T13:34:09.014Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-09-21T13:34:09.014Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2022-09-21T13:34:09.014Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2022-09-21T13:34:09.014Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2022-09-21T13:34:09.014Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2022-09-21T13:34:09.014Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2022-09-21T13:34:09.014Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2022-09-21T13:34:09.014Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2022-09-21T13:34:09.014Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2022-09-21T13:34:09.014Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2022-09-21T13:34:09.014Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2022-09-21T13:34:09.014Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2022-09-21T13:34:09.014Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2022-09-21T13:34:09.014Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2022-09-21T13:34:09.014Z] Caused by: java.lang.IllegalArgumentException
[2022-09-21T13:34:09.014Z] 	at java.base/java.lang.reflect.Array.newArray(Native Method)
[2022-09-21T13:34:09.014Z] 	at java.base/java.lang.reflect.Array.newInstance(Array.java:78)
[2022-09-21T13:34:09.014Z] 	at java.base/java.lang.Class.arrayType(Class.java:4506)
[2022-09-21T13:34:09.014Z] 	... 24 more

**Comment by smlambert** [comment]
Interesting, an UnsupportedOperationException seen first on Sept 20th, passing in the Sept 14th run, someone needs to look at both the test material and product code and check what has changed in between.

**Test Info**
Test Name: Jep334Tests_0
Test Duration: 1 sec
Machine: test-docker-alpine314-aarch64-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=632b9c1693ac60470bc771bb


**Build Info**
Build Name: Test_openjdk19_hs_sanity.functional_aarch64_alpine-linux
Jenkins Build start time: Sep 21 2022, 09:29 am
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_sanity.functional_aarch64_alpine-linux/56/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=632b9b8d93ac60470bc77191


**Java Version**
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Temurin-19+36 (build 19+36)
OpenJDK 64-Bit Server VM Temurin-19+36 (build 19+36, mixed mode, sharing)


**This test has been failed 3 times since Sep 20 2022, 11:22 am**
**Java Version when the issue first seen**
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Temurin-19+36 (build 19+36)
OpenJDK 64-Bit Server VM Temurin-19+36 (build 19+36, mixed mode, sharing)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_sanity.functional_aarch64_alpine-linux/54/

The test failed on machine test-docker-alpine314-aarch64-1 2 times 
The test failed on machine test-docker-alpine313-aarch64-1 1 times 


[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=Jep334Tests_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_alpine-linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.4-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk19&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk19%2Fjdk19-alpine-linux-aarch64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-19%2B36_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=66&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
