### ISSUE TITLE
Test pipeline initial clone retry should have cleanWs added

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/aqa-tests#4056]
**Describe the bug**
When the initial clone in a test pipeline happens on a node, if the clone fails and we go into retry, subsequent clones will fail if the .git folder has been created.

**To Reproduce**
Kill a clone after it has started to force into retry loop.

**Expected behavior**
Clone passes on retry

**Screenshots**
In this example, the machine was out of space, so the initial clone failed. However, subsequent clones failed because of the .git dir.
```
00:00:21.483  Running on [paix913.rtp.raleigh.ibm.com](https://hyc-runtimes-jenkins.swg-devops.com/computer/paix913.rtp.raleigh.ibm.com/) in /home/jenkins/workspace/Test_openjdk17_j9_sanity.jck_ppc64_aix
[Pipeline] {
[Pipeline] timeout
00:00:21.503  Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
00:00:21.604  [WS-CLEANUP] Deleting project workspace...
00:00:21.605  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
00:00:21.634  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // timeout
[Pipeline] retry
[Pipeline] {
[Pipeline] checkout
00:00:21.708  The recommended git tool is: git
00:00:21.770  No credentials specified
00:00:21.800  Cloning the remote Git repository
00:00:21.898  ERROR: Error cloning remote repo 'origin'
00:00:21.898  hudson.plugins.git.GitException: Could not init /home/jenkins/workspace/Test_openjdk17_j9_sanity.jck_ppc64_aix/aqa-tests
00:00:21.898  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1043)
00:00:21.898  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:798)
00:00:21.899  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:158)
00:00:21.899  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:151)
00:00:21.899  	at app//hudson.remoting.UserRequest.perform(UserRequest.java:211)
00:00:21.899  	at app//hudson.remoting.UserRequest.perform(UserRequest.java:54)
00:00:21.899  	at app//hudson.remoting.Request$2.run(Request.java:376)
00:00:21.899  	at app//hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
00:00:21.899  	at java.base@11.0.16.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:00:21.899  	at java.base@11.0.16.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:00:21.899  	at java.base@11.0.16.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:00:21.899  	at java.base@11.0.16.1/java.lang.Thread.run(Thread.java:840)
00:00:21.899  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to paix913.rtp.raleigh.ibm.com
00:00:21.899  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
00:00:21.899  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
00:00:21.899  		at hudson.remoting.Channel.call(Channel.java:1000)
00:00:21.899  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
00:00:21.899  		at jdk.internal.reflect.GeneratedMethodAccessor935.invoke(Unknown Source)
00:00:21.899  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:21.899  		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:00:21.899  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:129)
00:00:21.899  		at com.sun.proxy.$Proxy125.execute(Unknown Source)
00:00:21.899  		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1226)
00:00:21.899  		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1308)
00:00:21.899  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
00:00:21.899  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
00:00:21.899  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
00:00:21.899  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
00:00:21.899  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
00:00:21.899  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:00:21.899  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:00:21.899  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:00:21.899  		at java.base/java.lang.Thread.run(Thread.java:829)
00:00:21.899  Caused by: hudson.plugins.git.GitException: Command "git init /home/jenkins/workspace/Test_openjdk17_j9_sanity.jck_ppc64_aix/aqa-tests" returned status code 128:
00:00:21.899  stdout: 
00:00:21.899  stderr: error: copy-fd: write returned: There is not enough space in the file system.
00:00:21.899  fatal: cannot copy '/opt/freeware/share/git-core/templates/description' to '/home/jenkins/workspace/Test_openjdk17_j9_sanity.jck_ppc64_aix/aqa-tests/.git/description': There is not enough space in the file system.
00:00:21.899  
00:00:21.899  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2675)
00:00:21.899  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2605)
00:00:21.899  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2601)
00:00:21.899  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1969)
00:00:21.899  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1041)
00:00:21.899  	... 11 more
[Pipeline] }
00:00:21.907  ERROR: Error cloning remote repo 'origin'
00:00:21.908  Retrying
[Pipeline] {
[Pipeline] sleep
00:00:21.954  Sleeping for 3 min 0 sec
00:00:21.849  Cloning repository https://github.com/adoptium/aqa-tests.git
00:00:21.850   > git init /home/jenkins/workspace/Test_openjdk17_j9_sanity.jck_ppc64_aix/aqa-tests # timeout=10
[Pipeline] checkout
00:03:21.993  The recommended git tool is: git
00:03:22.084  No credentials specified
00:03:22.102   > git rev-parse --resolve-git-dir /home/jenkins/workspace/Test_openjdk17_j9_sanity.jck_ppc64_aix/aqa-tests/.git # timeout=10
00:03:22.131  ERROR: Workspace has a .git repository, but it appears to be corrupt.
```

**Additional context**
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests#L280
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests#L303
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests#L313

**Comment by llxia** [comment]
I think we can move 
https://github.com/adoptium/aqa-tests/blob/29bead466eff2edb987a7bbf62ad28199b479fa5/buildenv/jenkins/openjdk_tests#L279-L281

inside of 2 `retry {}` and before the git clone :

https://github.com/adoptium/aqa-tests/blob/29bead466eff2edb987a7bbf62ad28199b479fa5/buildenv/jenkins/openjdk_tests#L303

https://github.com/adoptium/aqa-tests/blob/29bead466eff2edb987a7bbf62ad28199b479fa5/buildenv/jenkins/openjdk_tests#L316

**Comment by llxia** [comment]
@renfeiw could you take care of this? Thanks
