### ISSUE TITLE
CryptoTests_0 FAILED in x86-32_windows, x86-64_windows and arm_linux

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4336]
2 failures, 2 errors on Windows 32bit builds (and 2 failures on x86-64_windows see [Test_openjdk11_hs_extended.functional_x86-64_windows/330](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-64_windows/330/)
- [cryptotest/CryptoTest.java.CryptoTest](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-32_windows/323/testReport/junit/cryptotest_CryptoTest/java/CryptoTest/)
- [cryptotest/tests/ConfigurationTests.java.ConfigurationTests](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-32_windows/323/testReport/junit/cryptotest_tests_ConfigurationTests/java/ConfigurationTests/)
- [cryptotest/tests/KeyStoreTests.java.KeyStoreTests](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-32_windows/323/testReport/junit/cryptotest_tests_KeyStoreTests/java/KeyStoreTests/)
- [cryptotest/tests/SignatureTests.java.SignatureTests](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-32_windows/323/testReport/junit/cryptotest_tests_SignatureTests/java/SignatureTests/)
 
```
[2023-02-11T18:21:57.066Z] --------------------------------------------------
[2023-02-11T18:21:57.066Z] Test results: passed: 27; failed: 2; error: 2
[2023-02-11T18:21:57.066Z] Report written to E:\workspace\Test_openjdk11_hs_extended.functional_x86-32_windows\aqa-tests\TKG\output_16761382023597\CryptoTests_0\report\html\report.html
[2023-02-11T18:21:57.066Z] Results written to E:\workspace\Test_openjdk11_hs_extended.functional_x86-32_windows\aqa-tests\TKG\output_16761382023597\CryptoTests_0\work
[2023-02-11T18:21:57.066Z] Error: Some tests failed or other problems occurred.
[2023-02-11T18:21:57.066Z] -----------------------------------
[2023-02-11T18:21:57.066Z] CryptoTests_0_FAILED
[2023-02-11T18:21:57.066Z] -----------------------------------
```

2 errors on [arm_linux](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_arm_linux/275/)
- [cryptotest/CryptoTest.java.CryptoTest](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_arm_linux/275/testReport/junit/cryptotest_CryptoTest/java/CryptoTest/)
- [cryptotest/tests/SignatureTests.java.SignatureTests](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_arm_linux/275/testReport/junit/cryptotest_tests_SignatureTests/java/SignatureTests/)

**Test Info**
Test Name: CryptoTests_0
Test Duration: 24 min 35 sec
Machine: test-ibmcloud-win2012r2-x64-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=63e8120aed0b30773bfa2876

**Build Info**
Build Name: Test_openjdk11_hs_extended.functional_x86-32_windows
Jenkins Build start time: Feb 11 2023, 12:52 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-32_windows/323/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=63e8110aed0b30773bfa233f

**Java Version**
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.19+1 (build 11.0.18+1)
OpenJDK Client VM Temurin-11.0.19+1 (build 11.0.18+1, mixed mode)

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=CryptoTests_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-32_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x86-32-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=182&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Console:

```
[2023-02-11T18:08:57.373Z] STDOUT:
[2023-02-11T18:08:57.373Z] running: cryptotest.tests.ConfigurationTests
[2023-02-11T18:08:57.373Z] 0)	SUN: 	JavaLoginConfig~JavaLoginConfig	 (Configuration)
[2023-02-11T18:08:57.373Z] cryptotest.utils.AlgorithmRunException: java.io.IOException: The system cannot find the path specified
[2023-02-11T18:08:57.373Z] failed to use: JavaLoginConfig from SUN version 11
[2023-02-11T18:08:57.373Z] Failed
[2023-02-11T18:08:57.373Z] Total checks: 1, failed: 1
[2023-02-11T18:08:57.373Z] 1 Configuration failed
[2023-02-11T18:08:57.373Z] ** failed runs: 1 **
[2023-02-11T18:08:57.373Z] java.lang.Exception: 0)	SUN: 	JavaLoginConfig~JavaLoginConfig	 (Configuration)
[2023-02-11T18:08:57.373Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:83)
[2023-02-11T18:08:57.373Z] 	at cryptotest.tests.ConfigurationTests.main(ConfigurationTests.java:58)
[2023-02-11T18:08:57.373Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-02-11T18:08:57.373Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-02-11T18:08:57.373Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-11T18:08:57.374Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-02-11T18:08:57.374Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-02-11T18:08:57.374Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-02-11T18:08:57.374Z] Caused by: cryptotest.utils.AlgorithmRunException: java.io.IOException: The system cannot find the path specified
[2023-02-11T18:08:57.374Z] 	at cryptotest.tests.ConfigurationTests.checkAlgorithm(ConfigurationTests.java:86)
[2023-02-11T18:08:57.374Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
[2023-02-11T18:08:57.374Z] 	... 7 more
[2023-02-11T18:08:57.374Z] Caused by: java.io.IOException: The system cannot find the path specified
[2023-02-11T18:08:57.374Z] 	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
[2023-02-11T18:08:57.374Z] 	at java.base/java.io.File.createNewFile(File.java:1035)
[2023-02-11T18:08:57.374Z] 	at cryptotest.tests.ConfigurationTests.createConfigFile(ConfigurationTests.java:100)
[2023-02-11T18:08:57.374Z] 	at cryptotest.tests.ConfigurationTests.checkAlgorithm(ConfigurationTests.java:70)
[2023-02-11T18:08:57.374Z] 	... 8 more
[2023-02-11T18:08:57.374Z] ** failed inits: 0 **
[2023-02-11T18:08:57.374Z] ** error runs: 0 **
[2023-02-11T18:08:57.374Z] 
[2023-02-11T18:08:57.374Z] FAILED: cryptotest.tests.ConfigurationTests
[2023-02-11T18:08:57.374Z] STDERR:
[2023-02-11T18:08:57.374Z] java.lang.RuntimeException: cryptotest.tests.ConfigurationTests failed with explanantion of 1479 chars long
[2023-02-11T18:08:57.374Z] 	at cryptotest.utils.TestResult.assertItself(TestResult.java:31)
[2023-02-11T18:08:57.374Z] 	at cryptotest.tests.ConfigurationTests.main(ConfigurationTests.java:61)
[2023-02-11T18:08:57.374Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-02-11T18:08:57.374Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-02-11T18:08:57.374Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-11T18:08:57.374Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-02-11T18:08:57.374Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-02-11T18:08:57.374Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
...

[2023-02-11T18:09:34.632Z] 10)	SunMSCAPI: 	Windows-MY-LOCALMACHINE~Windows-MY-LOCALMACHINE	 (KeyStore)
[2023-02-11T18:09:34.632Z] cryptotest.utils.AlgorithmRunException: java.io.IOException: java.security.KeyStoreException: Access is denied.
[2023-02-11T18:09:34.632Z] 
[2023-02-11T18:09:34.632Z] failed to use: Windows-MY-LOCALMACHINE from SunMSCAPI version 11
[2023-02-11T18:09:34.632Z] Failed
[2023-02-11T18:09:34.632Z] 11)	SunMSCAPI: 	Windows-ROOT~Windows-ROOT	 (KeyStore)
[2023-02-11T18:09:34.632Z] Passed
[2023-02-11T18:09:34.632Z] Total checks: 12, failed: 2
[2023-02-11T18:09:34.632Z] 2 KeyStore failed
[2023-02-11T18:09:34.633Z] ** failed runs: 2 **
[2023-02-11T18:09:34.633Z] java.lang.Exception: 6)	SunMSCAPI: 	Windows-ROOT-LOCALMACHINE~Windows-ROOT-LOCALMACHINE	 (KeyStore)
[2023-02-11T18:09:34.633Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:83)
[2023-02-11T18:09:34.633Z] 	at cryptotest.tests.KeyStoreTests.main(KeyStoreTests.java:58)
[2023-02-11T18:09:34.633Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-02-11T18:09:34.633Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-02-11T18:09:34.633Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-11T18:09:34.633Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-02-11T18:09:34.633Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-02-11T18:09:34.633Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-02-11T18:09:34.633Z] Caused by: cryptotest.utils.AlgorithmRunException: java.io.IOException: java.security.KeyStoreException: Access is denied.

...

```

**Comment by zzambers** [comment]
I have created PR, which should fix ConfigurationTests on Windows:
https://github.com/rh-openjdk/CryptoTest/pull/32

**Comment by zzambers** [comment]
These PRs should fix remaining issues on Windows:
https://github.com/rh-openjdk/CryptoTest/pull/36
https://github.com/rh-openjdk/CryptoTest/pull/37

**Comment by smlambert** [comment]
thanks kindly @zzambers !

**Comment by zzambers** [comment]
I re-tested this:

x86-64_windows: OK
https://ci.adoptium.net/job/Grinder/6751/

arm_linux: OK
https://ci.adoptium.net/job/Grinder/6752/
test-sxa-armv7l-ubuntu2004-odroid-1 (machine where it timeouted): OK
https://ci.adoptium.net/job/Grinder/6753/

Seems like there are no more windows issues after Cryptotest fixes.
When it comes to problems on arm, these were timeouts (based on name I guess is one of these small computers - probably not very fast). But it passed now, I think this timeout increase helped here: https://github.com/adoptium/aqa-tests/pull/4339

I think this issue can be closed. (I cannot close it myself)

**Comment by smlambert** [comment]
I had assumed you already addressed these issues, thanks for confirming with Grinder @zzambers, closing this now.

**Comment by smlambert** [comment]
There is still a failure on 32bit windows ([deep history](https://trss.adoptium.net/deepHistory?testId=6438b75517052c67154bfd6e)).

**Comment by zzambers** [comment]
Problem is SignatureTests timeout (240s) on win32, with stacktrace such as (just to make sure, information is not lost):
```
[2023-04-12T02:36:48.369Z] "MainThread" #13 prio=5 os_prio=0 cpu=239796.88ms elapsed=240.22s tid=0x011b08b0 nid=0x2564 runnable  [0x13b1e000]
[2023-04-12T02:36:48.369Z]    java.lang.Thread.State: RUNNABLE
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.implMulAdd(java.base@17.0.7-beta/BigInteger.java:3201)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.mulAdd(java.base@17.0.7-beta/BigInteger.java:3171)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.montReduce(java.base@17.0.7-beta/BigInteger.java:3120)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.implMontgomerySquare(java.base@17.0.7-beta/BigInteger.java:2867)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.montgomerySquare(java.base@17.0.7-beta/BigInteger.java:2823)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.oddModPow(java.base@17.0.7-beta/BigInteger.java:3093)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.modPow(java.base@17.0.7-beta/BigInteger.java:2754)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.passesMillerRabin(java.base@17.0.7-beta/BigInteger.java:1122)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.primeToCertainty(java.base@17.0.7-beta/BigInteger.java:978)
[2023-04-12T02:36:48.369Z] 	at java.math.BitSieve.retrieve(java.base@17.0.7-beta/BitSieve.java:203)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.largePrime(java.base@17.0.7-beta/BigInteger.java:847)
[2023-04-12T02:36:48.369Z] 	at java.math.BigInteger.probablePrime(java.base@17.0.7-beta/BigInteger.java:785)
[2023-04-12T02:36:48.369Z] 	at sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(java.base@17.0.7-beta/RSAKeyPairGenerator.java:173)
[2023-04-12T02:36:48.369Z] 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(java.base@17.0.7-beta/KeyPairGenerator.java:727)
[2023-04-12T02:36:48.369Z] 	at java.security.KeyPairGenerator.genKeyPair(java.base@17.0.7-beta/KeyPairGenerator.java:495)
[2023-04-12T02:36:48.369Z] 	at cryptotest.utils.KeysNaiveGenerator.getRsaKeyPair(KeysNaiveGenerator.java:165)
[2023-04-12T02:36:48.369Z] 	at cryptotest.utils.KeysNaiveGenerator.getRsaPrivateKey(KeysNaiveGenerator.java:169)
[2023-04-12T02:36:48.369Z] 	at cryptotest.tests.SignatureTests.checkAlgorithm(SignatureTests.java:87)
[2023-04-12T02:36:48.369Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
[2023-04-12T02:36:48.369Z] 	at cryptotest.tests.SignatureTests.main(SignatureTests.java:70)
[2023-04-12T02:36:48.369Z] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.7-beta/Native Method)
[2023-04-12T02:36:48.369Z] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.7-beta/NativeMethodAccessorImpl.java:77)
[2023-04-12T02:36:48.369Z] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.7-beta/DelegatingMethodAccessorImpl.java:43)
[2023-04-12T02:36:48.369Z] 	at java.lang.reflect.Method.invoke(java.base@17.0.7-beta/Method.java:568)
[2023-04-12T02:36:48.369Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-04-12T02:36:48.369Z] 	at java.lang.Thread.run(java.base@17.0.7-beta/Thread.java:833)
```

See also:
https://github.com/eclipse-openj9/openj9/issues/16711

I went through several results, all timeout, while performing BigInteger arithmetic (so not on blocking method like e.g. reading from random). Probably BigInteger arithmetic is just slow on some platforms.. :/

**Comment by smlambert** [comment]
Will also exclude on Solaris platforms until they can be fixed there.  (See https://github.com/adoptium/aqa-tests/issues/4518#issuecomment-1516318179 and https://github.com/adoptium/aqa-tests/issues/4518#issuecomment-1516315745).

**Comment by zzambers** [comment]
I think reason of slowness on 32-bit Intel (and possibly other platforms) may be due to absence of intrinsics on these platforms.

Method from stacktrace and some other BigInteger methods are marked `@IntrinsicCandidate`:
https://github.com/openjdk/jdk/blob/f5a6b7f7c03c00c96d0055f9be31057675205e13/src/java.base/share/classes/java/math/BigInteger.java#L3318

but intrinsics seem to be only available for x86_64 (64-bit):
https://github.com/openjdk/jdk/blob/f5a6b7f7c03c00c96d0055f9be31057675205e13/src/hotspot/cpu/x86/macroAssembler_x86.cpp#LL7218C22-L7218C29
https://github.com/openjdk/jdk/blob/f5a6b7f7c03c00c96d0055f9be31057675205e13/src/hotspot/cpu/x86/macroAssembler_x86.hpp#L1863

which could explain this... (as platforms without intrinsics would fall back to java code, which is slower)

I have made PR to increase timeout for SignatureTests:
https://github.com/rh-openjdk/CryptoTest/pull/48

**Comment by smlambert** [comment]
On arm_linux appears that the error is intermittent, one of the 31 testcases are timing out:

From https://ci.adoptium.net/job/Test_openjdk20_hs_extended.functional_arm_linux/121/testReport/cryptotest_CryptoTest/java/CryptoTest/ 

```
[2023-07-16T00:45:37.558Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk20_hs_extended.functional_arm_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 1200000ms, elapsed time including timeout handling was 1200330ms).
[2023-07-16T00:45:37.558Z] --------------------------------------------------
[2023-07-16T00:45:37.558Z] Test results: passed: 31; error: 1
[2023-07-16T00:45:37.558Z] Report written to /home/jenkins/workspace/Test_openjdk20_hs_extended.functional_arm_linux/aqa-tests/TKG/output_16894653571077/CryptoTests_0/report/html/report.html
[2023-07-16T00:45:37.558Z] Results written to /home/jenkins/workspace/Test_openjdk20_hs_extended.functional_arm_linux/aqa-tests/TKG/output_16894653571077/CryptoTests_0/work
[2023-07-16T00:45:37.558Z] Error: Some tests failed or other problems occurred.
```

Deep history shows that it 'sometimes' passes:
<img width="758" alt="Screenshot 2023-07-17 at 8 28 25 AM" src="https://github.com/adoptium/aqa-tests/assets/2836948/52203861-0d8f-4926-9789-ff5bc9392db1">


Possible cause for intermittency is described in: https://github.com/eclipse-openj9/openj9/issues/16712#issuecomment-1431483878
