### ISSUE TITLE
java/foreign/TestLargeSegmentCopy.java failed on aix with jdk20

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4429]
java/foreign/TestLargeSegmentCopy.java failed on aix with jdk20. Test was added last December. https://github.com/openjdk/jdk20/blob/master/test/jdk/java/foreign/TestLargeSegmentCopy.java

```
01:14:56  test TestLargeSegmentCopy.testLargeSegmentCopy(): failure
01:14:56  java.lang.OutOfMemoryError: Unable to allocate 2147484504 bytes
01:14:56  	at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unsafe.java:632)
01:14:56  	at java.base/jdk.internal.foreign.NativeMemorySegmentImpl.makeNativeSegment(NativeMemorySegmentImpl.java:116)
01:14:56  	at java.base/java.lang.foreign.MemorySegment.allocateNative(MemorySegment.java:1251)
01:14:56  	at TestLargeSegmentCopy.testLargeSegmentCopy(TestLargeSegmentCopy.java:49)
01:14:56  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
01:14:56  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

Suspect doesn't work AIX as segment is too large and out of memory.

**Comment by sophia-guo** [comment]
javax/management/mxbean/ThreadStartTest.java.
https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_0/25/
