### ISSUE TITLE
StringIndexOutOfBoundsException on AIX GrinderLink generation

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#4448]
See: https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_ppc64_aix/20/console
Suspect PR https://github.com/adoptium/aqa-tests/commit/a3a94ba9dfdbe8ad4eedefbb756faed7ef559596 may have trouble on AIX ?
```
20:04:28  TAP Reports Processing: START
20:04:28  Looking for TAP results report in workspace using pattern: Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_0/22/**/*.tap
20:04:28  Saving reports...
20:04:29  Processing '/home/jenkins/.jenkins/jobs/Test_openjdk20_hs_extended.openjdk_ppc64_aix/builds/20/tap-master-files/Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_0/22/aqa-tests/TKG/output_16791318333494/Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_0.tap'
20:04:29  Parsing TAP test result [/home/jenkins/.jenkins/jobs/Test_openjdk20_hs_extended.openjdk_ppc64_aix/builds/20/tap-master-files/Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_0/22/aqa-tests/TKG/output_16791318333494/Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_0.tap].
20:04:29  There are failed test cases. Marking build as UNSTABLE
20:04:29  TAP Reports Processing: FINISH
[Pipeline] echo
20:04:29  Saving Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_0/22/**/*.tap file on jenkins.
[Pipeline] archiveArtifacts
20:04:29  Archiving artifacts
20:04:29  Recording fingerprints
[Pipeline] findFiles
[Pipeline] echo
20:04:30  Tap file found: Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_1/17/aqa-tests/TKG/output_16791305624590/Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_1.tap...
[Pipeline] readFile
[Pipeline] cleanWs
20:04:31  [WS-CLEANUP] Deleting project workspace...
20:04:31  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
20:04:31  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
java.lang.StringIndexOutOfBoundsException: begin -1, end 67, length 67
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
	at java.base/java.lang.String.substring(String.java:2705)
	at java.base/java.lang.String.substring(String.java:2678)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor10087.invoke(Unknown Source)
```

**Comment by andrew-m-leonard** [comment]
@sophia-guo fyi

**Comment by sophia-guo** [comment]
https://github.com/adoptium/TKG/pull/423

**Comment by sophia-guo** [comment]
Fix and close it.
