### ISSUE TITLE
extended.openjdk timeout on node test-marist-sles15-s390x-2

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#4505]
Node [test-marist-sles15-s390x-2](https://ci.adoptium.net/computer/test-marist-sles15-s390x-2) is timing out after 15hours for extended.openjdk. The reason being due to testcase failures which timeout after 16mins each, thus extending the job...
See: https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0/82/console
```
23:57:03  Timeout refired 960 times
23:57:03  STDERR:
23:57:03  Unexpected exceptions: java.net.NoRouteToHostException: No route to host
23:57:03  java.net.NoRouteToHostException: No route to host
23:57:03  	at java.base/sun.nio.ch.Net.connect0(Native Method)
23:57:03  	at java.base/sun.nio.ch.Net.connect(Net.java:579)
23:57:03  	at java.base/sun.nio.ch.Net.connect(Net.java:568)
23:57:03  	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
23:57:03  	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
23:57:03  	at java.base/java.net.Socket.connect(Socket.java:633)
23:57:03  	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
23:57:03  	at java.base/sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:163)
23:57:03  	at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
23:57:03  	at GetPeerHostClient.<init>(GetPeerHostClient.java:46)
23:57:03  	at GetPeerHost.main(GetPeerHost.java:47)
23:57:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:57:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
23:57:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:57:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
23:57:03  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:57:03  	at java.base/java.lang.Thread.run(Thread.java:833)
23:57:03  Unexpected exceptions: java.lang.NullPointerException: Cannot invoke "javax.net.ssl.SSLSocket.startHandshake()" because "this.s" is null
23:57:03  java.lang.NullPointerException: Cannot invoke "javax.net.ssl.SSLSocket.startHandshake()" because "this.s" is null
23:57:03  	at GetPeerHostClient.run(GetPeerHostClient.java:61)
```

I have disconnect node test-marist-sles15-s390x-2
@Haroon-Khel fyi

**Comment by smlambert** [comment]
Pretty sure this issue is a dup of an issue opened in the infrastructure repo (where it should be transferred if it is not already there).
