### ISSUE TITLE
JavaTestRunner does not have enough heap to always process results

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#4534]
jdk17 Win32 jck-compiler-lang-ANNOT_0 runs out of heap space when JavaTestRunner processes the result summary, due to the size of the group:
```
22:44:59  Test results: passed: 6,617
22:44:59  
22:44:59  Results written to C:\Users\jenkins\workspace\Test_openjdk17_hs_extended.jck_x86-32_windows\aqa-tests\TKG\output_16824520094147\jck-compiler-lang-ANNOT_0\workdir
22:44:59  Report written to C:\Users\jenkins\workspace\Test_openjdk17_hs_extended.jck_x86-32_windows\aqa-tests\TKG\output_16824520094147\jck-compiler-lang-ANNOT_0\report
22:45:06  java.lang.OutOfMemoryError: Java heap space
22:45:06  	at java.xml/com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl.getNodeObject(DeferredDocumentImpl.java:942)
22:45:06  	at java.xml/com.sun.org.apache.xerces.internal.dom.DeferredElementImpl.synchronizeData(DeferredElementImpl.java:122)
22:45:06  	at java.xml/com.sun.org.apache.xerces.internal.dom.ElementImpl.getTagName(ElementImpl.java:332)
22:45:06  	at java.xml/com.sun.org.apache.xerces.internal.dom.DeepNodeListImpl.nextMatchingElementAfter(DeepNodeListImpl.java:198)
22:45:06  	at java.xml/com.sun.org.apache.xerces.internal.dom.DeepNodeListImpl.item(DeepNodeListImpl.java:146)
22:45:06  	at java.xml/com.sun.org.apache.xerces.internal.dom.DeepNodeListImpl.getLength(DeepNodeListImpl.java:116)
22:45:06  	at JavaTestRunner.generateSummary(JavaTestRunner.java:1099)
22:45:06  	at JavaTestRunner.main(JavaTestRunner.java:184)
```

**Comment by smlambert** [comment]
Tangentially related, we are looking to move away from JavaTestRunner and towards calling javatest executable more directly (see related: https://github.com/adoptium/aqa-tests/pull/4512).

**Comment by adamfarley** [comment]
[Here's a run](https://ci.eclipse.org/temurin-compliance/view/Win32/job/Test_openjdk17_hs_extended.jck_x86-32_windows/59/console) without the heap increase in the test itself, helping to isolate the heap increase for JavaTestRunner as the workaround that solved this.

**Comment by sophia-guo** [comment]
Win 32 is not supported any more. Close this.
