### ISSUE TITLE
OpenJ9 OpenJDK testing should include a -Xgcpolicy:balanced variation

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#4573]
In order to get more testing with -Xgcpolicy:balanced, a new openjdk target jdk_lang_j9 was added with variation Mode501. This uncovered some problems. Really we should add this variation to all openjdk targets. Ideally this should be done without having to create a j9 variation of each one. I'm told TKG needs to support this, so it knows -Xgcpolicy:balanced /. Mode501 is only applicable to OpenJ9 and an ignored variation for Hotspot.

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
[JDK11 xlinux](https://hyc-runtimes-jenkins.swg-devops.com/job/AQA_Test_Pipeline/489/) ==> running. Will update when the testing is done

**Comment by llxia** [comment]
[JDK11/17/21 aix](https://hyc-runtimes-jenkins.swg-devops.com/job/AQA_Test_Pipeline/490/) ==> running. Will update when the testing is done

**Comment by llxia** [comment]
`jdk_util_1` failure on [AIX](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_testList_0/152/):
```
04:55:41.715  STDOUT:
04:55:41.715  Compiling tz files!
04:55:41.715  testing!
04:55:41.715  OLD.getZoneInfoOld()[1]=462
04:55:41.715  OLD.getZoneInfoOld()[2]=350
04:55:41.715  OLD.getZoneInfoOld()[3]=230
04:55:41.715  OLD.getAvailableIDs()=1085, total=631
04:55:41.715  OLD.getAliasTable()=680, total=267
04:55:41.715  OLD.TotalTZ()=46 (ms)
04:55:41.715  NEW.getTimeZone()[1]=1161
04:55:41.715  NEW.getTimeZone()[2]=3
04:55:41.715  NEW.getTimeZone()[3]=948
04:55:41.715  NEW.getAvailableIDs()=25, total=631
04:55:41.715  NEW.getAliasTable()=27, total=267
04:55:41.715  NEW.TotalTZ()=195 (ms)
04:55:41.715  STDERR:
04:55:41.715  javazic: warning: found last rules for Morocco inconsistent.
04:55:41.715  javazic: warning: found last rules for Morocco inconsistent.
04:55:41.715  javazic: warning: found last rules for Eire inconsistent.
04:55:41.715  java.lang.RuntimeException: ZoneInfoOldMapping ZoneInfoMappings either doesn't exist or doesn't have data
04:55:41.715  	at ZoneInfoFile.getZoneInfoOldMappings(ZoneInfoFile.java:995)
04:55:41.715  	at ZoneInfoFile.getZoneIDs(ZoneInfoFile.java:737)
04:55:41.715  	at ZoneInfoOld.getAvailableIDs(ZoneInfoOld.java:606)
04:55:41.715  	at TestZoneInfo310.main(TestZoneInfo310.java:222)
04:55:41.715  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
04:55:41.715  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
04:55:41.715  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
04:55:41.715  	at java.base/java.lang.Thread.run(Thread.java:1595)
04:55:41.715  
04:55:41.715  JavaTest Message: Test threw exception: java.lang.RuntimeException
04:55:41.715  JavaTest Message: shutting down test
04:55:41.715  
04:55:41.715  
04:55:41.715  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: ZoneInfoOldMapping ZoneInfoMappings either doesn't exist or doesn't have data
```

**Comment by llxia** [comment]
without -Xgcpolicy:balanced:
- JDK11 xlinux: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39985/
- JDK21 AIX: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39986/

**Comment by pshipton** [comment]
Both ginders passed, so the failures with balanced look like real issues.

**Comment by llxia** [comment]
Issue opened:
- [jdk_util_1 sun/util/calendar/zi/TestZoneInfo310.java.TestZoneInfo310 RuntimeException on AIX with -Xgcpolicy:balanced](https://github.com/adoptium/aqa-tests/issues/5259#top)
- [jdk_util_1 java/util/concurrent/tck/JSR166TestCase.java#default.JSR166TestCase_default java.lang.Exception on JDK11 xlinux with -Xgcpolicy:balanced](https://github.com/adoptium/aqa-tests/issues/5260#top)

**Comment by gita-omr** [comment]
> @gita-omr @r30shah The above [jdk_vector_xxx tests](https://github.com/adoptium/aqa-tests/issues/4573#issuecomment-2067507293) failed due to `#VECTOR API` missing from *.jtr file. Please take a look to see if there is any real issue. Note: all tests are running with `-Xgcpolicy:balanced`

Just realized: it's most likely due to the `arraylets` used by balanced GC. We cannot vectorize access to such arrays. And we do have an explicit check for that: https://github.com/eclipse-openj9/openj9/blob/dba9d932e21c71dac4b2bd22846a712cbbeb0217/runtime/compiler/optimizer/VectorAPIExpansion.cpp#L51
