### ISSUE TITLE
NoAddresses.java in jdk_security4_1 FAILED in Test_openjdk20_hs_sanity.openjdk_ppc64_aix with UnknownHostException

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4673]
sun/security/krb5/auto/NoAddresses.java appears to fail across all available AIX machines:

```
java.net.UnknownHostException: adopt06: adopt06: Hostname and service name not provided or found
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1791)
	at NoAddresses.main(NoAddresses.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.net.UnknownHostException: adopt06: Hostname and service name not provided or found
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
	at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1061)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1683)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1004)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1673)
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1786)
	... 5 more

JavaTest Message: Test threw exception: java.net.UnknownHostException: adopt06: adopt06: Hostname and service name not provided or found
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.net.UnknownHostException: adopt06: adopt06: Hostname and service name not provided or found
    
```

**Test Info**
Test Name: jdk_security4_1
Test Duration: 13 min 8 sec
Machine: test-osuosl-aix72-ppc64-6
TRSS link for the test output: https://trss.adoptium.net/output/test?id=64b3f9a817052c671580a5fe

**Build Info**
Build Name: Test_openjdk20_hs_sanity.openjdk_ppc64_aix
Jenkins Build start time: Jul 15 2023, 09:08 pm
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk20_hs_sanity.openjdk_ppc64_aix/110/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=64b3f8a617052c671580a04d

**Java Version**
openjdk version "20.0.1-beta" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9-202307152344 (build 20.0.1-beta+9-202307152344)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9-202307152344 (build 20.0.1-beta+9-202307152344, mixed mode)

**This test has been failed 17 times since Jun 10 2023, 08:34 pm**
**Java Version when the issue first seen**
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9 (build 20.0.1+9)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9 (build 20.0.1+9, mixed mode)
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk20_hs_sanity.openjdk_ppc64_aix/94/

The test failed on machine test-osuosl-aix72-ppc64-6 2 times 
The test failed on machine test-osuosl-aix72-ppc64-3 3 times 
The test failed on machine test-osuosl-aix72-ppc64-5 4 times 
The test failed on machine test-osuosl-aix72-ppc64-4 2 times 
The test failed on machine test-osuosl-aix72-ppc64-1 1 times 
The test failed on machine test-osuosl-aix72-ppc64-2 4 times 
The test failed on machine build-osuosl-aix72-ppc64-2 1 times 

[Rerun in Grinder](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security4_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=20&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-aix-ppc64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=sw.os.aix.7_2&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=41&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by smlambert** [comment]
Transferring this issue to infrastructure repository.

It continues to be an issue seen on certain machines, including [test-osuosl-aix72-ppc64-5](https://ci.adoptium.net/computer/test-osuosl-aix72-ppc64-5), as seen in https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_ppc64_aix_testList_2/7/

```
04:05:27  STDERR:
04:05:27  java.net.UnknownHostException: adopt05: adopt05: Hostname and service name not provided or found
04:05:27  	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1936)
04:05:27  	at jdk.test.lib.Utils.getHostname(Utils.java:450)
04:05:27  	at JstatdTest.getDestination(JstatdTest.java:111)
04:05:27  	at JstatdTest.runJps(JstatdTest.java:132)
04:05:27  	at JstatdTest.runToolsAndVerify(JstatdTest.java:209)
04:05:27  	at JstatdTest.runTest(JstatdTest.java:346)
04:05:27  	at JstatdTest.doTest(JstatdTest.java:314)
04:05:27  	at TestJstatdPortAndServer.main(TestJstatdPortAndServer.java:40)
04:05:27  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
04:05:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
04:05:27  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
04:05:27  	at java.base/java.lang.Thread.run(Thread.java:1583)
```
