### ISSUE TITLE
test-macstadium-macos11-arm64-1 and -2 randomly go offline in Jenkins

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#4759]
Happens more often with test-macstadium-macos11-arm64-2. 

```
	at hudson.node_monitors.AbstractNodeMonitorDescriptor$Record.run(AbstractNodeMonitorDescriptor.java:305)
ERROR: Failed to monitor for JVM Version
java.util.concurrent.TimeoutException
	at hudson.remoting.Request$1.get(Request.java:322)
	at hudson.remoting.Request$1.get(Request.java:240)
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:66)
	at hudson.node_monitors.AbstractAsyncNodeMonitorDescriptor.monitorDetailed(AbstractAsyncNodeMonitorDescriptor.java:112)
	at hudson.node_monitors.AbstractAsyncNodeMonitorDescriptor.monitor(AbstractAsyncNodeMonitorDescriptor.java:76)
	at hudson.node_monitors.AbstractNodeMonitorDescriptor$Record.run(AbstractNodeMonitorDescriptor.java:305)
onitorDescriptor.java:76)
	at hudson.node_monitors.AbstractNodeMonitorDescriptor$Record.run(AbstractNodeMonitorDescriptor.java:305)
Sep 15, 2023 6:23:55 AM hudson.slaves.ChannelPinger$1 onDead
INFO: Ping failed. Terminating the channel channel.
java.util.concurrent.TimeoutException: Ping started at 1694783994970 hasn't completed by 1694784234975
	at hudson.remoting.PingThread.ping(PingThread.java:132)
	at hudson.remoting.PingThread.run(PingThread.java:88)

Sep 15, 2023 6:24:39 AM hudson.remoting.Request$2 run
INFO: Failed to send back a reply to the request UserRequest:hudson.FilePath$IsDirectory@e245c1a: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@1ae369b7:channel": channel is already closed
```
And then when trying to launch the node I will sometimes see this
```
The Agent is connected, disconnect it before to try to connect it again.
```

[-2](https://ci.adoptium.net/computer/test-macstadium-macos11-arm64-2/) is currently down at the moment. I can't ssh into it nor is it pingable

**Comment by Haroon-Khel** [comment]
Thought I was making this in the infra repo 😅 . Moved to https://github.com/adoptium/infrastructure/issues/3188
