### ISSUE TITLE
Jan CPU Dry-run Triage - Temurin JDK17

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4960]
#### Release Summary Report for release-openjdk17-pipeline 
**Report generated at:** Fri, 12 Jan 2024 13:02:57 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=65a000d596a988006d3c83bd&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=65a000d596a988006d3c83bd) 
Jenkins Build URL https://ci.adoptium.net/job/build-scripts/job/release-openjdk17-pipeline/50/ 
Started by upstream project "build-scripts/utils/releaseTrigger_jdk17u" build number 3634 at 1/11/2024, 9:48:57 AM 

---

✔️ results in these Tables means the activity has successfully completed.
⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
⛔ means there is no build planned for that version/platform combination.
⏸️ means activity not yet started.

| Platforms | Details | Status |
| --- | --- | --- |
| aarch64_linux  | [comment]() |  |
|  aarch64_mac | [comment]() |   |
| arm_linux  | [comment]() |   |
| ppc64_aix  | [comment]()|  |
| ppc64le_linux |[comment]()  |  |
|  s390x_linux | [comment]()|  |
| x86-32_windows  | [comment]()|  |
| x86-64_alpine-linux  |  [comment]()|  |
| x86-64_linux  |  [comment]()|  |
| x86-64_mac  |  [comment]()|  |
|  x86-64_windows |  [comment]()|  |

**Comment by sophia-guo** [comment]
aarch64_linux

extended.openjdk

jdk_security_infra -- excluded

sanity.system - rerun passed on same machine https://ci.adoptium.net/job/Test_openjdk17_hs_sanity.system_aarch64_linux_rerun/1/

**Comment by sophia-guo** [comment]
arm-linux
jdk_security_infra -- excluded

java/io/File/GetXSpace.java - rerun failed too. rerun on the same machine [test-docker-ubuntu2004-armv7l-2](https://ci.adoptium.net/computer/test-docker-ubuntu2004-armv7l-2)

```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by GetXSpace (file:/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_1/aqa-tests/TKG/output_17049888499942/jdk_io_2/work/classes/2/java/io/File/GetXSpace.d/)
WARNING: Please consider reporting this to the maintainers of GetXSpace
WARNING: System::setSecurityManager will be removed in a future release
FAILED: '/ total space': 934951190528 != 2943287296
FAILED: '/': 1360789504 ?? 65785298944
FAILED: '/ size': 934951190528 > 2943287296
FAILED: '/ total space': 934951190528 != 2943287296
FAILED: '/ usable space': 65785298944 > 2943287296
Warning: us > s.free()
FAILED: '/ usable vs. free space': 65785298944 > 1636368384
FAILED: '/ total space': 934951190528 != 2943287296
FAILED: '/': 1360523264 ?? 65785032704
FAILED: '/ size': 934951190528 > 2943287296
FAILED: '/ total space': 934951190528 != 2943287296
FAILED: '/ usable space': 65785032704 > 2943287296
Warning: us > s.free()
FAILED: '/ usable vs. free space': 65785032704 > 1636102144
30 tests: 12 failure(s); first: java.lang.RuntimeException: '/ total space': 934951190528 != 2943287296
FAILED: '/ total space': 934951190528 != 2943287296
FAILED: '/': 1360515072 ?? 65785024512
FAILED: '/ size': 934951190528 > 2943287296
FAILED: '/ total space': 934951190528 != 2943287296
FAILED: '/ usable space': 65785024512 > 2943287296
Warning: us > s.free()
FAILED: '/ usable vs. free space': 65785024512 > 1636093952
6 tests: 6 failure(s); first: java.lang.RuntimeException: '/ total space': 934951190528 != 2943287296
java.lang.RuntimeException: 2 test(s) failed
	at GetXSpace.main(GetXSpace.java:485)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:840)

JavaTest Message: Test threw exception: java.lang.RuntimeException: 2 test(s) failed
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: 2 test(s) failed
    
```

 [jdk_io_2](https://trss.adoptium.net/output/test?id=65a0422596a988006d418276) => [deep history 13/22 passed](https://trss.adoptium.net/deepHistory?testId=65a0422596a988006d418276) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=65a03f3396a988006d41531e&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_1&testId=65a0422596a988006d418276&testName=jdk_io_2)

Deep history shows failed on different machines since Nov 5th, 2023, after the last release.

**Comment by sophia-guo** [comment]
x86-64_windows

**Comment by sophia-guo** [comment]
x86-64_alpine-linux

**Comment by sophia-guo** [comment]
ppc64le

[Test_openjdk17_hs_extended.openjdk_ppc64le_linux](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux/149/) ⚠️ UNSTABLE ⚠️

[Test_openjdk17_hs_extended.openjdk_ppc64le_linux_rerun](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_rerun/1/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_security_infra_0,jdk_security_infra_1,jdk_tools_0,jdk_security_infra_0,jdk_security_infra_1,jdk_tools_0,jdk_security_infra_0,jdk_security_infra_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=1&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=3&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.0-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&DOCKER_REGISTRY_URL=&ITERATIONS=3&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk17u%2Fjdk17u-release-linux-ppc64le-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-17.0.10%2B6_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=15&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

java -version
Failures in the rerun test build
[jdk_security_infra_0](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e041c)
[jdk_security_infra_1](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e041d)
[jdk_tools_0](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e0420)
[jdk_security_infra_0](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e0422)
[jdk_security_infra_1](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e0423)
[jdk_tools_0](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e0426)
[jdk_security_infra_0](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e0428)
[jdk_security_infra_1](https://trss.adoptium.net/output/test?id=65a0d4f596a988006d4e0429)

[Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1/131/) ⚠️ UNSTABLE ⚠️
[jdk_management_0](https://trss.adoptium.net/output/test?id=65a0d4fe96a988006d4e0449) => [deep history 10/19 passed](https://trss.adoptium.net/deepHistory?testId=65a0d4fe96a988006d4e0449) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=65a0d26b96a988006d4dc22e&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1&testId=65a0d4fe96a988006d4e0449&testName=jdk_management_0)
[jdk_tools_0](https://trss.adoptium.net/output/test?id=65a0d4fe96a988006d4e044a) => [deep history 11/23 passed](https://trss.adoptium.net/deepHistory?testId=65a0d4fe96a988006d4e044a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=65a0d26b96a988006d4dc22e&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1&testId=65a0d4fe96a988006d4e044a&testName=jdk_tools_0)
[jdk_jfr_0](https://trss.adoptium.net/output/test?id=65a0d4fe96a988006d4e044b) => [deep history 10/19 passed](https://trss.adoptium.net/deepHistory?testId=65a0d4fe96a988006d4e044b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=65a0d26b96a988006d4dc22e&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1&testId=65a0d4fe96a988006d4e044b&testName=jdk_jfr_0)
[jdk_security_infra_0](https://trss.adoptium.net/output/test?id=65a0d4fe96a988006d4e044e) => [deep history 9/24 passed](https://trss.adoptium.net/deepHistory?testId=65a0d4fe96a988006d4e044e) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=65a0d26b96a988006d4dc22e&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1&testId=65a0d4fe96a988006d4e044e&testName=jdk_security_infra_0)

[Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_2](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_2/131/) ⚠️ UNSTABLE ⚠️
[jdk_nio_1](https://trss.adoptium.net/output/test?id=65a0d50f96a988006d4e04d8) => [deep history 15/20 passed](https://trss.adoptium.net/deepHistory?testId=65a0d50f96a988006d4e04d8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=65a0d26b96a988006d4dc232&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_2&testId=65a0d50f96a988006d4e04d8&testName=jdk_nio_1)
[jdk_security_infra_1](https://trss.adoptium.net/output/test?id=65a0d50f96a988006d4e04f5) => [deep history 6/18 passed](https://trss.adoptium.net/deepHistory?testId=65a0d50f96a988006d4e04f5) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=65a0d26b96a988006d4dc232&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_2&testId=65a0d50f96a988006d4e04f5&testName=jdk_security_infra_1)

Rerun failed
[tools/jpackage/share/MultiNameTwoPhaseTest.java.MultiNameTwoPhaseTest](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_rerun/1/testReport/junit/tools_jpackage_share_MultiNameTwoPhaseTest/java/MultiNameTwoPhaseTest/)
[tools/jpackage/share/RuntimePackageTest.java#id0.RuntimePackageTest_id0](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_rerun/1/testReport/junit/tools_jpackage_share_RuntimePackageTest/java_id0/RuntimePackageTest_id0/)

**Comment by smlambert** [comment]
x86-64_windows

**Comment by smlambert** [comment]
x86-64_alpine-linux

Many targets failing, Deep History shows many pass when run on test-docker-alpine317-x64-1, so run all failing testcases on test-docker-alpine317-x64-1 in https://ci.adoptium.net/job/Grinder/8465

**Comment by smlambert** [comment]
x86-32_windows

7 testcases fail:
[sun/tools/jhsdb/JShellHeapDumpTest.java.JShellHeapDumpTest](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/124/testReport/junit/sun_tools_jhsdb_JShellHeapDumpTest/java/JShellHeapDumpTest/)

[tools/jpackage/windows/Win8282351Test.java.Win8282351Test](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/124/testReport/junit/tools_jpackage_windows_Win8282351Test/java/Win8282351Test/) - infra https://github.com/adoptium/infrastructure/issues/2885

[compiler/loopopts/TestBackedgeLoadArrayFillMain.java.TestBackedgeLoadArrayFillMain](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/124/testReport/junit/compiler_loopopts_TestBackedgeLoadArrayFillMain/java/TestBackedgeLoadArrayFillMain/)

[compiler/loopopts/TestInfiniteLoopWithUnmergedBackedgesMain.java.TestInfiniteLoopWithUnmergedBackedgesMain](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/124/testReport/junit/compiler_loopopts_TestInfiniteLoopWithUnmergedBackedgesMain/java/TestInfiniteLoopWithUnmergedBackedgesMain/)

[compiler/loopopts/TestRemoveEmptyCountedLoop.java.TestRemoveEmptyCountedLoop](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/124/testReport/junit/compiler_loopopts_TestRemoveEmptyCountedLoop/java/TestRemoveEmptyCountedLoop/)

[compiler/rangechecks/TestRangeCheckCmpUOverflowVsSub.java.TestRangeCheckCmpUOverflowVsSub](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/124/testReport/junit/compiler_rangechecks_TestRangeCheckCmpUOverflowVsSub/java/TestRangeCheckCmpUOverflowVsSub/)

[compiler/splitif/TestCrashAtIGVNSplitIfSubType.java.TestCrashAtIGVNSplitIfSubType](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/124/testReport/junit/compiler_splitif_TestCrashAtIGVNSplitIfSubType/java/TestCrashAtIGVNSplitIfSubType/)

**Comment by smlambert** [comment]
ppc64_aix

jdk_imageio
TEST: javax/imageio/plugins/shared/ImageWriterCompressionTest.java
Test results: passed: 199; failed: 1

jdk_net_1
TEST: java/net/httpclient/StreamingBody.java
Test results: passed: 796; failed: 1

jdk_beans_0
TEST: java/beans/PropertyChangeSupport/Test4682386.java
TEST: java/beans/PropertyEditor/TestFontClassJava.java
TEST: java/beans/PropertyEditor/TestFontClassValue.java
TEST: java/beans/XMLEncoder/Test4631471.java
TEST: java/beans/XMLEncoder/Test4903007.java
Test results: passed: 344; failed: 5

jdk_jmx_0
TEST: javax/management/mxbean/ThreadStartTest.java
Test results: passed: 247; failed: 1

jdk_security_infra - excluded already

[renaissance-philosophers_0](https://trss.adoptium.net/output/test?id=65a1bc4c96a988006d67008b) - appears to fail intermittently with 
```
thread 11915 also had an error]
[thread 9088 also had an error]
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 336 bytes for AllocateHeap
# An error report file with more information is saved as:
# /tmp/hs_err_pid16974318.log
```
rerun in https://ci.adoptium.net/job/Grinder/8466

MauveSingleThrdLoad_HS_5m
MauveSingleInvocLoad_HS_5m
```
[2024-01-11T22:13:34.609Z] LT    Failure num.  = 1
[2024-01-11T22:13:34.609Z] LT    Test number   = 3560
[2024-01-11T22:13:34.609Z] LT    Test details  = 'Mauve[gnu.testlet.java.net.InetSocketAddress.InetSocketAddressTest]'
[2024-01-11T22:13:34.609Z] LT    Suite number  = 0
[2024-01-11T22:13:34.609Z] LT    Thread number = 0
[2024-01-11T22:13:34.609Z] LT  >>> Captured test output >>>
[2024-01-11T22:13:34.609Z] LT  FAIL: gnu.testlet.java.net.InetSocketAddress.InetSocketAddressTest: Error : test_Constructors failed - 0 Should not throw Exception here (number 0)
[2024-01-11T22:13:34.609Z] LT  PASS: gnu.testlet.java.net.InetSocketAddress.InetSocketAddressTest: Error : test_Constructors failed - 1 No wildcard address returned (number 0)
[2024-01-11T22:13:34.609Z] LT  FAIL: gnu.testlet.java.net.InetSocketAddress.InetSocketAddressTest: Error : test_Constructors failed - 2 Unexpected Exception here (number 0)
[2024-01-11T22:13:34.609Z] LT  FAIL: gnu.testlet.java.net.InetSocketAddress.InetSocketAddressTest: Error : test_Constructors failed - 3 Unexpected Exception here (number 0)
```

**Comment by smlambert** [comment]
s390x_linux

**Comment by smlambert** [comment]
x86-64_mac

**Comment by smlambert** [comment]
As ready as we can be for Jan CPU
