### ISSUE TITLE
jdk_security1_2 / AKISerialNumber testcase FAILED in Test_openjdk8_hs_sanity.openjdk_arm_linux

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5097]
[AKISerialNumber](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/648/testReport/junit/java_security_cert_CertPathBuilder_akiExt_AKISerialNumber/java/AKISerialNumber/) testcase fails with sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.  Appears to start failing in this way around Feb 3rd.

Console output:
```
[2024-02-23T19:12:59.238Z] rerun:
[2024-02-23T19:12:59.238Z] cd /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/TKG/output_17087153473001/jdk_security1_2/work/scratch/1 && \
[2024-02-23T19:12:59.238Z] DISPLAY=:0 \
[2024-02-23T19:12:59.238Z] HOME=/home/jenkins \
[2024-02-23T19:12:59.238Z] PATH=/bin:/usr/bin:/usr/sbin \
[2024-02-23T19:12:59.238Z]     /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/jdkbinary/j2sdk-image/bin/java \
[2024-02-23T19:12:59.238Z]         -Dtest.vm.opts='-ea -esa -Xmx512m' \
[2024-02-23T19:12:59.238Z]         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
[2024-02-23T19:12:59.238Z]         -Dtest.compiler.opts= \
[2024-02-23T19:12:59.238Z]         -Dtest.java.opts= \
[2024-02-23T19:12:59.238Z]         -Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/jdkbinary/j2sdk-image \
[2024-02-23T19:12:59.238Z]         -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/jdkbinary/j2sdk-image \
[2024-02-23T19:12:59.238Z]         -Dtest.timeout.factor=8.0 \
[2024-02-23T19:12:59.238Z]         -Dtest.root=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test \
[2024-02-23T19:12:59.238Z]         -Dtest.name=java/security/cert/CertPathBuilder/akiExt/AKISerialNumber.java \
[2024-02-23T19:12:59.238Z]         -Dtest.file=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/security/cert/CertPathBuilder/akiExt/AKISerialNumber.java \
[2024-02-23T19:12:59.238Z]         -Dtest.src=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/security/cert/CertPathBuilder/akiExt \
[2024-02-23T19:12:59.238Z]         -Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/security/cert/CertPathBuilder/akiExt \
[2024-02-23T19:12:59.238Z]         -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/TKG/output_17087153473001/jdk_security1_2/work/classes/1/java/security/cert/CertPathBuilder/akiExt \
[2024-02-23T19:12:59.238Z]         -Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/TKG/output_17087153473001/jdk_security1_2/work/classes/1/java/security/cert/CertPathBuilder/akiExt \
[2024-02-23T19:12:59.238Z]         -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/TKG/output_17087153473001/jdk_security1_2/work/classes/1/java/security/cert/CertPathBuilder/akiExt:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/security/cert/CertPathBuilder/akiExt \
[2024-02-23T19:12:59.238Z]         -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/TKG/output_17087153473001/jdk_security1_2/work/classes/1/java/security/cert/CertPathBuilder/akiExt:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/security/cert/CertPathBuilder/akiExt:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/jdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_arm_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar \
[2024-02-23T19:12:59.238Z]         AKISerialNumber
[2024-02-23T19:12:59.238Z] STDERR:
[2024-02-23T19:12:59.238Z] sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2024-02-23T19:12:59.238Z] 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
[2024-02-23T19:12:59.238Z] 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
[2024-02-23T19:12:59.238Z] 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[2024-02-23T19:12:59.238Z] 	at AKISerialNumber.main(AKISerialNumber.java:131)
[2024-02-23T19:12:59.238Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-02-23T19:12:59.238Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-02-23T19:12:59.238Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-02-23T19:12:59.238Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2024-02-23T19:12:59.238Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2024-02-23T19:12:59.238Z] 	at java.lang.Thread.run(Thread.java:750)
[2024-02-23T19:12:59.238Z] 
[2024-02-23T19:12:59.238Z] JavaTest Message: Test threw exception: sun.security.provider.certpath.SunCertPathBuilderException
[2024-02-23T19:12:59.238Z] JavaTest Message: shutting down test
[2024-02-23T19:12:59.238Z] 
[2024-02-23T19:12:59.238Z] 
[2024-02-23T19:12:59.238Z] TEST RESULT: Failed. Execution failed: `main' threw exception: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2024-02-23T19:12:59.238Z] --------------------------------------------------
[2024-02-23T19:15:50.569Z] Test results: passed: 175; failed: 1
```
**Test Info**
Test Name: jdk_security1_2
Test Duration: 3 min 3 sec
Machine: test-docker-ubuntu2004-armv7l-4
TRSS link for the test output: https://trss.adoptium.net/output/test?id=65d92ea543ff67006e8dbe59

**Build Info**
Build Name: Test_openjdk8_hs_sanity.openjdk_arm_linux
Jenkins Build start time: Feb 23 2024, 02:07 pm
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/648/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=65d92dac43ff67006e8dbd79

**Java Version**
openjdk version "1.8.0_412-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_412-beta-202402231854-b04)
OpenJDK Client VM (Temurin)(build 25.412-b04, mixed mode)

**This test has been failed 5 times since Jan 29 2024, 08:41 pm**
**Java Version when the issue first seen**
openjdk version "1.8.0_402-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_402-beta-202401300130-b06)
OpenJDK Client VM (Temurin)(build 25.402-b06, mixed mode)
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/642/

The test failed on machine test-docker-ubuntu2004-armv7l-4 1 times 
The test failed on machine test-docker-ubuntu2004-armv7l-1 2 times 
The test failed on machine test-docker-ubuntu2004-armv7l-2 1 times 
The test failed on machine test-docker-ubuntu2204-armv7l-2 1 times 

[Rerun in Grinder](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security1_2&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=arm_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faarch32-jdk8u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-arm-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=449&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by pshipton** [comment]
FYI https://bugs.openjdk.org/browse/JDK-8325096

**Comment by smlambert** [comment]
Will plan to exclude on JDK8 arm_linux while the [fix](https://github.com/openjdk/jdk8u-dev/pull/436) is not ported to the aarch32-jdk8u branch we build from:

https://github.com/adoptium/aarch32-jdk8u/blob/master/jdk/test/java/security/cert/CertPathBuilder/akiExt/AKISerialNumber.java
