### ISSUE TITLE
Verify initial Trestle pipelines against real-world examples of upstream PRs

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5137]
Related to https://github.com/adoptium/ci-jenkins-pipelines/issues/895 (see also https://github.com/adoptium/ci-jenkins-pipelines/wiki/Trestle-Initiative), we will test various use cases to validate the final feature set that the Trestle pipelines should deliver.

| Trestle Coverage | Upstream branch | Link(s) to results |
| --- | --- | --- |
| Support JDK8 | | |
| Support JDK11 | | |
| Support JDK17 | [PR](https://github.com/openjdk/jdk17u-dev/pull/2235) | |
| Support JDK21 | | |
| Support Tip (JDK23 atm) | | |

| Trestle Feature | Verify works as planned |
| --- | --- |
| Build 3 variants (release|fast-debug|slow-debug) | |  
| Trigger correct test sets  | | 
| Builds on expected nodes   | | 
| Displays properly in TRSS   | | 
| Discards artifacts after X days   | | 
| Access control for pipeline works   | |

**Comment by smlambert** [comment]
JDK17 triage notes

**Comment by smlambert** [comment]
JDK17 s390x_linux triage

Machine related failures: Cannot run program "hostname": error=2, No such file or directory on test-docker-sles12-s390x-1
```
java.lang.RuntimeException: Get hostname failed.
	at PostThruProxyWithAuth.getHostname(PostThruProxyWithAuth.java:263)
	at PostThruProxyWithAuth.doClientSide(PostThruProxyWithAuth.java:180)
	at PostThruProxyWithAuth.main(PostThruProxyWithAuth.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Cannot run program "hostname": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at jdk.test.lib.process.ProcessTools.privilegedStart(ProcessTools.java:611)
	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:442)
	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:421)
	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:408)
	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:489)
	at jdk.test.lib.process.ProcessTools.executeCommand(ProcessTools.java:537)
	at PostThruProxyWithAuth.getHostname(PostThruProxyWithAuth.java:260)
	... 8 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 17 more
```
