### ISSUE TITLE
jdk_math_1 FAILED in Test_openjdk11_hs_sanity.openjdk_ppc64_aix

### ISSUE THREAD

**Issue by RadekCap** [adoptium/aqa-tests#5245]
**Test Info**
Test Name: jdk_math_1
Test Duration: 1 min 42 sec
Machine: test-osuosl-aix72-ppc64-4
TRSS link for the test output: https://trss.adoptium.net/output/test?id=6620751f879917006ea746f0

**Build Info**
Build Name: Test_openjdk11_hs_sanity.openjdk_ppc64_aix
Jenkins Build start time: Apr 17 2024, 09:05 am
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.openjdk_ppc64_aix/678/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=6620743c879917006ea721ef

**Java Version**
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment Temurin-11.0.23+9 (build 11.0.23+9)
OpenJDK 64-Bit Server VM Temurin-11.0.23+9 (build 11.0.23+9, mixed mode)

**This test has been failed 33 times since Oct 14 2023, 01:37 pm**
**Java Version when the issue first seen**
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+8 (build 11.0.21+8)
OpenJDK 64-Bit Server VM Temurin-11.0.21+8 (build 11.0.21+8, mixed mode)
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.openjdk_ppc64_aix/631/

The test failed on machine test-osuosl-aix72-ppc64-4 4 times 
The test failed on machine test-osuosl-aix72-ppc64-3 6 times 
The test failed on machine test-osuosl-aix72-ppc64-2 6 times 
The test failed on machine test-osuosl-aix72-ppc64-1 7 times 
The test failed on machine test-osuosl-aix72-ppc64-6 7 times 
The test failed on machine test-osuosl-aix72-ppc64-5 3 times 

[Rerun in Grinder](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_math_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk11u%2Fjdk11u-release-aix-ppc64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-11.0.23%2B9_adopt&amp;LABEL_ADDITION=sw.os.aix.7_2&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=29&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by RadekCap** [comment]
According to the deep history:
Last success: 9/6/2023, 3:26:07 AM
First failure: 10/14/2023, 3:01:07 PM
https://trss.adoptium.net/deepHistory?testId=6620751f879917006ea746f0

**Comment by RadekCap** [comment]
Stacktrace
`Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Requested array size exceeds VM limit  `

Standard Error
`````
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at SymmetricRangeTests.testOverflowInMakePositive(SymmetricRangeTests.java:88)
	at SymmetricRangeTests.main(SymmetricRangeTests.java:624)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:829)

JavaTest Message: Test threw exception: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
`````

**Comment by RadekCap** [comment]
This test has many opened bugs:
https://bugs.openjdk.org/browse/JDK-8232195?jql=text%20~%20%22SymmetricRangeTests%22

One possible solution is 
`````
These tests require huge memory and need to run with -Xmx8g

They are not actually run in standard testing by jtreg.
`````
described in https://bugs.openjdk.org/browse/JDK-8232195

**Comment by RadekCap** [comment]
The same failure is on Mac - https://github.com/adoptium/aqa-tests/issues/5018

**Comment by zzambers** [comment]
I took a look to jtrs, test is ran in 2 configurations by aqa-tests (one passed, the other failed):
- with `-XX:+UseCompressedOops` - PASSED
- with `-XX:-UseCompressedOops` - FAILED
