### ISSUE TITLE
JDK8: Two failing charset tests in the NIO suite on AL2023

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#5381]
The following two tests fail on Amazon Linux 2023 but it's not limited to that platform (Verified on Debian12 and Ubuntu 24.04):

- [sun/nio/cs/TestCharsetMapping.java](https://ci.adoptium.net/job/Grinder/10264/testReport/sun_nio_cs_TestCharsetMapping/) - Not immediately obvious which is causing the real failure as there are a few "Error" references but it could be:
```
testing: x-IBM943        
  string de/encoding
    new String()
    String.getBytes()
  1 byte/char
    decode
    decode (direct)
  2 bytes/char
    decode
    decode (direct)
  1 byte/char
    encode
    encode (direct)
  2 bytes/char
    encode
      Error: U+8ec0 --> 3f3f, expected 8beb
      Error: U+8141 --> 3f3f, expected e445
      Error: U+6805 --> 3f3f, expected 8df2
      Error: U+7006 --> 3f3f, expected 93c0
      Error: U+8346 --> 3f3f, expected 8c74
      Error: U+7e48 --> 3f3f, expected e379
      Error: U+840a --> 3f3f, expected 9789
      Error: U+56ca --> 3f3f, expected 9458
      Error: U+ff0d --> 3f3f, expected 817c
      Error: U+688e --> 3f3f, expected 9e94
      Too many errors, giving up
    encode (direct)
      Error: U+8ec0 --> 3f3f, expected 8beb
      Error: U+8141 --> 3f3f, expected e445
      Error: U+6805 --> 3f3f, expected 8df2
      Error: U+7006 --> 3f3f, expected 93c0
      Error: U+8346 --> 3f3f, expected 8c74
      Error: U+7e48 --> 3f3f, expected e379
      Error: U+840a --> 3f3f, expected 9789
      Error: U+56ca --> 3f3f, expected 9458
      Error: U+ff0d --> 3f3f, expected 817c
      Error: U+688e --> 3f3f, expected 9e94
      Too many errors, giving upThe
```
- sun/nio/cs/TestIBMBugs.java - the failure here would be consistent with the error above with an IBM943 encoding failure:
```
java.lang.Exception: x-IBM943 failed to encode
	at TestIBMBugs.bug8235834(TestIBMBugs.java:225)
	at TestIBMBugs.main(TestIBMBugs.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.lang.Exception
JavaTest Message: shutting down test
```

**Comment by sxa** [comment]
Grinding on various random machines:
- [aws-rhel8-1](https://ci.adoptium.net/job/Grinder/10337/)
- [docker-u2004-5](https://ci.adoptium.net/job/Grinder/10338/)
- [docker-u2004-2](https://ci.adoptium.net/job/Grinder/10339)
- [docker-debian12-4](https://ci.adoptium.net/job/Grinder/10340)
- [docker-u2204-6](https://ci.adoptium.net/job/Grinder/10341)
