### ISSUE TITLE
JDK17: arm_linux: CheckCICompilerCount and GetXSpace fail and need investigation and exclusion

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#5473]
Issue generated from [original comment](https://github.com/adoptium/temurin/issues/50#issuecomment-2253696539) by Shelley Lambert in the July 2024 General Retrospective

Notes from aqa-tests triage:
CheckCICompilerCount and GetXSpace fail and need investigation exclusion, non-blocking on arm_linux

**Comment by smlambert** [comment]
More details at: https://github.com/adoptium/aqa-tests/issues/5443#issuecomment-2233724607, relevant bits repeated below for convenience

CheckCICompilerCount fails in both Grinder retries with: 
```
12:40:16  java.lang.RuntimeException: java.lang.RuntimeException: Expected to get exit value of [1]
12:40:16  
12:40:16  	at compiler.arguments.CheckCICompilerCount.verifyValidOption(CheckCICompilerCount.java:203)
12:40:16  	at compiler.arguments.CheckCICompilerCount.main(CheckCICompilerCount.java:222)
12:40:16  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:40:16  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
12:40:16  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:40:16  	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
12:40:16  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
12:40:16  	at java.base/java.lang.Thread.run(Thread.java:840)
12:40:16  Caused by: java.lang.RuntimeException: Expected to get exit value of [1]
12:40:16  
12:40:16  	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
12:40:16  	at compiler.arguments.CheckCICompilerCount.verifyValidOption(CheckCICompilerCount.java:197)
12:40:16  	... 7 more
12:40:16  
```
32-bit platforms would set TieredStopAtLevel to 1 by default (so that only C1 compilations are performed in the system). The test expects to run at level 2. Marking this failure as non-blocking. ACTION: Seen in April, need to understand why this test failure was not seen in January (was the testcase ProblemListed previously? and exclude testcase for arm_linux (a 32-bit platform).


GetXSpace fails in both Grinder retries with:
```
12:39:23  STDERR:
12:39:23  WARNING: A terminally deprecated method in java.lang.System has been called
12:39:23  WARNING: System::setSecurityManager has been called by GetXSpace (file:/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17212343561428/jdk_custom_0/work/classes/0/java/io/File/GetXSpace.d/)
12:39:23  WARNING: Please consider reporting this to the maintainers of GetXSpace
12:39:23  WARNING: System::setSecurityManager will be removed in a future release
12:39:23  FAILED: '/ total space': 934951190528 != 2943287296
12:39:23  FAILED: '/': 710688768 ?? 232638922752
12:39:23  FAILED: '/ size': 934951190528 > 2943287296
12:39:23  FAILED: '/ total space': 934951190528 != 2943287296
12:39:23  FAILED: '/ usable space': 232638922752 > 2943287296
12:39:23  Warning: us > s.free()
12:39:23  FAILED: '/ usable vs. free space': 232638922752 > 986267648
12:39:23  FAILED: '/ total space': 934951190528 != 2943287296
12:39:23  FAILED: '/': 710131712 ?? 232638365696
12:39:23  FAILED: '/ size': 934951190528 > 2943287296
12:39:23  FAILED: '/ total space': 934951190528 != 2943287296
12:39:23  FAILED: '/ usable space': 232638365696 > 2943287296
12:39:23  Warning: us > s.free()
12:39:23  FAILED: '/ usable vs. free space': 232638365696 > 985710592
12:39:23  30 tests: 12 failure(s); first: java.lang.RuntimeException: '/ total space': 934951190528 != 2943287296
12:39:23  FAILED: '/ total space': 934951190528 != 2943287296
12:39:23  FAILED: '/': 710008832 ?? 232638242816
12:39:23  FAILED: '/ size': 934951190528 > 2943287296
12:39:23  FAILED: '/ total space': 934951190528 != 2943287296
12:39:23  FAILED: '/ usable space': 232638242816 > 2943287296
12:39:23  Warning: us > s.free()
12:39:23  FAILED: '/ usable vs. free space': 232638242816 > 985587712
12:39:23  6 tests: 6 failure(s); first: java.lang.RuntimeException: '/ total space': 934951190528 != 2943287296
12:39:23  java.lang.RuntimeException: 2 test(s) failed
12:39:23  	at GetXSpace.main(GetXSpace.java:485)
12:39:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:39:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
12:39:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:39:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
12:39:23  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
12:39:23  	at java.base/java.lang.Thread.run(Thread.java:840)
12:39:23  
12:39:23  JavaTest Message: Test threw exception: java.lang.RuntimeException: 2 test(s) failed
12:39:23  JavaTest Message: shutting down test
```
GetXSpace should have been excluded on this platform, is non-blocking failure, but issue with ProblemList, see https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk17.txt#L146-L147 and https://github.com/adoptium/aqa-tests/issues/5227
