### ISSUE TITLE
jdk-23+37 riscv64 JVMCI and VectorApi extended.openjdk test failures

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#5613]
As reported here: https://github.com/adoptium/aqa-tests/issues/5598#issuecomment-2353240474
```
10:51:07  	hotspot_custom_0 - Test results: failed: 7 
10:51:07  		Failed test cases: 
10:51:07  			TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/NativeCallTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/MaxOopMapStackOffsetTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/DataPatchTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/SimpleDebugInfoTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/SimpleCodeInstallationTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/VirtualObjectDebugInfoTest.java
10:51:07          TEST: compiler/vectorapi/VectorGatherMaskFoldingTest.java
10:51:07          
10:51:07  	hotspot_custom_1 - Test results: failed: 7 
10:51:07  		Failed test cases: 
10:51:07  			TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/DataPatchTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/NativeCallTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/MaxOopMapStackOffsetTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/SimpleCodeInstallationTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/SimpleDebugInfoTest.java
10:51:07          TEST: compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/VirtualObjectDebugInfoTest.java
10:51:07          TEST: compiler/vectorapi/VectorGatherMaskFoldingTest.java
```
https://ci.adoptium.net/job/Grinder/10912/consoleFull

**Comment by andrew-m-leonard** [comment]
Various failures:
```
10:46:31  java.lang.AssertionError: java.lang.IllegalArgumentException: nmethod entry barrier is missing
10:46:31  	at jdk.vm.ci.code.test.CodeInstallationTest.test(CodeInstallationTest.java:121)
10:46:31  	at jdk.vm.ci.code.test.NativeCallTest.test(NativeCallTest.java:151)
10:46:31  	at jdk.vm.ci.code.test.NativeCallTest.testI32SDILDS(NativeCallTest.java:126)
```

```
10:47:44  Base Test: @Test testTwoDoubleVectorStoreMaskedNotEqualMask:
10:47:44  compiler.lib.ir_framework.shared.TestRunException: There was an error while invoking @Test method public static void compiler.vectorapi.VectorGatherMaskFoldingTest.testTwoDoubleVectorStoreMaskedNotEqualMask(). Target: null. Arguments: <void>
10:47:44  	at compiler.lib.ir_framework.test.BaseTest.invokeTestMethod(BaseTest.java:84)
10:47:44  	at compiler.lib.ir_framework.test.BaseTest.invokeTest(BaseTest.java:71)
10:47:44  	at compiler.lib.ir_framework.test.AbstractTest.run(AbstractTest.java:98)
10:47:44  	at compiler.lib.ir_framework.test.TestVM.runTests(TestVM.java:861)
10:47:44  	at compiler.lib.ir_framework.test.TestVM.start(TestVM.java:252)
10:47:44  	at compiler.lib.ir_framework.test.TestVM.main(TestVM.java:165)
10:47:44  Caused by: java.lang.reflect.InvocationTargetException
10:47:44  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
10:47:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
10:47:44  	at compiler.lib.ir_framework.test.BaseTest.invokeTestMethod(BaseTest.java:80)
10:47:44  	... 5 more
10:47:44  Caused by: java.lang.RuntimeException: assertFalse: expected false, was true
10:47:44  	at jdk.test.lib.Asserts.fail(Asserts.java:691)
10:47:44  	at jdk.test.lib.Asserts.assertFalse(Asserts.java:518)
10:47:44  	at jdk.test.lib.Asserts.assertFalse(Asserts.java:504)
10:47:44  	at compiler.vectorapi.VectorGatherMaskFoldingTest.testTwoDoubleVectorStoreMaskedNotEqualMask(VectorGatherMaskFoldingTest.java:765)
10:47:44  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
10:47:44  	... 7 more
```

**Comment by sxa** [comment]
Looks similar when run on the HiFive Unmatched board: https://ci.adoptium.net/job/Grinder/10913/console

**Comment by luhenry** [comment]
cc @robehn

**Comment by robehn** [comment]
https://bugs.openjdk.org/browse/JDK-8331704

```
bool CodeInstaller::pd_relocate(address pc, jint mark) {
  Unimplemented();
  return false;
}
```

I would probably compile with "--disable-jvm-feature-jvmci", tests should be skipped if there no such support.
I think doing a native image with graal works, but not using graal as a C2 replacement.
Any user can't tell what is what as the VM will says JVM CI yes but only one case works as it seems like.

**Comment by sxa** [comment]
Thanks @robehn - we'll kick off a build with that configure option and validate whether it causes any test failures 🤞🏻

**Comment by jiekang** [comment]
VectorGatherMaskFoldingTest failure is noted for risc-v here: https://bugs.openjdk.org/browse/JDK-8333248

That fix was not yet backported to 23.

**Comment by robehn** [comment]
> VectorGatherMaskFoldingTest failure is noted for risc-v here: https://bugs.openjdk.org/browse/JDK-8333248
> 
> That fix was not yet backported to 23.

Yes, it looks like there was an attempt to get into both 24 and 23, but it seem like it only got into 24.

**Comment by smlambert** [comment]
Some overlap between this issue and https://github.com/adoptium/aqa-tests/issues/5620, where the VectorGatherMaskFoldingTest was excluded for JDK23 (but noting that it is now seen failing for JDK21, https://github.com/adoptium/aqa-tests/issues/5690#issuecomment-2417474300)

**Comment by sophia-guo** [comment]
Back port to jdk23 is done https://bugs.openjdk.org/browse/JDK-8333248 . Back port to jdk21 is https://github.com/openjdk/jdk21u-dev/pull/1100. Make this dup of https://github.com/adoptium/aqa-tests/issues/5620
