### ISSUE TITLE
archiveArtifacts fingerprint

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#5635]
If the OS is in FIPS mode, MD5 is not available and we will get the following error in the test build

```
[2024-09-19T15:00:25.907Z] Archiving artifacts
[2024-09-19T15:00:26.471Z] Recording fingerprints
[2024-09-19T15:00:26.930Z] ERROR: Failed to record fingerprints
[2024-09-19T15:00:26.930Z] java.security.ProviderException: Error in Native Digest
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/sun.security.provider.NativeDigest.<init>(NativeDigest.java:91)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/sun.security.provider.NativeMD5.<init>(NativeMD5.java:38)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/java.security.Provider$Service.newInstanceOf(Provider.java:1953)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/java.security.Provider$Service.newInstanceUtil(Provider.java:1960)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/java.security.Provider$Service.newInstance(Provider.java:1935)
[2024-09-19T15:00:26.930Z] Caused: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: MD5, provider: SUN, class: sun.security.provider.NativeMD5)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/java.security.Provider$Service.newInstance(Provider.java:1942)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
[2024-09-19T15:00:26.930Z] 	at java.base@21.0.4/java.security.MessageDigest.getInstance(MessageDigest.java:185)
[2024-09-19T15:00:26.930Z] 	at Jenkins v2.462.2//hudson.Util.getMd5(Util.java:666)
[2024-09-19T15:00:26.930Z] 	at Jenkins v2.462.2//hudson.Util.getDigestOf(Util.java:642)
[2024-09-19T15:00:26.930Z] Caused: java.io.IOException: MD5 not installed
```

[internal issue](https://github.ibm.com/runtimes/jit-crypto/issues/534)

`Jenkins can record the 'fingerprint' of files (most often jar files) to keep track of where/when those files are produced and used.` https://www.jenkins.io/doc/pipeline/steps/core/

I think we don't need to record the fingerprints when we archive. If so, I would propose to turn it off. Otherwise, we will need to add the switch to turn it on and off based on whether the OS is in FIPS mode (as a workaround for now).

@smlambert what do you think?

**Comment by llxia** [comment]
Close this issue as the infra team rolled back to JDK 21.0.3 on the FIPS-enabled nodes.
