### ISSUE TITLE
hotspot_tier1_runtime CDS tests fail on Windows

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#5671]
Ref: https://github.com/adoptium/ci-jenkins-pipelines/issues/1104#issuecomment-2393086371

jdk11u Windows_x86:
TEST: runtime/CDSCompressedKPtrs/XShareAuto.java (https://ci.adoptium.net/job/Grinder/11104/)
```
21:17:44   stdout: [[0.026s][info][cds] _jvm_ident expected: OpenJDK Client VM (11.0.25-beta+8-202410071436) for windows-x86 JRE (11.0.25-beta+8-202410071436), built on Oct  7 2024 15:00:43 by "" with MS VC++ 17.7 (VS2022)
21:17:44  [0.026s][info][cds]              actual: OpenJDK Server VM (11.0.25-beta+8-202410071436) for windows-x86 JRE (11.0.25-beta+8-202410071436), built on Oct  7 2024 15:02:05 by "" with MS VC++ 17.7 (VS2022)
21:17:44  [0.026s][info][cds] UseSharedSpaces: The shared archive file was created by a different version or build of HotSpot
```

jdk17u Windows_x86:
TEST: runtime/cds/TestCDSVMCrash.java (https://ci.adoptium.net/job/Grinder/11129/)
```
09:49:59  java.lang.Error: Expected VM to crash
09:49:59  	at TestCDSVMCrash.main(TestCDSVMCrash.java:58)
09:49:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:49:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
09:49:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:49:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
09:49:59  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
09:49:59  	at java.base/java.lang.Thread.run(Thread.java:840)
09:49:59  
09:49:59  JavaTest Message: Test threw exception: java.lang.Error
```

jdk21u Windows_aarch64:
TEST: runtime/cds/TestCDSVMCrash.java (https://ci.adoptium.net/job/Grinder/11131/consoleFull)
TEST: runtime/ErrorHandling/UncaughtNativeExceptionTest.java (https://ci.adoptium.net/job/Grinder/11131/consoleFull)
```
09:50:59  java.lang.Error: Expected VM to crash
09:50:59  	at TestCDSVMCrash.main(TestCDSVMCrash.java:59)
09:50:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
09:50:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
09:50:59  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
09:50:59  	at java.base/java.lang.Thread.run(Thread.java:1583)
```
TEST: runtime/cds/CheckDefaultArchiveFile.java (https://ci.adoptium.net/job/Grinder/11131/consoleFull)
```
09:54:16  java.lang.RuntimeException: OpenJDK 64-Bit Server VM(aarch64)has no C:\Users\jenkins\workspace\Grinder\jdkbinary\j2sdk-image\bin\server\classes_nocoops.jsa
09:54:16  	at CheckDefaultArchiveFile.main(CheckDefaultArchiveFile.java:62)
```

jdk23u Windows_aarch64:
TEST: runtime/cds/CheckDefaultArchiveFile.java
TEST: runtime/cds/TestCDSVMCrash.java
TEST: runtime/ErrorHandling/MachCodeFramesInErrorFile.java
TEST: runtime/ErrorHandling/UncaughtNativeExceptionTest.java
TEST: runtime/memory/ReadFromNoaccessArea.java
TEST: runtime/jni/nativeStack/TestNativeStack.java
(https://ci.adoptium.net/job/Grinder/11117/)

**Comment by zzambers** [comment]
- `runtime/CDSCompressedKPtrs/XShareAuto.java`
I think this is likely problem with [test](https://github.com/openjdk/jdk11u-dev/blob/1393271305edc4d7bd1d9a5dcb2c011c93f4fd49/test/hotspot/jtreg/runtime/CDSCompressedKPtrs/XShareAuto.java#L41). It generates jsa with `-server` option, but then tries to use it with client VM (missing `-server`) I'll take a look later.

- `runtime/cds/TestCDSVMCrash.java`
  output on windows x86 actually contains:
```
10:49:59  [STDERR]
10:49:59  An error has occurred while processing the shared archive file.
10:49:59  Specified shared archive not found (c:\jenkins\workspace\Grinder\jdkbinary\j2sdk-image\bin\client\classes.jsa).
```
seems like 32-bit windows have .jsa file generated for server VM but not for client VM (default). On windows aarch64 issue is maybe different.

**Comment by adamfarley** [comment]
> ```
> 10:49:59  Specified shared archive not found (c:\jenkins\workspace\Grinder\jdkbinary\j2sdk-image\bin\client\classes.jsa).
> ```
> 
> seems like 32-bit windows have .jsa file generated for server VM but not for client VM (default). On windows aarch64 issue is maybe different.

An issue that resembles this has been seen on aarch64 Windows while running serviceability/jvmti/RedefineClasses/RedefineSharedClassJFR.java

```
02:29:57   stdout: [[0.009s][error][cds] An error has occurred while processing the shared archive file.
02:29:57  [0.009s][error][cds] Unable to map shared spaces
02:29:57  Error occurred during initialization of VM
02:29:57  Unable to use shared archive.
02:29:57  ];
02:29:57   stderr: []
02:29:57   exitValue = 1
02:29:57  
02:29:57  java.lang.RuntimeException: 'Class unloading: should_clean_previous_versions = false' missing from stdout/stderr
02:29:57  	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:238)
02:29:57  	at RedefineSharedClassJFR.main(RedefineSharedClassJFR.java:94)
02:29:57  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
02:29:57  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
02:29:57  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
02:29:57  	at java.base/java.lang.Thread.run(Thread.java:1583)
```

[Example](https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.openjdk_aarch64_windows_rerun/52/console).
[Rerun link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=hotspot_custom&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_windows&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=0&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.8-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk21u%2Fjdk21u-release-windows-aarch64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=serviceability%2Fjvmti%2FRedefineClasses%2FRedefineSharedClassJFR.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-21.0.8%2B9_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&TEST_TIME=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=aqavit-bot&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&RERUN_FAILURE=false&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=12&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None).
