### ISSUE TITLE
Mauve tests consistentlly failing on Windows jdk8u

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#5673]
The following tests consistently fail on Windows jdk8u (ref: https://github.com/adoptium/ci-jenkins-pipelines/issues/1104#issuecomment-2399390071)

Affects:
jdk8u Windows_x64
jdk8u Windows_x86

https://ci.adoptium.net/job/Grinder/11126/
https://ci.adoptium.net/job/Grinder/11128/
```
09:46:25  	MiniMix_5m
09:46:25  	MiniMix_10m
09:46:25  	MiniMix_aot_5m_0
09:45:30  	MauveSingleThrdLoad_HS_5m
09:45:30  	MauveSingleInvocLoad_HS_5m
09:45:30  	MauveMultiThrdLoad_5m
```

Symptoms:
```
09:41:01  LT  Test failed:
09:41:01  LT  java.lang.NoSuchMethodError: java.nio.CharBuffer.position(I)Ljava/nio/CharBuffer;
09:41:01  LT  	at gnu.testlet.java.nio.CharBuffer.compact.test(compact.java:35)
09:41:01  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:41:01  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:41:01  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:41:01  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
09:41:01  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
09:41:01  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
09:41:01  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:41:01  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:41:01  LT  	at java.lang.Thread.run(Thread.java:750)
```
```
09:41:46  LT  Test failed:
09:41:46  LT  java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
09:41:46  LT  	at gnu.testlet.java.nio.ByteBuffer.GetPut.bulkPut(GetPut.java:139)
09:41:46  LT  	at gnu.testlet.java.nio.ByteBuffer.GetPut.test(GetPut.java:36)
09:41:46  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:41:46  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:41:46  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:41:46  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
09:41:46  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
09:41:46  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
09:41:46  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:41:46  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:41:46  LT  	at java.lang.Thread.run(Thread.java:750)
```
```
09:42:49  LT  Test failed:
09:42:49  LT  java.lang.NoSuchMethodError: java.nio.ShortBuffer.position(I)Ljava/nio/ShortBuffer;
09:42:49  LT  	at gnu.testlet.java.nio.ShortBuffer.compact.test(compact.java:35)
09:42:49  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:42:49  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:42:49  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:42:49  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
09:42:49  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
09:42:49  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
09:42:49  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:42:49  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:42:49  LT  	at java.lang.Thread.run(Thread.java:750)
```
```
09:43:50  LT  Test failed:
09:43:50  LT  java.lang.NoSuchMethodError: java.nio.CharBuffer.position(I)Ljava/nio/CharBuffer;
09:43:50  LT  	at gnu.testlet.java.nio.CharBuffer.compact.test(compact.java:35)
09:43:50  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:43:50  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:43:50  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:43:50  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
09:43:50  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
09:43:50  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
09:43:50  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:43:50  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:43:50  LT  	at java.lang.Thread.run(Thread.java:750)
```
```
09:44:39  LT  Test failed:
09:44:39  LT  java.lang.NoSuchMethodError: java.nio.LongBuffer.position(I)Ljava/nio/LongBuffer;
09:44:39  LT  	at gnu.testlet.java.nio.LongBuffer.compact.test(compact.java:35)
09:44:39  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:44:39  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:44:39  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:44:39  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
09:44:39  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
09:44:39  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
09:44:39  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:44:39  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:44:39  LT  	at java.lang.Thread.run(Thread.java:750)
```
```
09:45:30  LT  Test failed:
09:45:30  LT  java.lang.NoSuchMethodError: java.nio.CharBuffer.position(I)Ljava/nio/CharBuffer;
09:45:30  LT  	at gnu.testlet.java.nio.CharBuffer.compact.test(compact.java:35)
09:45:30  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:45:30  LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:45:30  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:45:30  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
09:45:30  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
09:45:30  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
09:45:30  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:45:30  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:45:30  LT  	at java.lang.Thread.run(Thread.java:750)
```

**Comment by llxia** [comment]
I believe this issue is resolved by rolling back the mauve jar.
