### ISSUE TITLE
com/sun/jdi/FinalizerTest.java intermittently fails 

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5705]
This test regularly fails due to OOM on many platforms and across multiple versions.  It keeps cropping up during release triage since March 2024 (see https://github.com/adoptium/aqa-tests/issues?q=is%3Aissue+FinalizerTest) and is considered a nuisance test.  

```
[2024-10-16T22:46:16.750Z] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
[2024-10-16T22:46:16.750Z] at java.base/java.lang.ref.Finalizer.runFinalization(Finalizer.java:145)
[2024-10-16T22:46:16.750Z] at java.base/java.lang.ref.Reference$1.runFinalization(Reference.java:331)
[2024-10-16T22:46:16.750Z] at java.base/java.lang.Runtime.runFinalization(Runtime.java:788)
[2024-10-16T22:46:16.750Z] at java.base/java.lang.System.runFinalization(System.java:1985)
[2024-10-16T22:46:16.750Z] at FinalizerTarg.waitForAFinalizer(FinalizerTest.java:100)
[2024-10-16T22:46:16.750Z] at FinalizerTarg.main(FinalizerTest.java:111)
```

We should consider excluding it, or see if there are options that allow it to be more stable on the variety of test nodes we have.

**Comment by sophia-guo** [comment]
build/AbsPathsInImage.java should be excluded by propagate the eclipse problemlist to jdk23 and jdk24
