### ISSUE TITLE
jdk_net and jdk_nio fails on linux with java8

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#827]
**No issues in JBS:**
java/net/InetAddress/BadDottedIPAddress.java failed with 'UnknownHostException was not thrown for: 999.999.999.999'

```
Stacktrace

Execution failed: `main' threw exception: java.lang.Exception: UnknownHostException was not thrown for: 999.999.999.999    

Standard Output

    

Standard Error

java.lang.Exception: UnknownHostException was not thrown for: 999.999.999.999
	at BadDottedIPAddress.main(BadDottedIPAddress.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/306/testReport/junit/java_net_InetAddress_BadDottedIPAddress/java/BadDottedIPAddress/

**With issue opened in JBS:**
java/net/InetAddress/CachedUnknownHostName.java failed with 'java.lang.Exception: Missing java.net.UnknownHostException    '

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/306/testReport/junit/java_net_InetAddress_CachedUnknownHostName/java/CachedUnknownHostName/

```
Standard Error

Missing java.net.UnknownHostException for host bogusHostName
java.lang.Exception: Missing java.net.UnknownHostException
	at CachedUnknownHostName.main(CachedUnknownHostName.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

```
https://bugs.openjdk.java.net/browse/JDK-8056988 opened for window, should update with linux too.

**Comment by sophia-guo** [comment]
Without issue opened in JBS:
java/net/Socks/SocksV4Test.java failed with ' Test cannot run. resolvable address:doesnot.exist.invalid/104.17.16.123'
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/306/testReport/junit/java_net_Socks_SocksV4Test/java/SocksV4Test/

```
java.lang.RuntimeException: Test cannot run. resolvable address:doesnot.exist.invalid/104.17.16.123
	at SocksV4Test.assertUnresolvableHost(SocksV4Test.java:70)
	at SocksV4Test.main(SocksV4Test.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by sophia-guo** [comment]
With issue opened in JBS:
java/net/InetAddress/IPv4Formats.java.IPv4Formats failed with 'invalidhost.invalid should throw UnknownHostException!'

```
java.lang.RuntimeException: invalidhost.invalid should throw UnknownHostException!
	at IPv4Formats.main(IPv4Formats.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/306/testReport/junit/java_net_InetAddress_IPv4Formats/java/IPv4Formats/

https://bugs.openjdk.java.net/browse/JDK-8058932

**Comment by sophia-guo** [comment]
With issue opened in JBS:
java/net/SocketPermission/Wildcard.java failed with '"*.blabla.bla" "connect,listen,accept,resolve") does not imply ("java.net.SocketPermission" "bla.blabla.bla" '

```
java.lang.RuntimeException: Failed: ("java.net.SocketPermission" "*.blabla.bla" "connect,listen,accept,resolve") does not imply ("java.net.SocketPermission" "bla.blabla.bla" "connect,listen,accept,resolve")
	at Wildcard.main(Wildcard.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/306/testReport/junit/java_net_SocketPermission_Wildcard/java/Wildcard/

https://bugs.openjdk.java.net/browse/JDK-7021280

**Comment by sophia-guo** [comment]
No issue opened in JBS:
java/nio/channels/DatagramChannel/SendToUnresolved.java failed with 'java.lang.RuntimeException: Expected exception not thrown    '

```
java.lang.RuntimeException: Expected exception not thrown
	at SendToUnresolved.main(SendToUnresolved.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/306/testReport/junit/java_nio_channels_DatagramChannel_SendToUnresolved/java/SendToUnresolved/

**Comment by sophia-guo** [comment]
java/net/ipv6tests/B6521014.java
java/net/MulticastSocket/SetGetNetworkInterfaceTest.java on linuxgot 'Cannot assign requested address 'Test failed: cannot create socket'

```
Standard Error

java.lang.RuntimeException: Test failed: cannot create socket.
	at B6521014.main(B6521014.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.Socket.bind(Socket.java:644)
	at B6521014.test2(B6521014.java:103)
	at B6521014.main(B6521014.java:121)
	... 6 more
```

JBS: https://bugs.openjdk.java.net/browse/JDK-8006560

java/net/Inet6Address/B6206527.java 'Cannot assign requested address (Bind failed) '

```
java.net.BindException: Cannot assign requested address (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.bind(ServerSocket.java:329)
	at B6206527.main(B6206527.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)

```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_linux/433/testReport/junit/java_net_Inet6Address_B6206527/java/B6206527/
JBS: https://bugs.openjdk.java.net/browse/JDK-6670327

**Comment by sophia-guo** [comment]
com/sun/net/httpserver/Test1.java get timeout error Program /home/jenkins/workspace/openjdk8_hs_openjdktest_ppc64le_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960563ms)' could be a net work issue?
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_ppc64le_linux/265/console

**Comment by sophia-guo** [comment]
Intermittent failure on Macosx as timeout
java/net/Inet6Address/B6558853.java same behavior as java/net/ipv6tests/UdpTest.java

**Comment by smlambert** [comment]
This issue is pretty stale.  Are there more current or specific issues that cover the failures?  What actions need to be taken to address and close this one?

**Comment by sophia-guo** [comment]
Those tests failed with hotspot. Some of them are recorded in JBS with issue opened or resolved ( resolved, but still failed in AdoptOpenJDK). 

Most of them are still excluded by ProblemList. I can reenable to see if issues still exist.

**Comment by smlambert** [comment]
Doing a review of old issues, @sophia-guo is this an issue that needs to remain?  It is somewhat general and does not include some of information that we would hope to capture and there are also no PRs linked to this issue, though I have not looked in ProblemLists if there is mention of it.  There are 3 other issues that have referenced it.

**Comment by sophia-guo** [comment]
All tests mentioned here are referenced by ProblemLists. The exclusion may be done combined with others so no PR is linked.

**Comment by sophia-guo** [comment]
All tests excluded by https://github.com/adoptium/aqa-tests/issues/593.

**Comment by sophia-guo** [comment]
excluded tests with this issue jdk8
java/net/InetAddress/BadDottedIPAddress.java https://github.com/adoptium/aqa-tests/issues/827 linux-all
java/net/InetAddress/CachedUnknownHostName.java https://github.com/adoptium/aqa-tests/issues/827 linux-all
java/net/InetAddress/IPv4Formats.java https://github.com/adoptium/aqa-tests/issues/827 linux-all
java/net/SocketPermission/Wildcard.java https://github.com/adoptium/aqa-tests/issues/827 linux-all
java/net/Socks/SocksV4Test.java https://github.com/adoptium/aqa-tests/issues/827 linux-all
com/sun/net/httpserver/Test1.java https://github.com/adoptium/aqa-tests/issues/827 linux-ppc64le
java/nio/channels/DatagramChannel/SendToUnresolved.java https://github.com/adoptium/aqa-tests/issues/827 linux-all
java/net/Inet6Address/B6558853.java https://github.com/adoptium/aqa-tests/issues/827 macosx-all
grinder

linux-x64 https://ci.adoptium.net/view/Test_grinder/job/Grinder/11350/console 
mac https://ci.adoptium.net/view/Test_grinder/job/Grinder/11351/console
ppc64le https://ci.adoptium.net/view/Test_grinder/job/Grinder/11352/console


jdk21
java/net/Socket/asyncClose/AsyncClose.java https://github.com/adoptium/aqa-tests/issues/827 aix-ppc64, linux-ppc64le
aix https://ci.adoptium.net/view/Test_grinder/job/Grinder/11353/
ppc64le https://ci.adoptium.net/view/Test_grinder/job/Grinder/11354/
